### ISSUE TITLE
How to create a field that pulls a value from mongo and displays as is. 

### ISSUE THREAD

**Issue by rwatts3** [aldeed/meteor-autoform#1012]
I am writing a link tracking package that will store a count of clicks in the database. 
In my autoform I would like to have a field called count. Where the value will be a number either a string or a natural number. 

My question is how do I create a field where I can simply return text that displays the number. It is not an input field but more so an informative field. 

Something like this http://screencast.com/t/cfEyYoP9w

**Comment by sturoid** [comment]
Can you just set it to disabled?

**Comment by dpankros** [comment]
Disabling it, as @sturoid suggested, would work, I would think.  You could even set the background color of that element to white (or whatever you're using in your app) so it doesn't *look* disabled.

You could also try digging into the [API](https://github.com/aldeed/meteor-autoform/blob/master/api.md).  I believe if you created a helper and then called the helper within your autoForm, you'd see the autoform data within the data context.  The API could probably get you the data you need, if the number is within your form.  You also might want to override the before hooks to remove it from the doc before inserts/updates.

**Comment by rwatts3** [comment]
Thank you I will give this a shot

**Comment by rwatts3** [comment]
This works thank you for the suggestion.
