### ISSUE TITLE
Is it possible to populate "options" from another collection?

### ISSUE THREAD

**Issue by neilyoung** [aldeed/meteor-autoform#1019]
As subject says.

Regards

**Comment by neilyoung** [comment]
Sorry, solved. Found it.

**Comment by ricardodovalle** [comment]
@neilyoung, Could you post the solution, please?

**Comment by neilyoung** [comment]
Hi, yes.

this works for me:

where your schemas are defined:

  Schemas.Cars = new SimpleSchema({
      brand: {
          type: String,
          label: 'Brand'
     } 
  });

 
  Schemas.People = new SimpleSchema({
      name: {
        type: String,
        label: 'Name'
    },
    favoriteCar: {
        type: String,
        optional: true
    }
 });

where your collections are defined:

  Cars = Collections.Cars = new Mongo.Collection("cars");
  Cars.attachSchema(Schemas.Cars);

  PeopleWithCars = Collections.PeopleWithCars = new Mongo.Collection("peoplewithcars");
  PeopleWithCars.attachSchema(Schemas.People);

Then, in your template markup:

  <template name="test">

     <h2>Test</h2>

   {{#autoForm collection=Collections.PeopleWithCars id="form" type="insert"}}
         {{> afQuickField name='name' autofocus='' }}
        {{> afQuickField name="favoriteCar" options=carOptions}}
         <input type="submit" value="Submit">
     {{/autoForm}}

</template>

and in your viewmodel:

  Template.test.helpers({
    carOptions: function () {
      return Cars.find().map(function (c) {
        return {label: c.brand, value: c._id};
      });
    }
  });

Somehow like this. Gives you a select containing the elements from the Car collection to be chosen from.

**Comment by bipin244** [comment]
thanks it is nice
but if i want to get this value in checkbox
