### ISSUE TITLE
Possible to Preset Array values in form? 

### ISSUE THREAD

**Issue by weijian19391** [aldeed/meteor-autoform#1027]
I have the following code: 
````
owner: {
    type: [Object]
  },
  'owner.$.userId':{
    type: String,
    label: "Device's owner's userId",
    autoValue:function(){ return this.userId;}
  },
  'owner.$.email': {
    type: String,
    label: "Device's owner's email",
    //autoValue:function(){ return Meteor.user().emails[0].address;}
  }
````

Can i pre-set the input that user is supposed to fill in when i call this : 
`{{> afQuickField name='owner'}}`

**Comment by joerodrig3** [comment]
To use preset data, you can write a helper that retrieves your document data and set the data context using doc=<helper_method_here> in the autoform area.
ie.
```
// Helper
Template.Owner_Form.helpers({
    // Retrieve owner data from the Owners collection
    // Parameters: [String] ownerID - ID of owner to retrieve  
    // Returns: [Object] Owner data from collection || undefined
    'ownerData': function(ownerID) {
        return Owners.findOne({_id: ownerID });
    },
})


// Form
  {{#autoForm collection=Owners doc=ownerData id="ownerForm" type="method-update" meteormethod="editOwner"}}
                        <fieldset>
                         {{> afQuickField name='owner' value='full_name' }}
                        </fieldset>
                        <button type="submit" class="btn btn-sm btn-success">
                            <i class="fa fa-save"></i> Update
                        </button>
{{/autoForm}}
```

**Comment by weijian19391** [comment]
@joerodrig3 Hi! 
I don't quite understand your answer. May i know where does the `full_name` comes from?

**Comment by joerodrig3** [comment]
@weijian19391 Sorry, I left full_name in from a different example and just updated my answer. When you set the data context using "doc=ownerData", any fields that exist in your autoform that correlate to the ownerData retrieved will be auto-populated.

ie. 
If ownerData returns something like ```{owner : "Joe"}```, your  ```name='owner'``` input field will contain that value by default

**Comment by weijian19391** [comment]
@joerodrig3 Thank you so much for this information, it has helped me tremendously.

**Comment by cellulosa** [comment]
I'm having issue setting the default value of a template which is being called during a loop. Is it possible to get like the $scope variable? Or would it be better to use a different approach - like  hook?

Here is my code:

    // view.ng.html
    <div ng-repeat="item in items">
        <meteor-include src="ordersTemplate"></meteor-include>
    </div>

    // orders.html
    <template name="ordersTemplate">
        {{#autoForm collection="Orders" id="insertOrderForm" type="insert" doc=defaultValues}}
            {{item.name}}
            {{> afQuickField name='quantity'}}
            {{> afQuickField name='itemId'}} // I would like to remove this, and set it using defaultValues
        {{/autoForm}}
    </template>

    // controller
    Template.ordersTemplate.helpers({
        defaultValues: function() {
            return { itemId: this.parent.item._Id }; // here I'm trying to find a way to get {{item._id}}
        }
    });

**Comment by pablohirafuji** [comment]
Hey @cellulosa, I was having the same issue. When you pass value thought the doc, your field must exist in autoform render, i.e.: it can't be set in Schema to `autoform.omit: true`. So you can hide the field defining `autoform.type: hidden` in you Schema, or if you are using afQuickField, like in your example, do this:
`{{> afQuickField name='itemId' type='hidden' value=item._id}}`

Hope it's work for you!

**Comment by cellulosa** [comment]
Thank you, @pablohirafuji. But is there a way to avoid rendering the hidden field? It would be a bit more secure not to allow users to edit the fields using the HTML inspector.

**Comment by pablohirafuji** [comment]
@cellulosa I agree. For more security, a little more code is necessary. You can set up a hook in your client code, like this:

`AutoForm.hooks({
  insertOrderForm: {
    before: {
      insert: function (doc) {
        doc.itemId = Template.currentData().defaultValues.itemId; // Before insert, set the doc itemId to Template's value defaultValues.itemId.
        return doc; // Must return the resulting doc.
      }
    },{
    onSuccess: function (insert, result) {
      Router.go('sucess/'+result); // What to do after successed inserting the doc. Param result is the generated _id of inserted document.
    }
  }
})`

SimpleShcema, Collections2 and AutoForm are really powerful packages. I really apreciate the authors work!

**Comment by cellulosa** [comment]
@pablohirafuji my issue is that I am rendering forms in a loop with specific ids, and as far as I understand hooks can either be attached to all the app's forms or to specific ones; but than this would require me to add every single ids - and this is obviously unpractical

**Comment by pablohirafuji** [comment]
@cellulosa I see. I didn't realize that you were using an autoform loop. I don't know if it's going to work, but in last case I think you can call a meteor method with an array of itemId's param to be sure what's being inserted. Don't know if it's the best though.
