### ISSUE TITLE
Pre-defining state of check-boxes, taking reference from collection fields.

### ISSUE THREAD

**Issue by meShubham99** [aldeed/meteor-autoform#1041]
So I have this collection that consists of a field named "categories", which is an array consisting of strings. The user adds these strings to the array field by checking the check-boxes in the form.

But when he wishes to update the document of the collection, he must see what categories he had checked previously. 
I wish to set the checked field of that particular check-box to be true, which has a value in the "categories" array in the collection field.
Can we do this with auto-form? If yes how?

Thanks :)

**Comment by aldeed** [comment]
Yes if you use `type="select-checkbox"` and provide the options, it should work and preselect them automatically. For ways to provide the options, see https://github.com/aldeed/meteor-autoform#what-are-the-various-ways-i-can-specify-options-for-a-select-radio-group-or-checkbox-group
