### ISSUE TITLE
Incompatibility with BlazeComponent

### ISSUE THREAD

**Issue by smeijer** [aldeed/meteor-autoform#1044]
There is currently an issue when using BlazeComponents as custom input type.

Whenever you define a component as custom type, the required `valueOut` method is never called. This is due to the check at: [autoform-api.js#L457](https://github.com/aldeed/meteor-autoform/blob/80162d6d04ae920709826a9e7c762642e555a00b/autoform-api.js#L457)
```js
AutoForm.getInputTypeTemplateNameForElement = function (element) {
  var view = Blaze.getView(element);
  //...
  while (view && view.name.slice(0, 9) !== "Template.") { //  <<< the issue lies here
    view = view.originalParentView || view.parentView;

```

Components are not called `Template.myInput` but contain a `BlazeComponent` prefix; like `BlazeComponent.FiInputComponent`.

**Comment by smeijer** [comment]
So, am I the only one trying to use BlazeComponents with autoform? Or am I doing something wrong that I'm the only one running into troubles?

**Comment by kingkevin** [comment]
I'd like to see this merged in as well

**Comment by smeijer** [comment]
Some feedback would be nice.
