### ISSUE TITLE
best practices for formatting currencies?

### ISSUE THREAD

**Issue by adamwong246** [aldeed/meteor-autoform#1048]
I have an issue with formatting cents to dollars and I was wondering what the best practices are? I'm storing the amount as cents, not dollars and I'm the type is Integer. I've found 2 jQuery plugins- autonumeric and moneyMask but they operate on text inputs, not number inputs.

**Comment by ganySA** [comment]
Hi

I used autoNumeric for currencies works pretty well and i created my own InputType, i store mine as string but if you want to split this out further into mongo numbers you can do so on update and would need to change the code to populate them.

1) Create a Template (code in Jade):

    template(name="afCurrencyInput")
        input.form-control.currency-input(type="text" $dyn=atts)

2) Create template js file with appropriate code below 

    AutoForm.addInputType("afCurrencyInput", {
        template: "afCurrencyInput",
       valueOut: function () {
        if (this.val()) {
            var val = $('.currency-input').autoNumeric('get');
            return val;
        }
      },
    });

    Template.afCurrencyInput.helpers({
    atts: function addFormControlAtts() {
        var atts = _.clone(this.atts);
        return atts;
      }
     });

    Template.afCurrencyInput.rendered = function () {
    self = this;
    this.$('.currency-input').autoNumeric('init');


    this.autorun(function () {
        var data = Template.currentData();
        self.$('.currency-input').autoNumeric('set', data.value);
    });

3) Use template in code / custom form using "type" as the type you made above (using jade).

    +afFieldInput type='afCurrencyInput' name="services.$.price" arrIndex=servIndex data-a-sep="," data-a-dec="." data-a-sign="R " data-w-empty="empty"

4) I store my values as a string but if you need to actually split out the dollars/cents you can just split the string out using
      var hooksObject = {
            before: {
                             'form-type': function(doc)
                                           {
                                                   // you can modify the doc here.
                                           }

**Comment by deuceBag33** [comment]
I have found a simple solution that may work, in your model or schema, 

`price: {
		type: String,
		label: "How much Monies",
		regEx: /^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?$/
	}`

then out side of attachSchema you can set a message for it like so

`SimpleSchema.messages({
	regEx: [
		{exp: /^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?$/, msg: "it's got to be monies!"}
	]
});`

since it is a string you will have to convert it to number todo the maths on it.

i may be under thinking it. I am a Lazy coder like that.

**Comment by adamwong246** [comment]
well, I'll close the issue. Maybe someday I'll turn this into a plugin. Here's what works for me
```
AutoForm.addInputType "usdCents",
  template: "usdCentsField"
  valueIn: (val) ->
    toReturn = val / 100
    console.log "in()", val, " --> ", toReturn
    toReturn

  valueOut: ->
    toReturn = Number(@val().replace(/$/, '').replace(/,/g, '').replace(/./, ''))
    console.log "out()", @val(), " --> ", toReturn
    toReturn

  valueConverters:
    string: (val) ->
      console.log "error! implement this method later."
      # toReturn = val * 100
      # console.log "string()", val, " --> ", toReturn
      # toReturn
    number: (val) ->
      toReturn = val * 100
      console.log "number()", val, " --> ", toReturn
      toReturn

Template.usdCentsField.onRendered ->
  $input = @$("input")
  $input.inputmask
    alias: "currency"
    prefix: "$"
    rightAlign: false
```
