### ISSUE TITLE
method-update form does not work

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-autoform#1059]
Err, edit.

Seems like pairing `meteormethod` and `type="method-update"` does not seem to work. Am I doing something wrong?

```
+quickForm collection="Players" type="method-update" meteormethod="Players._updateForGame"
```

**Comment by tjflaagan** [comment]
I am also having a similar problem where the method does not get called.

**Comment by jholl** [comment]
Is there error being thrown or just nothing happening?

Since this is update, is your method accepting the modifier and documentId parameters?

````
Meteor.methods({
   someMethod: function(modifier, docId){
       ...
   }
});
````

**Comment by tjflaagan** [comment]
https://github.com/aldeed/meteor-autoform/issues/1075

In mine I do accept both modifier and docId and nothing happens. The console.logs in the method do not even show up in the server console.

**Comment by AlexFrazer** [comment]
I think I might have found the problem... `meteor-ionic` is locking the version at a very far behind version. Sorry bout that

**Comment by tjflaagan** [comment]
Looking closer, my autoform package is outdated as well, there are packages that depend on the old version. After trying to force the newest message I get the error shown below.

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency:
   aldeed:autoform 5.3.2, was 4.2.2.
   Constraints on package "aldeed:autoform":
   * aldeed:autoform@5.3.2 <- top level
   * aldeed:autoform@4.0.0 || 5.0.0 <- aldeed:autoform-bs-datepicker 1.1.1
   * aldeed:autoform@4.0.0 || 5.0.0 <- cfs:autoform 2.2.1
   * aldeed:autoform@4.0.0 || 5.0.0 <- aldeed:autoform-bs-datetimepicker 1.0.6
   * aldeed:autoform@4.2.2 || 5.1.2 <- yogiben:autoform-modals 0.3.5
   
   To allow potentially incompatible changes to top-level dependencies, you
   must pass --allow-incompatible-update on the command line.

**Comment by aldeed** [comment]
To take major version updates, you need to run `meteor update --allow-incompatible-update`. Did you try that?

**Comment by evanglerm** [comment]
I did try this 
```javascript 
meteor update --allow-incompatible-update
```
 but it is not updating the version for me. 

Any more suggestions.

**Comment by allenfuller** [comment]
I'm getting the same symptoms. Added a quickform update form and clicking Submit does nothing.

Form:
```
<template name="contactEdit">
      {{#if Template.subscriptionsReady}}
        {{#with currentContact}}
          {{> quickForm collection="Contacts" doc=currentContact id="updateContactForm" type="method-update" meteormethod="updateContact"}}
        {{/with}}
      {{else}}
        <p>Loading...</p>
      {{/if}}
</template>
```
Method:
```
Meteor.methods({
  addContact( doc ) {
    // arguments and insert code here
  },
  updateContact( doc, contactId ) {
    console.log( doc );
    check( doc, Contacts.simpleSchema() );
    try {
      var contactId = Contacts.update({_id: contactId}, doc );
      return contactId;
    } catch( exception ) {
      return exception;
    }
  }
});
```
Hook:
```
AutoForm.addHooks(['updateContactForm'], {
  onSuccess: function(operation, result, template) {
    Bert.alert( 'Contact updated', 'success', 'growl-top-right' );
    FlowRouter.go("/contacts/_id");
  }
});
```
I click Submit and nothing happens.

**Comment by aldeed** [comment]
@allenfuller Call `AutoForm.debug()` in the console before submitting in case you have missing keys or something. Also check the .versions file to make sure you're using the latest autoform release.
