### ISSUE TITLE
defaultValue on Boolean doesn't cause check box to be checked on insert quickForm

### ISSUE THREAD

**Issue by stephentcannon** [aldeed/meteor-autoform#108]
If you have a schema like this

```
isActive: {
      type: Boolean,
      label: 'Active',
      defaultValue: true,
    },
```

and you use quickForm the check box for that form field is not checked by default on a  n INSERT form (it is fine on an update quickForm).

**Comment by ababba15** [comment]
It doesn't work in my case for some reason..

```
work_days: {
		type: [String],
		label: "Дни работы",
		optional: true,
		autoform: {
			type: "select-checkbox",
			options: function () {
				return [
					{
						label: "Понедельник",
						value: "Mon",
						defaultValue: true
					},
					{
						label: "Вторник",
						value: "Twe"
					},
					{
						label: "Среда",
						value: "Wed"
					},
					{
						label: "Четверг",
						value: "Thu"
					},
					{
						label: "Пятница",
						value: "Fri"
					},
					{
						label: "Суббота",
						value: "Sat"
					},
					{
						label: "Воскресенье",
						value: "Sun"
					}
        	];
			}
		}
	}
```

**Comment by aramk** [comment]
@ababba15 There's not default value for that select-checkbox, so it won't have anything checked by default I think.

**Comment by ababba15** [comment]
@aramk okay, got it. But how can I make it checked on startup (I don't want to use jQuery)

**Comment by aramk** [comment]
Perhaps adding `defaultValue: ["Mon", "Tue", "Wed"]`? Also note there's a typo in your Tuesday value. I'm not sure about `select-checkbox` since it's not a `Boolean` type but rather an array of strings: `[String]`. So it depends on how AutoForm would handle it. Feeding in that value from a document would do it afaik.

**Comment by ababba15** [comment]
@aramk yes, mate! Your variant works, thanks a lot. Also thank you for telling me about typo, that could cause unexpected errors in future. Cheers =)

**Comment by aramk** [comment]
Awesome, glad it helped!
