### ISSUE TITLE
Could I show loading (spinner) for wating the complete submit (save data)?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform#1109]
Could I show loading (spinner) for wating the complete submit (save data)?
Please help me.

**Comment by abernix** [comment]
This is in the docs.  Please look at the [Callbacks/Hooks](https://github.com/aldeed/meteor-autoform#callbackshooks), and specifically ``beginSubmit`` and ``endSubmit``.  You can add the spinner in the ``beginSubmit`` and remove it in the ``endSubmit``.

**Comment by thearabbit** [comment]
Thank, but I am not sure how to show/hide `spinner` in JS (I use `sacha:spinner`).

**Comment by bharathkeshav12** [comment]
@thearabbit - did you find a way to show the spinner on beginSubmit? if yes, could you share how?

**Comment by thearabbit** [comment]
Now I used `blockUI` [https://github.com/malsup/blockui/] instead.
But don't up to date.
