### ISSUE TITLE
password field

### ISSUE THREAD

**Issue by aashuagg** [aldeed/meteor-autoform#111]
Does autoform supports a password field? I could not find any type for password (<input type="password" />) to show asterisk instead of String.

**Comment by zhaoyao91** [comment]
can we specify type="password" in simple-schema and use quickForm instead of quickField?

**Comment by DylanKojiCheslin** [comment]
@zhaoyao91 

password: {
    type: String,
    min: 8,
    max: 25,
    autoform: {
      label: "Password 8-25 in length",
      type: "password"
    }
  },

you can do this, make sure that your for uses a meteor method to do accounts.create on the server for security reasons.
