### ISSUE TITLE
Using symbols or special characters in labels

### ISSUE THREAD

**Issue by reel** [aldeed/meteor-autoform#1115]
I would like to use:

``` javascript
    label: "Félix"

or 
    label: "F&eacute;lix"
```

in the Schema, but it renders like that in autoform. 

Any clue?

**Comment by nasuke0302** [comment]
Hey @reel, there's still no way of doing that. I REALLY need it.
@aldeed, any news on this, please?

**Comment by reel** [comment]
Sorry, I am no longer using meteor

**Comment by nasuke0302** [comment]
Thanks for anwering so fast, I'm still looking for a solution :-/

**Comment by reel** [comment]
I don't remember what I did or if I found a solution. Let me know if you want me to reopen this issue

**Comment by nasuke0302** [comment]
Well, that would be just great, thanks
