### ISSUE TITLE
Get the template instance on valueOut of a plugin.

### ISSUE THREAD

**Issue by jimmiebtlr** [aldeed/meteor-autoform#1129]
I'm probably missing something obvious, but when creating an autoform plugin, what is the easiest way to get a value from the plugin's template instance?

    AutoForm.addInputType("pluginName", {
      template: "pluginTemplate",
      valueOut: function( ){
        return getTemplateInstanceVariable();
      }
    });

I've tried

    AutoForm.addInputType("pluginName", {
      template: "pluginTemplate",
      valueOut: function( ){
        var t = Template.instance();
      }
    });
    

But it seems to be the entire form template, rather than the plugin's template instance.

**Comment by jimmiebtlr** [comment]
For the moment, I've used the form ID along with a global store.  Don't think this is ideal, but not terribly messy either.

**Comment by isubasti** [comment]
@jimmiebtlr Hi, it seems that you managed to get this working. It will be great if you can share a snippet on how to do it.

**Comment by jimmiebtlr** [comment]
https://github.com/ElevateDev/meteor-autoform-slingshot/blob/master/template.js

Wasn't to happy with the solution, but it's concise.

**Comment by isubasti** [comment]
@jimmiebtlr Thanks for your help. I had implemented mine in similar way and indeed it's not pretty but seems to be the only way for now.

**Comment by gregory** [comment]
lol @jimmiebtlr  - https://github.com/ElevateDev/meteor-autoform-slingshot/blob/master/template.js#L64

**Comment by pouya-eghbali** [comment]
If anyone is still trying to find a solution to this, here's one:

```javascript
Blaze.getView(this.get(0)).templateInstance()
```
