### ISSUE TITLE
Fine tuning validation='none' makes validateForm contradict validateField

### ISSUE THREAD

**Issue by mordrax** [aldeed/meteor-autoform#1131]
When you set validation='none', it actually forces any AutoForm.validateForm(form) call to return true. I'm not sure if this is expected behaviour, I would have thought it doesn't do any validation but also doesn't return a incorrect value for programmatically invoking validation.

Secondly, calling AutoForm.validateField(form, field) will return false and perform the validation (on the DOM too) so even though the form is valid, the fields are not!

The reason behind this is I'm using autoform with other styling snipplets so I'm just using it for schema, validation and submission and want to have my own trigger for validation.

WORKAROUND:
I'm currently setting validation='submit' and evoking AutoForm.validateForm(form) whenever my triggers fire. This works as expected.

**Comment by mj1930** [comment]
Can you show me the code of that autoform as how did you use it because when i set it to none it isn't working.

**Comment by mordrax** [comment]
This issue is a year old and I have moved away from meteor, closing as no longer applicable.
