### ISSUE TITLE
formId is undefined in afFieldValueIs helper

### ISSUE THREAD

**Issue by tab00** [aldeed/meteor-autoform#1142]
I was having intermittent problems with using afFieldValueIs in a template; sometimes it was reactive, sometimes it wasn't.

So I did a little debugging in the autoform code and found that formId was often undefined in the options object that is passed into getFieldValue in the afFieldValueIs helper:

```
Template.registerHelper('afFieldValueIs', function autoFormFieldValueIs(options) {
  options = parseOptions(options, 'afFieldValueIs');

  var currentValue = AutoForm.getFieldValue(options.name, options.formId);
  return currentValue === options.value;
});
```

Passing a hard-coded form ID value into the getFieldValue function worked.

Please fix it so that options.formId is not undefined.

**Comment by serkandurusoy** [comment]
This looks like #1136 which is caused by something in the 5.4.1 update
