### ISSUE TITLE
Support for react?

### ISSUE THREAD

**Issue by nikhildaga** [aldeed/meteor-autoform#1164]
Dear @aldeed ,  is it possible for you to provide support for using autoform with reactjs ? Can you guide of way to do so?

P.S. :  You have addicted us to meteor-autoform. We don't like using anything else now.

**Comment by Gaelan** [comment]
I'm going to try to wrangle `thereactivestack:blazetoreact` into allowing us to use AutoForm from React. No promises, but if I get it to work I'll but it on Atmosphere.

**Comment by petewwa** [comment]
@Gaelan, I just tried blazetoreact and it seems to get the job done. Thanks!

**Comment by Gaelan** [comment]
@petewwa The problem with BTR is that it doesn't (currently) support block helpers, so you will only be able to use `quickForm`. Hopefully, I'll have something on Atmosphere soon that gets it to work.

**Comment by petewwa** [comment]
@Gaelan have you made any progress on block helpers?

**Comment by Gaelan** [comment]
Sadly, I have given up for now. My WIP code is in a PR on blaze-to-react. Sorry!

**Comment by jrothman** [comment]
+1 for React AutoForm

**Comment by aldeed** [comment]
Not on the roadmap for now. There is too much to do already with Blaze improvements, but I will revisit eventually if people stick with React and do not move on to pure web components or some other new thing.

**Comment by petermikitsh** [comment]
@aldeed Given the recent announcements from MDG, are you considering a separate repository for React?

**Comment by sahanDissanayake** [comment]
Cmon lets make this happen guys

**Comment by zhaoyao91** [comment]
+1 for autoform-react

**Comment by zyu** [comment]
for autoform-react

**Comment by TedAvery** [comment]
+1

**Comment by TedAvery** [comment]
In the meantime, is there a more hacky way to do this that will at least work?
In the new [Meteor React](https://www.meteor.com/tutorials/react/adding-user-accounts) tutorial they make a wrapper component for a Blaze template. So I've followed the same principle and I'm able to make a QuickForm.

```
QuickFormWrapper = React.createClass({
  componentDidMount() {
    this.view = Blaze.renderWithData(Template.quickForm, this.props, ReactDOM.findDOMNode(this.refs.container));
  },
  componentWillUnmount() {
    // Clean up Blaze view
    Blaze.remove(this.view);
  },
  render() {
    // Just render a placeholder container that will be filled in
    return <span ref="container" />;
  }
});
```

And then put one of these somewhere: `<AutoFormWrapper collection="FormTemplate" id="insertTemplateForm" type="insert" />`

But I don't know how to do a wrapper for AutoForm because of the opening and closing tags it uses in Blaze. Is there any other solution I can use right now?

**Comment by zhaoyao91** [comment]
@TedAvery I don't know how to make `autoForm` a react comp, but you can make a `concrete autoForm` react comp. See my demo project if something can help you.
[github](https://github.com/zhaoyao91/meteor-react-autoform-demo/tree/master/packages)

**Comment by aldeed** [comment]
There will almost certainly be something like autoform that supports react. In the near term, it will probably involve splitting out the pieces of autoform that are not blaze-specific into separate packages. First I need to finish SimpleSchema v2 and the replacement for Collection2, though. :)

**Comment by Custos** [comment]
@aldeed the amount of work you do wrangles my head.

**Comment by thearabbit** [comment]
:+1:

**Comment by petermikitsh** [comment]
For those that are looking to migrate to React quickly, there certainly are existing solutions for forms, such as [redux-form](https://github.com/erikras/redux-form).

**Comment by nicolaslopezj** [comment]
https://github.com/nicolaslopezj/meteor-react-form

This new projects attempts to create the same functionality of Autoform for React.

**Comment by thearabbit** [comment]
How, I will check soon :+1: .

**Comment by ThomasHoadley** [comment]
Am I correct in thinking this issue can be resolved as described in the Meteor guide? (I'm new to meteor / react so apologies if its a silly question!)

http://guide.meteor.com/react.html#blaze-in-react

**Comment by wesleyfsmith** [comment]
I do this

`import Blaze from 'meteor/gadicc:blaze-react-component';`
`<Blaze template="quickForm" schema="requiredProviderSchema" id="providerDetailsForm" />`

And that has worked perfectly so far.

**Comment by nickwild-999** [comment]
@wesleyfsmith: Sorry I am a newbie with Meteor. I can get your solution to work with a schema, but when I replace with a collection and type=insert I get an error  "not in the window scope."

Any thoughts ?

**Comment by nickwild-999** [comment]
@wesleyfsmith have you managed to get autoform to work with all the associated formatting?

**Comment by divyanshupathak** [comment]
Hello @wesleyfsmith ,
Can you please share some more code ? I am also stuck on the same issue.

Thanks

**Comment by DeanKamali** [comment]
+1 for React AutoForm

**Comment by thearabbit** [comment]
@DeanKamali, Please check alternative [Uniforms](https://github.com/vazco/uniforms)

**Comment by DeanKamali** [comment]
@thearabbit thanks very much, will definitely check it out.
