### ISSUE TITLE
endSubmission is called whenever onSubmit returns false

### ISSUE THREAD

**Issue by panayi** [aldeed/meteor-autoform#1172]
With the `type = normal` and an onSubmit hook:

```html
{#autoForm schema=registerSchema class="p-t-15" id="registerForm" type="normal"}}
  <!-- ... -->
{{/autoForm}} 
```

```coffeescript
AutoForm.addHooks ['registerForm'],
  onSubmit: (doc) ->
    # Run some async code that calls this.done() when is complete
    false
```

Looking at https://github.com/aldeed/meteor-autoform/blob/8544c659ea5235bbbc9f737e170d405c11e23cac/formTypes/normal.js#L54, it seems that `this.endSubmission()` is called when the `onSubmit` hook returns `false`. Shouldn't `endSubmission` be called inside the call of `done` (passed to the hook)?

**Comment by aldeed** [comment]
You're right. Fixed in 5.7.1
