### ISSUE TITLE
question: server vs client side

### ISSUE THREAD

**Issue by streamnsight** [aldeed/meteor-autoform#1197]
Sorry this is not an issue but I'm struggling with some basic concept here:
the schema is used both on server and client side... that's exposing quite a bit of the inner workings of my DB.
is it possible to have a schema for the client side and one for the server side where obviously the client side schema is a subset of the server side schema?
I'm not sure to understand how that works.
Thanks for help.

**Comment by aldeed** [comment]
If attaching schemas with Collection2, it's best for them to be the same, or call `attachSchema` only in server code. Your form schemas can be anything you want on the client. There isn't really any link back and forth from the server to the client schemas, so you can define variations of the same schema in client vs. server code. The important thing is that whatever passes validation with your client schema will need to pass your server schema, too.
