### ISSUE TITLE
TypeError: Cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-autoform#1200]
I am trying to create an update autoform. I have tried to pass the document as a template helper and local data context, and both are producing the same error:

```
TypeError: Cannot read property 'schema' of undefined
```

# Template helper
I have tried to pass a document in to autoForm via a template helper, as such:

```javascript
'document': function () {
    // Get Home ID from template data context
    // convert the 'String' object to a string for the DB query
    var documentId = this.toString();
    
    // Get home document
    var document = Documents.findOne(documentId);
    console.log(document);
    return document;
}
```

# Data context

I have also tried passing the document as a template data context and constructing the AutoForm as such:

```html
{{#autoForm id="editDocument" type=update collection=Documents doc=this  }}
...
```

When using `this` in the template, it behaves as expected:

```html
{{ this.title }} <!-- displays the document title in the template -->
```

# Package versions
My Meteor project is at version 1.1.0.3.

Here is the output of `meteor list`:
```
...
aldeed:autoform                5.5.0 
aldeed:autoform-select2        1.0.5* 
aldeed:collection2             2.5.0 
aldeed:simple-schema           1.3.3
...
```

# Related issues
I have found the following issues, which may be related:
* https://github.com/aldeed/meteor-autoform/issues/790
* https://github.com/aldeed/meteor-autoform/issues/753
* https://github.com/aldeed/meteor-autoform/issues/350

**Comment by brylie** [comment]
I am running AutoForm 5.5.0. I have also tried passing the document as a template data context and constructing the AutoForm as such:

```html
{{#autoForm id="editDocument" type=update collection=Documents doc=this  }}
...
```

When using `this` in the template, it behaves as expected:

```html
{{ this.title }} <!-- displays the document title in the template -->
```

**Comment by brylie** [comment]
Here is the output of `meteor list`
```
...
aldeed:autoform                5.5.0 
aldeed:autoform-select2        1.0.5* 
aldeed:collection2             2.5.0 
aldeed:simple-schema           1.3.3
...
```

**Comment by aldeed** [comment]
It has nothing to do with your document. It's complaining about `collection=Documents`. Probably you do not have a helper named "Documents", so you meant to do `collection="Documents"`

**Comment by dakota11** [comment]
I was getting the same error when my schema was formatted as such :

```
var Schemas = {};
Schemas.Room = new SimpleSchema({
    title: {
        type: String,
        label: "Title",
        max: 200
    }
});
```

When I changed my schema to :

```
Rooms.attachSchema(new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  }
}));
```

It worked...
