### ISSUE TITLE
Select options that depends on another field value

### ISSUE THREAD

**Issue by shactdeveloper** [aldeed/meteor-autoform#1202]
Hi, lets say I have a collection called Countries and one called States. In the app, you can select a country and then multiple states from that country

And in my simpleschema:
```
countryId:{
 type: String,
 autoform:{
  type:'selectize',
  options:{
    return Countries.find().map(function (c) {
        return {label: c.name, value: c._id};
    });
  }
 }
},
statesIds:{
 type: [String],
 autoform:{
  type:'selectize',
  multiple:'true',
  options:{
    AutoForm.getFieldValue('countryId');
    return States.find({countryId:countryId).map(function (c) {
        return {label: c.name, value: c._id};
    });
  }
 }
},
```

The problem is, when an UPDATE autoform is generated (so I already have a country selected), the options of States are not populated until I change the country select field for something else (to call the 'change' event)
Is there a way to solve this?
(I know that this data modeling for countries/states is not the best for no-sql, but this was just an example)

**Comment by bySabi** [comment]
@shactdeveloper do you solved?
I have infinite rerun on `statesIds.auotoform.options` function

**Comment by shactdeveloper** [comment]
Try using universe-select

**Comment by bySabi** [comment]
Thanks for advice on `universe-select`. Look nice!
Actually my problem was that in put `AutoForm.getFieldValue` on a nested schema and from them siblings fields reactivy don´t fire.

**Comment by aldeed** [comment]
This is most likely a problem with selectize plugin not properly implementing option reactivity.
