### ISSUE TITLE
Add possible values, along with allowed values

### ISSUE THREAD

**Issue by taxigy** [aldeed/meteor-autoform#1203]
I faced a challenge which is, I believe, very common. I have a collection property that is basically a `String`, and I want to recommend users possible values but not constrain them within `allowedValues`. Say, something like this:

```javascript
Schemas.Contact = new SimpleSchema({
    name: {
        type: String,
        label: 'Name',
        unique: true
    },
    livesIn: {
        type: String,
        defaultValue: 'Singapore',
        possibleValues: [
        	'Shanghai',
        	'Beijing'
        ]
    }
});
```

which should basically be picked by autoform and rendered as an input field with autosuggestion or similar. The key point is to store possible values within the schema, not helpers or such.

Right now, I'm getting the following error:

```
W20150917-11:55:53.356(4)? (STDERR) Error: Invalid definition for livesIn field.
W20150917-11:55:53.356(4)? (STDERR)     at packages/aldeed:simple-schema/simple-schema.js:465:1
```

Is it fixable somehow easier than via PR?

**Comment by aldeed** [comment]
This is what options are for: https://github.com/aldeed/meteor-autoform#what-are-the-various-ways-i-can-specify-options-for-a-select-radio-group-or-checkbox-group
