### ISSUE TITLE
How to set parentId?

### ISSUE THREAD

**Issue by MichaelJCole** [aldeed/meteor-autoform#1211]
Hi, I have a collection of Parents.  
On a Parent's template, is an Add Child button
```
    <a class="btn btn-lg btn-primary" href="{{pathFor 'childNew' parentId=this._id}}">Add Child</a>
```
How do I set the new childs `parentId` using quickform?
```
<template name="childNew">
  {{> quickForm collection="Children"
      id="childInsertForm"
      type="insert"
      autosave=true
      }}
</template>
```
Thanks!

**Comment by aldeed** [comment]
Add `doc=doc` and add a `doc` template helper that returns `{parentId: this.parentId}`

**Comment by MichaelJCole** [comment]
Awesome!  Thanks!
