### ISSUE TITLE
Validate/require a field

### ISSUE THREAD

**Issue by Rastalamm** [aldeed/meteor-autoform#1212]
I have a radio list of options to select. 

On the last one, it displays an input field. (kinda like an other category)

How can I validate and more importantly show a message if 
1. No options are chosen (currently its set to required but no message is displayed)
2. The last option is chosen but the input field is blank - no idea how to add a conditional required to this.

Any help is appreciated.

**Comment by aldeed** [comment]
See here for conditional requiredness: https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required

There should be an error message if no options are chosen and it's required. If this isn't working, please submit a new issue with a link to a simple reproduction app.
