### ISSUE TITLE
defaultValue/autoValue doesn't seem to set the values when using method type form

### ISSUE THREAD

**Issue by mbabauer** [aldeed/meteor-autoform#1218]
In my form I have a `state` field that represents the current state of the request: `Request`, `Approved`, `Inspected`, and `Completed`.  When a user fills out the form, I want the `state` to default to `Request`, but when the `Method.call` happens state isn't set.

Here is my schema code:
```javascript
Assignments = new Mongo.Collection("assignments");

var Schemas = {};

Schemas.Assignment = new SimpleSchema({
	firstName: {
		type: String,
		label: "First Name",
		max: 200
	},

	lastName: {
		type: String,
		label: "Last Name",
		max: 200
	},

	email: {
		type: String,
		label: "Email",
		regEx: SimpleSchema.RegEx.Email,
		max: 200
	},

	state: {
		type: String,
		label: "Assignment State",
		allowedValues: ['Request', 'Approved', 'Inspected', 'Completed'],
		autoValue: function() {
			var state = this.field('state');
			if (!state.isSet) {
				return 'Request';
			}
		},
		autoform: {
			firstOption: false,
			options: [
				{label: 'Request for Assignment', value: 'Request'},
				{label: 'Approved/Waiting Scheduled', value: 'Approved'},
				{label: 'Inspected/In Report Draft', value: 'Inspected'},
				{label: 'Completed', value: 'Completed'}
			]
		}
	},

	scheduledAt: {
		type: Date,
		label: "Scheduled On",
		optional: true,
		autoform: {
			afFieldInput: {
				type: 'bootstrap-datepicker'
			}
		}
	},

	estimatedCompletion: {
		type: Date,
		label: "Scheduled On",
		optional: true,
		autoform: {
			afFieldInput: {
				type: 'bootstrap-datepicker'
			}
		}
	},

	fileIds: {
		type: [String],
		label: "Attachments",
		autoform: {
			afFieldInput: {
				type: 'cfs-files',
				collection: 'attachments'
			}
		},
		optional: true
	},

	// Force value to be current date (on server) upon insert
	// and prevent updates thereafter.
	createdAt: {
		type: Date,
		autoValue: function() {
			if (this.isInsert) {
				return new Date;
			} else if (this.isUpsert) {
				return {$setOnInsert: new Date};
			} else {
				this.unset();  // Prevent user from supplying their own value
			}
		},
		denyInsert: false,
		denyUpdate: true,
		optional: true
	},
	
	// Force value to be current date (on server) upon update
	// and don't allow it to be set upon insert.
	updatedAt: {
		type: Date,
		autoValue: function() {
			if (this.isUpdate) {
				return new Date();
			}
		},
		denyInsert: true,
		optional: true
	}
});

Assignments.attachSchema(Schemas.Assignment);
```

I also tried having state like:
```javascript
state: {
	type: String,
	label: "Assignment State",
	allowedValues: ['Request', 'Approved', 'Inspected', 'Completed'],
	defaultValue: 'Request',
	autoform: {
		firstOption: false,
		options: [
			{label: 'Request for Assignment', value: 'Request'},
			{label: 'Approved/Waiting Scheduled', value: 'Approved'},
			{label: 'Inspected/In Report Draft', value: 'Inspected'},
			{label: 'Completed', value: 'Completed'}
		]
	}
}
```

And in my server, I get the error:
```
I20150924-08:49:55.471(-4)? Exception while invoking method 'createNewAssignment' Error: Match error: Assignment State is required
I20150924-08:49:55.472(-4)?     at [object Object].SimpleSchema.condition (packages/aldeed:simple-schema/simple-schema.js:602:1)
I20150924-08:49:55.472(-4)?     at checkSubtree (packages/check/match.js:220:1)
I20150924-08:49:55.472(-4)?     at check (packages/check/match.js:32:1)
I20150924-08:49:55.472(-4)?     at [object Object].Meteor.methods.createNewAssignment (app/server/methods/assignments.js:3:3)
I20150924-08:49:55.472(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150924-08:49:55.472(-4)?     at packages/ddp/livedata_server.js:648:1
I20150924-08:49:55.472(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150924-08:49:55.472(-4)?     at packages/ddp/livedata_server.js:647:1
I20150924-08:49:55.473(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150924-08:49:55.473(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150924-08:49:55.473(-4)?     at packages/ddp/livedata_server.js:546:1
I20150924-08:49:55.473(-4)? Sanitized and reported to the client as: Assignment State is required [400]
```

Which is true, `state` is required, but shouldn't it be set to the default value before the `Method.call` to the server?

I do have the following hooks in place because I am using the cfs-autoform for file uploads:
```javascript
Template.assignments.onRendered(function() {
	AutoForm.hooks({
		insertAssignmentsForm: {
			before: {
				method: CfsAutoForm.Hooks.beforeInsert
			},
			after: {
				method: function(err, result) {
					if (err) {
						console.log('An error occured: ', err);
					} else {
						console.log('Insert was successful: ', result);
						method: CfsAutoForm.Hooks.afterInsert(err, result);
					}
				}
			}
		}
	});
});
```

**Comment by skirunman** [comment]
Same problem

**Comment by mbabauer** [comment]
I ended up having to call the clean manually like this:

```javascript
Template.assignments.onRendered(function() {
	AutoForm.hooks({
		insertAssignmentsForm: {
			before: {
				method: function(doc) {
					CfsAutoForm.Hooks.beforeInsert.call(this, doc);
					
					Assignments.simpleSchema().clean(doc);
					return doc;
				}
			},
			after: {
				method: function(err, result) {
					if (err) {
						console.log('An error occured: ', err);
					} else {
						method: CfsAutoForm.Hooks.afterInsert.call(this, err, result);
					}
				}
			}
		}
	});
});
```

Notice the call to `Assignments.simpleSchema().clean(doc);` in the `before` hook.  I am not sure if this is normal behavior or not, but this is how I "fixed" it.

**Comment by skirunman** [comment]
After further reading I'm guessing the behavior is that when you submit a doc using the method type, autoform does not itself call "clean" on the doc until the method function returns from the server so autovalues never get triggered correctly. Autovalues from my schema are executing correctly using method-update type autoform. Also, I would guess most people are using collections2 with autoform and simple-schema so they don't run into this issue as collections2 runs clean on the doc itself.

I got it to work how I want by just running clean in my insert method function before doing anything else in the function and only running when on the server. 

```
// Clean doc on server to add autovalue fields. 
if (Meteor.isServer) {
  Schema.mySchema.clean(doc);
}
```

**Comment by aldeed** [comment]
autoValues are intentionally not added on the client because then you couldn't trust them, and furthermore, your `isSet` checks when running the autoValues again on the server would be incorrect because they would now be set. So the correct solution is to call `clean` at the top of your method, which is best practice anyway.

**Comment by mbabauer** [comment]
@aldeed So, you are saying the better approach would be to call the `clean()` in the server-side method prior to doing the `check()`?  Hmm, I guess I never thought about doing it that way, but it seems to make sense.

**Comment by aldeed** [comment]
Yes. You can do some client side cleaning if you really need to optimize, but the point is to be aware that you could get unexpected behavior if you set auto values on the client and then are checking `isSet` again on the server because you can't know whether they were set by the user or by the client-side autovalue cleaning, plus automatic Dates could be wrong, etc. It's usually safest to do all cleaning on the server.

**Comment by mbabauer** [comment]
How does that work with validation?  If a field is not optional, and doesn't have a value, does the code know to ignore it's validation until the `clean()` is called?

**Comment by xpluscal** [comment]
+1 for @mbabauer

**Comment by tetiogit** [comment]
+1 too @mbabauer

**Comment by Mzwamandla** [comment]
can anyone help, is't  possible to use function to get defaultValue from a collection, or just use a function to get default values like this..

`state: {

    type: String,
    label: "Assignment State",
    allowedValues: ['Request', 'Approved', 'Inspected', 'Completed'],
    defaultValue:  function () {
      return ['Request', 'Approved', 'Inspected', 'Completed'];
    }'  
    autoform: {
        firstOption: false,
        options: [
            {label: 'Request for Assignment', value: 'Request'},
            {label: 'Approved/Waiting Scheduled', value: 'Approved'},
            {label: 'Inspected/In Report Draft', value: 'Inspected'},
            {label: 'Completed', value: 'Completed'}
        ]
    } 
}`
