### ISSUE TITLE
Within a custom()-method: How to save to a different field within an embedded array?

### ISSUE THREAD

**Issue by thebarty** [aldeed/meteor-autoform#1219]
Hi guys,

I am building a icecream-order-machine where customers place their icecream-orders. :+1: 

There are 2 Collections: 
1) Scoops (= our inventory, types of scoops) 
2) ScoopOrders (= a customer can order multiple amounts of scoops).
**An example: "Jimmy Hendrix orders 2 scoops of vanilla and 3 scoops of chocolate."**

The orderItems are embedded as an array into the ScoopOrder Collection. 

**Question:**
We are doing MongoDB-NoSQL, so the best way to go is to **save the scoop._id** PLUS the **full ScoopObjekt** for each ScoopOrder.

**How do I do this with Collection2 & Autoform?**

This is the code I have so far - I am stuck within the custom() method:

```
AutoformScoopOrders = new Mongo.Collection('autoformscooporders');

autoformScoopOrdersSchema = new SimpleSchema({
  customerName: {
    type: String
  },

  // scoopItems Array
  scoopItems: {
    type: Array,
    optional: true,
  },
  'scoopItems.$': {
    type: Object
  },
  'scoopItems.$.amount': {
    type: Number,
  },
  'scoopItems.$.scoopId': {
    type: String,
    autoform: {  // Foreign-Key Relationship to single Scoops-Object
      options: function () {
        return Scoops.find().map(function (c) {
          return {label: c.name + '( ' + c.price + '$ )', value: c._id};
        });
      }
    },
    custom: function () {
      if (this.isInsert || this.isUpdate) {
        var theScoopInstance = Scoops.findOne(this.value);
        **// QUESTION: How do I save the instance to scoopItems.$.scoopInstance?**
      }
    },
  },
  'scoopItems.$.scoopInstance': {
    type: Object,
    optional: true,
    autoform: {
      type: 'hidden',
      label: false,
    },
  },  
});

AutoformScoopOrders.attachSchema(autoformScoopOrdersSchema);
```

**Comment by serkandurusoy** [comment]
Try this, or something similar since I have not tested this, but it should point you in the right direction.

```javascript
AutoformScoopOrders = new Mongo.Collection('autoformscooporders');

autoformScoopOrdersSchema = new SimpleSchema({
  customerName: {
    type: String
  },
  // scoopItems Array
  scoopItems: {
    type: Array,
    optional: true,
  },
  'scoopItems.$': {
    type: Object
  },
  'scoopItems.$.amount': {
    type: Number,
  },
  'scoopItems.$.scoopId': {
    type: String,
    autoform: {  // Foreign-Key Relationship to single Scoops-Object
      options: function () {
        return Scoops.find().map(function (c) {
          return {label: c.name + '( ' + c.price + '$ )', value: c._id};
        });
      }
    }
  },
  'scoopItems.$.scoopInstance': {
    type: Object,
    blackbox: true // or define schema keys for instance properties if you want
    optional: true,
    autoValue: function () {
        var theScoopInstanceId = this.siblingField('scoopId');
        var theScoopInstance = theScoopInstanceId.isSet && Scoops.findOne(theScoopInstanceId.value);
        return _.omit(theScoopInstance, '_id');
    },
    autoform: {
      omit: true;
    },
  },  
});
```

**Comment by MikeSmith12222** [comment]
Hi @serkandurusoy 

yeah man! Got it going:

```
  'scoopItems.$.scoopInstance': {
    type: Object,
      blackbox: true, // or define schema keys for instance properties if you want
      optional: true,
      autoValue: function () {
          var theScoopInstanceId = this.siblingField('scoopId');
          var theScoopInstance = theScoopInstanceId.isSet && Scoops.findOne(theScoopInstanceId.value);
          return _.omit(theScoopInstance, '_id');
      },
      autoform: {
        omit: true,
      },
  },
```

Now I'll try to use collection-hooks to update the scoopInstance on update/deletes on the Scoops Object.

Thanks a lot for your help!

**Comment by serkandurusoy** [comment]
No problem, glad it worked!

Sent from my iPhone



On Sep 28, 2015, at 10:36, MikeSmith12222 <notifications@github.com> wrote:

Hi @serkandurusoy <https://github.com/serkandurusoy>

yeah man! Got it going:

  'scoopItems.$.scoopInstance': {
    type: Object,
      blackbox: true, // or define schema keys for instance properties
if you want
      optional: true,
      autoValue: function () {
          var theScoopInstanceId = this.siblingField('scoopId');
          var theScoopInstance = theScoopInstanceId.isSet &&
Scoops.findOne(theScoopInstanceId.value);
          return _.omit(theScoopInstance, '_id');
      },
      autoform: {
        omit: true,
      },
  },

Now I'll try to use collection-hooks to update the scoopInstance on
update/deletes on the Scoops Object.

Thanks a lot for your help!

—
Reply to this email directly or view it on GitHub
<https://github.com/aldeed/meteor-autoform/issues/1219#issuecomment-143661034>
.
