### ISSUE TITLE
Limit access to logged in user

### ISSUE THREAD

**Issue by Atu** [aldeed/meteor-autoform#1226]
Hi there,

Do you have an idea to limit the submission to logged in users? For example to submit, you have to register.

Thanks

**Comment by aldeed** [comment]
There are many ways you could do this. On the client, you might want to hide the submit button if there isn't a current user. Securing it on the server would depend on what your form is doing and how it is doing it. If you're submitting to a method, throw an error at the top of the method if `this.userId` isn't set. If form is directly inserting or updating, then use a deny rule that prevents the action when `userId` isn't set.
