### ISSUE TITLE
Manually added autoform-remove-item button

### ISSUE THREAD

**Issue by kovacss** [aldeed/meteor-autoform#1228]
Hello,

I'm trying to edit manually an array with these 2 buttons:

`<button type="button" class="autoform-add-item" data-autoform-field="questions">add</button>`
`<button type="button"class="autoform-remove-item" data-autoformfield="questions"> delete</button>`

Adding a new item works but I can't remove an item from the 'questions' field.
I think I have this issue because I have an array inside another array (so I have two buttons with 'autoform-remove-item' class). I want to associate each buttons to a different autoformfield.

I checked meteor-autoform source code and I think that to make the 'autoform-remove-item' button work in my case, we should pull data related to the field from html data attributes (like 'autoform-add-item'). 

Thank you.

**Comment by bipin244** [comment]
if you use collection2 than
```
minCount: 1,
maxCount: 1
```
I think this work for you
