### ISSUE TITLE
"blur" validation remove manual error UI

### ISSUE THREAD

**Issue by Adiel-Sharabi** [aldeed/meteor-autoform#1231]
Hi, 
I'm adding manually error with "context.addInvalidKeys(..)" 
The error is show up for a sec and then disappear. 
The validation type is "blur". when I remove it the error stay... 
The invalidKeys function still contain the error but the UI clear it. 
Tnks

**Comment by Adiel-Sharabi** [comment]
I managed to workaround with sticky errors but it's not "clean" 
```
AutoForm.templateInstanceForForm(formId)._stickyErrors[key] = {type: "customType", value: customValue};
````
and to remove
````
delete AutoForm.templateInstanceForForm(formId)._stickyErrors[key];
````

maybe the sticky errors should be more public.

**Comment by aldeed** [comment]
5.7.0 now has `AutoForm.addStickyValidationError` and `AutoForm.removeStickyValidationError`.
