### ISSUE TITLE
Best way to add numeric values as a field in a schema.

### ISSUE THREAD

**Issue by rwatts3** [aldeed/meteor-autoform#1236]
Greetings,

I want to track how many times an item in a specific schema is clicked. 
I have banner ads, and on the front end I will increase a value in the db whenever the ad is clicked.
When the user looks at the form in the admin panel I'd like to show them 22 impressions or 9999 impressions, etc. 

Is there any recommended approach to getting this accomplished.

**Comment by aldeed** [comment]
Set the schema to `type: Number` and then do an update with `{$inc: {counter: 1}}` every time it is clicked, assuming you name the property `counter`.

**Comment by rwatts3** [comment]
Thank you I appreciate the follow up. I will give that a shot
