### ISSUE TITLE
How to dynamically generate the name parameter for an autoform component?

### ISSUE THREAD

**Issue by maxfi** [aldeed/meteor-autoform#1240]
Is there a way to set a dynamic name attribute on an autoform field by taking part of the name from the data context and the other part from a parameter in the autoform field spacebar template? 

Example:
* The expected name parameter is `name="firstString.secondString"`. 
* The "firstString" part is in the context at `this.firstString` 
* The "secondString" part should be passed in via the spacebar template like `{{> afQuickField  secondString="secondOutput }}`
* The expected rendered field should be the same as if I had directly called `{{> afQuickField  name="firstString.secondOutput }}`
* Other parameters such as `label`, etc should still be correctly passed to `afQuickField`.

The reason I'm trying to achieve this is to be able to access properties of an object who's name is passed to included templates from a parent context.

It's quite possible that I'm going about this completely the wrong way...

**Comment by aldeed** [comment]
With Meteor 1.2 you could use a nested subexpression

```
{{> afQuickField name=(combine firstString "secondString")}}
```

Where `combine` is a helper defined like this:

```js
combine: function (first, second) {
  return first + '.' + second;
}
```

**Comment by maxfi** [comment]
Nice one @aldeed! Thanks!
For reference: https://github.com/meteor/meteor/pull/4101
