### ISSUE TITLE
Question: Best way to customize embedded arrays?

### ISSUE THREAD

**Issue by thebarty** [aldeed/meteor-autoform#1243]
Hi guys,

I have an simple schema with an embedded array
and within the autoform I'd like to customize it's individual fields via a ``afQuickField``.

Right now I am embedding the array with a {{> afArrayField name='embeddedArrayData'}} which gives me **no option** to use ``afQuickField`` or to wrap individual element with html.

I'd like to do something like:
```
// PSEUDO CODE ( NOT WORKING )
{{>each arrayField='embeddedArrayData'}}
    {{afQuickfield name='field1'}}
    {{afQuickfield name='field2'}}
{{/each}}
```

**Whats the best way to do this?**
**Any ideas?**

*PS*
*I opened the same topic on meteor forums:  https://forums.meteor.com/t/autoform-gurus-how-to-customize-an-embedded-array/11285*

**Comment by aldeed** [comment]
Is this what you're looking for? https://github.com/aldeed/meteor-autoform#afeacharrayitem

**Comment by thebarty** [comment]
@aldeed: Thanks a lot for your tip. Reading the docs is always a good thing. They made me realize that the schema is the solution.

I just ended up doing simple things in the schema like:
```
    autoform: {
      afFormGroup: {
        'formgroup-class': 'col-md-9',
      }
    }
```

That should do it for now! :+1:
