### ISSUE TITLE
AutoForm Hooks not working

### ISSUE THREAD

**Issue by Bala2Excel** [aldeed/meteor-autoform#1252]
HI, 

I have installed aldeed:autoform 5.7. 

This is my code. I am unable to hook onto the OnSubmit Method. I need to redirect to the list page when the user adds a new item. Please point me in the right direction.

<template name="insertCalendarForm" >
 {{#autoForm collection="Calendar" id="insertCalendarForm" type="insert"}}
  <fieldset>
    <legend>Add a Book</legend>
    {{> afQuickField name='title' template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9" }}
    {{> afQuickField name='presenter' template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}
    {{> afQuickField name='summary' rows=6 template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}
    {{> afQuickField name='trainingDate' template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}
  </fieldset>
  <button type="submit" class="btn btn-primary">Insert</button>
  {{/autoForm}}
</template>

AutoForm.hooks({
  insertCalendarForm: {
    onSubmit: function (insertDoc, updateDoc, currentDoc) {
      console.log("Inside the onSubmit....");
      this.done();
      return false;
    }
  }
});

**Comment by seanfcarroll** [comment]
You want something like this

```
AutoForm.addHooks('insertCalendarForm', {
  after: {
    insert: function(error, result) {
      if (error) {
        console.log("Insert Error:", error);
      } else {
        console.log("Document inserted:", result);
        Router.go('listCalendars');  // or whatever your list route is called
    },
```

PS - these questions are better asked on StackOverflow or the Meteor forums. Good luck!

**Comment by Bala2Excel** [comment]
Sorry for the late reply. I just got back to this issue and got it working. Thanks
