### ISSUE TITLE
Please add simple captcha field type option to autoform

### ISSUE THREAD

**Issue by cyclops24** [aldeed/meteor-autoform#1260]
Hi,

I used autoform for many project and really love it but unfortunately I didn't find a simple captcha addOn for it on the other side all of the captcha package available in atmospherejs are about reCaptcha (see [this link](https://atmospherejs.com/?q=captcha)) I also asked a [question in stackoverflow](http://stackoverflow.com/questions/31891786/simple-captcha-field-type-for-meteor-autoform) and after 2 month and 150 view nobody help me to create simple captcha field type for autoform.

I create this issue to suggest that please add a simple and handy captcha support to autoform. (really simple and without external service and dependency and independent of recaptcha for handy usage)
Many captcha packages available in npm repository like [this](https://www.npmjs.com/package/node-captcha).

Thanks for your attention and for awesome package.

**Comment by aldeed** [comment]
Added this request to https://github.com/aldeed/meteor-autoform/issues/438
