### ISSUE TITLE
Doubt with relationship

### ISSUE THREAD

**Issue by weverton** [aldeed/meteor-autoform#1264]
I have two schemas and the second has a relationship with the first. How can I do to show the list of data of first schema on second schema autoform?? Actually it shows a form to create a new first schema item.

**Comment by robertclarkson** [comment]
It sounds liek you need an update form rather than an insert form

**Comment by weverton** [comment]
No. I need a list (select control) to choose one item.

**Comment by aldeed** [comment]
https://github.com/aldeed/meteor-autoform#use-a-helper
