### ISSUE TITLE
How can I access a checkbox's value on success?

### ISSUE THREAD

**Issue by kayvanbree** [aldeed/meteor-autoform#1269]
I want to add some logic that depends on a checkbox (I want to close modals if we don't want to add another). How can I access the checked attribute of my field? The following does not work, as getFieldValue returns undefined (the actual value attribute, not checked):

``` Javascript
AutoForm.addHooks(['insertArtistForm'], {
  onSuccess: function(formType, result){
    var addAnother = AutoForm.getFieldValue("addAnother");
    console.log(addAnother);
    if(!addAnother){
      $('.modal').modal('hide');
    }
  }
});
```

I should mention that I didn't add the checkbox to the Schema of the artist. I don't want it to be saved, so I should not put it in the Schema, right?

**Comment by marktomm** [comment]
You can try

```javascript
var addAnother = AutoForm.getFieldValue("addAnother", "FormId");
```

maybe that will work, can't test right now, sry.

Also why not get the value from the 'before' hooks if you use type=update/insert/

```javascript
AutoForm.addHooks(['insertArtistForm'], {
  before: {
    formType(insert or update): function(doc) {
      var addAnother = doc.addAnother;
    }
  }
});
```

Or in the 'onSumbit' hook if the form type is 'normal'
```javascript
AutoForm.addHooks(['insertArtistForm'], ({
  FormId: {
    onSubmit: function (insertDoc, updateDoc, currentDoc) {
      currentDoc = currentDoc.addAnother;
      // or mb var addAnother = AutoForm.getFieldValue("addAnother");
    }
  }
});
```

```
I should mention that I didn't add the checkbox to the Schema of the artist. I don't want it to be saved, so I should not put it in the Schema, right?
```

Does it work?
You can put it in the Schema, add 'optional = true' attribute to the Schema element and remove it from the doc in those before/onSubmit hooks from the doc/form.

```javascript
Books.attachSchema(new SimpleSchema({
....  
  addAnother: {
    ....
    optional = true,
    ....
  },
....
}));

AutoForm.addHooks(['insertArtistForm'], {
  before: {
    formType(insert or update): function(doc) {
      //removedoc.addAnother
    }
  }
});
```

**Comment by kayvanbree** [comment]
I ended up with a solution that uses this.event to get to the checkbox. It saves add another as a Session variable in the before hook. In the onSuccess hook it gets it from the Session. I found out that the form will be erased at the onSuccess hook, so you will always end up with addAnother = false. Here's my code:

``` Javascript
AutoForm.addHooks(['insertArtistForm', 'insertGenreForm', 'insertProductionForm'], {
  before: {
    insert: function(doc){
      var addAnother = this.event.target.addAnother.checked;
      Session.set("addAnother", addAnother);
      return doc;
    }
  },
  onSuccess: function(formType, result){
    if(!Session.get("addAnother")){
      $('.modal').modal('hide');
    }
  }
});
```
As you can see I can now use this hook on multiple forms without changing the schemas. Exactly what I want, except for one tiny hickup. Every time I set addAnother to true, it defaults back to false, so I have to set it everytime I want to add another. Now I'm thinking: maybe there's another way that's better. Is there a way to prevent a field from being reset after submit? 

Something like the following would be the perfect solution, but I don't know if it's possible:
```Javascript
AutoForm.addHooks(['insertArtistForm', 'insertGenreForm', 'insertProductionForm'], {
  onSubmit: function(formType, result){
    AutoFormgetField("addAnother").preventReset(true);
  }
});
```

**Comment by marktomm** [comment]
You said before that you didn't add 'addAnother' to the Schema, bc you don't want to add it to the artist Collection, then why not take the checkbox out of the autoform and make a separate checkbox outside with a simple Template event?

**Comment by marktomm** [comment]
If You for some reason need the checkbox in the autoform then You could use 'autoform' type Autoforms (https://github.com/aldeed/meteor-autoform#autoform-1) 'resetOnSuccess' option to turn off the reset of all form fields and the reset all the necessary fields in the 'OnSuccess' hook.

**Comment by kayvanbree** [comment]
The last solution would defeate my purpose of being able to use this in any form without having to rewrite code. Or is there a way to loop over the fields and reset them if they are not my field?

**Comment by marktomm** [comment]
Perhaps something like the following example:

```javascript
//test.html

<body>
  <h1>Welcome to Meteor!</h1>

  {{> test}}
</body>

<template name="test">
  {{> quickForm collection="TestColl" id="testForm" type="insert" resetOnSuccess=false}}
</template>



// test.js

TestColl = new Mongo.Collection('test');
TestColl.attachSchema(new SimpleSchema({
  title: {
    type: String
  },
  anotherElem: {
    type: Number
  },
  checkBox: {
    type: Boolean,
    optional: true
  }
}));

if (Meteor.isClient) {
  AutoForm.hooks({
    testForm: {
      before: {
        insert: function(doc) {
          doc.checkBox = undefined;
          return doc;
        }
      },
      onSuccess: function(formType, result) {
        var keys = _.without(this.ss._schemaKeys, 'checkBox');
        
        $('#testForm :input').each(function() {
          if(_.contains(keys, this.name)) {
            $(this).val('');
          }
        });
      }
    }
  });
}
```

(used jquery and underscore)
