### ISSUE TITLE
afEachArrayItem does not work with meteoric

### ISSUE THREAD

**Issue by Kunal1985** [aldeed/meteor-autoform#1272]
Hi,

I have tried using the below code template for Array fields in one of my collections.

<template name="afArrayField_custom">
  {{#afEachArrayItem name=this.atts.name }}
            {{afFieldLabelText name=this.current.label }}
            {{> afFieldInput name=this.current.amount }}
  {{/afEachArrayItem}}      
</template>

This does not work as the fields get displayed, add/remove buttons also work fine but nothing gets saved to the collection.
Not sure if this is a problem with meteor version 1.2.0 or with meteoric.

Kindly suggest.

Thanks,
Kunal Kishor Ugale

**Comment by seanfcarroll** [comment]
Please provide a link to a sample repo with the issue.

**Comment by Kunal1985** [comment]
Sorry for a delayed response here. This is resolved as there was problem with the way how I was using the template rather than afEachArrayItem itself. Read the Meteor collection documentation for using the template and it works fine now.
