### ISSUE TITLE
Spelling mistake on Readme

### ISSUE THREAD

**Issue by robertclarkson** [aldeed/meteor-autoform#1274]
Small thing i know, but might help noobs who are getting started (like me)

on the "Another Custom Insert Form" example

{{/autoForm}}

has a capital F

this must be a lowercase f

**Comment by robertclarkson** [comment]
Actually my solution is wrong, they should both be capital F

**Comment by seanfcarroll** [comment]
Please close this issue if it is no longer valid :-)

**Comment by robertclarkson** [comment]
still valid, the opening tag should have a capital F
