### ISSUE TITLE
Hidden Fields validate on submit

### ISSUE THREAD

**Issue by Ajaxsoap** [aldeed/meteor-autoform#1277]
Hi @aldeed ,
I have an autoform that has the functionality of show/hide fields depends on the user selection like [this](http://autoform.meteor.com/fieldvalues).

My problem is why is it that the hidden fields are validated on submission? The fields that are hidden are a relationship from other collection which has a selection.

Here some of my code snippet
```
clientType: {
    type: String,
    label: "Client Type",
    allowedValues: [
      'Principal',
      'Dependent-Children',
      'Dependent-Spouse',
      'Dependent-Sibling',
      'Dependent-Parent'
    ],
    autoform: {
      type: "select",
      options: function(){
        return [
          {label:'Principal', value: "Principal"},
          {label:'Dependent-Children', value: 'Dependent-Children'},
          {label:'Dependent-Spouse', value:'Dependent-Spouse'},
          {label:'Dependent-Parent', value: 'Dependent-Parent'}
        ];
      },
      afFormGroup: {
        'formgroup-class': 'col-xs-6 col-sm-4'
      }
    }
  },
  childrenId: orion.attribute('hasMany', {
      label: "Dependent-Children",
      optional: true,
      autoform: {
        afFormGroup: {
          'formgroup-class': 'col-xs-6 col-sm-4'
        }
      }
    },
    {
      collection: Enrollments,
      titleField: 'children.name',
      additionalFields:['_id'],
      publicationName: 'childrenClaim',
      filter: function(userId) {
        var user = Meteor.users.findOne({"_id": userId},{fields: {profile: 1}});
        var admin = Roles.userHasRole(userId, "admin");
        var hq = Roles.userHasRole(userId, 'HQ');
        var branch = Roles.userHasRole(userId, 'Branch');
        var insurer = Roles.userHasRole(userId, 'insurer');
        if ( admin ) {
          console.log( "Hello Admin" );
          return {};
        } else if ( hq ) {
          console.log( "Hello HQ" );
          return { company: user.profile.company };
        } else if ( branch ) {
          console.log( "Hello Branch" );
          return { createdBy: userId };
        } else if ( insurer ) {
          console.log( "Hello Insurer" );
          return { insurer: user.profile.insurer };
        }
      }
    }),
```
Here's on the template:
```
{{> afQuickField name="clientType" options="allowed" noselect=true template="bootstrap3-inline"}}
      {{#if afFieldValueIs name="clientType" value="Dependent-Children"}}
           {{> afQuickField name="childrenId"}}
       {{/if}}
       {{#if afFieldValueIs name="clientType" value="Dependent-Spouse"}}
           {{> afQuickField name="spouseId"}}
       {{/if}}
       {{#if afFieldValueIs name="clientType" value="Dependent-Parent"}}
           {{> afQuickField name="parentId"}}
       {{/if}}
       {{#if afFieldValueIs name="clientType" value="Dependent-Sibling"}}
           {{> afQuickField name="siblingId"}}
       {{/if}}
```
As you can see, on the client-type key, if the user select the ```Dependent-Children```, the ```childrenId``` key will appear, I have the same code for parent, spouse and siblings. But during submission all the hidden fields are validated even if I set the field as optional.

How do i bypass the validation?

Thanks,

Marvin

**Comment by marktomm** [comment]
In the schema:

```javascript
someElem:
{
  label: 'some.elem',
  ...
  optional: function() {
    // logic basedon data from field values
  }
}
```

**Comment by Ajaxsoap** [comment]
Thanks @marktomm for the response!

Actually, i don't have the problem on hiding the fields. 

All the fields on the autoform options function are actually hidden, see below:

```
clientType: {
    type: String,
    label: "Client Type",
    allowedValues: [
      'Principal',
      'Dependent-Children',
      'Dependent-Spouse',
      'Dependent-Sibling',
      'Dependent-Parent'
    ],
    autoform: {
      type: "select",
      options: function(){
        return [
          {label:'Principal', value: "Principal"},
          {label:'Dependent-Children', value: 'Dependent-Children'},
          {label:'Dependent-Spouse', value:'Dependent-Spouse'},
          {label:'Dependent-Parent', value: 'Dependent-Parent'}
        ];
      },
      afFormGroup: {
        'formgroup-class': 'col-xs-6 col-sm-4'
      }
    }
  },
```
the above schema will complement to the below:
```
{{#if afFieldValueIs name="clientType" value="Dependent-Children"}}
           {{> afQuickField name="childrenId"}} // Dependent-Children
       {{/if}}
       {{#if afFieldValueIs name="clientType" value="Dependent-Spouse"}}
           {{> afQuickField name="spouseId"}} // Dependent-Spouse
       {{/if}}
       {{#if afFieldValueIs name="clientType" value="Dependent-Parent"}}
           {{> afQuickField name="parentId"}} // Dependent-Spouse
       {{/if}}
       {{#if afFieldValueIs name="clientType" value="Dependent-Sibling"}}
           {{> afQuickField name="siblingId"}} // Dependent-Sibling
       {{/if}}
```
on my form all above fields are hidden except when the user select like ```Dependent-Children``` then the children will appear with all the children from the principal Id.

My issue is, after I hit submit button, i think the hidden fields that are not selected is being validated. my proof of this is, when I removed the options function, the form will submit.

How do i bypass the validation of the hidden unselected fields?

From your suggestion, i have to put an optional function outside autoform? Something like 
```
option: function () {
  if (not selected) {
    return true;
  }
}
```
Thanks,

**Comment by marktomm** [comment]
Sry mb you haven't noticed, option/options/optional are different parameters (and idt that 'option' is valid).
I suggested giving spouseId,parentId and siblingId 'optional' parameter, which can be a function, f.ex.:

```javascript
siblingId:
{
  type: String
  label: 'Sibling Id',
  ...
  optional: function() {
    // if 'clientType' value is not 'Dependent-Sibling', return true, otherwise false
  }
}
```

Now if you would choose something other than 'Dependent-Sibling' in the form, then optional parameter for 'siblingId' would reutrn true and on insert/update/etc the value of 'siblingId' would be undefined or empty string and  (by default) empty values are not inserted into the collection and since 'siblingId' would be optional, no error will occur.

Another thing I can suggest is to use type=normal for the form itself and do all the validation manually in the onSubmit hook. 
https://github.com/aldeed/meteor-autoform#normal
https://github.com/aldeed/meteor-autoform#callbackshooks

**Comment by Ajaxsoap** [comment]
Thanks @marktomm for the insights! 

I will close this issue as I've debugged my code, there's no problem on my form validation, I have another function that's causing this issue.

Thanks.
