### ISSUE TITLE
Question: Omit required fields?

### ISSUE THREAD

**Issue by invisonybygg** [aldeed/meteor-autoform#1279]
Hello!

The way my app is made, is that you have to input your name first, (to init some db things in the callback), and then the whole form appears.

The problem is, is that I had to set all the fields to optional: true to make this work. Unless, the form wouldn submit at the first page (where only the name input is shown), since optional fields were not populated since they were hidden.

Is it possible to fix this in a way? To omit all the required fields but the name at the first page for example.

**Comment by invisonybygg** [comment]
Nobody knows?

**Comment by marktomm** [comment]
Maybe make the first form with the name a regular non-autoform form and on submit, get the value, do whatever needs to be done and then open an autoform form with the rest of the fields. If You need the name in db, you can later add it to the doc in the autoform before/onSubmit hooks .

**Comment by aldeed** [comment]
It's hard to say without seeing the actual form, but generally for this situation, you just need to use a `schema` on your form that is different from the schema attached to your collection. One that includes only the visible field.

Or use multiple forms, or set the required values to something in the beforeInsert hook. There are lots of potential ways to make it work depending on the situation.
