### ISSUE TITLE
Multiple collections, single form?

### ISSUE THREAD

**Issue by odesey** [aldeed/meteor-autoform#1280]
I have 2 Collections ```Cars``` and ```Paints```. In my Cars form/schema how can I reference my Paints collection?

So for example, I want to select the color of the car via a drop down menu, but I want to populate that list with all the "Paint Colors" available in my ```Paints``` collection. Is that possible? 

I searched the open and closed issues but didn't find anything that answered this specific question.

Thanks.

**Comment by matt-jay** [comment]
Might this help:

https://github.com/aldeed/meteor-autoform/issues/6

**Comment by odesey** [comment]
This led me in the right direction, thanks.
