### ISSUE TITLE
BUG Safari: Date input field

### ISSUE THREAD

**Issue by HedgeShot** [aldeed/meteor-autoform#1283]
Hi,

There is a strange bug in Safari. I use collection2 to validate a form that I created with AutoForm. 
One field has to be a "Date". It is working great on Chrome (I get a placeholder with dd.mm.yyyy and a calendar automatically) but nothing is displayed on Safari. If I enter a date like 20.11.2015, I get a negative feedback saying that a Date is required...

Any idea?

My collection looks like:
```
variableName: {
        type: Date,
        label: "variable label"
    }
```
my html code:
```
{{>afQuickField name="variableName"}}
```

**Comment by HedgeShot** [comment]
I am not sure why the behavior is inconsistent between Chrome and Safari but reading carefully the doc shows that date type should be : (YYYY-MM-DD) and it is indeed working. I think it has to do with localization settings in Chrome that bypass AutoForm.

**Comment by Idariel** [comment]
I have the same problem. 
Chrome date is dd/mm/yyyy, but it works fine with the calendar.
The date is yyyy-mm-dd with Firefox, Internet Explorer, MSN. 
Safari gives me a placeholder date in  yyyy-mm-dd but says it's not a valid date when I try to enter one.
Bugs me somehow.
