### ISSUE TITLE
Question: How to scroll to the first invalid field with quickform

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-autoform#1291]
I have some very long forms which, when submitted, I'd like to auto scroll to the first invalid element if there is one.

This is to minimize user confusion when the form cannot submit and the user does not have visual cues that the form actually has an invalid field up somewhere not visible in the current viewport.

**Comment by marktomm** [comment]
You can call AutoForm.selectFirstInvalidField(formId, SimpleSchema) in onError hook. onError hook is  called when the submitted form contains invalid fields and AutoForm.selectFirstInvalidField calls focus() on the first invalid element.
```javascript
  AutoForm.hooks({
    exampleInsertForm: {
      onError: function(formType, error) {
        AutoForm.selectFirstInvalidField('exampleInsertForm', this.ss);
      }
    }
  });
```

**Comment by serkandurusoy** [comment]
Wow this is great!

I wonder why it is not a builtin form option.

I also wonder, can I use this on a global autoform enerror hook such that
specific hooks for specific forms also do get run? are multiple hooks
merged?

Sent from my iPhone



On Nov 13, 2015, at 13:16, marktomm <notifications@github.com> wrote:

You can call AutoForm.selectFirstInvalidField(formId, SimpleSchema) in
onError hook. onError hook is called when the submitted form contains
invalid fields and AutoForm.selectFirstInvalidField calls focus() on the
first invalid element.

  AutoForm.hooks({
    exampleInsertForm: {
      onError: function(formType, error) {
        AutoForm.selectFirstInvalidField('exampleInsertForm', this.ss);
      }
    }
  });

—
Reply to this email directly or view it on GitHub
<https://github.com/aldeed/meteor-autoform/issues/1291#issuecomment-156400787>
.

**Comment by marktomm** [comment]
I am not sure, haven't tried yet, but the 'Callbacks/Hooks' paragraph in the docs states that you can add multiple hook objects/multiple callback hooks to one/many/all forms.

https://github.com/aldeed/meteor-autoform#callbackshooks

**Comment by serkandurusoy** [comment]
Yep, that's right. Thank you very much!
