### ISSUE TITLE
Question: Generic helper to get an array of invalid fields and messages

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-autoform#1292]
I need pointers to use  (if there already exists one) or create a generic helper that I can use in all autoforms (and possibly within quickforms by changning the template accordingly) which basically returns an array of either invalid fields, validation messeges, or better yet both.

**Comment by marktomm** [comment]
```javascript
var getFormInvalidKeys = function(formId) {
  var doc = AutoForm.getFormValues(formId);
  var ss = AutoForm.getFormSchema(formId);
  var ssCont = ss.newContext();
  ssCont.validate(doc.insertDoc, {});
      
  return ssCont.invalidKeys();
}
```

**Comment by serkandurusoy** [comment]
Hmm bu this does not take into account any error that's also created by the
server, thise like unique errors or ones added by stickyerrors, right? I
want to be able to grab whatever the actual form error state is.

But thank you this is still a good step in solving most of the problem.

Sent from my iPhone



On Nov 13, 2015, at 13:57, marktomm <notifications@github.com> wrote:

var getFormInvalidKeys = function(formId) {
  var doc = AutoForm.getFormValues(formId);
  var ss = AutoForm.getFormSchema(formId);
  var ssCont = ss.newContext();
  ssCont.validate(doc.insertDoc, {});

  return ssCont.invalidKeys();
}

—
Reply to this email directly or view it on GitHub
<https://github.com/aldeed/meteor-autoform/issues/1292#issuecomment-156411489>
.

**Comment by marktomm** [comment]
not sure exactly what are 'errors created by the server' in the current context.

'I want to be able to grab whatever the actual form error state is'. You mean you want to get the forms current visible error state? Get the field names on invalid inputs and error messages that are rendered in the view?

**Comment by serkandurusoy** [comment]
I want a list of whatever error is visible at that point to the user so that I can print them together in a block elsewhere, possibly right above the submit button.

Now what I realize is, if there are other errors that are generated by the server, those that I add to the form from an onError hook with addStickyValidation, are not normally available to ssCont.validate(doc.insertDoc, {}); are they?
