### ISSUE TITLE
Question: How do you autovalue a field in a nested array based on another field in that array

### ISSUE THREAD

**Issue by kluch** [aldeed/meteor-autoform#1302]
Hi,

I am trying to get supplierName to get autovalued from the ID I selected in the supplierId field. Not sure how to get the values from array items.

    shareholderSplitSchema = new SimpleSchema({
    "monthlyConfigs.$.month": {
          type: String
      },
      "monthlyConfigs.$.shareHolderSplit": {
          type: Number
      },
      "monthlyConfigs.$.nonShareholderSplit": {
          type: Number
      },
      "monthlyConfigs.$.suppliersSplit": {
          type: [Object],
      },
      "monthlyConfigs.$.suppliersSplit.$.supplierId": {
          type: String,
          autoform: {
              type: "select2",
              options: function() {
                  return _.map(SuppliersCollection.find({}).fetch(), function(service) {
                      return {
                         label: service.supplierName,
                         value: service._id
                      };
                });
              }
          }
      },
      "monthlyConfigs.$.suppliersSplit.$.supplierName": {
          type: String,
          optional: true,
          autoValue: function() {
              return SuppliersCollection.findOne({ _id:     AutoForm.getFieldValue('monthlyConfigs.suppliersSplit.supplierId')},{fields:    {name:1}}).supplierName;
          },
          autoform: {
              omit: true
          }
      }
    })

**Comment by aldeed** [comment]
Not currently possible, but SimpleSchema v2 will provide enough info to make this possible.

**Comment by serkandurusoy** [comment]
What about `siblingField()`?
