### ISSUE TITLE
How to remove hooks?

### ISSUE THREAD

**Issue by zhaoyao91** [aldeed/meteor-autoform#1309]
I want to make a react component with autoform, and let the user can pass success and failed callback into the component. React component has a life time, so I want to hook these callback in and out of the autoform.
By reading the doc, I know how to hook in, but I don't know how to remove hook.

**Comment by aldeed** [comment]
There is not a public API, but you can find them on the `AutoForm._hooks` object by form ID, so just delete `AutoForm._hooks[formId]` when the component is removed.
