### ISSUE TITLE
Change `class` to something else (reserved keyword)

### ISSUE THREAD

**Issue by lfilho** [aldeed/meteor-autoform#1313]
Hello there.

Since ES2015 is here, `class` is a reserved keyword so maybe we should change our `class` properties to `cssClasses` or `classNames` or something like that?

**Comment by aldeed** [comment]
Which specific places are you referring to? Reserved words are fine to use as object properties.

**Comment by lfilho** [comment]
Oh, right! Well, let's close this then.
