### ISSUE TITLE
How to use atuform with React?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform#1332]
I would like to try `autoform` with `react`, because I hear the many people talk about in meteor forums.
How to use `atoform` with `react` such as `Autoform.hook(........)`?

**Comment by java99** [comment]
Gwendall uses https://github.com/gwendall/meteor-blaze-to-react.. please report back if its working for you and what is not working. Thx :)

**Comment by thearabbit** [comment]
Thanks, so it mean that we use `react` combine with `blaze`.
Work fine.
