### ISSUE TITLE
Schema is not in the window scope

### ISSUE THREAD

**Issue by adavia** [aldeed/meteor-autoform#1341]
I am having a hard time using autoform to validate a schema, instead of a collection, like it states in https://github.com/aldeed/meteor-autoform#non-collection-forms. For some reason doing Schema = {} keeps throwing undefined in the console along along with "newUserFormSchema is not in the window scope". This is my code so far..

app/_globals/lib/collections/users/user_collections.coffee
```javascript
Schema = {}

# Create user country schema
Schema.UserCountry = new SimpleSchema
  name: 
    type: String

  code:
    type: String
    regEx: /^[A-Z]{2}$/

# Create user profile schema
Schema.UserProfile = new SimpleSchema
  birthday:
    type: Date

  gender:
    type: String
    allowedValues: [
      'male'
      'female'
    ]
    autoform:
      options: 
        male: "Male" 
        female: "Female"
      
  country:
    type: Schema.UserCountry
    optional: true

# Create user schema
Schema.User = new SimpleSchema
  username:
    type:String
    min: 6
    regEx: /^[a-z0-9A-Z_]{3,15}$/

  email:
    type: String
    regEx: SimpleSchema.RegEx.Email

  profile:
    type: Schema.UserProfile

  password: 
    type: String
    min: 6
```

app/accounts/client/signup.coffee
```javascript
Template.signup.helpers
  newUserFormSchema: ->
    Schema.User
```

app/accounts/client/signup.jade

     template(name="signup")
          +autoForm schema="newUserFormSchema" type="method" meteormethod="accounts.register-user" id="newUser" preserveForm="true"
                +afQuickField name="username" autocorrect="off" autocomplete="off"
                +afQuickField name="email" autocorrect="off" autocomplete="off"
                +afQuickField name="profile.birthday"
                +afQuickField name="profile.gender" type="select-radio-inline"
                +afQuickField name="password" type="password"

                button.btn.btn-block.btn-primary Sign Up

app/accounts/account_methods.coffee

```javascript
Meteor.methods
  "accounts.register-user": (ops={}) ->
    
    Accounts.createUser(ops)
```

**Comment by adavia** [comment]
Using coffeescript should be @Schema = {}
Also i removed the " " from newUserFormSchema in the form

**Comment by OverflowClancy** [comment]
Almost 5 years on....

_"Also i removed the " " from newUserFormSchema in the form"_

That solved my problem.  Thank you.
