### ISSUE TITLE
how to set value to afArrayField ?

### ISSUE THREAD

**Issue by michaelmax28** [aldeed/meteor-autoform#1353]
`Schema={};`
`Schema.Gain=new SimpleSchema({`
`gain:{`
`type:Array`
`},`
   ` 'gain.$':{`
   ` type:Object`
    `},`
   ` 'gain.$.serviceId':{`
    `type:String,`
    `max:33`
   ` },`
   ` 'gain.$.logs':{`
   ` type:Number,`
    `min:1`
  `  }`
`});`
`Gains.attachSchema(Schema.Gain);`

`Template.gainsTab.helpers({`
    `service:function(){`
        `return Services.find();`
    `},`
    `uniqueFormId:function(){`
        `return 'form-'+this._id;`
   ` }`
`});`

`<template name="gainsTab">`
                `{{#each service}}`
                    `{{#autoForm type="insert" id=uniqueFormId collection="Gains"}}`
                        `{{> afArrayField name="gain"}}`
                        `<button type="submit">Send</button>`
                    `{{/autoForm}}`
                `{{/each}}`
`</template>`

How to set the value of 'gain.$.serviceId' for each ServiceId using a helper?
I tried `{{> afArrayField name="gain" value=arrayReturnedFromHelper}}` but didn't works

Thanks

**Comment by abate** [comment]
I'm having the same problem. How did you solve this ? thanks !

**Comment by daorren** [comment]
I know it's been years, for those who came to this issue for solution:

consider using `doc` attribute in `autoForm `.

in this case
```
{{#autoForm type="insert" id=uniqueFormId collection="Gains" doc=formData}}
  {{> afArrayField name="gain"}}
  <button type="submit">Send</button>
{{/autoForm}}
```
where `formData = {gain: returnGain()}`
