### ISSUE TITLE
Autoform using method get's Internal server Error in Google Chrome

### ISSUE THREAD

**Issue by xvendo** [aldeed/meteor-autoform#1363]
<b>I tested this in Firefox 43.0.4 and Google Chrome 48.0.2564.82.</b>
<p>Result: My Autoform "Insert" button below the form was clicked and console.log shows:</p> 

<code>
errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}
</code>

<b>In Firefox this is working as expected.</b>

My Meteor version: 1.2.1
Autoform version: 5.8.1

**Comment by xvendo** [comment]
The above can be closed. I tested it over and over again. Obviously It was caused by hardware.

**Comment by seanmavley** [comment]
@xvendo you can close it yourself.
