### ISSUE TITLE
Force string into array

### ISSUE THREAD

**Issue by JulianKingman** [aldeed/meteor-autoform#1374]
I have a 'select2' form field and want to be able to use it as a select box. However, it's for telescope, and telescope requires an array for this particular field, what's the best way to transform the result into an array (e.g. if the result is "string", turn it into ["string"] before it's validated.

**Comment by Tim-W** [comment]
You can set the onSubmit hook using AutoForm.hooks() and modify the document before it is submitted

**Comment by JulianKingman** [comment]
Thanks, I did as you suggested. I actually tried that before, but forgot to add the file responsible to packages.js.
*sigh*
