### ISSUE TITLE
using both of "collection" and "schema" attribute for autoform

### ISSUE THREAD

**Issue by rslp2** [aldeed/meteor-autoform#1389]
I have one "Ads" collection in mongoDB, and too many schema in following format:  

    AdsBaseSchema = new SimpleSchema({
      _parentId: {
        type: String,
        optional: true
      },
      title: {
        type: String,
        label: "Title",
        max: 200
      }
      description: {
        type: String,
        label: "Description",
        optional: true
      }
    });

but they are different is some fields.

and I want to use them for insert autoform. like this:

    {{> quickForm schema="AdsBaseSchema" id="insBaseAds" type="method" meteormethod="insBaseAds"}}

whit this method:

    insBaseAds: function(doc) {
        Ads.insert(doc);
        this.unblock();
    }

**this approach works correctly!**

but its hard for me to use this approach for all of my schema!

I want to ask you: "is this possible for meteor to use something like below autoform, and use just one autoform (form generator) for all schema?"

    {{> quickForm collection="Ads" schema="AdsBaseSchema" id="insertAds" type="insert"}}

**Comment by Tim-W** [comment]
You could try writing a helper for your template which returns a schema name dynamically, like so:

`{{> quickForm collection="Ads" schema=schema id="insertAds" type="insert"}}`
`Template['myTemplate'].helpers({
 schema() {
 //Write your logic here
 return "adsBaseSchema";
 }
})`

**Comment by rslp2** [comment]
thanks. it works
