### ISSUE TITLE
quickForm allowed values vs autoForm+afQuickField

### ISSUE THREAD

**Issue by aaronjudd** [aldeed/meteor-autoform#141]
This might not rise to the level of being a bug, more of a behavioral observation:

When the schema is defined like such:

```
"settings.port":
  type: Number
  label: "Port"
  allowedValues: [25, 587, 465, 475, 2525]
  optional: true
```

and you use a _quickform_, the _port_ field will be a select with available options from the _allowedValue_.

When you use an _autoform_ with a _afQuickField_ 

```
{{>afQuickField name='settings.port'}}
```

You don't get the automatic select/options.

I know that you can supply them with _options=_  but seems like it would be intuitive for the select options to be the same as on a quick form. 

Just wondering if I missed something, or options= is expected implementation.

**Comment by chiester** [comment]
I think 

```
options="allowedValues"
```

would be more intuitive.
