### ISSUE TITLE
[Question] How to manually set custom error message for some field

### ISSUE THREAD

**Issue by th0r** [aldeed/meteor-autoform#144]
I'm using `autoform` for login form validation. My `onSubmit` callback looks like this:

``` js
AutoForm.addHooks('loginForm', {
    onSubmit: function (user) {
        loginForm.clean(user);
        Meteor.loginWithPassword({ username: user.login }, user.password, function (err) {
            if (err && err.reason === 'Incorrect password') {
                // Set `{{ afFieldMessage name='password' }}` to "Wrong password"
            }
        });
        return false;
    }
});
```

Is there any way to manually set error message for the specific form field?

**Comment by afuggini** [comment]
@aldeed is it possible to prevent form from submitting if the validation within the `custom` function returns invalid? e.g. if a username already exists in the DB, I would like not to trigger the onSubmit hook.
Thanks.

**Comment by aldeed** [comment]
No because form submission is synchronous by nature. But you can have the form submit to a method, do the username check in the method, and add invalid keys back on the client based on the error that comes back from the method.

**Comment by afuggini** [comment]
Well, the form is definitely not submitted if any other field is invalid according to my schema (e.g. minimum number of characters not met, etc), so does it not work like this with custom validation?

**Comment by aldeed** [comment]
It does, but you're calling `addInvalidKeys` in the callback, so your form will have already submitted (if no other fields were invalid) by that time.

**Comment by afuggini** [comment]
Ok I figured it out, thanks for the information @aldeed !

**Comment by afifsohaili** [comment]
@afuggini you figured it out? do you mind sharing your solution? I'm having the same problem.

**Comment by lnmunhoz** [comment]
@afuggini How did you fix the async validation?
