### ISSUE TITLE
Meteor 1.3 collection is not in the window scope

### ISSUE THREAD

**Issue by yasaricli** [aldeed/meteor-autoform#1449]
Hi;

I updated application **Meteor.1.3** and template error because it is not imported  

**> quickForm collection="Books"**

```
import { Mongo } from 'meteor/mongo';
import { SimpleSchema } from 'meteor/aldeed:simple-schema';

import const Books = new Mongo.Collection("books");
Books.attachSchema(new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  author: {
    type: String,
    label: "Author"
  },
  copies: {
    type: Number,
    label: "Number of copies",
    min: 0
  },
  lastCheckedOut: {
    type: Date,
    label: "Last date this book was checked out",
    optional: true
  },
  summary: {
    type: String,
    label: "Brief summary",
    optional: true,
    max: 1000
  }
}));
```
## Template

```
<template name="insertBookForm">
  {{> quickForm collection="Books" id="insertBookForm" type="insert"}}
</template>
```

**> Exception in template helper: Error: Books is not in the window scope**

but so that the solution:

```
import { Template } from 'meteor/templating';
import { Books } from '/imports/books.js';


Template.insertBookForm.helpers({
  books() {
    return Books;
  }
});
```
## Template

```
<template name="insertBookForm">
  {{> quickForm collection=books id="insertBookForm" type="insert"}}
</template>
```

Any ideas?  or another solution?

thanks.

**Comment by lnmunhoz** [comment]
Import your collections on a  `main.js` client file and add them to the window scope.

main.js
```
import { Books } from '/imports/books.js';

window.Books = Books
```

**Comment by bmansfie** [comment]
Been looking for this solution for hours.  Perfect, thanks.

**Comment by jebarjonet** [comment]
@lnmunhoz it works but putting it in the `windows` scope is not ok to me.

I would rather do : 
```es6
import {Books} from "/imports/books.js";

Template.insertBookForm.helpers({
    formCollection() {
        return Books;
    }
});
```
and
```handlebars
{{> quickForm collection=formCollection id="insertBookForm" type="insert"}}
```

**Comment by lnmunhoz** [comment]
Yeah! This looks like a more isolated approach.

Em sex, 22 de abr de 2016 13:30, Jean-Elie Barjonet <
notifications@github.com> escreveu:

> @lnmunhoz <https://github.com/lnmunhoz> it works but putting it in the
> windows scope is not ok to me.
>
> I would rather do :
>
> import {Books} from "/imports/books.js";
> Template.insertBookForm.helpers({
>     formCollection() {
>         return Books;
>     }
> });
>
> and
>
> {{> quickForm collection=formCollection id="insertBookForm" type="insert"}}
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/aldeed/meteor-autoform/issues/1449#issuecomment-213499971>
>
-- 
Lucas N. Munhoz
- Skype: lnmunhoz
- Github: http://github.com/lnmunhoz
- Twitter: http://twitter.com/lnmunhoz
- Linkedin: https://www.linkedin.com/in/lucasnmunhoz

**Comment by nosizejosh** [comment]
I am using meteor 1.4.2 and I have the same problem. IS this a bug with autoform? I never had this issue with previous autoform versions.

**Comment by nosizejosh** [comment]
@jebarjonet I tried your suggestion but it doens work for me. @lnmunhoz why does this  `window.Books = Books` work? is it a bug with new meteor versions or autoform. I am using meteor 1.4.2

**Comment by aldeed** [comment]
In general, setting them on `window` isn't ideal. Docs should probably be updated in a few places. One solution I sometimes use is a global helper, where you have something like this in your client code:

```js
import Books from '/imports/collections/Books';
import Another from '/imports/collections/Another';

const Collections = {
  Books,
  Another,
};

Template.registerHelper('Collections', Collections);
```

And then in the template:

```html
{{> quickForm collection=Collections.Books id="insertBookForm" type="insert"}}
```

**Comment by nosizejosh** [comment]
@aldeed thank you for replying. In previous versions, you could just do

> `import Books from '/imports/collections/Books';
> {{> quickForm collection=Books id="insertBookForm" type="insert"}}`

what changed?

**Comment by jebarjonet** [comment]
@nosizejosh Meteor 1.3 was a huge update.  Instead of binding everything to window like before, you had to import it with modules (https://guide.meteor.com/1.3-migration.html)

**Comment by nosizejosh** [comment]
@jebarjonet @aldeed I am sure i am not explaining myself well. I am using meteor 1.4.2 and autoform 5.*. I am aware of the imports, I use it, but just this type, I am getting the "not in scope error"

> import { Meteor } from 'meteor/meteor';
> import { Template } from 'meteor/templating';
> 
> import { Demographics } from '../../api/demographics/demographics.js';
> import './demographic.html';
> 
> window.Demographics = Demographics; //without this, I get the not in scope error
> 
> Template.Demographic.onCreated(function(){    
> 
> 	let template = Template.instance(); 
>     template.autorun( function () {  
>         // subscribe to remote ratings publication
>         let allDemographics = template.subscribe('demographics.all'); 
>         // let ratingSub = template.subscribe('ratings.all'); 
>         console.log(Demographics.find().count()); 
>         // console.log(ratings);
>         if (allDemographics.ready()) {
>         let demos = Demographics.find().fetch();    
>         // console.log(ratings.find().count()); 
>         console.log(demos); 
>         } else {
>             console.log("> Demographics Subscription is not ready yet. \n\n");
>         } 
> 
>     });
> 
> });

**Comment by aldeed** [comment]
@nosizejosh 

With quotes, `collection="Books"`, means "look for `window.Books`"

Without quotes, `collection=Books`, means "look for a helper or property or variable in current scope with the name `Books`"

So it sounds like you are just using quotes when you don't mean to.

**Comment by nosizejosh** [comment]
@aldeed Thank you. taking the quotes out now presents a new error 

> Exception in template helper: TypeError: Cannot read property 'schema' of undefined
>     at Object.quickFormContext (http://localhost:3000/packages/aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:6713:34)

reading around suggests bringing the quotes back. I am stuck and I need this working. 

> aldeed:autoform@5.8.1
> aldeed:collection2@2.7.1
> aldeed:simple-schema@1.5.3

**Comment by jebarjonet** [comment]
>  taking the quotes out now presents a new error

Have you set a `helper` called `Books` that injects the collection in the template?

**Comment by nosizejosh** [comment]
@aldeed @jebarjonet Thank you guys. I had to add the global template as suggested earlier by @aldeed to  make it all work. Thank you.

**Comment by Harry97** [comment]
Instead of importing, why don't you guys suggest the usage of subscribe & publish?
