### ISSUE TITLE
Adding reactive data to autoform input field

### ISSUE THREAD

**Issue by williamkhshea** [aldeed/meteor-autoform#145]
I am new to autoform and I am currently making a form for editing user profile. I would like the form to populate existing value by including {{profile.name}} in the HTML.

This is what I am targeting at:
<input name="name" type="text" placeholder="{{i18n 'name'}}" value="{{profile.name}}">

When I am using afQuickField, the following won't work:
{{> afQuickField name="name" placeholder="{{i18n 'name'}}" value="{{profile.name}}"}}

It will output {{profile.name}} in the input field instead of the name of the user from profile.

Just wonder is it supported or is there any other way to do it?

Thanks.

**Comment by tsengelenkhbat** [comment]
{{> afObjectField name="birthPlace" value=doc.profile.birthPlace }}
        
        {{> afArrayField name="family"}}
        
        {{> afArrayField name="relatives" value=doc.profile.relatives}}
        
        {{> afObjectField name="contact" value=doc.profile.contact}}
        
        {{> afObjectField name="emergencyContact" value=doc.profile.emergencyContact
how to getting object field value in existing form
