### ISSUE TITLE
How to implement hook with Meteor 1.3.2.4

### ISSUE THREAD

**Issue by thorque** [aldeed/meteor-autoform#1457]
Hello,

I am trying to add a hook to autoform, but I don't know what I need to import to get this running. I tried so far:

`
import { Template } from 'meteor/templating';
import { Session } from 'meteor/session';
import { AutoForm } from 'aldeed/autoForm';

AutoForm.addHooks('team_edit',{
    onSuccess: function(){
        console.log("Hook hitted")
        Modal.hide('team_edit');
    }
});`

But this doesn't work due to missing a module:
`Unable to resolve some modules:

  "aldeed/autoForm" in
/Users/___/Documents/Projekte/p/agile-toolbox/imports/ui/components/teams/team.js
(web.browser)
If you notice problems related to these missing modules, consider running:
  meteor npm install --save laded`

I've tried to google this but with no results. perhaps you can help me?
Thanks
Thorsten

**Comment by thorque** [comment]
After refining my search I found the solution:

import { AutoForm } from 'meteor/aldeed:autoform';

**Comment by lonniev** [comment]
I'm curious: how does a third-party package get to be published so that its import namespace is under "meteor/"? It took me a while to figure out that `import { AutoForm } from 'aldeed:autoform'` wasn't going to work because the package was actually under `meteor`.

**Comment by micchickenburger** [comment]
@lonniev Atmosphere packages need the `meteor/` prefix in the import statement, else meteor will try to resolve an NPM package instead.
