### ISSUE TITLE
Ability to pass "disabled" to afFieldInput

### ISSUE THREAD

**Issue by joseconstela** [aldeed/meteor-autoform#1463]
Suggestion to support `disabled` when using `afFieldInput`

So:
`{{> afFieldInput name="fieldName" disabled}}`

Will output:
`<input type="text" name="fieldName" data-schema-key="fieldName" class="form-control" disabled>`

**Comment by chrise86** [comment]
`{{> afFieldInput name="fieldName" disabled=shouldDisable}}` does this for me, however I want to be able to pass a conditional. It would be cleaner than conditionally rendering the whole field.
