### ISSUE TITLE
Autoform render issue only on Firefox html tables

### ISSUE THREAD

**Issue by keyscores** [aldeed/meteor-autoform#1473]
There seems to be an issue on using Autoform on tables. This only happens in Firefox, as far as I can tell.

Sometimes its necessary to have an inline form in an html table. If the Autform helper is encompassing the <td> </td>  the field will not render, only in Firefox.

~~~~
<tr>
  <td> {{this.name}}</td>
  {{#autoForm id=this._id doc= this  type = "update" collection="Hours"}}
  <td>
    {{> afQuickField name='month'}}
  </td>
  {{/autoForm}}
</tr>
~~~~

See a full reproduction of the issue here: 
https://github.com/keyscores/meteorautoformissue

Compare it in Chrome and FireFox. This is the expected render in Chrome:
______

![screenshot 2016-05-26 15 32 05](https://cloud.githubusercontent.com/assets/1364012/15587411/22baeb7a-2357-11e6-81b4-ba3734bd37a0.png)

**Comment by kwoodbury1** [comment]
I am having a similar issue in Firefox, and found adding an HTML < div > tag allowed the form to render (ex. below).  I am still investigating this, however, does this workaround work for you as well???

< div >{{>insertCloudRegAutoform}}< / div >

**Comment by keyscores** [comment]
I guess wrapping the form in a new template would work. I just find this quite bizarre considering chrome and safari are fine. 
@aldeed any ideas?

**Comment by aldeed** [comment]
@keyscores @kwoodbury1 AutoForm is properly rendering all of the elements but Firefox does not display them. It seems FF has just chosen not to render tables that are within forms. (FF may be wrong or maybe Chrome is wrong.) Even without using autoform, this also does not render in FF:

```js
<tr>
        <td> {{this.name}}</td>
        <form>
          <td><input type="text"></td>
        </form>
</tr>
```

As far as how to fix it, I'd suggest using divs and styling as a table, and wrap the entire row. Something like this:

```js
<div class="table">
    <div class="table-row">
      <div class="table-cell">Country Code</div>
      <div class="table-cell">Region</div>
      <div class="table-cell">Hello</div>
    </div>
    {{#each eachDoc}}
      {{#autoForm id=this._id doc=this type="update" collection="Hours" class="table-row"}}
        <div class="table-cell">{{this.name}}</div>
        <div class="table-cell">
          {{> afQuickField name='year'}}
        </div>
        <div class="table-cell">
          {{> afQuickField name='month'}}
        </div>
        <div class="table-cell" style="vertical-align:middle;">
          <button type="submit" class="btn">Update</button>
        </div>
      {{/autoForm}}
    {{/each}}
  </div>
```

With this in your stylesheet:

```css
.table { display: table; }
.table-row { display: table-row; }
.table-cell { display: table-cell; }
```
