### ISSUE TITLE
Submit ('insert') not working by autoform when button inside a included template

### ISSUE THREAD

**Issue by tomyo** [aldeed/meteor-autoform#1518]
I have this structure in my template, the submit button inside the template templateWithSubmitButton doesn't triggers the autoform 'insert' method, it just do a normal browser submit, without invoking the onSubmit callback, so I guess autoform is not graving the event at all.
```
{{#autoform ...}}

{{> templateWithSubmitButton}}
{{/autoform}}

<template name="templateWithSubmitButton">
<button type="submit"> Insert </button>
</template>
```

**Comment by raphaelarias** [comment]
As far as I understood correctly, you have the `button` outside the `autoform` block. By default, as the button is outside the `form` tag, it will not fire the submit event, right?

Have you tried to put on your button: `form=<<formID>>`?

**Comment by tomyo** [comment]
I had one form inside another, miss that.
