### ISSUE TITLE
"readonly=true" don't work when update blaze to 2.2.0?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform#1541]
`readonly=true` don't work when update `blaze to 2.2.0`.
```js
{{> afQuickField name="amountPaid" value=totalDue readonly=true}}
```
Pl hlep me

**Comment by bharathkeshav12** [comment]
Facing the same issue. readonly=true  / using a helper is not getting the field to be readonly.

**Comment by thearabbit** [comment]
Thanks for your reply, I will close this and comment on https://github.com/meteor/blaze/issues/151
