### ISSUE TITLE
How to make quickForm element read-only?

### ISSUE THREAD

**Issue by Netherdrake** [aldeed/meteor-autoform#1542]
My schema is as follows:
```
GameSchema = new SimpleSchema({
    post: {
        type: Object,
    },
    'post.identifier': {
        type: String,
        index: 1,
        unique: true,
        label: "Post identifier",
        max: 200,
        autoform: {
            afFieldInput: {
                readonly: true,
            }
        }
    },
```

This particular field is pre-filled by template helper, and it should not be change-able by user.

However the readonly flag seems to have no effect.

Any ideas on how to approach this?

**Comment by Netherdrake** [comment]
In other words, how can I make a field that is visible, but grayed out (cannot be edited)?

**Comment by wesleyfsmith** [comment]
This works for me:

```js
name: {
    type: String,
    autoform: {
      disabled: true
    }
  }
```

**Comment by wesleyfsmith** [comment]
Seems you can do the same thing with read only:

```js
name: {
    type: String,
    autoform: {
      readonly: true
    }
  }
```

I think the issue you are having is the 'afFieldInput'. I don't think you need that for these kinds of options.

**Comment by Netherdrake** [comment]
`readonly` hasn't worked for me, however `disabled` did the job perfectly. You're my hero @wesleyfsmith.

If I may ask another question, do you happen to know why, if I make a field `hidden`, it fails like this:
```
    post: {
        type: Object,
        autoform: {
            type: 'hidden',
        }
    },
```

```
Error: Post must be an object
```
https://i.gyazo.com/adcd1db92a43bd46ebae6c93c2e200ea.png

**Comment by Netherdrake** [comment]
As mentioned elsewhere, `readonly` should be `readOnly`.
