### ISSUE TITLE
autoform update

### ISSUE THREAD

**Issue by achinsngh** [aldeed/meteor-autoform#1544]
So far I have made an update autoform which fills its values from the database. No problem with that. This update method is working fine as autosave is set to true. But I dont want the form to get automatically updated. I want to update this form only when the submit button is clicked. I have tried many things but didnt work so Here I am attaching my code which has autosave=True. it is working fine.

html code

```
<template name="updatemachine">
 {{#with getDocument }}
 <div class="container">
 {{#autoForm collection="Machines" id=onupdateMachinesID doc=this type="update" autosave=true }}
                 {{> afQuickField name="serverName" disabled=shouldBeDisabled}}
                 {{> afQuickFields omitFields="serverName,owner,createdAt,updatedAt,hardware,powerStatus"}}
                <!-- {{#with shouldBeDisabled "hardware"}} -->
                 {{> afQuickField name="hardware" disabled=shouldBeDisabled}}
                 {{> afQuickField name="powerStatus" disabled=shouldBeDisabled}}
                 {{/autoForm}}
   <button type="submit" class="btn btn-primary" >submit</button>
   {{> quickRemoveButton collection="Machines" _id=this._id onError=onError onSuccess=onSuccess beforeRemove=beforeRemove class="btn btn-danger"}}
 </div>
 {{/with}}
 </template>
```

now the java script

```
if(Meteor.isClient){
Template.updatemachine.helpers({

  onupdateMachinesID: function () {
     return "update-each-" + this._id;
	},
getDocument: function() {
 var docId = FlowRouter.getParam('_id');
     var doc = Machines.findOne(docId) ;
     return doc;   
     },
onSuccess: function () {
     return function (result) {
     console.log(result);
     console.log("deleted");
     window.location.assign("/servers");
     };
       
  },
  beforeRemove: function () {
     return function (collection, id) {
     var doc = collection.findOne(id);
     if (confirm('Really delete "' + doc.loginUser + '"?')) {
     this.remove();
        }
      };
    }


});
Template.registerHelper("shouldBeDisabled", function () {
    var fieldName = "hardware";
    var test = AutoForm.getFieldValue("onupdateMachinesID", fieldName);
    return true;
});
Template.updatemachine.events({
    "click .btn-primary": function(id) {
    sessionStorage.setItem("sent", id);
    console.log("button was clicked");
    alert("form updated");
 window.location.assign("/servers");
 }
 
});}



I have tried with type= metero-update and methodname= .....  But it wasnt working. even if i make autosave =false I dont how to manually update it.

```

**Comment by ifalldev** [comment]
@achinsngh, you fixed that? I'm passing by a similar trouble.

Thank you!

**Comment by achinsngh** [comment]
@ifalldev  this worked for me. 
`{{#autoForm collection="Machines" id=idForUpdateMachines doc=this type=updateMachinesForm }}
                 {{> afQuickField name="serverName" disabled=shouldBeDisabled}}
                 {{> afQuickFields omitFields="serverName,owner,createdAt,updatedAt,hardware,powerStatus"}}
                 {{> afQuickField name="hardware" disabled=shouldBeDisabled}}
                 {{> afQuickField name="powerStatus" disabled=shouldBeDisabled}}
                 
   <button type="submit" class="btn btn-primary" >submit</button>
   {{> quickRemoveButton collection="Machines" _id=this._id onSuccess=onSuccess beforeRemove=beforeRemove class="btn btn-danger"}}
 {{/autoForm}}`

this is the javascript

` idForUpdateMachines: function () {
     return "update-each-" + this._id;
	},
  updateMachinesForm: function () {
      return "update";
  },
`
This will do the update without autosaving
