### ISSUE TITLE
novalidate attribute missed on rendered form

### ISSUE THREAD

**Issue by andreaderuvo** [aldeed/meteor-autoform#1545]
I'm trying aldeed:autoform  (5.8.1) with a very basic schema but the rendered form misses the attribute novalidate.

I'm using meteor 1.4.2.3

**Comment by andreaderuvo** [comment]
maybe it's related to https://github.com/meteor/blaze/issues/151

**Comment by cesarve77** [comment]
If you don't want downgrade you can change one line in meteor-autoform/componets/autoForm/autoForm.js


43   - htmlAttributes.novalidate = "novalidate";
43   +htmlAttributes.noValidate = "novalidate";

Note v -> V
