### ISSUE TITLE
Autoform Incompatible with collection2-core@2.0.0

### ISSUE THREAD

**Issue by Amritpd** [aldeed/meteor-autoform#1552]
As mentioned in the [collection2 docs](https://github.com/aldeed/meteor-collection2#important-note-the-version-in-this-repo-is-deprecated), aldeed:collection2 has deprecated and instead collection2-core@2.0.0 should be used with the NPM package version of [Simple Schema](https://github.com/aldeed/node-simple-schem). In order to use the new packages, `aldeed:simple-schema` should not be listed in your .meteor/versions file. However, I noticed that **it is still listed**. The problematic package is `aldeed:autoform`, since it automatically installs `aldeed:simple-schema` by [design](https://atmospherejs.com/aldeed/autoform). Aldeed, it would be great if you can release an updated version of AutoForm that does not explicitly depend on the aldeed:simple-schema package

**Comment by jankapunkt** [comment]
I created a PR where I moved the dependencies to the npm package since I strongly require on this package.

https://github.com/aldeed/meteor-autoform/pull/1557

**Comment by Taslack** [comment]
6.0 is released and fixes this issue.
