### ISSUE TITLE
simpleSchema.mergedSchema is not a function

### ISSUE THREAD

**Issue by ggazzo** [aldeed/meteor-autoform#1568]
I got this error 
```
simpleSchema.mergedSchema is not a function
```
the error occurs in this [line](https://github.com/aldeed/meteor-autoform/blob/ffe37e8bd6ac9999a3d479bc54ecce6e852d3101/components/quickForm/quickForm.js#L21)
```
 {{> quickForm collection="Thing" type="insert" id="Thing"}}
```

**Comment by dukye** [comment]
+1 Same problem, same line, trying different solution via properties collection="" and schema="" same error again.

Thanks for reply ;)

**Comment by aldeed** [comment]
You are probably trying to use v6.0 without also switching to the SimpleSchema from NPM. See https://github.com/aldeed/meteor-autoform/blob/devel/CHANGELOG.md#600 (or pin to version 5.x of autoform)

**Comment by dukye** [comment]
npm i --save simpl-schema

Yeah i've seen, I have not read your documentation well really sorry :)
RTFM my friend ;)
thx Aldeed

**Comment by danyhiol** [comment]
+1 Same here with all version to the latest: aldeed:autoform@6.0.0, aldeed:collection2-core@2.0.0 and "simpl-schema": "^0.2.3".

**Comment by tobico** [comment]
Here's a stack trace:
```
Exception in template helper: TypeError: Cannot read property 'mergedSchema' of undefined
    at Object.quickFormContext (http://localhost:3000/packages/aldeed_autoform.js?hash=a18c62226899c358fbb26d882c56bd78f140b218:6424:38)
    at http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:3050:16
    at http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:1714:16
    at http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:3102:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:3743:12)
    at http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:3101:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at http://localhost:3000/packages/aldeed_autoform.js?hash=a18c62226899c358fbb26d882c56bd78f140b218:6387:23
    at wrappedArgFunc (http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:2959:14)
    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:2672:26)
```

Versions in `versions` file:
```
aldeed:autoform@6.0.0
aldeed:collection2-core@2.0.0
```

and in `package.json`:
```
    "simpl-schema": "^0.2.3"
```

**Comment by tobico** [comment]
On further investigation, it looks like this was a result of me not correctly passing the collection object to the template. Specifically, I had the following code to import my collection in the client:

```
import Recipes from '/imports/collections/recipes'
```

when it needed to be:

```
import { Recipes } from '/imports/collections/recipes'
```

Adding an error message when the passed in value for `collection` is not a valid collection could be a good way to help users troubleshoot this kind of issue. I'd be happy to put together a pull request for this if you think it's a good idea.
