### ISSUE TITLE
How to disable fistOption in select

### ISSUE THREAD

**Issue by asesec** [aldeed/meteor-autoform#1569]
Hi

How can be disabled the first option of a select so that it appears but is not selectable?

**Comment by aldeed** [comment]
First, turn off firstOption with `firstOption=false`. Then include the first option as the first element in your options array, with `disabled: true`.

```js
options: [
        {label: "(Select One)", value: "", disabled: true},
        {label: "Red", value: "red"},
        {label: "Green", value: "green"},
        {label: "Blue", value: "blue"}
      ]
```

**Comment by asesec** [comment]
Thanks @aldeed for the answer but still doesn't work, "(Select One)" option still selectable.

![select](https://cloud.githubusercontent.com/assets/26021646/23830649/1d346ec2-0710-11e7-9076-047a665f4502.png)

That is the result with:

```
interestedIn:{
    label: 'Interested in:',
    type: String,
    optional: true,
    autoform: {
      type: "select",
      firstOption: false,
      options: [
        {label: "(Select One)", value: "", disabled: true},
        {label: "Red", value: "red"},
        {label: "Green", value: "green"},
        {label: "Blue", value: "blue"}
      ]
    }
  },
```

and 

```
{{#autoForm id="professionalForm" type=formType collection=professionalsCollection doc=professional}}
    <div class="row">
        <div class="col s4">
            {{> afQuickField name="interestedIn"}}
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
{{/autoForm}}
```

**Comment by vedovato** [comment]
Despite the issue age, @asesec, you had to make your field in template like follows:

`{{> afQuickField name="interestedIn" firstOption=false}}`
