### ISSUE TITLE
v6.0.0 Breaks the schema

### ISSUE THREAD

**Issue by rikyperdana** [aldeed/meteor-autoform#1570]
Im doing this in coffee

```
collection1 = new Mongo.Collection 'collection1'
schema1 = new SimpleSchema
    content:
        type: String
        autoform:
            type: 'textarea'
collection1.attachSchema schema1
```
And it gives me error like this on server console
`Invalid defenition for content field`

When I switch back to 5.8.1, everything is back and fine
Do something

**Comment by aldeed** [comment]
Use 5.8.1. You should only update to 6.0 if you are going to switch to the NPM SimpleSchema package (which everyone should do eventually).
