### ISSUE TITLE
Not rendering errors in html

### ISSUE THREAD

**Issue by gibson** [aldeed/meteor-autoform#1572]
I have a form and `AutoForm.debug()`

```
{{#autoForm schema=getSchema id="addForm" type="method" meteormethod="create"}}
    <div class="form-group {{#if afFieldIsInvalid name='name'}}has-error{{/if}}">
        <label for="name">name</label>
        {{> afFieldInput name="name" id="name"}}
        <span class="help-block">{{#if afFieldIsInvalid name='name'}}{{afFieldMessage name='name'}}{{/if}}</span>
    </div>
   …
    <button type="submit" class="btn btn-success">
        add
    </button>
{{/autoForm}}
```

But if field not validated error showing only in console not in form.

**Comment by imajus** [comment]
`AutoForm.validateForm('…')` returns `false` but not clue what was wrong not in HTML nor in console.

**Comment by imajus** [comment]
I've found the solution, you just need to add Tracker reference to `SimpleSchema` constructor. Described here https://github.com/aldeed/node-simple-schema#enable-meteor-tracker-reactivity
