### ISSUE TITLE
Form insert not submitting

### ISSUE THREAD

**Issue by vestrep** [aldeed/meteor-autoform#1575]
I have a problem with a quickform that is not submitting. I have an error that says:
errorClass

details:undefined
error:404
errorType:"Meteor.Error"
message:"Method '/clients/insert' not found [404]"
reason:"Method '/clients/insert' not found"

I have insecure package working in my app.

My collection is defined like this (imports/api/collections/clients.js):

import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';
SimpleSchema.extendOptions(['autoform']);

export const Clients = new Mongo.Collection('clients');

Clients.attachSchema(new SimpleSchema({
  name: {
    type: String,
    label: "Nom"
  },
  surname: {
    type: String,
    label: "Prénom"
  },
  email: {
    type: String,
    label: "E-mail"
  },
  telephone: {
    type: String,
    label: "Téléphone"
  },
  gender: {
    type: String,
    label: "Genre",
    allowedValues: ['M','F']
  }
}));

My js file for the template is (imports/ui/pages/clients_add.js):

import { Clients } from '../../../api/collections/clients.js';
import { Template } from 'meteor/templating';
import './clients_add.html';

Template.clientsAdd.helpers({
  formCollection(){
    return Clients;
  }
});

and my template (imports/ui/pages/clients_add.html):
<template name="clientsAdd">
    {{> quickForm collection=formCollection id="addClientForm" type="insert"}}
</template>

I don't understand what I'm doing wrong...

**Comment by lonniev** [comment]
bummer, I have this issue now, too, I wonder what is the oversight.

**Comment by guncebektas** [comment]
the same thing started on my project after meteor 2.3.2 update

**Comment by jankapunkt** [comment]
@guncebektas are you Sure you have the insecure package added?
