### ISSUE TITLE
Dependency problem with simpl-schema

### ISSUE THREAD

**Issue by abate** [aldeed/meteor-autoform#1578]
I'm trying to use autoform as a dependency form my package. This is my package.js

```
Npm.depends({
  'simpl-schema': '0.2.3',
});

Package.onUse(function(api) {
  api.versionsFrom('1.4');

  api.use([
    'mongo',
    'coffeescript',
    'ecmascript',
    'aldeed:collection2-core',
    'aldeed:autoform@6.0.0',
...
```

and this is the error I get on start up:

> => Exited with code: 1
> W20170308-14:33:37.819(1)? (STDERR) WARNING: npm peer requirements (for aldeed:meteor-collection2-core) not installed:
> W20170308-14:33:37.820(1)? (STDERR)  - simpl-schema@0.x.x not installed.
> W20170308-14:33:37.820(1)? (STDERR) 
> W20170308-14:33:37.820(1)? (STDERR) Read more about installing npm peer dependencies:
> W20170308-14:33:37.820(1)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
> W20170308-14:33:37.821(1)? (STDERR) 
> W20170308-14:33:37.843(1)? (STDERR) /home/abate/.meteor/packages/meteor-tool/.1.4.3_1.1wkjdp4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
> W20170308-14:33:37.843(1)? (STDERR) 						throw(ex);
> W20170308-14:33:37.844(1)? (STDERR) 						^
> W20170308-14:33:37.844(1)? (STDERR) 
> W20170308-14:33:37.844(1)? (STDERR) Error: Can't find npm module 'simpl-schema'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
> W20170308-14:33:37.844(1)? (STDERR)     at Object.require (/home/abate/Projects/repos/meteor/abate:budget/.meteor/local/build/programs/server/boot.js:200:17)
> W20170308-14:33:37.845(1)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
> W20170308-14:33:37.845(1)? (STDERR)     at require (packages/modules-runtime.js:126:16)
> W20170308-14:33:37.845(1)? (STDERR)     at meteorInstall.node_modules.meteor.aldeed:collection2-core.collection2.js (packages/aldeed:collection2-core/collection2.js:9:22)
> W20170308-14:33:37.845(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
> W20170308-14:33:37.845(1)? (STDERR)     at require (packages/modules-runtime.js:120:16)
> W20170308-14:33:37.846(1)? (STDERR)     at /home/abate/Projects/repos/meteor/abate:budget/.meteor/local/build/programs/server/packages/aldeed_collection2-core.js:721:15
> W20170308-14:33:37.846(1)? (STDERR)     at /home/abate/Projects/repos/meteor/abate:budget/.meteor/local/build/programs/server/packages/aldeed_collection2-core.js:732:3
> W20170308-14:33:37.846(1)? (STDERR)     at /home/abate/Projects/repos/meteor/abate:budget/.meteor/local/build/programs/server/boot.js:303:34
> W20170308-14:33:37.846(1)? (STDERR)     at Array.forEach (native)
> => Exited with code: 1
> => Your application is crashing. Waiting for file change.
> 

I'm not quite sure what is the reason of this problem...

**Comment by abate** [comment]
now, installing simpl-schema on the toplevel works
`meteor npm install --save simpl-schema`

but I still don't understand why I've to do that ...

**Comment by abate** [comment]
I got it : [peer-npm-dep](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies)

**Comment by ryanmattos** [comment]
Pedro Abate, luv ya man

**Comment by skhuni** [comment]
Thanks a lot
