### ISSUE TITLE
Why can´t I install autoform 6?

### ISSUE THREAD

**Issue by Mklueh** [aldeed/meteor-autoform#1579]
Whenever I install autoform, it installs a previous version instead of 6.0.0. Why?

> This project is already at Meteor 1.4.3.2, the latest release.
> Your top-level dependencies are at their latest compatible versions.
> 
> The following top-level dependencies were not updated to the very latest version available:
>  * aldeed:autoform 5.8.1 (6.0.0 is available)
> 
> Newer versions of the following indirect dependencies are available:
>  * aldeed:collection2-core 1.2.0 (2.0.0 is available)
>  * aldeed:schema-deny 1.1.0 (2.0.0 is available)
>  * aldeed:schema-index 1.1.1 (2.0.0 is available)
> To update one or more of these packages, pass their names to
> `meteor update`, or just run `meteor update --all-packages`.

**Comment by Fotso** [comment]
Same thing here. I still stuck with autoform 5.8.1

**Comment by rcurrier666** [comment]
Ditto for me. I'm going to try forcing it to install by specifying the version.

**Comment by rcurrier666** [comment]
If you haven't done so try ```meteor remove aldeed:autoform``` and then ```meteor add aldeed:autoform```. The remove will also remove the old version of aldeed:simple-schema that seems to be what was preventing the upgrade. Worked for me.

**Comment by Fotso** [comment]
It still doesn't work.
Removing and adding the `aldeed:autoform ` with meteor command doesn't change anything on my  project. 
I still have the former version of autoform package `aldeed:autoform@5.8.1`
aldeed:autoform is one of the dependencies for [Yogiben Admin](https://atmospherejs.com/yogiben/admin). 

I am not quite sure but among the several dependencies packages in Yogiben admin, some could use autoform and preventing it to update on version 6 ...

**Comment by aldeed** [comment]
Yes, in general `remove` and then `meteor add aldeed:autoform@6.0.0` will always work or will give you an explanation of why it can't be installed. Yogiben admin has not been updated, so someone may want to update a fork of that. You can't use latest autoform unless every pkg you use also uses latest.
