### ISSUE TITLE
Sub-Schema not rendering correctly in quickForm

### ISSUE THREAD

**Issue by kamin438** [aldeed/meteor-autoform#1583]
For some reason, the Sub-schema of UserCountry, in the schema of Bio, is rendering just as a single input field instead of display the full subdocument. The nested schema comes out as the key being a String type. Any explanation as to why? 

```javascript
import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';


SimpleSchema.extendOptions(['autoform']);

export const Bio = new Mongo.Collection('bio');

const Schema = {};
Meteor.isClient && Template.registerHelper('Schema', Schema);

Bio.allow({
  insert: function (userId, doc) {
    return !!userId;
  },
});


Schema.UserCountry = new SimpleSchema({
    name: {
        type: String
    },
    code: {
      type: String,
      regEx: /^[A-Z]{2}$/
    }
});

Schema.Bio = new SimpleSchema({
  name: {
    type: String,
    label: "Job Title"
  },
  description: {
    type: String,
    label: "Description"
  },
  author: {
    type: String,
    label: "Author",
    autoValue() {
      return this.userId;
    },
    autoform: { type: 'hidden' }
  },
  createdAt: {
    type: Date,
    label: "Created At",
    autoValue() {
      return new Date();
    },
    autoform: { type: 'hidden' }
  },
  country: {
    type: Schema.UserCountry,
    optional: true
  }
});

Bio.attachSchema(Schema.Bio);


Template.NewRecipes.helpers({
  Bio(){
    return Bio;
  }
});

```

```html
<template name="BioInfo">
  <h1>My Bio</h1>
  <div class="new-bio-container">
    {{> quickForm collection=Bio id="insertBioForm" type="insert"  class="new-bio-from"}}
  </div>
</template>
```

**Comment by danyhiol** [comment]
Same here. Can't render another SimpleSchema instance in a schema. Alway output just one field as String. Another problem I have is that i can't use:
`{{#autoForm schema=Schema.UserCountry id="insertSchemaForm" type="insert" }}
       ...
  {{/autoForm}}` To insert only in the Schema.UserCountry instance.

**Comment by elhoucine** [comment]
I am facing the same issue.

You can use extend as a workaround.

```
Schema.Bio = new SimpleSchema({
  ...
  country: {
    type: Object,
    optional: true
  },
  "country.name": {
    type: String
  },
  "country.code": {
    type: String,
    regEx: /^[A-Z]{2}$/
  }
});
```

**Comment by danyhiol** [comment]
@elhoucine Thanks for your suggestion. I already figured that out. Using Objects or Array in the Schema works. The only problem is when rendering with autoForm.  I could render the collection fields (array field) using `afArrayField` but insert didn't work. And another problem is that is couldn't find any way to display array object with [aldeed:tabular](https://atmospherejs.com/aldeed/tabular)

**Comment by aldeed** [comment]
Latest release, 6.2.0, should fix this
