### ISSUE TITLE
autoForm schema=Schemas.mySchema not working

### ISSUE THREAD

**Issue by danyhiol** [aldeed/meteor-autoform#1587]
I'm relatively new in Meteor and we are building an app that will require lots of forms. We decide to go with collection@core2, autoForm, and Simpl-schema.  Since MongoDB is not good for relation (Or at leat not as relational DB) we opt to build one collection for our app that will include lots of schema interacting with each other and the core collection.
Here is an example:

Schema:

```
Books = new Mongo.Collection("books");
const Schemas = {};
```

```
Schemas.Info = new SimpleSchema({
    name: {
        type: String,
        label: "Infos. name",
    },
    desc: {
        type: String,
        label: "Infos. Description"
    }
});
```

```
Schemas.Books = new SimpleSchema({
    title: {
        type: String,
        label: "Title",
        max: 200
    },
    author: {
        type: String,
        label: "Author"
    },
    copies: {
        type: SimpleSchema.Integer,
        label: "Number of copies",
        min: 0
    },
    lastCheckedOut: {
        type: Date,
        label: "Last date this book was checked out",
        optional: true
    },
    summary: {
        type: String,
        label: "Brief summary",
        optional: true,
        max: 1000
    },
    info: {
        type: Schemas.Info,
        optional: true
    }
});
```

`Books.attachSchema(Schemas.Books);` 

the same design is defined [here](https://github.com/aldeed/meteor-collection2-core#attach-a-schema-to-meteorusers)

Now then I tried to insert only on the info schema, nothing happens.

`{{#autoForm schema=Schemas.Info id="insertSchemaForm" type="insert"}}`
_________________________________________________________________________________
**SOLUTION**
I found the problem. 
1. When definining `schemas` with `simple-schema` that will be attached to another schema, it's not important to use Arrays as long as you define a helper in your client.js: `Template.registerHelper("Schemas", Schemas);` .
2. See [documentation](https://github.com/aldeed/meteor-autoform#should-the-value-of-schema-and-collection-have-quotation-marks-around-it) for more.
3. The Schema declaration schould be made globally (without var/const): `Schemas = {};`
_________________________________________________________________________________
Nothing is displayed. 
The idea is to be able to use each schema on its own to render/submit data to the collection fields.
Also the autoForm syntax:

`autoform: {
            afFieldInput: {
                type: "file"
            }
}`
in no more working with simple schema. 

It would be great if anyone could help...maybe with some example code. I've been searching for a solution on this for quite a long time.

**Comment by elhoucine** [comment]
Maybe there is an issue where autoform does not render a subSchema.  see #1583

**Comment by lonniev** [comment]
I'm only a few days ahead of you up the learning curve.

A quick check: is Schemas.About non-null in the context of your HTML template? It can be if you haven't imported your javascripts adequately. You may need a Template helper to be able to carry the reference to the Schema from where it is defined into the template's scope.

**Comment by danyhiol** [comment]
@lonniev Thanks for your reply. I don't think the schema has a null context since the form is rendered without any field. The submit button manually added to the Schema `<button type="submit" class="btn btn-primary">Insert</button>` . If i add a html tag to the form (like `<h1>Title</h1>`) it will be displayed.
But I still can you provide some example code of what you mean, so I can try it.
I also update my schema since there was an error in it. The schema I was trying to render using autoForm is `Schemas.Info` and not `Schemas.About` Sry for that.

**Comment by aldeed** [comment]
Seems like this is resolved? You need to `SimpleSchema.extendOptions(['autoform']);` now
