### ISSUE TITLE
Invalid Definition Field when using Autoform 6 with Simple Node Schema

### ISSUE THREAD

**Issue by Mona786** [aldeed/meteor-autoform#1594]
I am running into problem when doing meteor build with invalid field error:

**Sample Code**

var SimpleSchema = require("node-simple-schema");
import SimpleSchema from 'simpl-schema';
SimpleSchema.extendOptions(['autoform']);

studentData = "studentData";  // avoid typos, this string occurs many times.

StudentData = new Mongo.Collection(studentData);

const schema = new SimpleSchema({  
   schoolcode: {
    type: String,
    optional: false,
    max: 20,
    autoform: {
      group: studentData,
      placeholder: "Please insert the student ID"
    }
  },
});

**Error** 
Error: Invalid definition for schoolcode field.
    at /home/mona/finalemis/emis/testemis/bundle/programs/server/npm/node_modules/node-simple-schema/simple-schema.js:478:13
    at /home/mona/finalemis/emis/testemis/bundle/programs/server/npm/node_modules/lodash/index.js:3073:15
    at baseForOwn (/home/mona/finalemis/emis/testemis/bundle/programs/server/npm/node_modules/lodash/index.js:2046:14)
    at /home/mona/finalemis/emis/testemis/bundle/programs/server/npm/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/home/mona/finalemis/emis/testemis/bundle/programs/server/npm/node_modules/lodash/index.js:3346:13)
    at [object Object].SimpleSchema (/home/mona/finalemis/emis/testemis/bundle/programs/server/npm/node_modules/node-simple-schema/simple-schema.js:475:5)
    at meteorInstall.lib.collections.Non-formal.EspecialNeed.blind.BlindData.js (lib/collections/Non-formal/EspecialNeed/blind/BlindData.js:108:16)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at /home/mona/finalemis/emis/testemis/bundle/programs/server/app/app.js:67615:

**1) Meteor Version**
Meteor 1.4.4.1

**2) Meteor List**

accounts-base                   1.2.16* A user account system
accounts-password               1.3.5  Password support for accounts
alanning:roles                  1.2.16  Authorization package for Meteor
aldeed:autoform                 6.0.0  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2-core         2.0.0  Core package for aldeed:collection2
aldeed:template-extension       3.4.3* Adds template features currently missing from the templating package
aslagle:reactive-table          0.8.40  A reactive table designed for Meteor
blaze-html-templates            1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
check                           1.2.5  Check whether a value matches a pattern
dburles:google-maps             1.1.5  Google Maps Javascript API v3
differential:event-hooks        1.5.0  Provides hooks for various user-triggered events
ecmascript                      0.7.3  Compiler plugin that supports ES2015+ in all .js files
ejson                           1.0.13  Extended and Extensible JSON library
fortawesome:fontawesome         4.7.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
gwendall:auth-client-callbacks  0.1.0  Adds client-side onLogin and onLogout methods
harrison:papa-parse             1.1.7  A powerful, in-browser CSV parser for big boys and girls
ian:accounts-ui-bootstrap-3     1.2.89  Bootstrap-styled accounts-ui with multi-language support.
id-map                          1.0.9  Dictionary data structure allowing non-string keys
iron:router                     1.1.2  Routing specifically designed for Meteor
jquery                          1.11.10  Manipulate the DOM using CSS selectors
kookoskar:iron-router-roles     0.0.2  Adds roles to Iron.Router
less                            2.7.9  Leaner CSS language
logging                         1.1.17  Logging facility.
maazalik:highcharts             0.4.0  HighCharts for Meteor, with an easy to use helper to get you started!
maazalik:highcharts-3d          0.4.0  HighCharts 3D charts for Meteor
matb33:collection-hooks         0.8.4  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
mdg:geolocation                 1.3.0  Provides reactive geolocation on desktop and mobile.
meteor-base                     1.0.4  Packages that every Meteor app needs
meteorhacks:aggregate           1.3.0  Proper MongoDB aggregations support for Meteor
meteorhacks:npm                 1.5.0  Use npm modules with your Meteor App
meteortoys:allthings            3.0.0  Insanely Handy Development Tools
mike:mocha                      0.6.6  Run mocha tests in the browser
mobile-experience               1.0.4  Packages for a great mobile user experience
mongo                           1.1.16  Adaptor for using MongoDB and Minimongo over DDP
npm-container                   1.2.0+ Contains all your npm dependencies
peppelg:mongo-sum               2.0.0  Reactive sum queries in MiniMongo on client.
pfafman:filesaver               0.2.3_2* filesaver.js packaged for use in Meteor.
random                          1.0.10  Random number generator and utilities
reload                          1.1.11  Reload the page while preserving application state.
sacha:spin                      2.3.1  Simple spinner package for Meteor
sanjo:jasmine                   1.0.1  Velocity integration of the Jasmine testing framework
session                         1.1.7  Session variable
shell-server                    0.2.3  Server-side component of the `meteor shell` command.
spacebars                       1.0.15  Handlebars-like template language for Meteor
standard-minifier-css           1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js            2.0.0  Standard javascript minifiers used with Meteor apps by default.
tracker                         1.1.2  Dependency tracker to allow reactive callbacks
twbs:bootstrap                  3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
velocity:html-reporter          0.10.1  Reactive Velocity test reports in your app

Am I missing something as I am new to Meteor? Please help as I need to fix this issue asap.

Thanks,

**Comment by plumpudding** [comment]
You must add this and make sure that it runs before you create your first schema:
`SimpleSchema.extendOptions(['autoform', 'denyInsert', 'denyUpdate'])`

**Comment by Mona786** [comment]
Thank you for your quick response. I tried that with no luck. Probably be faster to create a form from scratch.

**Comment by aldeed** [comment]
@Mona786 This line should not be there, but maybe you were just experimenting with the package locally?

```js
var SimpleSchema = require("node-simple-schema");
```

The other thing is look in your `.meteor/versions` file and make sure `meteor-simple-schema` does not appear. If some package you are using is pulling in the old Meteor package, it can interfere.

**Comment by Mona786** [comment]
Thank you very much. You are correct after removing that line it is working.
