### ISSUE TITLE
aldeed:autoform causes error in 1.4.4.2

### ISSUE THREAD

**Issue by apitlekays** [aldeed/meteor-autoform#1596]
I'm building a web app and wanted to use autoform. Once added the package, the browser console threw several errors:
```
1. Uncaught Error: Cannot find module 'mongo-object'
2. Uncaught TypeError: Cannot read property 'AutoForm' of undefined
3. Uncaught ReferenceError: meteorInstall is not defined
4. There's no route for the path: /
``` 

Anybody facing the same problem?

**Comment by apitlekays** [comment]
solved it by installing simpl-schema

**Comment by davidsocias** [comment]
Hello, I have the problem, can you tell me which package you used? thanks

**Comment by vermadivyanshu** [comment]
Hey @davidsocias i faced the problem today with autoform version 6.2.0. I downgraded the same to 5.8.1. that fixed the problem for me. Hope this helps you out

**Comment by davidsocias** [comment]
@vermadivyanshu I fixed the problem by adding some lines of code:
import SimpleSchema from 'simpl-schema'; 
SimpleSchema.extendOptions(['autoform']);

Thanks bro
