### ISSUE TITLE
using method form type without collection2 throws typeError

### ISSUE THREAD

**Issue by Jaredrlaw** [aldeed/meteor-autoform#1616]
I do not use collection2.
I have simpl-schema added to my project from npm.

I'm running into an issue where when both schema and collection are provided to the quickForm template, it attempts to validate against the collection schema (presumably from collection2) which throws:

`Uncaught TypeError: collection.simpleSchema is not a function` from method.js:44

Context of method.js:44 is:
```
    // If there is a `schema` attribute but you want to force validation against the
    // collection's schema instead, pass useCollectionSchema=true
    ss = (this.useCollectionSchema && collection) ? collection.simpleSchema() : ss;
```
issue persists when passing useCollectionSchema=false attribute to the quickForm template. Is this a bug?

I was able to resolve it by commenting out that line from the package (variable ss is defined properly when it is declared).

**Comment by StillOnMyWay** [comment]
Did you try removing the '()' from `collection.simpleSchema()` ?

**Comment by Jaredrlaw** [comment]
Thanks for replying!

That's a line from the autoform package itself.

The trouble is that it's resolving true, even though the comment above it makes it seem like the useCollectionSchema variable should default to false and when setting it false explicitly via:
`{{>quickForm collection=collection schema=schema type="insert" ... useCollectionSchema=false}}`
