### ISSUE TITLE
img input type

### ISSUE THREAD

**Issue by FelBraSil** [aldeed/meteor-autoform#1639]
I've been looking for a way to upload images using meteor and autoform v6+
So i've been reading the documentation and also the demo instances, and i found the img input type, and also the file type [here](http://autoform.meteorapp.com/types)
The file type works fine, but there's something i'm missing with the image type.
Is it supposed to upload an image?  it does nothing when clicking so i don't know what it does, no dialogues or the file manager opening, like it does with the file type.

Is there a way to use the image type to upload then use an image?
Does the file type have a way to display images?

What i need in the end is to call the image with the usual brackets {{image}} like i do with any variable, hope there's a way to do this, any guidance or help, or documentation about img type is welcome

**Comment by jalvarezh1994** [comment]
Same problem here
