### ISSUE TITLE
AutoForm.getSchemaForField() results in error

### ISSUE THREAD

**Issue by ddanna** [aldeed/meteor-autoform#1640]
Calling `AutoForm.getSchemaForField(fieldName)` when triggered from an event results in an error: `TypeError: undefined is not an object (evaluating 'form._resolvedSchema')`

I'm adding a "row" of inputs to an array field using:
`AutoForm.arrayTracker.addOneToField(formId, name, simpleSchema)`

After this, I need to get a data map of the inputs for this array field, so I use:
`rows = AutoForm.arrayTracker.getField(formId, name)`

Which returns an array of the "rows" of inputs, which I then loop through.
Within this loop of rows, I loop through each input ("col") for this row:

`Object.keys(row.current).forEach(function(col){})`

Within this inner loop of col, I need to get the schema for each input, so I calculate the name of the "cell" using row and col:
``let cellName = `{$row.name}.${col}` ``

Which would give me something like "players.0.firstName" which I then try to get the schema for:

`let cellSchema = AutoForm.getSchemaForField(cellName)`

And this is where my error is. All of this code is inside the .onRendered for my template, and the schema is loaded for each cell when the function is first called, but it seems like AutoForm is losing context when I run the function again (triggered from an event). Is there anyway to get AutoForm to know it's context? I have access to formId at all times, but I can't figure out how to have that help me.

**Comment by FelBraSil** [comment]
when i get this kind of error is when i use server-sided object being called from a client-sided event  
i usually use an if to check if server then do what i need, still, that won't work with client sided events
