### ISSUE TITLE
this.current not present in afEachArrayItem block

### ISSUE THREAD

**Issue by alexpyslar** [aldeed/meteor-autoform#1642]
@aldeed 
I'm using autoform v6.3.0 and seeing next error in console:

> Exception in template helper: TypeError: Cannot read property 'singleType' of undefined
    at SimpleSchema.getQuickTypeForKey

`{{#afEachArrayItem name='organizations'}}
{{> afQuickField name=this.current.state label=false}}
{{/afEachArrayItem}}`

what's wrong with this.current?

**Comment by alexpyslar** [comment]
@aldeed 
I created repo as you wrote [here](https://github.com/aldeed/simple-schema-js/issues/100#issuecomment-373456985)

Repo [link](https://github.com/alexpyslar/meteor)

pressing on book you will see how it acts inside afEachArrayItem block
I added console log for the book object.
Errors discussed [here](https://github.com/aldeed/simple-schema-js/issues/100#issuecomment-373456985) about **property 'singleType'** you also can see in browser console. 
Hope this is enough.
Please check asap.

**Comment by alexpyslar** [comment]
@aldeed any luck?)

**Comment by poojabansal** [comment]
@aldeed I am also facing the same issue.

**Comment by krishaamer** [comment]
Same problem here.

**Comment by CaptainN** [comment]
This seems to be coming from upstream - the `atts` obj which is passed to `getQuickTypeForKey` has only an `id` attribute, no name which `getQuickTypeForKey` seems to assume it'll get. The origin of that `atts` object is `/components/afFieldInput/afFieldInput.js`'s `this` prop, which I would assume is some kind of Blaze thing, and I don't know Blaze well enough to determine whether that should have a name field, and/or why it does not - but I can confirm it only contains an `id` property, and that seems to be the origin of the error.

**Comment by Pagebakers** [comment]
See https://github.com/EmurgoHK/Emurpas/issues/47#issuecomment-419828098

**Comment by Pagebakers** [comment]
Solution:

https://github.com/aldeed/meteor-autoform/blob/d8f8b6a6e36079c054976ca8bda7bec97f548b4f/autoform-arrays.js#L60

https://github.com/aldeed/meteor-autoform/blob/d8f8b6a6e36079c054976ca8bda7bec97f548b4f/autoform-arrays.js#L167

```js
if (typeof AutoForm.Utility.getFieldDefinition(ss, field + '.$').type === 'object') {

}
```

**Comment by rootedsoftware** [comment]
@Pagebakers have you submitted a pull request for this change? I'm not finding one.

**Comment by alexpyslar** [comment]
Sorry guys that didn't write earlier, I did resolve it with my approach, as @aldeed didn't answered.
My solution is temporary, but it works for sure:
- create ui helper
`Handlebars.registerHelper('collectionPointer', function (propName) {
    return this.name + '.' + propName;
});`
- inside template call it like:
`{{> afQuickField name=(collectionPointer 'name') template="some-templ"}}`

**Comment by alexpyslar** [comment]
@Pagebakers tried your solution, my meteor instance crashes on compilation when I made those changes, lol

**Comment by Pagebakers** [comment]
That's odd, what errors are you getting?
