### ISSUE TITLE
meteor insert collection with wizard autoform and SimpleSchema

### ISSUE THREAD

**Issue by AtouiIlyes** [aldeed/meteor-autoform#1645]
Hello I am trying to insert a orders collection using a wizard autoform with SimpleSchema this is my code

`import {Template} from "meteor/templating";
import SimpleSchema from 'simpl-schema';
import {Meteor} from "meteor/meteor";
Orders = new Mongo.Collection('orders');

Schemas = {};

Schemas.company = new SimpleSchema({
    name:{
        type: String,
        label: 'Name'
    },
    address: {
        type: String,
        label: 'Address'
    },
    phone: {
        type: String,
        label: 'Phone'
    },
    email: {
        type: String,
        label: 'Email'
    }
});
Schemas.features = new SimpleSchema({
    featureType: {
        type: String,
        label: 'Feature Type',

    }
});
Orders.attachSchema(Schemas.company);
Orders.attachSchema(Schemas.features);

Template.contracts.onCreated(function contractsOnCreated() {
});
Template.viewOrder.onCreated(function viewOrderOnCreated() {
});
Template.contracts.helpers({
    steps: function() {
        return [{
            id: 'company',
            title: 'Company information',
            schema: Schemas.company
        }, {
            id: 'features',
            title: 'Features',
            schema: Schemas.features,
            onSubmit: Meteor.call('insertOrders',  function (er) {
                if (er) {
                    toastr.error( "insert problem");
                    console.log(er);

                } else {
                    toastr.success( "orders added successfully","success");

                }
            }),
        }];
    }
});

Template.viewOrder.helpers({
    name: function() {
        return Orders.findOne(FlowRouter.current().params._id).name
    }
});
Template.viewOrder.events({
    'click #place'(event) {
        event.preventDefault();
        FlowRouter.go('/conversation');
    }
});

Wizard.useRouter('kadira:flow-router');`

and this is my collection /server/collections.js

`Orders = new Mongo.Collection('orders');
`
and this is my methods /server/methods.js

`import {Meteor} from "meteor/meteor";

Meteor.methods({
    register: function(user,role) {

        var id = Accounts.createUser(
            user
        );

        Roles.addUsersToRoles(id, role);

    },

    insertOrders: function(data, wizard) {
        var self = this;
        Orders.insert(_.extend(wizard.mergedData(), data), function(err, id) {
            if (err) {
                console.log(err);
                self.done();
            } else {
                FlowRouter.go('/orders/' + id)
            }
        });
    }
});`
when submit i got this error

> errorClass {isClientSafe: true, error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", …}details: undefinederror: 500errorType: "Meteor.Error"isClientSafe: truemessage: "Internal server error [500]"reason: "Internal server error"stack: "Error: Internal server error [500]↵ at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=69c1d15adcf9b913cb4704b652adeff4bc462aa8:1975:25)↵ at Connection.onMessage (http://localhost:3000/packages/ddp-client.js?hash=69c1d15adcf9b913cb4704b652adeff4bc462aa8:2169:14)↵ at http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:262:13↵ at Array.forEach ()↵ at ClientStream.forEachCallback (http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:353:33)↵ at SockJS.socket.onmessage (http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:261:18)↵ at SockJS.REventTarget.dispatchEvent (http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:641:22)↵ at SockJS._dispatchMessage (http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:1820:10)↵ at SockJS._didMessage (http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:1886:16)↵ at WebSocket.that.ws.onmessage (http://localhost:3000/packages/socket-stream-client.js?hash=7063aa833005aff7419b3f8c222e877582f1a3e0:2044:15)"proto: Error

any help please!!

**Comment by abate** [comment]
try to format the code a bit better. It's pretty difficult to understand what is your problem
