### ISSUE TITLE
quickform doesn't work when simpl-schema upgraded to 1.5.0

### ISSUE THREAD

**Issue by goodideal** [aldeed/meteor-autoform#1653]
Hello @aldeed 

The quickform shows error when I upgraded simpl-schema to 1.5.0. Please find the following screenshot:

![image](https://user-images.githubusercontent.com/1137524/38779270-7ec8c886-40f8-11e8-81ac-17b69abc4ea5.png)

It works on simpl-schema 1.4.2

**Comment by Nico999777** [comment]
Did you upgrade simple schema as well? It is a npm now.

**Comment by Nico999777** [comment]
Probably delete the old version then

**Comment by rootedsoftware** [comment]
@Nico999777 
@goodideal is talking about the npm package. I have the same problem when I upgrade to 1.5.0

**Comment by norx85** [comment]
Same problem for me, using a quickForm with user schema.
The only workaround is to downgrade simpl-schema package to 1.4.3

It keeps spawning exceptions in file `autoform-api.js`, line 763, in function 'getInputType' :
the code at this line is:
`var schemaType = ss && ss.getQuickTypeForKey(atts.name);`
The exception occurs because `atts.name` is undefined: `atts` seems to be an object with only an `id` field.

**Comment by tab00** [comment]
I got the same problem with `[object Object]` being output when displaying contacts array:
`{{> afQuickField name="contacts" value=contacts}}`

I downgraded to 1.4.3 and there was no longer a problem.

Please fix this.

**Comment by anormore** [comment]
How did you downgrade?

**Comment by norx85** [comment]
@anormore you can just set version 1.4.3 in `package.json` of your project and then run `npm i`

**Comment by anormore** [comment]
Thanks for quick reply, here's how I did it: 

npm install simpl-schema@1.4.2

WORKS! Cool.

**Comment by marcoschwartz** [comment]
Same issue here, for me it is also coming from the latest version of simpl-schema (1.5.0). When I revert to 1.4.3 the issue goes away. I noticed it's only with quickForms, when I use #autoform it works without issues. 

Would be great to have a fix for it however, to keep up with future updates of simpl-schema

**Comment by erisevaline** [comment]
Same issue here and downgrade fix works too for me.

**Comment by tab00** [comment]
Is there going to be a proper fix?

Downgrading shouldn't be the solution.

**Comment by fillipefeitosa** [comment]
Downgrade worked for me.

**Comment by tab00** [comment]
Can we have a proper fix?

**Comment by jankapunkt** [comment]
Fix (in SimpleSchema) is ready to be merged: https://github.com/aldeed/simple-schema-js/pull/291

**Comment by rootedsoftware** [comment]
Any reason we can't merge this code fix?

**Comment by jankapunkt** [comment]
This is fixed; install latest SimpleSchema to make this work.
