### ISSUE TITLE
Change "file" filetype and size

### ISSUE THREAD

**Issue by Nico999777** [aldeed/meteor-autoform#1655]
I am trying to put this in my form: 
```
   file: {
      type: String,
      optional: true,
      autoform: {
         type: 'file'
		
      }
}
```
But people can upload whatever they want which is not good. Is there a way to restrict what people can upload (For instant only pdf and png) and maybe the size (5mb) as well? Couldn't find anything

**Comment by jankapunkt** [comment]
Please use `ostrio:meteor-files` wit `ostrio:autoform-files` to achieve this goal
