### ISSUE TITLE
Colleciton.update(some_id, {$set .... Doesn't work!

### ISSUE THREAD

**Issue by advancedsoftwarecanada** [aldeed/meteor-autoform#1658]
```
                        console.log(theCase);
			Cases.update(_id:theCase._id,
				{$set: {
					caseStatus: "closed",
					}
				}
			);
			console.log("THIS NEVER WORKS");
```
So, I've got a valid "Case" from my collection, but when I try to update the caseStatus... Meteor just stops. No errors, nothing. It simply never gets to console.log("THIS NEVER WORKS").

Whyyyyyy?

**Comment by rikyperdana** [comment]
You didn't wrap your selector in a bracket. Change to this {_id: something._id}
