### ISSUE TITLE
Loaded Callback

### ISSUE THREAD

**Issue by luixal** [aldeed/meteor-autoform#1671]
Hi,

I just started working with **big** forms using Autoform. Maybe's not the best option for this kind of forms, but it's really quick to get up running.

Problem is, the form takes some seconds to load (many selectizes on board) and will be great to show a "loading" message while the form gets entirely loaded.

I haven't found in the docs any callback fired when the form is totally loaded, any idea on how to accomplish this?

Thanks!

**Comment by raymondcarl** [comment]
Hi,

Check out how this boilerplate does it.  https://github.com/kjetilhau/meteor-skeleton

First, I would run it locally and see if it does exactly what you are looking for.  Then, you could look in the schema methods, form helpers, etc. to see how it works.
