### ISSUE TITLE
select autoform

### ISSUE THREAD

**Issue by rrmorales87** [aldeed/meteor-autoform#1674]
Hello Aldeed 
I need call a async method in options of  select  for autoform
for example:
  region: {
    type: String,
    optional: true,
    autoform:{
       type:'select',

      options:function(){
        geonames.search({q: 'CONT'}) //get continents
        .then(resp => {
          return resp.geonames.map(function(r){
            console.log(r);
            return {label:r.name,value:r.geonamesId}
       

      }

    }
  },

This could be?

**Comment by mozfet** [comment]
I think you need to wait for the promise to resolve in order for it to work.
Assuming you can use ES6, try this:
```
options: async function() {
   const resp = await geonames.search({q: 'CONT'}) //get continents
   return resp.geonames.map(function(r){
        console.log(r);
        return {label:r.name,value:r.geonamesId}
   }
}
```
