### ISSUE TITLE
use moment package from NPM

### ISSUE THREAD

**Issue by markdowney** [aldeed/meteor-autoform#1676]
Is there any reason this package depends on the `momentjs:moment` meteor package? It seems using the npm package is the recommended option now so this dependency introduces an extra 53kb if your app already uses the npm version. 

Lmk if you're willing to change this, I'd be happy to submit a PR.

**Comment by jankapunkt** [comment]
It's planned to get fully rid of moment in favour of builtin Date or a lightweight solution
