### ISSUE TITLE
Adding a CSS Class to afQuickField labels : class-label not working

### ISSUE THREAD

**Issue by Joris-SEBIRE** [aldeed/meteor-autoform#1685]
Hello,

I have an issue with new version of AutoForm i just updated. 

On previous version, my forms looked like that : 
![image](https://user-images.githubusercontent.com/38475496/50484380-964de880-09f0-11e9-87b3-c6f1ceab90c9.png)

With the associated CSS class : 
![image](https://user-images.githubusercontent.com/38475496/50484390-a1087d80-09f0-11e9-8a04-ff25f9e59dec.png)

And the result was : 
![image](https://user-images.githubusercontent.com/38475496/50484372-7fa79180-09f0-11e9-9a25-dc34462849d3.png)
![image](https://user-images.githubusercontent.com/38475496/50484510-21c77980-09f1-11e9-81b9-39dca09a1e01.png)

Today, witht the new version of meteor, my label don't have the class anymore and i couldn't find a way to add it.
![image](https://user-images.githubusercontent.com/38475496/50484529-3441b300-09f1-11e9-9f80-1c744355325c.png)
![image](https://user-images.githubusercontent.com/38475496/50484539-458abf80-09f1-11e9-9228-59f07bc66eb0.png)

Anybody having a solution on that ? I need to add a red (*) to my required fields.

Thanks in advance :)

**Comment by jankapunkt** [comment]
This issue has been resolved with AutoForm 7.0.0, please migrate to the latest version and reopen in case the issue persist
