### ISSUE TITLE
latest meteor

### ISSUE THREAD

**Issue by interfaith** [aldeed/meteor-autoform#1688]
does not work with the latest meteor version

**Comment by interfaith** [comment]
W20190113-15:39:41.760(-8)? (STDERR) Error: Invalid definition for transportation field: "type" may not be an array. Change it to Array.
W20190113-15:39:41.761(-8)? (STDERR)     node_modules/simpl-schema/dist/SimpleSchema.js:1133:13

**Comment by interfaith** [comment]
old meteor version of simpl schema plugin is OK ! for latest meteor but NOT the npm package !

**Comment by interfaith** [comment]
custom form (autoform) is ok but quickform fails

**Comment by jankapunkt** [comment]
Please see #1653 
Use simpl-schema@1.4.3 to fix this

**Comment by interfaith** [comment]
autoform.addhooks works autoform.hooks does not ( with latest meteor)

**Comment by jankapunkt** [comment]
@interfaith thank you for your hints but they are incomplete unless you add some error stacktrace.

**Comment by jankapunkt** [comment]
Should all be fixed by now and it should all run fine with the latest `simpl-schema`

**Comment by jankapunkt** [comment]
I am closing this issue, feel free to reopen if the issue persist or you re-encounter the issue.
