### ISSUE TITLE
afQuickField id field is overwritten - v7

### ISSUE THREAD

**Issue by lynchem** [aldeed/meteor-autoform#1696]
This issue was introduced in 7, working previously.

We have a modal with a datetimepicker in it (eonasdan-bootstrap-datetimepicker) which is hidden. Before showing the modal we try and set the date in the picker but the picker has not been initialised so fails. 

The template that the modal contains has been rendered so I can only imagine that there might be an optimisation to not init controls that are not visible somewhere in 7?

**Comment by jankapunkt** [comment]
thank you @lynchem is this the correct repo: https://github.com/Eonasdan/bootstrap-datetimepicker ?

Do you activate the modal during the form using a custom mechanism or this part of the mentioned repo? Once I get a reproduction I can fix it asap.

**Comment by lynchem** [comment]
Nothing to do with the datetimepicker repo AFAIK and yes, that's the correct repo. 
Actually, thinking about it a bit more, this is most likely an issue in how the plugins interact with AF. So in this case there's an atmosphere package https://atmospherejs.com/aldeed/autoform-bs-datepicker which should be creating the datetimepicker. 
We have a local modified copy of this package (to fix some TZ issues) so I'll look and see if I can figure anything more

**Comment by jankapunkt** [comment]
Acutally we have this package also now under the MCP hood: https://github.com/Meteor-Community-Packages/meteor-autoform-bs-datepicker :-) If there is anything causing trouble I could fix that, too. Publishing would be then just a few steps away

**Comment by lynchem** [comment]
Right Jan, I'll make a mental note - I should always start with the simplest thing that could be going wrong.  :smile: 

When you create a control like this: 
```
{{> afQuickField id="disbursement-paid-date" name='date'}}
```
It seems in v7 is replaces the id leaving you with 
![image](https://user-images.githubusercontent.com/12910319/97992676-4d80cb00-1de3-11eb-9390-05bfa3859db3.png)

where it used to leave that alone and you'd have
![image](https://user-images.githubusercontent.com/12910319/97992706-5a052380-1de3-11eb-987f-e09b5c39bacc.png)

I'm guessing I'm not alone in having using the id= field occasionally to reference a control so might be a good idea to leave that as it was. Or add it to the breaking changes. It's simple enough to fix. 

I'll change the name of the issue to reflect this.

**Comment by jankapunkt** [comment]
Thanks for this investigation @lynchem 
Removing the id is of course not an intended behaviour at all. I will get to the bottom of this and inform you, once it's fixed and added to the PR.

**Comment by jankapunkt** [comment]
Hi @lynchem I found and fixed this issue. It has been removed during the rewrite. I reversed this but at the same time also support the id setting mechanism that @pouya-eghbali has introduced. Can you verify it's working now using a local copy of the v7-dev branch? Alternatively I could also publish another rc version.

**Comment by lynchem** [comment]
Great. Would be handy if you can publish it. I'll try have a look over the weekend

**Comment by jankapunkt** [comment]
Published as `6.4.0-rc.7.0.1`, you need to set the version explicitly via `aldeed:autoform@6.4.0-rc.7.0.1` or it won't be updated.

**Comment by lynchem** [comment]
Ok, I can confirm it's fixed in 7.0.1 :tada:
