### ISSUE TITLE
Problem with Meteor 1.11.1 Blazejs

### ISSUE THREAD

**Issue by gladenko** [aldeed/meteor-autoform#1699]
I have follow this guide but i have this error

meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1059 Exception in template helper: Error: Products is not in the window scope

if i remove quoted and insert in helpers this

 Products(){     
         return Products
}

no error but i don't show nothing!

**Versions (please complete the following information):**
 - Meteor version: 1.11.1
 - Browser: all
 - Package version: 7.0.0
 

**Additional context**
this my packages

accounts-password                      1.6.2  
aldeed:autoform                        7.0.0  
aldeed:collection2                     3.2.1  
blaze-html-templates                   1.1.2  
communitypackages:autoform-bootstrap4  1.0.5  
ecmascript                             0.14.3 
es5-shim                               4.8.0  
fortawesome:fontawesome                4.7.0  
johanbrook:publication-collector       1.1.0  
jquery                                 3.0.0  
less                                   3.0.1  
meteor-base                            1.4.0  
meteortesting:mocha                    2.0.1  
mobile-experience                      1.1.0  
momentjs:moment                        2.29.1 
mongo                                  1.10.0 
ostrio:files                           1.14.3 
ostrio:flow-router-extra               3.7.5  
reactive-var                           1.0.11 
session                                1.2.0  
shell-server                           0.5.0  
standard-minifier-css                  1.6.1  
standard-minifier-js                   2.6.0  
tracker                                1.2.0  
typescript                             3.7.6

Can You help me?

**Comment by evolross** [comment]
I use Blaze too and I always have to return the collection in a helper. Are you doing an `insert` or `update`? Have you defined your `type` field to specify this?

**Comment by jankapunkt** [comment]
Hi @gladenko could you please add the HTML code defining your `autoForm` or `quickForm`?

**Comment by jankapunkt** [comment]
> no error but i don't show nothing!

@gladenko did you follow the new [installation and migration guide](https://github.com/Meteor-Community-Packages/meteor-autoform#installation)? With AutoForm 7 you have to separately install the theme (to reduce bundle size at startup) otherwise the forms will be simply blank. The guide covers it all.

**Comment by jankapunkt** [comment]
@gladenko has this been resolved?

**Comment by jankapunkt** [comment]
@gladenko friendly ping. If there is no reaction from your side I will assume it's been resolved and soon close the issue. You can, however reopen any time in case it hasn't been resolved.
