### ISSUE TITLE
minCount and maxCount undefined inside afEachArrayItem

### ISSUE THREAD

**Issue by GaetanRouzies** [aldeed/meteor-autoform#1704]
**Describe the bug**

Inside the afEachArrayItem template, minCount and maxCount values are undefined for all items except the first one.

**To Reproduce**

Steps to reproduce the behavior (Project way):
1. Clone and launch this simple project: https://github.com/GaetanRouzies/bug-autoform-counts-afEachArrayItem
2. Click on "+" button
3. minCount and maxCount values are undefined for all items except the first one

Steps to reproduce the behavior (Code way):
1. Create a simple "SimpleSchema" with a type: Array
```js
export const mySchema = new SimpleSchema({
  myArray: {
    type: Array,
    autoform: {
      minCount: 1,
      maxCount: 3
    }
  },
  'myArray.$': {
    type: String
  },
}, { tracker: Tracker });
```
2. Use the afEachArrayItem template
```html
<template name="hello">
  {{#autoForm id="insert-config-form" schema=mySchema type="insert"}}
  {{#afEachArrayItem name="myArray"}}
  <div>
    <button type="button" class="autoform-add-item" data-autoform-field="myArray">+</button>
    <span>index: {{index}}, minCount:{{minCount}}, maxCount:{{maxCount}}</span>
  </div>
  {{/afEachArrayItem}}
  {{/autoForm}}
</template>
```
3. Click on "+" button
4. minCount and maxCount values are undefined for all items except the first one

**Expected behavior**

The minCount and maxCount should have a correct value. So we can write custom templates.

**Screenshots**

![image](https://user-images.githubusercontent.com/6534433/108213684-9a3ca780-712f-11eb-9ec9-bef1a67c0922.png)

See the simple HTML Template: https://github.com/GaetanRouzies/bug-autoform-counts-afEachArrayItem/blob/main/client/main.html
See the simple schema: https://github.com/GaetanRouzies/bug-autoform-counts-afEachArrayItem/blob/main/client/main.js#L7

**Versions :**
 - Meteor version: 2.0
 - Browser: Chrome
 - Package version: aldeed:autoform@7.0.0
 

**Additional context**

This bug add difficulties to create a custom template with afEachArrayItem, and using afArrayFieldHasMoreThanMinimum and afArrayFieldHasLessThanMaximum because we can't give it the good minCount and maxCount.

**Comment by jankapunkt** [comment]
Thank you for the issue report. I will reproduce asap and will let you know about the next steps

**Comment by jankapunkt** [comment]
Please check out the PR here: https://github.com/Meteor-Community-Packages/meteor-autoform/pull/1705

Then please add a review to confirm or request changes. Please consider edge-cases, too.

**Comment by jankapunkt** [comment]
@GaetanRouzies please test the PR and comment if it runs or if there are still issues

**Comment by GaetanRouzies** [comment]
I tested it on both the "bug-autoform-counts-afEachArrayItem" and on a personal project and it fixed the issue. Now the minCount and maxCount value are correct. 
It also avoid adding more item than the maxCount when clicking on the 'autoform-add-item'.
So that's great, thanks you

**Comment by jankapunkt** [comment]
Merged, will be published asap
