### ISSUE TITLE
Run a meteor method in before hook and await callback?

### ISSUE THREAD

**Issue by crimsonrocks** [aldeed/meteor-autoform#1709]
Is it possible to run a method call in the before hook and await the result of the callback before continuing on to submit the form?

**Comment by jankapunkt** [comment]
Hi @crimsonrocks could you please provide a minimal example that I can reproduce? From there we can Talk about your issue and whether it can be solved using a different Code/API usage or by implementing a new behavior.

**Comment by crimsonrocks** [comment]
AutoForm.hooks({
        SomeForm: {
            before : {
                "method" : function(insertDoc){
                    let determiner;
                    Meteor.call("some.method",someData,function(err,result){
                        if(err){
                            determiner = false;
                            console.log(err.reason);
                        }else{
                           determiner = true;
                           // Do some logic here, such as updating the form doc
                        }
                    });
                    return ((determiner) ? insertDoc : false);
                },
            },
            // Other hooks
    },
});

I'm playing around with a payments system, and one of the features I was thinking about was something like a 4 digit pin code that a user could add to their account if they wanted to. Anytime they're about to pay for something the keypad pops up and asks them to input their code, and hits up a method call to validate it. If validation succeeds the form is submitted, otherwise it fails.

I haven't come up with a better way of doing this other than running a method call in the before hook and trying to get it to wait for the result of that call before continuing. I know methods on the client are asynchronous, but there must be some way to achieve this with AutoForm I think.

**Comment by jankapunkt** [comment]
You could use a "normal" form and to the validation and submission manually:

```html
{{> quickForm id="testForm" type="normal" schema=testSchema}}
```

```js
Template.myTemplate.events({
  'submit #testForm' (event, templateInstance) {
    // prevent auto submittion:
    event.preventDefault()

    // get form values
    const { insertDoc } = AutoForm.getFormValues('testForm')

    // validate form data but do not validate the pin here, 
    // just it's type (String or Number; length etc.)
    const ctx = testSchema.newContext()
    ctx.validate(insertDoc, { modifier: false }) // true if updateDoc
    const errors = context.validationErrors()

    // if we have already errors at this stage, add them to form and skip the rest!
    if (errors && errors.length > 0) {
      errors.forEach(err => AutoForm.addStickyValidationError('testForm', err.key, err.type, err.value))
      return
    }
    
    // now let's validate the PIN
    const { pin } = insertDoc
    Meteor.call('validatePinMethod', { pin }, err => {
      // if the server threw an error, add the error to the form and skip
      // see https://github.com/longshotlabs/simpl-schema/blob/main/package/lib/SimpleSchema.js#L906
      if (err) {
        return AutoForm.addStickyValidationError('testForm', 'pin', 'notAllowed', [pin])
      }
      
      // do not forget to remove the error if it passed
      else {
        AutoForm.removeStickyValidationError('testForm', 'pin')
      }
      
      // otherwise submit data to server
      Meteor.call('submitForm', insertDoc, (submissionError, res) => { ... })
    })
  }
})
```
Note: I would keep the pin validation separate from data submission in case you need to validate it anywhere else.
Would that solve your problem?

**Comment by crimsonrocks** [comment]
@jankapunkt that completely solves my problem! I honestly forgot about 'normal' forms. Thanks for taking the time to write that out.
