### ISSUE TITLE
Please add error/warning messages if no theme is installed

### ISSUE THREAD

**Issue by ebradbury** [aldeed/meteor-autoform#1731]
Now that autoform 7 decouples themes, you must manually install and activate a theme separately. But if you don't the form simply doesn't render and there are no client or server errors.

Could you please add an error/warning message if there is no theme installed or activated?

**Comment by jankapunkt** [comment]
Should be not a big issue. Care to create a PR?

**Comment by ebradbury** [comment]
Something here? https://github.com/Meteor-Community-Packages/meteor-autoform/blob/devel/autoform-api.js#L311

**Comment by jankapunkt** [comment]
Yes, that's the line. Please also update the tests, which will be a bit more work but should be not that much either.
