### ISSUE TITLE
Form doesn't submit

### ISSUE THREAD

**Issue by aramk** [aldeed/meteor-autoform#199]
I'm not sure why, but the following form doesn't submit:

```
<template name="customerItem">
{{#autoForm collection="Customers" id="customerItem" doc=updateItem type="update"}}
{{> afQuickField name='name'}}
<button type="submit" class="ui green submit button">Save</button>
{{/autoForm}}
</template>
```

```
AutoForm.addHooks('customerItem', {
  onSubmit: function (insertDoc, updateDoc, currentDoc) {
    console.log(arguments);
    return false;
  }
});
```

The input loads the correct data but clicking submit does nothing - no submission, no error, no onSubmit call. I think the reason is that no events were bound because the submit wasn't detected. If this is the case I suspect adding a `console.warn()` may be useful so the developer knows something is missing. But it could be something else entirely. I can confirm that this works:

```
{{> quickForm collection="Customers" id="customerItem" type="update" doc=updateItem}}
```

**Comment by morgunder** [comment]
thanks for that debug hook.  however it didn't work for me (AutoForm was not defined) because i was pulling in aldeed:autoform from yogiben:admin.  i had to add it directly as a top level package to resolve AutoForm.  might want to add that to the docs :)

**Comment by aramk** [comment]
Dependencies aren't exposed to the app unless you use imply() in the package.js.
