### ISSUE TITLE
Change the buttons +/- of afArrayField

### ISSUE THREAD

**Issue by camelaissani** [aldeed/meteor-autoform#207]
I would like to change a little bit the afArrayField buttons:
Add a custom label "Add element" / "Remove element" change the position to the right...

Currently, I made some changes in my css but I cannot customize the labels.
Can we imagine to add a template for these buttons (same of what we have on afDeleteButton)?

**Comment by ajamjoom** [comment]
@aldeed your link to the template isn't working! Thanks in advnace
