### ISSUE TITLE
How to pass a default value for a field in 'insert' form?

### ISSUE THREAD

**Issue by a-ruzin** [aldeed/meteor-autoform#210]
How to pass a default value for a field in 'insert' form?

My process is:
1. A User selects some value in a list on a page, then
2. The 'insert' from opens, and I want that one field to be initialized with the value the user choosed on a previous step.

Can't figure out how to pass a parameter withing URL (or any other way).
The problem is how to initialize form with the value.

Suppose I have an URL:

http://localhost:3000/activity/new/Sport
# 

router.js:

``` javascript
...
Router.map(function () {
    ...
    this.route('newActivity', {
        path: '/activity/new/:tag',
        data: function() {
            Session.set('tag', this.params.tag);
            return null;
        }
    });
    ...
```
# 

models/activity.js

``` javascript
...
Activities = new Meteor.Collection("activities", {
    schema: {
        title: {
            type: String,
            label: 'название'
        },
        ...
        tag: {
            type: String,
            label: 'тэг'
        }
    }
});
```
# 

templates/avtibity.js

``` javascript
...
Template.newActivity.helpers({
    defaultTag: function() {
        return Session.get('tag');
    }
});
...
```
# 

templates/activity.html

``` html
...
<template name="newActivity">
    <h1>Create new Activity!</h1>
    {{#autoForm collection="Activities" id="insertActivityForm" type="insert"}}
        {{> afQuickField name="title"}}
        ...
        {{> afQuickField name="tag" value="   ??????    "}} // ? {{defaultTag}}
        ho ho ho {{defaultTag}}
    {{/autoForm}}
</template>
```

**Comment by arvi** [comment]
Hi @aldeed! What if I want to pass a parameter. I tested this and it didn't work 
{{> afQuickField name="tag" value=defaultTag(myParameter)}}

Do you have any suggested workaround for that? Thanks!

**Comment by aldeed** [comment]
@arvi, when helpers need an argument, you need to use a with block

```js
{{#with defaultTag myParam}}
{{> afQuickField name="tag" value=this}}
{{/with}}
```

**Comment by pcoady** [comment]
Passing a helper value doesn't work for me:

Template.insertLocationForm.helpers({
  parentID: function() {
    return 100;
  }
});

<template name="insertLocationForm">
  <div class="row">
    {{#autoForm collection="Locations" id="insertLocationForm" type="insert"}}
      <fieldset>
        <div>
          {{> afQuickField name='parent' value={{parentID}} }} // This throws error          
        </div>
      </fieldset>
      <button type="submit" class="btn waves-effect waves-light">Insert</button>
    {{/autoForm}}
  </div>
</template>

**Comment by srinivasdamam** [comment]
@aldeed  thanks for the above solution.
