### ISSUE TITLE
Validation errors not pushed to form UI

### ISSUE THREAD

**Issue by dbmzzo** [aldeed/meteor-autoform#214]
I use Autoform and SimpleSchema for account creation with a custom `emailAvailable` validation method to protect against dupes. This works great and I get a nice `Email must be unique` message as expected. However, I have issues when using the same setup (minus a password field) to allow users to change their email address.

My first issue is that even though the `emailAvailable` method works as expected and prevents the user from changing their email address to one that is already in use, it fails silently and the errors do not appear in the form. I know that the validation errors are caught by SimpleSchema because thanks to `SimpleSchema.debug = true`, I see a `SimpleSchema invalid keys for "account" context` message containing the `name: email, type: notUnique` error being logged.

My second issue is that the server method to update the account is called despite the validation clearly failing. This results in a `Exception while invoking method 'updateAccount' MongoError: E11000 duplicate key error index: meteor.users.$emails.address_1` message. I understand that the documentation for SimpleSchema explains that this may happen since the validation is run on the client and not the server, but I'm confused as to why the same error doesn't occur when validation fails for account creation.

Thanks! Relevant code is below:

My account creation schema:

``` javascript
// create account
Schema.users= new SimpleSchema({
  email: {
    type: String,
    unique: true,
    regEx: SimpleSchema.RegEx.Email,
    // check for duplicate email address
    custom: function () {
      if (Meteor.isClient && this.isSet) {
        Meteor.call('emailAvailable', this.value, function (error, result) {
          if (!result) {
            Schema.users.namedContext('register').addInvalidKeys([{name: 'email', type: 'notUnique'}]);
          }
        });
      }
    }
  },
  password: {
    type: String
  },
  name: {
    type: String
  }
});

```

My account update schema:

``` javascript
// update account
Schema.profile = new SimpleSchema({
  email: {
    type: String,
    unique: true,
    regEx: SimpleSchema.RegEx.Email,
    // check for duplicate email address
    custom: function () {
      if (Meteor.isClient && this.isSet) {
        Meteor.call('emailAvailable', this.value, function (error, result) {
          if (!result) {
            Schema.users.namedContext('account').addInvalidKeys([{name: 'email', type: 'notUnique'}]);
          }
        });
      }
    }
  },
  name: {
    type: String
  }
});
```

My check email method:

``` javascript
emailAvailable: function(email) {
    var currentId = "";
    if (Meteor.user()) {
      var currentId = Meteor.user()._id;
    }
    var findEmail = Meteor.users.find(
      {_id:
        {
          $ne: currentId
        }
        ,emails:
        {
          $elemMatch:{
            address:email
          }
        }
      }
    );
    var findEmailCount = findEmail.count();
    if (findEmailCount == 0) {
      return true;
    }
    return false;
  }
```

My server methods:

``` javascript
Meteor.methods({
  registerAccount: function(doc) {
    check(doc, Schema.users;
    Accounts.createUser({
      email: doc.email,
      profile: {
        name: doc.name
      },
      password : doc.password
    });
  },
  updateAccount: function(doc) {
    check(doc, Schema.profile);
    Meteor.users.update(
      {_id:Meteor.user()._id},
      {$set:
        {
          "profile.name": doc.name,
          "emails": [ {address:doc.email} ]
        }
    });
  },
  emailAvailable: function(email) {
    var currentId = "";
    if (Meteor.user()) {
      var currentId = Meteor.user()._id;
    }
    var findEmail = Meteor.users.find(
      {_id:
        {
          $ne: currentId
        }
        ,emails:
        {
          $elemMatch:{
            address:email
          }
        }
      }
    );
    var findEmailCount = findEmail.count();
    if (findEmailCount == 0) {
      return true;
    }
    return false;
  }
});
```

**Comment by tomyo** [comment]
I was struggling with this until I read @aldeed line 
> AutoForm uses the form ID as the context name

I don't recall seen that in the autoForm or simpleSchema documentation btw.

Turns out I could do what @dbmzzo wanted simply by doing:
```coffescript
AutoForm.hooks
  signupForm:
    onSubmit: (data, updateDoc, currentDoc) ->
      (...)
      Accounts.createUser data, (error) =>
        if error
          @done error
    onError: (formType, error) ->
      if error.reason == "Email already exists."
        Schema.users.namedContext('signupForm').addInvalidKeys([{name: "email", type: "notUnique"}]);
```
