### ISSUE TITLE
type=Boolean field with type='hidden' can not be validated

### ISSUE THREAD

**Issue by solo999** [aldeed/meteor-autoform#216]
If I use hidden field of boolean type, update can not be validated because value="true" (or "false") does not converted to value=true (false) and trow error:
SimpleSchema invalid keys for "myOptions" context: 
message: "enabled must be a boolean"
name: "enabled"
type: "expectedBoolean"
value: "true"

Same template with not hidden boolean field works ok, so the problem must be in hidden fields converting...

**Comment by abhirakshit** [comment]
Has this been resolved in the latest release?

**Comment by abhirakshit** [comment]
I got the same error when using latest quickform. I have two booleans in the schema which are hidden and throw validation errors. 
--------------------------
captured: {
        type: Boolean,
        autoform: {
            type: "hidden",
            label: false,
        },
        defaultValue: false
    },
--------------------------

Any other hidden type like string does not give a problem. Is there some specific handling I need to do for booleans.
