### ISSUE TITLE
Reactive form

### ISSUE THREAD

**Issue by mquandalle** [aldeed/meteor-autoform#23]
I have a form with some fields. If the user isn't connected (with the build-in user management system) I want to add one more field (`pseudo`). I want this field to be added/removed reactively if the user connect/disconnect.

One way to handle this use case could be to add a `condition` key in the field definition (coffeescript):

``` coffeescript
message:
    type: String
pseudo:
    type: String
    max: 16
    condition: -> !Meteor.userId()
```
- If `condition() !== true`, then Autoform do not display the item, and do not return its value in the doc given to the callback function.
- SimpleSchema validation start to check this condition
  - if condition is true, the field is required to be in the document
  - otherwise, it act as if the field wasn't defined, as a result the field is required to not be in the document
- If `optional` is set to true, the field is optional even if condition is true

Thoughts?

**Comment by KristerV** [comment]
for future googlers: http://stackoverflow.com/questions/28685163/meteor-autoform-how-to-update-select-options-based-on-another-control
