### ISSUE TITLE
Nested Arrays in Arrays

### ISSUE THREAD

**Issue by legel** [aldeed/meteor-autoform#254]
I have a schema structure of arrays in arrays like follows:

```
schema: {
    'level1': {
      type: Array,
      optional: true
    },
    'level1.$': {
      type: Object
    },
    'level1.$.level2a': {
      type: String
    },
    'level1.$.level2b': {
      type: Array,
      optional: true
    },
    'level1.$.level2b.$': {
      type: Object
    },
    'level1.$.level2b.$.level3a': {
      type: String
    },
    'level1.$.level2b.$.level3b': {
      type: String
    }
  }
```

I would like to explicitly identify each field in the .html, similar to lines 250-260 of [meteor-autoform-example.html](https://github.com/aldeed/meteor-autoform-example/blob/master/meteor-autoform-example.html).  Following that example one might try something like:

```
<fieldset>
    {{#afEachArrayItem name='level1'}}
        {{> afQuickField name='this.current.level2a'}}
        {{#afEachArrayItem name='this.current.level2b'}}
            {{> afQuickField name='this.current.level3a'}}
            {{> afQuickField name='this.current.level3b'}}
        {{/afEachArrayItem}}
    {{/afEachArrayItem}}
</fieldset>
```

However nothing renders.  Ignoring the nested array structure, I was able to get a form that could render the arrays separately, like:

```
<fieldset>
    {{#afEachArrayItem name='level1'}}
        {{> afQuickField name='this.current.level2a'}}
    {{/afEachArrayItem}}

    {{#afEachArrayItem name='level1.$.level2b'}}
        {{> afQuickField name='this.current.level3a'}}
        {{> afQuickField name='this.current.level3b'}}
    {{/afEachArrayItem}}
</fieldset>
```

But upon submission the second array structure is not recorded in the database.

Am I missing something or is this not possible with the current architecture?

**Comment by keyscores** [comment]
@aldeed I know this was closed long ago, but is there a pattern for describing the add/remove buttons for complex nested arrays like this. When I tried this I got a mismatch and all or none of the array objects were removed incorrectly. Thanks!

**Comment by alvaraj2** [comment]
@keyscores Hey,  I experienced the same issue and was able to come to a solution, this was how I did it:

`{{#afEachArrayItem name="sales"}}
                    {{> afQuickField name=this.current.supplier}}
                    <a type="button" class="btn autoform-add-item"
                       data-autoform-field={{this.arrayFieldName}}><span class="glyphicon glyphicon-plus"></span>
                    </a>
                {{/afEachArrayItem}}`

The key is {{this.arrayFieldName}}. A button with autoform-remove-item should work the same as long as you have it within the afEachArrayItem:

`<a type="button" class="btn btn-primary autoform-remove-item"><span
                                            class="glyphicon glyphicon-minus"></span></a>`

**Comment by alvara** [comment]
@keyscores I faced the same issue and was able to solve it with this:

```javascript
{{#afEachArrayItem name="sales"}}
                    {{> afQuickField name=this.current.supplier}}
                    <a type="button" class="btn btn-primary autoform-remove-item"><span
                            class="glyphicon glyphicon-minus"></span></a>
                    <a type="button" class="btn autoform-add-item"
                       data-autoform-field={{this.arrayFieldName}}><span class="glyphicon glyphicon-plus"></span>
                    </a>
                {{/afEachArrayItem}}
```

The key is {{this.arrayFieldName}}.

**Comment by Aparus** [comment]
@aldeed , now this.current doesn't work. May be because of updates. Please help to find an solution.

**Comment by Gigacross** [comment]
May be you can try using the `afArrayField` template.

This worked for me: 

```
  {{#autoForm id="testComplexForm" schema=schema type=method meteormethod="ComplexDB.test" }}

    {{> afArrayField name='transactions'}}

  {{/autoForm}}
```

It renders correctly for the following schema:

```
const transactions = new SimpleSchema({
  transactions: {
    type: Array
  },
  'transactions.$': {
    type: Object
  },
  'transactions.$.transactionNumber': {
    type: String
  },
  'transactions.$.test' :{
    type: String
  },
})
```
