### ISSUE TITLE
Feature Request: Tooltips

### ISSUE THREAD

**Issue by picsoung** [aldeed/meteor-autoform#257]
Hi,

One of the feature that I would love to see is the ability to add "tooltips" to fields, a way to explain people what to put in it.

I don't think it's possible today. Right ?

I started to modify the template so I can render a _?_ sign
![example](https://www.evernote.com/shard/s37/sh/95a1d5e0-c9e6-4d94-898f-9edb1a8765b6/3009bbdb4e689ffcb47337e00547d198/deep/0/APIs.io.png)

But my question now is "where the tooltip text should be stored ?", on the simpleschema itself ? or like messages in another array.

If you can point me to the right directions I will be able to submit a pull request soon :)
Thanks

**Comment by rwatts3** [comment]
Has anyone got anywhere with this I'm looking to do this and also need to be help for going in the right direction.

**Comment by Pantela777** [comment]
I can't understand how I can add **tooltip** for **afQuickField**, please help...
![image](https://cloud.githubusercontent.com/assets/7046596/25520759/2a651632-2c0e-11e7-95af-4a9b93b36770.png)
