### ISSUE TITLE
multiple forms on one page

### ISSUE THREAD

**Issue by dohomi** [aldeed/meteor-autoform#298]
Hi Eric,

I created a small blog with comments function. On the comments section each comment has one autoform element. As I use the `id="formId"` for each form element I have now the same `id`repeatedly, even the handling is not working properly. Any idea how to solve this?
Thanks, Dominic

**Comment by maxnowack** [comment]
+1 for regular expression support on ````addHooks````

**Comment by aldeed** [comment]
As commented above:

> this.formId is now available in hooks. You can define a global hook and do your own regex match or string parsing on that.

Does that meet your needs?

**Comment by gabriel-dehan** [comment]
+1 for regular expression too.

I find `thid.formId` a bit clunky and less readable. It feels like adding a hook that will run on ALL forms and then filter inside the hook feels un-natural to me and a bit too 'heavy' maybe. 

Just my opinion though.

**Comment by cedricmay** [comment]
+1 for regular expression support on `addHooks`

**Comment by ebradbury** [comment]
FYI, #1397
