### ISSUE TITLE
IE8 Object expected

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-autoform#306]
IE8 is throwing "Object expected" at this line:

[autoform-events.js#L272: getFormValues(...);](https://github.com/aldeed/meteor-autoform/blob/c6e49dc0563a827eede2861745d7e42ee094f044/autoform-events.js#L272)

```javascript
// Gather all form values
var formDocs = getFormValues(template, formId, ss);
```

**Comment by aldeed** [comment]
No longer actively trying to support IE8, but I'll accept a pull request if someone figures out a fix.
