### ISSUE TITLE
AutoForm should handle reactive changes to any of its attributes properly

### ISSUE THREAD

**Issue by yourcelf** [aldeed/meteor-autoform#353]
I'm using autoforms to create a complex form using a wizard pattern -- the same form template is rendered serially with different fields, form ID's and data.  However, due to meteor/meteor#2001 / meteor/meteor#2010, the ``Template.autoForm.created`` function only fires once, and thus subsequent steps in the wizard all fail with ``getFormValues: There is currently no autoForm template rendered for the form with id``.

AutoForm needs some kind of workaround (like the ones mentioned in the issues above) to populate ``templatesById`` in the event that a reactive data change causes a different form to be rendered on the same page.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
