### ISSUE TITLE
template.data.doc is null on onSuccess in AutoForm.hooks

### ISSUE THREAD

**Issue by fungilation** [aldeed/meteor-autoform#355]
Sample code:

``` coffeescript
AutoForm.hooks
  afClubForm:
    onSuccess: (operation, result, template) ->
      Router.go('Club', {_clubName: template.data.doc.name}) if _.contains ['insert', 'update'], operation
```

Prior to either Meteor 0.9.1 or 0.9.2, template.data.doc.name would be the name field of the doc that was successfully inserted. Currently at Meteor 0.9.2.2, autoform@2.0.2, template.data.doc is null.

**Comment by buduguru** [comment]
both `result` and `this.docId` work in `onSuccess` returning a newly created document Id, so, both following examples work: 

```javascript
AutoForm.hooks({
    insertDocumentForm: {
        onSuccess: function (operation,result) {
            Router.go('documentPage', {_id: result});
        }
    }
});  

AutoForm.hooks({
    insertDocumentForm: {
        onSuccess: function () {
            Router.go('documentPage', {_id: this.docId});
        }
    }
}); 
``` 

I think this should be mentioned in readme somehow

**Comment by aldeed** [comment]
@buduguru hook contexts are documented better in the next autoform release.
