### ISSUE TITLE
template.find("form").submit() causes page reload

### ISSUE THREAD

**Issue by jakobdamjensen** [aldeed/meteor-autoform#356]
Is it not possible to submit the form programatically? I'm using type="method" but it seems like the only way to submit is to have a submit button inside the form.

Is that correct? Is there a way to work around this? I'm doing a wizard kinda UI and I don't want the buttons to be a part of the form it self.

**Comment by JohnnyRuvac** [comment]
Same thing happened to me, quite difficult to find out where was the problem.

**Comment by comerc** [comment]
+1
METEOR@1.2.1
aldeed:autoform@5.7.1
