### ISSUE TITLE
Lookup Field Type with autocomplete

### ISSUE THREAD

**Issue by panigrah** [aldeed/meteor-autoform#358]
Add ability to look up any of the fields from a collection and save the document id of the related collection in the field. 

Ideally i would like to be able to add this relationship to the schema and let auto-form automatically pick it up and display in the form.

e.g. The schema 

```
Person = new Collection(...);
Book = new Collection(...);
BookSchema = new SimpleSchema({
                             name: {type: String}, 
                             author: {type:RelatedField, collection:"Person", display:["name","about"] }
                        });

PersonSchema =  new SimpleSchema({
    name: {type: string}, about: {type: string}});
```
1. The displayed auto-form field should then either autocomplete using the Person collection and searching for the name and about fields. Or display a search icon to allow searching and selecting a person from a popup window.
2. The author field could then store the following two fields in the Books Collection. 
            author._id and author.name 

I started down the path of implementing this and using mizzao:autocomplete. I have it most of the way done - except for being able to save the lookup data into the collection. To get started I updated SimpleSchema to add in the new attributes and duplicated some of the code relating to afObjectField. Added the mizzao autocomplete to the template.

Is this the best way and/or are there better alternatives to this approach?

**Comment by Sojourneer** [comment]
+1
I had the same requirement. I used mizzao:autocomplete to cross populate an autoform field bound to the _id. It was pretty hacky getting the update scenario (i.e. prepopulating) to work.

**Comment by h4de5** [comment]
@Sojourneer i think i'm trying the same thing. i use https://atmospherejs.com/mpowaga/autoform-autocomplete to combine the autocomplete settings within a SimpleSchema and Autoforms. so far i got the autocomplete to search for a title and save the corresponding _id to the field. But it always shows the _id in field. Is there a possibility to save the _id, but show a title field instead - like in an autocomplete dropdown?
