### ISSUE TITLE
Strange case of submit disabling button but not re-enabling it

### ISSUE THREAD

**Issue by sebsolere** [aldeed/meteor-autoform#363]
When I submit a form with errors, the submit button is disabled and stays disabled. I understand that the disabling during submit is normal but I don't understand why it stays disabled even when the error is corrected.
When I add debug, the button is never disabled.
Any idea?
Thanks.

**Comment by BradRyan** [comment]
I'm having an issue related to this.  I have a method in the before hook that is causing issues.  When the Meteor.call returns error I am trying to cancel the form submission.  It seems no matter what I return, the endSubmit function doesn't run.  I'm trying to run a captcha verification function before inserting the form doc and cancel the form if the reCaptcha response is an error.

If I remove my code and simply return false in the before insert function, the submission stops just fine.  When I try returning false after my meteor call the submit button remains disabled.  Any ideas?  Is there something else I should be returning?  My code is below:

```javascript
AutoForm.hooks({
	GroupRequestBasic: {
		before: {
			insert: function(doc, template) {
				if (!Meteor.userId()) {
					var recaptchaResponse = grecaptcha.getResponse();
					Meteor.call('verifyCaptcha', recaptchaResponse, function(error, result) {
			            if (error) {
			                console.log('There was an error: ' + error.reason);
			                console.log('ending submit');
			                return false;
			            } else {
			                console.log('Success!');
							return doc;
			            }
			        });
				} else {
					doc.userId = Meteor.userId();
			        console.log("returning doc, signed in user");
					return doc;
				}
			}
		},
		after: {
			insert: function(error, result, template){
				if (error) {
		          console.log("Insert Error:", error);
		        } else {
		          console.log("Insert Result:", result);
		        }
		    }
		}
	}
});
```

**Comment by aldeed** [comment]
@BradRyan, when doing something asynchronous, you have to do `var self = this` at the top of the hook function, and then do `self.result(false)` or `self.result(doc)` within your callback.

**Comment by BradRyan** [comment]
Ah!  Excellent.  Thanks for getting back to me so quick!  Fixed!

**Comment by Rebolon** [comment]
I have the same king of errors : 
When submiting form with error, then the submit button is disabled
If i fix the field that provide the error, then the error message disappear, but the submit button is not enabled.

type of the form is type="method-update"

here are the hooks : 
  "UserProfileEdit": {
    "endSubmit": function(formId, tpl) {
      if (!Meteor.status().connected) {
        Bert.alert('Pas de réseau, sauvegarde reportée ultérieurement', 'warning', 'growl-top-right');
      }

      $(tpl.find('[id*="' + formId + '"]')).find('input').prop('disabled', false);
    },
    "onSuccess": function() {
      Bert.alert('Sauvegarde réussie', 'info', 'growl-top-right');
      FlowRouter.go('/home');
    },
    "onError": function() {
      Bert.alert("Erreur d'édition du profile", 'danger', 'growl-top-right');
    }
  },

**Comment by tomtom87** [comment]
I have the same problem, when I submit any of my autoforms and there is a validation error the submit button does not re-enable

**Comment by tomtom87** [comment]
@aldeed any ideas on this, I'm currently getting this problem and really need to find a fix...

**Comment by tscizzle** [comment]
Also having this issue of no re-enabling from standard validation error.

(Not sure if commenting that is helpful, but maybe it's helpful to know that more people have the same issue.)

**Comment by nelson-uruworks** [comment]
Hi guys, I was having the same issue, and in my case it started happening when I wanted to use my own hook for `endSubmit`.

Checking at the source I saw they just make the button enabled when the default hook is called, but it's up to us to handle the UI if we use a custom hook.

If you are in the same case as me, then adding this code inside your custom hook should make it work again.

```
var submitButton = Template.instance().find("button[type=submit]") || Template.instance().find("input[type=submit]");
        if (submitButton) {
            submitButton.disabled = false;
        }
```

Also, let me know if there is a better/safer option to obtain the submit button.
