### ISSUE TITLE
Implement workaround for update form reset issue

### ISSUE THREAD

**Issue by emmanuelbuah** [aldeed/meteor-autoform#370]
Tried using this.restForm() with no luck. I stepped through the code and looks like ArrayTracker is used to track the fields etc but for some reason no fields are initialized with the ArrayTracker. There follow code 

``` javascript
ArrayTracker.prototype.resetForm = function atResetForm(formId) {
    var self = this;
    _.each(self.info[formId], function (info, field) {
        self.resetField(formId, field);
    });
};
```

self.info[formId] is always undefined. I'm I missing something here?

**Comment by emmanuelbuah** [comment]
@aldeed Is this issue fixed in the current release

**Comment by aldeed** [comment]
It should be.
