### ISSUE TITLE
selected attribute of option element not updating UI

### ISSUE THREAD

**Issue by mjgallag** [aldeed/meteor-autoform#38]
When navigating between various updates/submits of the same Autoform the select element is not displaying the correct selected option. The HTML is correct, the option that should be displayed has its selected attribute set, but the UI doesn't reflect this. If you refresh the page, it works as expected, so it seems to be a problem with dynamic rendering. Interestingly, if I add the selected attribute to the option dynamically, via a browser debug console, it updates the UI as expected. I haven't found a browser where it works without a refresh, I've tested Chrome, Safari Desktop/Mobile & Firefox. I've googled around and it seems it may have something to do with the way Meteor dynamically injects HTML into the DOM. The fact that it works via the debug console leads be to believe maybe there is a way to dynamically inject the selected attribute that works, but to be honest, I have no idea what is going on here...

**Comment by kjrhody** [comment]
Im having this issue - the workaround link doesn't seem to be working and I don't have enough experience to extrapolate an answer from this thread. What was the answer, is there a code example somewhere?  I have the following field in my template, and a change to the radio button here should trigger a change to a colored box on the UI for a photo in a list of photographs. How it is currently working:

 - User clicks button to change status for one photo.
 - User goes to next photo and clicks button, no change happens OR user refreshses page and clicks button and status changes.
 - User clicks a different, second button (without refreshing page), status changes.

Template:
```

{{#autoForm id="editPhotoForm" collection="Photos" doc=doc type="update" autosave=true class="form-horizontal"}}
<table>
  <tbody>                            
    <tr>
      <th><label class="control-label">Photo Status:</label></th>
         <td>{{> afFieldInput name="graphicStatus" options="allowed" noselect=true}}</td>
   </tr>
  </tbody>
</table>
{{/autoForm}}
```
