### ISSUE TITLE
text doubles with contenteditable

### ISSUE THREAD

**Issue by benjamin79** [aldeed/meteor-autoform#383]
Hi,

when using   {{> afFieldInput type="contenteditable"  name="editor" class="form-control" }} the content duplicates on submit. I know there is a bug with meteor / blaze and a possible solution:
https://github.com/Swavek/contenteditable but i don´t know how to connect it with autoform. Please help.
thanks

**Comment by comerc** [comment]
"reactive: false" is works as workaround, thanks.

**Comment by comerc** [comment]
"reactive: false" is works, thanks.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
