### ISSUE TITLE
quickForm: set the focus back on the first field after submit?

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-autoform#394]
Consider a simple (name, age) collection, and the insertion quickform. The user types the name, tabs to the age, then presses Enter. autoform will "submit" and insert the record, then the focus will remain on "age".

Would it be better UX to return focus to the first field, or keep it in the last field that had focus?

**Comment by manosinistra** [comment]
I had to use:

```javascript
AutoForm.addHooks(['myForm'], {                                           |~
  onSuccess: function (formType, result) {                                          |~
    $('input.form-control[data-schema-key]').first().focus();                       |~
  }                                                                                 |~
});
```
