### ISSUE TITLE
form-horizontal?

### ISSUE THREAD

**Issue by aadamsx** [aldeed/meteor-autoform#399]
Is there a way to automatically set the generated form to form-horizontal?

Thanks

**Comment by CTimmerman** [comment]
On http://autoform.meteorapp.com/quickform using 
```
{
   firstName: {
      type: String
   },
   lastName: {
      type: String
   },
   scenes: {
      type: Array,
      optional: true
   },
   "scenes.$": {
      type: Object,
      optional: true
   },
   "scenes.$.start": {
      type: String
   },
   "scenes.$.end": {
      type: String
   }
}
```
I still need `$('.form-group label').addClass('col-sm-3'); $('.form-group input').addClass('col-sm-9');` to fix the layout in the array element forms.

**Comment by sgelbart** [comment]
@CTimmerman Per Aldeed's example, you can actually add these classes within quickform via label-class & input-col-class
`{{> quickForm id="demo" schema=schemaFromJSON type="method" meteormethod="demoSubmission" template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}`
