### ISSUE TITLE
No Cancel button for Forms?

### ISSUE THREAD

**Issue by aadamsx** [aldeed/meteor-autoform#401]
It seems with the quickForm template you get no Cancel (only Submit) button by default?

```
{{> quickForm collection="ClientAccounts" id="CreateClientAccountForm" type="insert"}}
```

Is there a way to add this as an option?

**Comment by prakas25** [comment]
can change the default submit button's(of quickform) position(which is extreme left)?

**Comment by luixal** [comment]
Good be great to have an ```allowReset = true``` and a ```resetButtonContent='Clear'```.


Just saying... :)

**Comment by Pushplaybang** [comment]
@luixal auto form and quick form particularly make simple forms so easy, would be a really great option
