### ISSUE TITLE
form-groups missing required class

### ISSUE THREAD

**Issue by kev1597770** [aldeed/meteor-autoform#413]
Below is an example of how AutoForm renders a required form-group (from http://autoform.meteor.com):
```
<div class="form-group">
    <label class="control-label">First name</label>
    <input type="text" name="firstName" required="" data-schema-key="firstName" class="form-control">    
</div>
```

Based on threads such as http://stackoverflow.com/questions/23141854/adding-asterisk-to-required-fields-in-bootstrap-3 it appears as though a required class is also supposed to be added to the form-group class list.  An example appears below:

```
<div class="form-group required">
    <label class="control-label">First name</label>
    <input type="text" name="firstName" required="" data-schema-key="firstName" class="form-control">    
</div>
```

Without this additional class it is difficult / impossible to style a label field based on whether it accompanies a required input field solely through CSS.

Can you please add this required class to the form-group class list or let me know how I can style a field's label based on whether the field is required.

Thank you.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
