### ISSUE TITLE
Date as type="text" with time

### ISSUE THREAD

**Issue by medihack** [aldeed/meteor-autoform#414]
In my Schema I defined a data field and in the autoform use it as `type="text"` (for a Javascript datetime picker to work). Unfortunately I only get the date component this way and not the time component (type="datetime" is not an option cause of the Javascript library). Wouldn't it be more useful to present the Date type like the output of `toISOString` function and let the user decide what information he needs?

Example:

Field in Schema
```
date: {
  type: Date,
  defaultValue: new Date()
},
```

Field in AutoForm
```
{{> afQuickField name="date" type="text"}}
```

Outputs `2014-10-25` and what I have in mind is `2014-10-25T00:00:00.000Z`.

**Comment by aldeed** [comment]
This should be handled by creating a custom input type copied from the built-in "text" type but with a different conversion function. Closing.
