### ISSUE TITLE
radio-inline option

### ISSUE THREAD

**Issue by aadamsx** [aldeed/meteor-autoform#426]
I'd like the option for the radio buttons to be inline.  We can place a "radio-inline" class on the div above the label to accomplish this like so:

```
<div class="form-group">
    <label class="col-lg-2 control-label">Gender:</label>
    <div class="col-lg-10">
    <div class="af-radio-group" data-schema-key="Gender">
      <div class="radio-inline">
        <label>
          <input type="radio" value="Male" name="Gender" required="">
          Male
        </label>
      </div>
      <div class="radio-inline">
        <label>
          <input type="radio" value="Female" name="Gender" required="">
          Female
        </label>
      </div>
  </div>   
      <span class="help-block"></span>
    </div>
  </div>
```

It would look like this (I'll have to find out why, when adding radio-inline, the text gets bolded):
![screen shot 2014-11-03 at 12 24 38 pm](https://cloud.githubusercontent.com/assets/5341158/4887683/c102a738-6386-11e4-84fc-0a296754b192.png)

Instead of the default that looks like this:
![screen shot 2014-11-03 at 12 25 32 pm](https://cloud.githubusercontent.com/assets/5341158/4887690/d6c9cad8-6386-11e4-8dca-0f15ef89d126.png)

in the bootstrap3.html file in Autoform I see the reference only to "radio" for that div and none in the repository for radio-inline.

```
<template name="afRadio_bootstrap3">
  <div class="radio">
    <label>
      <input type="radio" value="{{this.value}}" {{atts}} />
      {{afFieldLabelText name=this.name}}
    </label>
  </div>
</template>

<template name="afRadioGroup_bootstrap3">
  <div class="af-radio-group" {{dsk}}>
    {{#each this.items}}
      <div class="radio">
        <label>
          <input type="radio" value="{{this.value}}" {{atts}} />
          {{this.label}}
        </label>
      </div>
    {{/each}}
  </div>
</template>
```

**Comment by nspangler** [comment]
@aldeed , @aadamsx  is this still valid in 5.0.2. I can't get it to work.
` shape: {
        type: String,
        allowedValues: ['Rectangular', 'Cylindrical', 'Conical', 'Spherical', 'Other'],
        label: "Shape",
        optional: true,
        autoform: {
            options: [
                {label: "Rectangular", value: "Rectangular"},
                {label: "Cylindrical", value: "Cylindrical"},
                {label: "Conical", value: "Conical"},
                {label: "Spherical", value: "Spherical"},
                {label: "Other", value: "Other"}
            ]
        }
    },`

`{{> afQuickField name="shape" options="allowed" noselect=true template="bootstrap3-horizontal" label-class="col-md-4" input-col-class="col-md-8"}}`

**Comment by aldeed** [comment]
@nspangler, you need `type="select-radio-inline"` and you don't need `noselect=true` (though it probably has no effect).

**Comment by zqalyc** [comment]
@aldeed hope you update it on the api
