### ISSUE TITLE
Conditional validation

### ISSUE THREAD

**Issue by aadamsx** [aldeed/meteor-autoform#431]
I'm looking to validate a based on the state of other controls on the page, like so:

![screen shot 2014-11-05 at 10 14 11 pm](https://cloud.githubusercontent.com/assets/5341158/4930831/8c537f58-656b-11e4-80a3-140beada5bcb.png)

In this case, if Does Not Apply is checked, then I don't want to validate the Middle Name, but if Does Not Apply is not checked, then Middle Name becomes mandatory.

From the looks of it, the schema is on or off (optional or not).  If this is true, then I'll need to make both optional, and in the onSubmit hook, heck for the above scenarios and somehow change the validation on the controls?  What do you recommend?

**Comment by alejandrosofter** [comment]
ohh genius!!
