### ISSUE TITLE
Add API function for getting containing template instance

### ISSUE THREAD

**Issue by wI2L** [aldeed/meteor-autoform#433]
Helo @aldeed 

Would it be possible to passe the template for the `onSubmit` hook?
Something like that:
```
    onSubmit: function(insertDoc, updateDoc, currentDoc, template) {},
````

William

**Comment by elie222** [comment]
Same question here. Would like to access a reactive stored in the template

**Comment by aldeed** [comment]
I think the best solution here is to add `aldeed:template-extension` pkg and use the new [this.template.get(myProp)](https://github.com/aldeed/meteor-template-extension#templategetfieldname). Let me know if that works for you.

**Comment by RobertLowe** [comment]
@aldeed my natural thought was that the callbacks would provide you the parent template context; perhaps there should be: `this.template` (autoform) and `this.parentTemplate`(parent) and the `template` parameter can be removed from the hooks function signatures?

**Comment by aldeed** [comment]
I'm not sure it's worth doing since you can get the template and any parent templates through blaze/templating pkg APIs now.

**Comment by dkmooers** [comment]
@aldeed So how do you access the parent template?

I have a ReactiveVar attached to my Template instance, which shows/hides an "add/insert" form:

    Template.oneTimeTasks.onCreated(function() {
	    this.shouldDisplayAddForm = new ReactiveVar(false);
    });

And I need to be able to manipulate that ReactiveVar from an "onSuccess" AutoForm hook, to close/destroy the add/insert form template:

    AutoForm.hooks({
	    'add-one-time-task-form': {
		    onSuccess: function(formType, error) {
			    ????.shouldDisplayAddForm.set(false);
			    displayNotice('success', 'Task added!');
		    }
	    },
    });

**Comment by dkmooers** [comment]
Here's the template code:

    template(name="oneTimeTasks")
	    h1 One-Time Tasks
	    button.btn.btn-primary#add-one-time-task-button.dropdown-form-button
		    i.fa.fa-plus
		    | Add One-Time Task
	    if shouldDisplayAddForm
		    +oneTimeTaskAdd

    template(name="oneTimeTaskAdd")
	    .dropdown-form
		    +autoForm id="add-one-time-task-form" class="one-time-task-form" schema="OneTimeTaskSchema" type="method" meteormethod="addOneTimeTask" doc=null resetOnSuccess=true
			    ...

**Comment by pouyant** [comment]
+1

**Comment by bmanturner** [comment]
+1

**Comment by pbibalan** [comment]
Althought onSuccess doesn't have the template argument I confirmed that you can access the template using this.template (instead of Template.instance()).
```
AutoForm.hooks({
  sampleForm: {
    onSuccess: function (formType, result) {
      this.template.parent().parent().yourReactiveVari(undefined);
    }
  }
});

**Comment by dkmooers** [comment]
@pbibalan Thanks!! That works perfectly.
