### ISSUE TITLE
Make clean options work with all form types

### ISSUE THREAD

**Issue by greyarch** [aldeed/meteor-autoform#434]
I have an AutoForm of type method. The meteor method simply upserts the document that is sent by the AutoForm. The problem is, that when I want to empty a field and update, the empty attribute is not sent to the server and is not updated in the db.

'removeEmptyStrings=false' only works on insert and update type of AutoForm

Replacing the entire document in the db does not work as well because of validation error asking me if I have forgotten the $set.
Please help!

**Comment by aldeed** [comment]
I believe this we fixed through other changes I made in the devel branch.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
