### ISSUE TITLE
{{> afFieldLabel name='name'}} deprecated in 4.0, replacement?

### ISSUE THREAD

**Issue by fungilation** [aldeed/meteor-autoform#436]
{{> afFieldLabel name='name'}} is no longer available, when it would have generated html like this using a Collection2 field label:

```
<label class="control-label" for="name">URL Name</label>
```

Is there an alternative for the afFieldLabel helper in 4.0?

**Comment by dalgard** [comment]
Would be awesome if this were written in the documentation somewhere :+1:
