### ISSUE TITLE
Need help formatting (radio) options

### ISSUE THREAD

**Issue by Maxhodges** [aldeed/meteor-autoform#449]
I'm trying to generate options which look like this:

```
     <div class="radio">
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios1" class="px">
                  <span class="lbl"><strong>amazon.co.jp</strong></span><br>
                  <span class="lbl">Ordered qty 1 on Oct 13, 2014 (4 days ago)</span><br>
                </label>
              </div>
```

but it seems like i don't have much control over html formatting. Is my only option to create my own template? I've looked at the example templates, but I can hardly understand it. In the bootstrap3-horizontal template, I don't see any reference to 'option' or 'radio'. So it's not much help in figuring out how to create a custom template for options.

Any tips or examples much appreciated!

**EDIT**
We are generating the options with this in the template:

```
     {{> afQuickField name='purchaseItemId' options=purchaseSelectOptions noselect=true template="bootstrap3-horizontal" label-class="col-sm-2" input-col-class="col-sm-10" class="form-control"}}
```

and a function in the js

```
    purchaseSelectOptions: function() {
    return _.chain(this.potentialPurchaseItems)
      .filter(function(potentialPurchaseItem) {
        return potentialPurchaseItem.totalQuantityReceived < potentialPurchaseItem.quantityPurchased;
      })
      .map(function(purchaseItem) {
        var vendor = Vendors.findOne({_id: purchaseItem.vendorId});
        var vendorName = vendor ? vendor.vendorName : 'loading...';
        return {
          label: vendorName + ' - waiting to receive ' + (purchaseItem.quantityPurchased - purchaseItem.totalQuantityReceived) + '. (Qty ' + purchaseItem.quantityPurchased + ' ordered ' + moment(purchaseItem.purchasedAt).format("MMM-DD-YYYY") +')',
          value: purchaseItem._id,
        };
      })
      .value();
    },
```

So it's not merely a matter of styling the elements individually. I'm trying to figure out how to modify the template or something so I have more control over the structure and classes.

**Comment by dengjianan** [comment]
I have defined that override theme templatee:
<template name="afRadio_metronicTemplate">
  <div class="md-radio">
        <input type="radio" name="lengthUnit" id="foot">
        <label for="foot">
        <span></span>
        <span class="check"></span>
        <span class="box"></span>
        foot</label>
   </div>
</template>
and
Template.afRadio_metronicTemplate.helpers({
  atts: function selectedAttsAdjust() {
    var atts = _.clone(this.atts);
    if (this.selected) {
      atts.checked = "";
    }
    return atts;
  }
});
finally:
<div class="col-md-4">
          {{> afQuickField name="base.property" afFieldInput-template="metronicTemplate"}}
          </div>
the result is fail ,why?
