### ISSUE TITLE
"Object field" demo with Bootstrap inline doubles the label & placeholder

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-autoform#454]
In the [quickform demo](http://autoform.meteor.com/quickform), select **Object field** and **Bootstrap inline**.

![image](https://cloud.githubusercontent.com/assets/33569/5042706/9607f112-6b8f-11e4-94a0-f31dbd235b0a.png)

Same issue with Array of object fields, and Complex nested array fields.

**Comment by aldeed** [comment]
@voidale, it should be possible to do whatever you want, but it might require a custom template. I would need to see an example of what you're trying.

**Comment by voidale** [comment]
I actually digged more into it, It's definitely possible with a new template! Awesome learning a new package from you (Weird the best packages are yours :+1: )
