### ISSUE TITLE
Polymer paper / material design theme

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-autoform#463]
Anyone working on a Polymer paper / Google Material design [custom theme template](https://github.com/aldeed/meteor-autoform#creating-a-custom-template) for autoform? It looks quite cool:

https://www.polymer-project.org/components/paper-elements/demo.html

**Comment by chompomonim** [comment]
Yeah, autoform + polymer would be killer feature for me. Do you have plan to do in natively as a part of autoform or just waiting until someone from community will do that?

**Comment by aldeed** [comment]
A polymer pkg would be an add-on community pkg. I had been investigating more of a low-level support for web components in general (unify autoform input type definitions with web component spec), but for now it seems more complex than useful.

**Comment by aldeed** [comment]
Closing. See #438

**Comment by dandv** [comment]
Not *quite* Polymer Paper, but Bootswatch has released a [Paper theme](https://atmospherejs.com/bootswatch/paper).
