### ISSUE TITLE
unwanted correlation between forms

### ISSUE THREAD

**Issue by ChenRoth** [aldeed/meteor-autoform#469]
hi,

I've been having trouble with using 2 separate autoForms on one page
Whenever one form is updated (autosaved), the input in the other form is being reset

I don't believe the specific content of the forms matters, so here's a minimal version of the template:

```
 {{#autoForm id="profilePictureForm" type='update' schema="Schemas.basic" }}    
    {{> afQuickField name="photo"}}
 {{/autoForm}}

 {{#autoForm schema="Schemas.basic" collection='Users' doc=user autosave=true id="userProfileForm" trimStrings=true type="update" class="form" }}                        
            {{> afFieldInput name="profile.firstName" class="text-capitalize" placeholder="schemaLabel"}}                
{{/autoForm}}
```

as you can see, there are 2 autoForms here, each with its own unique Id
also, form #1 has no doc attached to it, so there's no possibility of it being reactively reset due to changes in form #2's doc

has anyone had a similar problem?

**Comment by ChenRoth** [comment]
hey @aldeed , found this related open issue #566 

i think it's the same issue

**Comment by aldeed** [comment]
I agree it's probably the same issue. It's fixed on devel branch.
