### ISSUE TITLE
Insert after callback doesn't trigger

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#477]
For some reason the `before` callback triggers, but the insert operation fails silently (even with `AutoForm.debug()`) before the `after` callback. `onSuccess` and `onError` also do not trigger. 

Any suggestion?

Relevant files:
- [post submit form](https://github.com/TelescopeJS/Telescope/blob/quickform/client/views/posts/post_submit.html)
- [post submit js](https://github.com/TelescopeJS/Telescope/blob/quickform/client/views/posts/post_submit.js)
- [post schema](https://github.com/TelescopeJS/Telescope/blob/quickform/collections/posts.js)
- [custom template](https://github.com/TelescopeJS/Telescope/tree/quickform/client/views/forms)
- [custom datetime type](https://github.com/TelescopeJS/Telescope/tree/quickform/packages/telescope-datetimepicker)

(as far as I can tell the problem does not seem related to either the custom template or custom datetime picker)

**Comment by Benco1** [comment]
I'm also having issues with the 'insert after' callback. It seems to not be recognizing my use of `this.currentDoc`. Am I doing it wrong? I have virtually the same hook setup for 'update after' and it works fine. Was the original issue with 'insert after' callback ever resolved / discovered?

**Comment by Benco1** [comment]
Ah, ok. I think I needed to be using `this.insertDoc` because the "current" refers to the pre-existing populated form fields, NOT the newly inserted or updated doc / form values, correct?

**Comment by Benco1** [comment]
Yay, got it!
