### ISSUE TITLE
Use collection query for allowedValues

### ISSUE THREAD

**Issue by rjsandman** [aldeed/meteor-autoform#48]
Is it possible to take the values from one collection and use them as options in an input form for another collection?  For example: if I had a collection named Singers and in my schema I had a "genre" category, if I wanted to create a genre collection and then add different genres to this collection so it would show up as one of the options under the singer collection genre options, is this possible?

Thanks

**Comment by myknbani** [comment]
Is there any way to do this now?  I think this is going to be a common use case.

**Comment by s7dhansh** [comment]
Yes.

At least in meteor-starter package, I can. I believe though that it's supported by the meteor-autoform package directly, and @yogiben did not do anything extra. @aldeed may let us know for sure.

Let's say you want data from a collection called `Info`.

```
type: String,
autoform: {
  options: function() {
    return Info.find().fetch();
  }
}
```

**Comment by abstractmatter** [comment]
More like this to bring the label/value object:

		autoform: {
			options: function() {
				var opts = Entities.find().map(function(entity) {
					return {
						label: entity.name,
						value: entity._id
					};
				});
				return opts;
  			}
  		}
