### ISSUE TITLE
How to define data- attributes for select options?

### ISSUE THREAD

**Issue by atoi** [aldeed/meteor-autoform#484]
Sometimes there is a need in mixing different entities in a single combobox.
For example an entity has parentId and parentType fields.
My use scenario is:
1. User selects 'parentId' value in combobox
2. Hidden field 'parentType' is auto-populated depending on data-type attribute of the selected option

Looking at the code I did not see a way to define any additional attributes to a single select option.
Did I miss something?

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
