### ISSUE TITLE
When doing partial update of an object, autoform wrongly overwrites inner objects

### ISSUE THREAD

**Issue by neoromantic** [aldeed/meteor-autoform#487]
http://autoformbug.meteor.com

Steps to recreate:

Fill out first field with anything, submit. Now you have document like {innerObj: {field1: 12345}}

Do not fill second field, submit second form. Autoform is creating modifier like {$unset: "innerObj"}, so, here's a problem right there.

Thanks!

**Comment by Kostanos** [comment]
I know it is closed, but type="hidden" not the best solution in my case, I have many fields, included i18n translations.
Any updates on this issue?

So far, I did workaround for removing $unset of translations, if someone interested:

    AutoForm.hooks({
      myForm: {
        before: {
          'method-update': function(doc){
            // For some reason all translations are unset here for fields that were not in form
            if (doc['$unset']){
              doc['$unset'] = _.pick(doc['$unset'], function(item, key){
                return key.indexOf('i18n.') !== 0;
              });
            };
            return doc;
          },
        }
      }
    });
