### ISSUE TITLE
Zurb Foundation Templates

### ISSUE THREAD

**Issue by scottmcpherson** [aldeed/meteor-autoform#493]
I personally prefer working with Zurb Foundation and was wondering if you might accept a PR with Foundation templates?

**Comment by MichaelFBA** [comment]
1+ I would like to help out with a foundation package

**Comment by dstollie** [comment]
@scott-mcpherson and @micahalcorn have you already started working on this template? Im using foundation and to use this package I need a decent support for foundation.

**Comment by logankoester** [comment]
I use `meteor-autoform` with Zurb Foundation also - excited to see interest in this!
