### ISSUE TITLE
Live cross validating fields on credit card form

### ISSUE THREAD

**Issue by fusepilot** [aldeed/meteor-autoform#498]
I'm trying to validate a credit card date to make sure it hasnt expired.

I have two fields ````cardMonth```` and ````cardYear````. I would like for both fields to validate when either one is modified.

This is my current schema and shared date validation method. 

````
Cart.isCardDateValid = (month, year) ->
  currentDate = new Date()
  currentMonth = currentDate.getMonth()
  currentYear = currentDate.getFullYear()
  currentYearShort = parseInt(currentYear.toString().substr(2,2))

  if year > currentYearShort
    return true
  else if year == currentYearShort and month >= currentMonth 
    return true

Cart.CheckoutSchema = new SimpleSchema
  cardMonth:
    type: Number
    custom: ->
      unless Cart.isCardDateValid @value, @field("cardYear").value
        return "cardExpired"
      unless @value >= 1 && @value <= 12
        return "cardInvalidMonth"

  cardYear:
    type: Number
    custom: ->
      unless Cart.isCardDateValid @field("cardMonth").value, @value
        return "cardExpired"
      unless @value.toString().length == 2
        return "cardInvalidYear"
````

And in my template.

````
+quickForm schema="Cart.CheckoutSchema" validation="keyup"
````

This works when submitting. But doesn't work as I enter values. I have to click in and then click off the other field for it to validate.

How can this be done cleanly?

**Comment by aldeed** [comment]
The issue here is that on keyup and blur, we revalidate only the current field for performance reasons. A workaround for your situation would be to define your own keyup and blur handlers that call `AutoForm.validateForm`. For now I will close this, but if enough people need this, maybe some way to force additional fields to be validated on keyup could be added.

**Comment by egoldblum** [comment]
+1 on this feature request

I too have a pair of fields that validate against each other.  Would expect that if I reference a `field`/`siblingField` in a `custom` validator function, the validator would rerun when the referenced field changes value.
