### ISSUE TITLE
multi-line margin for "select-checkbox-inline"

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#509]
![before](https://cloud.githubusercontent.com/assets/1025241/5343089/737ee57c-7f14-11e4-9488-2a46324ee2b2.png)

```
.checkbox-inline {
  margin-right: 10px;
  color: green;
}
.checkbox-inline+.checkbox-inline {
  margin-left: 0px;
  color: red;
}
```

![after](https://cloud.githubusercontent.com/assets/1025241/5343098/80e5e1c0-7f14-11e4-8ace-84e604e5f7bf.png)

**Comment by aldeed** [comment]
Fixed in devel branch. Even though this is a bootstrap issue not specific to autoform, it seems useful enough to include the workaround in the package.

Borrowed the CSS from here: http://stackoverflow.com/questions/15975968/twitter-bootstrap-inline-checkbox-alignment-issue

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
