### ISSUE TITLE
suggest afPanel

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#511]
>afObjectField

>When you use the afQuickField component for a field that is an Object, it is rendered using the afObjectField component unless you override the type or specify options. This happens by default when you use a quickForm for a schema that has a field of type Object.

>The afObjectField component renders all of an object field's subfields together as one group. The group is labeled with the name of the object field. The actual visual representation of the group will vary based on which theme template you use. For the "bootstrap3" default template, the group appears in a panel with a heading.

OK. But if I want to use several fields from object-field, then I will lose panel-style of Bootstrap.

I want suggest solution.

```
<template name="afPanel">
  <div class="panel panel-default">
    {{#with afFieldLabelText name=this.name}}
    <div class="panel-heading">
      <h3 class="panel-title">{{this}}</h3>
    </div>
    {{/with}}
    <div class="panel-body">
      {{> UI.contentBlock}}
    </div>
  </div>
</template>
```

Example

```
  {{#autoForm id="testObject" schema=Schemas.FieldsExamples}}
    {{#afPanel name="address"}}
      {{> afQuickField name="address.city"}}
      {{> afQuickField name="address.street"}}
    {{/afPanel}}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  {{/autoForm}}
```

```
Schemas.FieldsExamples = new SimpleSchema({
  address: {
    type: Object,
    label: 'Your address'
  },
  'address.street': {
    type: String
  },
  'address.city': {
    type: String
  }
});
```

**Comment by aldeed** [comment]
This looks like something a custom afObjectField template can handle.

**Comment by comerc** [comment]
I released afPanel
https://github.com/comerc/meteor-autoform-bs-more/blob/master/autoform-bs-more.html#L1
