### ISSUE TITLE
The autoform would look better with type [object] like this

### ISSUE THREAD

**Issue by veekungx** [aldeed/meteor-autoform#529]
My English really suck I don't know how to explain into word
Please compare the images.

![Image of white space](http://i.imgur.com/O1f4qlH.png)

![Image of white space](http://i.imgur.com/UVcbI29.png)

**Comment by aldeed** [comment]
Fixed in devel branch.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
