### ISSUE TITLE
class="form-horizontal" for autoForm 

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#532]
... does not set automaticaly, when I use AutoForm.setDefaultTemplate("bootstrap3-horizontal")

(only for quickForm)

**Comment by aldeed** [comment]
It would not set for an autoForm because autoForms don't have a theme template. You must set the form class yourself.

**Comment by comerc** [comment]
Ok, may be we define template for autoForm? Or use other way for "global" define class attr.
