### ISSUE TITLE
Error using user schema and meteor method

### ISSUE THREAD

**Issue by dukye** [aldeed/meteor-autoform#536]
Hello,

I have an error hard to solve, i'll check all my fields hundred of times please could you help me.

Consider using the same user shema (profile, country, user) as presented in your README.md

File : lib/schemas.js (at the end of schema declaration)
------------------------------------------
var Schemas = {};
Schemas.User = new SimpleSchema({ ... });
Meteor.users.attachSchema(Schemas.User);

File : server/methods.js
------------------------------------------
Meteor.methods({
  autoFormCreateUser: function (formDoc, e) {
    check(formDoc, Schemas.User);
    return Accounts.createUser(formDoc);
  }
});

File : clent/templates/register.html
------------------------------------------
{{#autoForm id="insertUser" type="method" schema="Schemas.User" meteormethod="autoFormCreateUser"}}
[ ... FIELDS ... ]
{{/autoForm}}

ERROR :
Exception while invoking method 'autoFormCreateUser' Error: Enter a password is required

Thanks in advance :)

**Comment by gabriel-dehan** [comment]
@aldeed Where is the password stored then ? Got the same issue and was wondering ?

**Comment by aldeed** [comment]
Somewhere under `services` I think? You can add a user and look at the new document in mongo to see. I don't think the accounts packages do a very good job of documenting all the various properties they set in the user doc.

**Comment by pggalaviz** [comment]
I'm having the same issue, does any body found a solution?
```javascript
Exception while invoking method 'createNewUserAccount' Error: First Name is required.
```
All validations pass on client side and using `check(userData, Schemas.User);` the problem is uniquely when calling `Accounts.createUser(userData);`.

It appears that all fields are being passed with a null value.

```javascript
details: "[{"name":"profile.firstName","type":"required","value":null},{"name":"profile.lastName","type":"required","value":null},{"name":"profile.state","type":"required","value":null},{"name":"emails","type":"required","value":null},{"name":"password","type":"required","value":null},{"name":"passwordConfirmation","type":"required","value":null}]"
error: 400
errorType: "Meteor.Error"
```

any suggestion?
