### ISSUE TITLE
docId not available on client with validation when using collection2

### ISSUE THREAD

**Issue by jwvdiermen** [aldeed/meteor-autoform#538]
Hi there,

When using autoform, `this.docId` is not set for validation logic (in `custom`, but also `autoValue` methods from simple-schema) on the client due the update method not using `{ _id: docId }` (see here: https://github.com/aldeed/meteor-autoform/blob/master/autoform-events.js#L355).

This causes unexpected behavior, because when the same logic executes on the server, `this.docId` is available. It's also available when you set `schema` on the `autoForm` component.

**Comment by Kestanous** [comment]
:+1: This is causing is preventing me from setting up scoped uniqueness.

**Comment by Kestanous** [comment]
I am now using isServer for validation. It works so I am not blocked anymore:
```js
custom: function () {
  if (Meteor.isServer) { ... }
}
```

**Comment by aldeed** [comment]
Fixed as workaround in devel branch and also created https://github.com/aldeed/meteor-collection2/issues/163

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
