### ISSUE TITLE
Underscores in template names unsupported

### ISSUE THREAD

**Issue by zda** [aldeed/meteor-autoform#539]
Many JS developers (if a minority) prefer snake_case to camelCase, and `AutoForm.addInputType` breaks if you pass it a `template` option value containing an underscore, due to [line 271 of autoform-api.js](https://github.com/aldeed/meteor-autoform/blob/master/autoform-api.js#L271). It took us hours to figure out this was the reason our custom input types weren't working.

**Comment by mitar** [comment]
+1

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.

**Comment by caioreis** [comment]
@aldeed, just had this same issue again on aldeed:autoform@5.3.0.
