### ISSUE TITLE
How to translate Submit buttons etc.

### ISSUE THREAD

**Issue by mdocter** [aldeed/meteor-autoform#545]
Maybe I'm looking in the wrong places, but I can't figure out how to translate generated elements like the 'Submit' button text etc.
Can you point me in the right direction?

**Comment by SachaG** [comment]
Would we have to do this form by form, or is there an easier way to provide a function for setting the default submit button text for all forms?

**Comment by aldeed** [comment]
Some way to set global default attributes per component could be added, and/or a reactive function that returns translations of the default strings.

**Comment by mirkogeest** [comment]
mdocter, did you find a solution to this? 

Because I cannot solve it this way, if I try:

`buttonContent="{{_ 'Submit'}}"`

, the content of the i18n tag is not interpreted, the button's caption is "{{_ 'Submit'}}"

**Comment by mininao** [comment]
@mirkogeest If you use tap-i18n, maybe try ``` buttonContent=TAPi18n.__('Submit') ``` ?
If not, what i18n module do you use ?

**Comment by abate** [comment]
if I understand correctly there is no way to change all "submit" buttons for all components at once ... Or Am I missing something ?
