### ISSUE TITLE
Preserve AutoForms on Hot Code Push does not work for date input type

### ISSUE THREAD

**Issue by fpoirier1** [aldeed/meteor-autoform#554]
Seems like the value for `<input type="date" ` is not preserve through Hot Code Push.

**Comment by fpoirier1** [comment]
Here is a repo project. http://meteorpad.com/pad/3z2dziLdDeJsXQZuT/Autoform-date

All you need to do is to select a todo and than change code (add/remove comments) to force hot code push

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
