### ISSUE TITLE
I want to use afFieldMessage for help text 

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#555]
But now it available only for error messages

**Comment by comerc** [comment]
Hmm. Why "separate package"? It is template for input field. 😊

**Comment by aldeed** [comment]
It's not needed by everyone so you can make a separate `afFormGroup` template and release it as a separate pkg. `afFieldMessage` is the error message, so help text is something separate.

**Comment by comerc** [comment]
But `afFormGroup` integrated in generator of `quickForm`. I get fragmentation of code.

**Comment by gwendall** [comment]
Any clean solution for that ?
