### ISSUE TITLE
using 'afFieldValueContains Helper' 

### ISSUE THREAD

**Issue by ZHosseinpour** [aldeed/meteor-autoform#558]
i want to show something in may page based in the main category selection by user. in other words i want to show something when the main category value becomes true. this is what i wrote:

   HTML:

    {{#autoForm collection="coll" id="insertcollForm" type="insert" doc=defualtDoc}}
    {{> afQuickField name='mainCategory'}}
    {{#if afFieldValueContains name="mainCategory" value="true"}}
    {{>afQuickField name='item.mainCategory' options=mainCatOption}}
    {{else}}
    {{>afQuickField name='item.subCategory' options=subCatOption}} 
    {{/if}} 

   JavaScript:

    coll = new Mongo.Collection("coll");
    coll.attachSchema(new SimpleSchema({ 
    mainCategory: {
         type: Boolean,
         label: "mainCategory",
         optional: true
     },
    'item.mainCategory':{
         type:String,
         label:"mainCategory List",
         optional:true
     }
     }));

**Comment by yfinkenbrink** [comment]
I've got the same Issue and I'm interessted in the solution you have found @ZHosseinpour 



HTML
```
{{# autoForm collection="Analysis" type="insert" id="insertAnalysis"}}
    ...
    {{> afQuickField name="tees.$.fairway" options="allowed" type="select-radio-inline"}}
    {{> afQuickField name="tees.$.greenInRegulation"}}
    {{#if afFieldValueContains name="tees.$.greenInRegulation" value=false}}
        {{> afQuickField name="tees.$.shotType" options="allowed" type="select-radio-inline"}}
    {{/if}}
    ...
{{/ autoForm}}
```

Collection
```
"tees.$.fairway": {
    "type": String,
    "optional": true,
    "allowedValues": ["left", "straight", "right"]
},
"tees.$.greenInRegulation": {
    "type": Boolean,
    "optional": true
},
"tees.$.shotType": {
    "type": String,
    "optional": true,
    "allowedValues": ["pitch", "chip", "bunker"]
},
```

I want to create a analysis Tool for our golf team. If they didn't reach a green in regulation they can select which shot they made to get on the green. Like they select the fairway.

The field `name="tees.$.greenInRegulation"` is a boolean checkbox and works fine

`<input type="checkbox" value="true" name="tees.$.greenInRegulation" id="fhw3TPB8YWzhvCecL" data-schema-key="tees.$.greenInRegulation">`
