### ISSUE TITLE
afDestroyUpdateForm should be form-specific

### ISSUE THREAD

**Issue by medihack** [aldeed/meteor-autoform#566]
Under some circumstances (the doc option must be set) when calling `resetForm` (or `done`) in `onSubmit` other forms on the same page get also reset (or at least destroyed and created again).

I created a minimal example to reproduce it: https://github.com/medihack/issue_reset_form

Just fill something into the field `Foo`, but submit the second form (that one with the field `Bar`). The value of `Foo` in the first form gets blanked even though just the second form was reset.

**Comment by aldeed** [comment]
I think this is because `afDestroyUpdateForm` should be form-specific. I'll try to get a fix out soon.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
