### ISSUE TITLE
How to use select option groups in quickForm?

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-autoform#567]
I have a quickForm rendering in a page, with a select list. When I convert it from a list of items to a list of option group objects, I get the following error:

```
Uncaught Error: Meteor does not currently support objects other than ObjectID as ids
```

Is it possible/recommended to define the options groups variable within the schema, or is it only possible to do it through a template helper?
http://autoform.meteor.com/select

**Comment by ianserlin** [comment]
If you try to use `options="allowed"` on an autoform input but you don't specify the `autoform: { options: [my labels and values] }` on your schema and instead simply tried to use the `allowedValues` property on your schema and those "values" were objects with a `value` and a `label` field... you will see this error.

Try setting `allowedValues` and `autoform: { options: [] } }` on the property you're trying to display as a select in your schema for that collection.

**Comment by bob360** [comment]
I am having the same problem setting the schema with optgrp and options.Cant find a clear tutorial on how to set the schemas for an aldeed autoform.Seems to me that Developpers have forgotten to make tutorial idiotproof,making themselves nothing else than <Idiots>.Well ...welcome to my world.

**Comment by MichaelInfoworks** [comment]
E.g.

```
	sourceSubtype: {
		type: String,
		label: "Source Subtype",
		allowedValues: sourceSubTypes,
		autoform: {
			firstOption: "Select a source type",
			options: [{
				optgroup: "File",
				options: sourceFileLabels,
			},{
				optgroup: "RDBMS",
				options: sourceRDBMSLabels
			}]
		}
	},
```
