### ISSUE TITLE
How to build an autoForm with nested [Object] or [Array] values?

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-autoform#568]
Is there a quick example of an autoForm that allows nested [Object] or [Array] values to be dynamically added? I.e. it would function like the quickForm example, but with the individual fields defined via an autoForm.

**Comment by craig-l** [comment]
@brylie is [this](http://meteorpad.com/pad/Xjxv9XTovToLDd7ao/Copy%20of%20quickForm-Objects) what you were referring to? This gives you exactly what your `quickForm` gave you. 
Check out  [afQuickField examples](https://github.com/aldeed/meteor-autoform#afquickfield-examples) and [#afEachArrayItem](https://github.com/aldeed/meteor-autoform#afeacharrayitem) if you wanted to completely customize how that object appears along with your own + and - buttons.

**Comment by brylie** [comment]
OK, great. I'll review those sources.
