### ISSUE TITLE
doc values not selected after code reload

### ISSUE THREAD

**Issue by sirpy** [aldeed/meteor-autoform#570]
I have a form with an object field Days with all the week days as sub fields.
when I give the form in the doc attribute default values, non of the radio buttons for the days fields is checked, other fields do get their default value.

```js
Days:{
      type:Object,
      minCount:7,
      maxCount:7,
      optional:false,
  },
  "Days.sun":{
      type:String,
      autoform: {         
        options: function () {
            return [{label:"0",value:0},{label:"1",value:1},{label:"2",value:2}];
        },
        type:"select-radio",
        template:"buttonGroup",
      }
  },
```

**Comment by aldeed** [comment]
Should be fixed in next release.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.

**Comment by freer4** [comment]
I just ran into this! Updated and it works. Thanks aldeed!
