### ISSUE TITLE
using autosave with type="method"

### ISSUE THREAD

**Issue by ChenRoth** [aldeed/meteor-autoform#577]
hey

according to docs, autosave is only for type="update"
any reason it shouldn't be available for type="method" too?

**Comment by aldeed** [comment]
In next release it will work on any form type, though using with insert forms would rarely be a good idea.

**Comment by maxnowack** [comment]
:+1: 
When is the new version coming?

**Comment by aldeed** [comment]
Still testing and squashing bugs and hoping to get the firefox recursion issue fixed somehow before release, all in spare time. Pretty close though. Hopefully this week.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
