### ISSUE TITLE
Add ability to use parsley.js message translations

### ISSUE THREAD

**Issue by almogdesign** [aldeed/meteor-autoform#578]
It says "Default validation error messages that appear under the fields, and can be customized and translated." 

But I'm not seeing were this is set? or docs on this? Is this using ParsleyJS how can I set this

**Comment by aldeed** [comment]
@almogdesign, it should be possible to create a lightweight add-on package that loops through the `window.ParsleyConfig.i18n` object and registers all the messages defined there as SimpleSchema messages. Then you could just drop the parsley [i18n folder](https://github.com/guillaumepotier/Parsley.js/tree/master/src/i18n) into /client/lib. I'm not sure when I would have time, but maybe someone else wants to tackle it.

**Comment by aldeed** [comment]
Closing. See #438
