### ISSUE TITLE
[Question] Generating a preview

### ISSUE THREAD

**Issue by msamoylov** [aldeed/meteor-autoform#583]
I have a tabbed page layout with a form and a preview. Is there any way to validate a form with pushing the 'Preview' button, and to switch to the second tab once it's valid? I.e. we are not creating anything until the 'Submit' button is pressed.

        <div class="tab-content">
        <div class="tab-pane text-left fade in active" id="compose">
            {{#autoForm collection="Jobs" id="insertJobForm" type="insert"}}
                {{> afQuickField name="title" class="form-control input-lg"}}
                [more fields]
                <div class="form-group">
                    <button type="submit">Preview</button>
                </div>
            {{/autoForm}}
        </div>
        <div class="tab-pane text-left" id="preview">
            <h2>{{currentFieldValue "title"}}</h2>
            [more output]
            <button type="submit">Submit</button>
        </div>
    </div>

**Comment by aldeed** [comment]
Switch both buttons to `type="button"`. In the click event handler for Preview, do `AutoForm.validateForm("insertJobForm")`. If it returns `true`, switch tabs. In the click event handler for Submit, do `$('form#insertJobForm').submit()`.

**Comment by msamoylov** [comment]
Awesome, thanks!
