### ISSUE TITLE
Dynamic Label Feature

### ISSUE THREAD

**Issue by rclai** [aldeed/meteor-autoform#584]
Sort of like autoValue where you can do this.field('someOtherField'). Example:

```
{
    type: String,
    label: function () {
         if (this.field('someOtherField').value === 'someValue')) {
                return 'My Custom Label';
         }
         return 'My Default Label';
    }
}
```
Further, if this field was within an array or deeply embedded in arrays it would be useful to reference
```
this.field('someArr.$.someField').value
```

Perhaps this could be connected to the reactivity needed in #483.

**Comment by aldeed** [comment]
This could probably be added eventually, but it would actually be a change in the SimpleSchema package. Can you post this to that repo instead?
