### ISSUE TITLE
getFieldValue doesn't react to changes from jQuery

### ISSUE THREAD

**Issue by craig-l** [aldeed/meteor-autoform#586]
Go to 
http://autoform.meteor.com/fieldvalues

put this in your console:
```$("input[name=a][value=foo]").prop('checked', true);```

Expected behavior of afFieldValueIs doesn't happen

**Comment by craig-l** [comment]
Figured it out.. The key is to put `.trigger('change')` at the end.

`$("input[name=a][value=foo]").prop('checked', true).trigger('change');` works as expected!

**Comment by aldeed** [comment]
Yeah, I agree this isn't ideal, but I can't think of any other way for autoform to find out that you changed it.
