### ISSUE TITLE
BUG: contenteditable, autosave=true, [F5] - focused field lost value

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#590]
because blur-event (with change-event) not called

Solution

I will save value in LocalStorage on every input-event. If change-event will call then I will delete value from LocalStorage else I will focus this field when window open in next time and I will set value to field from LocalStorage for continue editing.

Problem: [input-event](https://developer.mozilla.org/en-US/docs/Web/Events/input) unstable. OK, I released input2-event for contenteditable.

You can use [frozeman:storage](https://github.com/frozeman/meteor-storage/) as wrapper of LocalStorage.

```coffee
Template.myTemplate.events
  "input2 [contenteditable]": (event, template) ->
    $element = template.$(event.target)
    LocalStore.set 'draft4' + template.view.name,
      elementId: event.target.id
      value: $element.html()
    , reactive: false
  "change [contenteditable]": (event, template) ->
    LocalStore.set('draft4' + template.view.name, null, reactive: false)

Template.myTemplate.rendered = ->
  draft = LocalStore.get('draft4' + @view.name, reactive: false)
  if (draft)
    $element = @.$("[contenteditable]#" + draft.elementId + ":first")
    $element.focus()
    $element.html(draft.value)
```

**Comment by aldeed** [comment]
I don't see any reason to use localstorage. A normal variable would make more sense.

We may just want a more general solution here, like doing an additional autosave before the form is destroyed. Needs some investigation.

**Comment by comerc** [comment]
We are losing data, if use normal variable.

I released standalone package for solve this and some other problems: https://github.com/comerc/meteor-autoform-contenteditable2

**Comment by aldeed** [comment]
Maybe you need to use Session or something but definitely not local storage. The way you are doing it is a potential security issue. Field value will be saved in browser when I log out (assuming `change` is not called). Then someone else logs in and will see the text I was typing.

**Comment by comerc** [comment]
It is not bug for me. It is feature. 😊

But OK. We need option for LocalStorage/Session.

**Comment by aldeed** [comment]
Fixed in devel.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
