### ISSUE TITLE
I get atts in lowercase

### ISSUE THREAD

**Issue by miguelalarcos** [aldeed/meteor-autoform#591]
I have made an autocomplete widget that I want to integrate with AutoForm. This is the template:
```html
<template name='xautocomplete'>
    <div class="xwidget xautocomplete ui input" tabindex=100 {{this.atts}}>
    ...
```

And here I use it:
```html
{{> afFieldInput formId="afInsertDemo" name='value' type='xautocomplete' call='items' valueFunction='valueAuthors' renderFunction='renderAuthors'}}
```
But you can see the output in HTML:
```html
<div class="xwidget xautocomplete ui input" tabindex="100" formid="afInsertDemo" name="value" call="items" valuefunction="valueAuthors" renderfunction="renderAuthors" required="" data-schema-key="value">
...
```
I coded ```formId``` but I get ```formid``` (lowercase). The same for the rest of atts. Is this normal? Thanks in advance.

**Comment by aldeed** [comment]
It turns out this is actually something browsers do based on the HTML5 spec:

http://www.w3.org/html/wg/drafts/html/master/dom.html#attr-data-*

Note:

> All attribute names on HTML elements in HTML documents get ASCII-lowercased automatically
