### ISSUE TITLE
AutoForm.getFieldValue does not react when tracked field is changed by jQuery's .val()?

### ISSUE THREAD

**Issue by Benczyk** [aldeed/meteor-autoform#592]
Hi,
I'm having unexpected behavior with AutoForm.getFieldValue.

In a form I'm setting some values with jQuery's .val(), and tracking these fields with AutoForm.getFieldValue (for later use in the form).

Expected behavior: AutoForm.getFieldValue vars are always up to date.
Current behavior: AutoForm.getFieldValue only reacts if the values are set through a user input (eg. using keyboard).

Is there some misunderstanding / misuse on my part, or is this a bug?

Cheers,
Ben
PS:
- my AutoForm.getFieldValue is in a "this.autorun" (inside a Template.someTemplate.rendered)
- I'm using aldeed:autoform@4.2.1

**Comment by aldeed** [comment]
You probably have to call `.val().trigger('change')`. It's not ideal, but I'm not sure if there's any way for autoform to know that you changed the value if you don't fire the change event.

**Comment by Benczyk** [comment]
Ah, yes indeed.
Thanks!
