### ISSUE TITLE
bootstrap colorselector

### ISSUE THREAD

**Issue by almogdesign** [aldeed/meteor-autoform#593]
Is it possible to setup a drop down with custom options I would like to do something like this

```html
  <option value="106" data-color="#A0522D">sienna</option> 
```

Basically setting up a  bootstrap colorselector or something like this - https://atmospherejs.com/natestrauser/bootstrap-colorpicker

**Comment by aldeed** [comment]
You can do it by [making a custom input type](https://github.com/aldeed/meteor-autoform#defining-custom-input-types).
