### ISSUE TITLE
Validate a modifier when submitting to methods

### ISSUE THREAD

**Issue by fpoirier1** [aldeed/meteor-autoform#594]
I am wondering, how can we validate a modifier with `check()` or `schema.newContext()`?

> you must call check() in the method or perform your own validation since a user could bypass the client side validation.

>That method will be called with three arguments:
- document: the document resulting from the form submission.
- modifier: the modifier object.
- documentId: when updating an existing document, that document's _id (optional).

Thanks!

**Comment by aldeed** [comment]
`check(modifier, schema)`

**Comment by fpoirier1** [comment]
Thanks !
