### ISSUE TITLE
onSubmit turns <select> into <input>

### ISSUE THREAD

**Issue by leebenson** [aldeed/meteor-autoform#595]
I have a "country" field defined like so:

`+afQuickField name="country" options=countries firstOption="Please select"`

"countries" is a map of {label, value} objects.

It looks like it should, i.e:

![screen shot 2015-01-06 at 15 30 22](https://cloud.githubusercontent.com/assets/719722/5630815/073a5a3e-95b9-11e4-895d-3bff83d3465e.png)

... until I add an onSubmit hook:

    Autoform.addHooks('registerUserForm', {
        onSubmit: function() {
            alert('got here');
            console.log(arguments);
        }
    });

Adding the hook turns the select box into a textbox field.

Result:

![screen shot 2015-01-06 at 15 30 34](https://cloud.githubusercontent.com/assets/719722/5630821/1316bf3c-95b9-11e4-9e64-c9b9364af009.png)

**Comment by aldeed** [comment]
Please provide a MeteorPad or cloneable repo showing the issue. I can't reproduce this with the info you have here.
