### ISSUE TITLE
AutoForm not defined

### ISSUE THREAD

**Issue by advany** [aldeed/meteor-autoform#597]
I get the error autoform not defined when I do new Autoform....

I have the following code:

Events = new Mongo.Collection('posts');

Events.attachSchema(new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  summary: {
    type: String,
    label: "Brief summary",
    optional: true,
    max: 1000
  }
}));

if (Meteor.isClient) {
  Template.eventsList.helpers({
    events: function() {
      return Events.find();
    }
  });
}

EventsForm = new AutoForm(Events);
EventsForm.hooks({
  EventForm: {
    // Called when any operation succeeds, where operation will be
    // "insert", "update", "submit", or the method name.
    onSuccess: function(operation, result, template) {
      Router.go('eventsList');
    },
  }
});

**Comment by almogdesign** [comment]
How are you adding your form in the template?

**Comment by advany** [comment]
I also tried AutoForm.hooks but same error. Also reinstalled AutoForm

AutoForm.addHooks(null, {
    onSuccess: function () {
      console.log("onSuccess on all input/update/method forms!");
    }
  });

**Comment by advany** [comment]
sorry... just found out that AutoForm is client only... now it works

**Comment by jeffyamada** [comment]
@advany You just saved me some time, thanks!

**Comment by MohammedEssehemy** [comment]
Thanks @advany , you saved my day.
