### ISSUE TITLE
getFieldValue in schema options

### ISSUE THREAD

**Issue by almogdesign** [aldeed/meteor-autoform#598]
Is it possible to update the options in schema once a field is selected or getFieldValue is called? 

My understanding is that schema and options run on template render just once so there is no way to change a field value based on different sections.

**Comment by aldeed** [comment]
In the schema probably not, but you can do so in an options helper. Hopefully we can eventually make the schema functions run reactively, too.

**Comment by almogdesign** [comment]
Thanks actually I just got it working, It seems to be working really good in the options.
