### ISSUE TITLE
Provide current field name/context to attribute functions

### ISSUE THREAD

**Issue by almogdesign** [aldeed/meteor-autoform#599]
I'm trying to do the following but not sure how to reference the correct field as it's an array
```javascript
 PO: {
        type: Array,
        optional: false,
        minCount: 0,
        maxCount: 10
    },
    "PO.$.REF": {
        type: String,
        optional: false
    },
    "PO.$.CE": {
        type: String,
        autoform: {
            afFieldInput: {
                type: "text"
            },
            options: function () {
                var REF = AutoForm.getFieldValue("formSchema", "PO.$.REF");
                console.log(REF);
            }
        }
    }
    } 
```
I tried PO and PO.$.REF but noting

**Comment by aldeed** [comment]
Here is one way: http://meteorpad.com/pad/NBackKhB5PEDvK9yt/AutoForm%20#599

In summary:
1. Add `template-afFormGroup="addOptions"` to your `afQuickField`.
2. Defined a template named `afFormGroup_addOptions`, which is copied from the bootstrap template [here](https://github.com/aldeed/meteor-autoform/blob/master/templates/bootstrap3/bootstrap3.html#L18-L26). In your custom template, change `this.afFieldInputAtts` to `afFieldInputAtts`.
3. Copy the [built-in template's helpers](https://github.com/aldeed/meteor-autoform/blob/master/templates/bootstrap3/bootstrap3.js#L21-L34) to your custom template, too.
4. Add an additional helper, `afFieldInputAtts`, as defined in the meteorpad.

**Comment by flanamacca** [comment]
Hey Aldeed, 

Just with the way you have proposed doing that, it only works AFTER the the blur effect (or something similar) takes place.  If we were to pass into the options a context that contains just the index... that would allow for that (current options context is the window element).

In essence... a "getCurrentIndex" function available ?

**Comment by aldeed** [comment]
Yeah, I have some ideas around this.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
