### ISSUE TITLE
Expose hook references for testing

### ISSUE THREAD

**Issue by dmeneses** [aldeed/meteor-autoform#601]
Is there a way to access/spy the callback hooks for a specific form using sinon for example.

**Comment by aldeed** [comment]
The object where they're stored isn't part of the exported API, but that could be changed. I'm not familiar with sinon, but is that all you would need? An `AutoForm.Hooks` object?

**Comment by dmeneses** [comment]
yeap, thats what I need, sinon generates code around a function to identify if its called or not:

sinon.spy(AutoForm.Hooks['formId'], "onError");
sinon.spy(AutoForm.Hooks['formId'], "onSuccess");

In this way i will ensure that this methods are called, which ones not and what they receive.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.

**Comment by dmeneses** [comment]
Thanks :+1:

**Comment by charlesdeb** [comment]
For others coming here afterwards, the exact syntax for doing this appears to be:

```
const hookSpy = sinon.spy(AutoForm._hooks["myFormId"].onSubmit, [0]);

doSomething();

expect(hookSpy).to.have.been.called;
```
Hope this is helpful. It took me hours to figure out the exact sinon syntax for accessing elements of the array of hook functions for each hook type - hence the `[0]` in the create spy function.
