### ISSUE TITLE
Calling this.done("error") in onSubmit reloads page

### ISSUE THREAD

**Issue by obiwarn** [aldeed/meteor-autoform#602]
When I call this.done() it doesn't reload (which is what I want).
but when it includes an error message I cannot run any further code (since the page is reloaded / POST is called)

**Comment by aldeed** [comment]
Are you returning `false` from the `onSubmit`?

**Comment by obiwarn** [comment]
I am kicked out of the onSubmit before I could return anything. 
However, I got it to work with this.event.preventDefault()

maybe this.done() calls preventDefault on it's own?

**Comment by aldeed** [comment]
OK, you haven't defined an `onError` handler, right? If you don't, then the error is thrown, and if the error is thrown, I guess it doesn't prevent default because you never return `false`. So maybe there is a bug here. Before it throws the error, it should probably prevent default for you.

**Comment by aldeed** [comment]
This seems to be fixed by changes in `devel` branch.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.

**Comment by luixal** [comment]
Hi,

As for now (AutoFrom 5.8.1), I still needed to include ```the this.event.preventDefault()```. For what I read here, maybe I need to return something on the onSubmit, onSuccess or onError handlers but, following the examples, I defined both handlers and still got the default submit call made by the browser.
