### ISSUE TITLE
AutoForm.getSelectedOptions

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#606]
If you like this idea, I will set pull request for https://github.com/comerc/meteor-autoform/commit/2b17bb8f3b1e4b693fc17a335f249075c57d3dfc

usage:
```coffee
Cars.attachSchema new SimpleSchema
  carId:
    type: String
  details:
    type: Object
  "details.complectation":
    type: [Number]
    autoform:
      options:
        1: "one"
        2: "two"

data = Collections.Cars.findOne {carId: @params._id}
ss = Collections.Cars.simpleSchema()
a = AutoForm.getSelectedOptions(data.details.complectation, "details.complectation", ss)
return a.join(", ")
```

**Comment by aldeed** [comment]
I think this would be better as a separate add-on package.

**Comment by comerc** [comment]
I released this issue with other way
https://github.com/comerc/meteor-autoform-fixtures/blob/master/autoform-fixtures.coffee#L72
