### ISSUE TITLE
autoform for Meteor.users (schema)?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-autoform#607]
I would like to create `autoform` for `Meteor.users` that have any fields:
```
username, emails, password, confirm password,
```
how to build schema?

**Comment by aladine** [comment]
You can create a new Schema as such:
      Schemas.UserJoin = new SimpleSchema(
        username:
          type: String,
          label: "Username"
        email:
          type: String,
          regEx: SimpleSchema.RegEx.Email
          label: "Email"
         password:
          type: String,
          label: "Password"
          min: 6
        passwordConfirmation:
          type: String,
          min: 6
          label: "Password confirmation"
          custom: () ->
            if @value != @field('password').value
              return "passwordMissmatch"
      )

In Helper: 
 
        Template[...].helpers
           userJoinSchema: Schemas.UserJoin 

then in autoform 
{{#autoForm schema=userJoinSchema collection=Users }}

**Comment by yuomtheara** [comment]
login page i use `ian:accounts-ui-bootstrap-3 ` that have struct schema
```js
{
    "_id" : "w76CMrJpjrQnfAo59",
    "createdAt" : ISODate("2015-01-06T04:17:10.518Z"),
    "emails" : [ 
        {
            "address" : "yuom.theara@gmai.com",
            "verified" : false
        }
    ],
    "profile" : {},
    "services" : {
        "password" : {
            "bcrypt" : "$2a$10$8hH7KvF2XfSVWtTINQVaLuNYVKhufpB.v9RI/.6VvnC7S5QV2zc9i"
        },
        "resume" : {
            "loginTokens" : [ 
                {
                    "when" : ISODate("2015-01-09T06:34:32.172Z"),
                    "hashedToken" : "9Oc2KpFvciwlv6DUu3d/1YEdOKdGt+lwv9hEMCrxrsU="
                }
            ]
        }
    },
    "username" : "admin"
}
```
so i want folloup like this.

**Comment by aldeed** [comment]
It's not a good idea to directly insert new users. The correct way is to make a separate form schema as @aladine suggests, and then use an `onSubmit` hook for that form to call `Accounts.createUser`. That way you let the accounts package deal with the important security concerns for properly creating a user, sending the password to the server, etc.

**Comment by yuomtheara** [comment]
It is good, it work fine.

**Comment by JoshuaNovak919** [comment]
I am having a lot of trouble finding the best way to handle user forms with auto form. @aldeed You mentioned using `Accounts.createUser`, but I don't quite know how all this should hook up since I am new to Meteor. Is there a working example somewhere that has the schema, form code, and form js working with Meteor.users, so I can see what I need to do? Or would someone be kind enough to post a full example. I've been scouring the internet and issues on here and haven't found a full example, only bits and pieces, or I wouldn't bug you guys.

**Comment by leizard** [comment]
Hi @JoshuaNovak919, I'm digging into the same problem too. Have you found any solution for this ?
