### ISSUE TITLE
Custom Input Type for Objects?

### ISSUE THREAD

**Issue by ndee** [aldeed/meteor-autoform#612]
I came back to checkout AutoForm 4.0 after its refactoring. Great enhancements! :+1: 

I'm currently playing around with custom input types and I'm trying to realize a custom input type for objects. After reading the documentation I'm not sure if this is (currently) possible for non built-in data types.
I tried to register my input type the following way but my template helper is never called:

```
PriceSchema = new SimpleSchema({
    value: {
        type: Number
    },
    currency: {
        type: String,
        allowedValues: ['EUR', 'USD']
    }
});

ItemSchema = new ItemSchema({
    name: {
        type: String,
        label: "Name"
    },
    price: {
        type: PriceSchema,
        label: "Price",
        autoform: {
            afFieldInput: {
                type: 'specialPriceInput'
            }
        }
    }
});
```

**Comment by aldeed** [comment]
What does your form look like? Did you tell it to use an input rather than an object field for the object?

**Comment by ndee** [comment]
I used a quickform. In my app I will have lots of types/schemas. My goal is to use only quickforms  and realize type specifics with custom input types.

**Comment by aldeed** [comment]
OK, then it might work if you change

```js
afFieldInput: {
  type: 'specialPriceInput'
}
```

to

```js
afQuickField: {
  type: 'specialPriceInput'
}
```

Or you might need both. Quick forms use `afQuickFields`, and an `afQuickField` will use an `afObjectField` for objects unless you have a `type` attribute on it.

**Comment by ndee** [comment]
Yeah! If i use both (afQuickField and afFieldInput) it works!
