### ISSUE TITLE
ie8: breaking on line 68 of bootstrap3.js - Unable to get property 'helpers' of undefined or null reference

### ISSUE THREAD

**Issue by zaklampert** [aldeed/meteor-autoform#613]
My application is spitting out "Unable to get property 'helpers' of undefined or null reference" in the ie8 emulator followed by 64 other errors, most of which are 'Template' is undefined .

The referenced file is aldeed_autoform.js, Line 7699, Column: 3

```
_.each([
    "afInputButton_bootstrap3",
    "afInputSubmit_bootstrap3",
    "afInputReset_bootstrap3",
  ], function (tmplName) {
  Template[tmplName].helpers({
    atts: function addFormControlAtts() {
      var atts = _.clone(this.atts);
      // Add bootstrap class
      atts = AutoForm.Utility.addClass(atts, "btn");
      return atts;
    }
  });
});
```

**Comment by aldeed** [comment]
I'm not actively working to support IE8 anymore. I'll accept a pull request if someone else wants to figure out the fix.
