### ISSUE TITLE
Hard time customizing template

### ISSUE THREAD

**Issue by yanndebelgique** [aldeed/meteor-autoform#615]
Hi. I have an object schema that only one has level (i.e. {foo: "Bar", amount : 12}, so no nested objects and arrays). The default afArrayField is sweet but I would like to represent it in a table for my use case.
my schema is the following :

```js
{
 medication : {
  type : Object
 },
"medication.peros" : {
 type : [MedicationSchema]
}
}
```

And medication schema is :

```js
var MedicationSchema = new SimpleSchema({
  "name" : {
    type : String,
    label : "Naam"
  },
  "intake_time" : {
    type : Number,
    label : "Tijdstip",
    allowedValues : [8, 12, 17, 22]
  }
});
```

In need to display the "medication.peros" as a table.

I can post the template I got so far.

**Comment by yanndebelgique** [comment]
Ok finally found a disgusting hack! Don't judge! For those who want to go down that road:

<fieldset>
    <legend>{{afFieldLabelText name=this.atts.name}}</legend>

    {{#if afFieldIsInvalid name=this.atts.name}}
      <div class="autoform-array-field-error">
        {{{afFieldMessage name=this.atts.name}}}
      </div>
    {{/if}}

    <table class="table table-striped table-hover">
    	<thead>
    		<tr>
              {{#afEachArrayItem name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
                {{#if afArrayFieldIsFirstVisible}}
                {{#each afFieldNames name=this.name}}
                  <th>
                    {{afFieldLabelText name=this}}
                  </th>
                {{/each}}
                <th>
                </th>
                {{/if}}
              {{/afEachArrayItem}}
    		</tr>
    	</thead>
    	<tbody>
        {{#afEachArrayItem name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}


            <tr>
              {{#each afFieldNames name=this.name}}
                <td>
                  {{>afFieldInput name=this options="auto"}}
                </td>
              {{/each}}
              <td>
                {{#if afArrayFieldHasMoreThanMinimum name=../atts.name minCount=../atts.minCount maxCount=../atts.maxCount}}
                  <button type="button" class="autoform-remove-item">Remove</button>
                {{/if}}
              </td>
            </tr>

        {{/afEachArrayItem}}
        <tr>
          <td colspan="2">
            {{#if afArrayFieldHasLessThanMaximum name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
              <div style="margin-top: 20px;">
                <button type="button" class="autoform-add-item" data-autoform-field="{{this.atts.name}}" data-autoform-minCount="{{this.atts.minCount}}" data-autoform-maxCount="{{this.atts.maxCount}}">Add</button>
              </div>
            {{/if}}
          </td>
        </tr>
    	</tbody>
    </table>

  </fieldset>

**Comment by aldeed** [comment]
Not disgusting, seems about right. You could consider releasing your custom template as an add on package. I'm sure others would like a table layout in some cases.

**Comment by yanndebelgique** [comment]
Ok I'll give it a shot.

**Comment by yuomtheara** [comment]
I try, it don't work.
what the `name=this.atts.name`?
