### ISSUE TITLE
Accessing field labels in your code

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#616]
I know you can use the `{{> afFieldLabelText}}` helper to access a field's label inside a template. But is there a way to do it from within your own code? As far as I can tell the label is not part of the context that's passed to the form templates. 

This is related to https://github.com/aldeed/meteor-autoform/issues/483, I wanted to try using labels as an internationalization key to translate them in the template.

**Comment by aldeed** [comment]
Through simple-schema, you can do `mySchema.label(fieldName)`, which is reactive. If you don't necessarily know the form's schema, then you'd first have to figure out that.

**Comment by SachaG** [comment]
Thanks! But actually, how would I figure out the schema? Is there anything in Autoform to help do that, or should I figure it out some other way (based on the route, etc.)?

**Comment by SachaG** [comment]
OK, so this is a little tricky… It seems like `mySchema.label(fieldName)` will fall back on the capitalized, prettified field name if it can't find a label. 

Which in most cases would be desirable, but for my specific purposes I want to fall back on the actual field name, which I then use as an i18n key. 

So I guess unless there's a way in Autoform to access the `label` property itself and know when it's `undefined`, I'll have to just look it up on the global schema object. Sorry if this is a bit confusing…

**Comment by aldeed** [comment]
It's not yet released, but in the next version of autoform I'm working on, there is `AutoForm.getFormSchema(formId)`, which can also be called without passing a formId when you're within a form's reactive context, and then will return the schema for the closest form.

So you could then do `AutoForm.getFormSchema().schema(fieldName).label`, and then check whether it's a function and if so, call it. That's the equivalent of what `mySchema.getDefinition` does, minus the label inflection. You'll also be missing the label reactivity, though.

If you want to add an option to `getDefinition` and `label` functions to skip the inflection, I would merge that PR. Relevant code is here: https://github.com/aldeed/meteor-simple-schema/blob/master/simple-schema.js#L820

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
