### ISSUE TITLE
Error: Can't select in removed DomRange

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#618]
I sometimes get this error when submitting Telescope's settings form (which is a type=meteormethod quickForm): 

`Error: Can't select in removed DomRange`

The form still works fine though, and the error doesn't appear every time. So I'm not sure what's going on.

**Comment by aldeed** [comment]
I've done some work to mitigate this in devel branch. You can reopen if you figure out a reliable reproduction.
