### ISSUE TITLE
validateForm returns false for fields that aren't in the form

### ISSUE THREAD

**Issue by mattkrick** [aldeed/meteor-autoform#620]
I've got 2 forms that feed into the same collection. That collection has a single schema.
If I manually validate one of the forms, it returns false. Using the SimpleSchema debugger, it shows the fields that are captured in the other form and says their values are null.
As I understand it, the validateForm should essentially loop through every field in the form, not every field in the schema, right?

**Comment by aldeed** [comment]
If your schema has required fields and they're not in the object that is built from the form values, then the object is invalid. You can use the `schema` attribute on each form to provide a schema that does not include the required fields, or you can include hidden inputs for the required fields that you don't want to appear. You can use `mySchema.pick(['field1', 'field2'])` to get a new schema that is a subset of another.
