### ISSUE TITLE
[Question] AutoForm.getFieldValue for array fields

### ISSUE THREAD

**Issue by msamoylov** [aldeed/meteor-autoform#622]
CC'ing from http://stackoverflow.com/questions/27903737/autoform-getfieldvalue-for-array-fields

I have a schema declared as:

    JobSchema = new SimpleSchema({
        responsibilities: {
            type: [String],
            optional: true
        },
        'responsibilities.$': {
            min: 2,
            autoform: {
                afFieldInput: {
                    class: 'form-control'
                },
                placeholder: 'E.g. "Build tools according to specifications"'
            }
        }
    });

Also I have an UI helper declared as:

    Template.registerHelper('currentFieldValue', function (fieldName) {
        return AutoForm.getFieldValue('insertJobForm', fieldName) || '';
    });

I have a template where I used this helper to generate a form preview. It works like charm for all fields except the array ones. Nothing is being rendered. Any ideas?

    {{# if currentFieldValue "responsibilities"}}
        <h3>Responsibilities</h3>
        {{{currentFieldValue "responsibilities"}}}
    {{/if}}

**Comment by msamoylov** [comment]
A quick and dirty workaround:

**job_create.js**


    Template.jobCreate.helpers({
        responsibilities: function() {
            var formData = AutoForm.getFormValues('insertJobForm');
            return formData.insertDoc.responsibilities || [];
        }
    });

**job_create.html**

    {{# if responsibilities}}
        <h3>Responsibilities</h3>
        {{responsibilities}}
    {{/if}}

But, there's a problem. The last entered responsibility is not displayed for some reason. It looks like a reactivity issue.

**Comment by aldeed** [comment]
Which input type is used? I tried with the default "select-multiple" input type and it seems to work fine. It will be easier to debug if you set up a reproduction in a cloneable repo or a MeteorPad.

**Comment by msamoylov** [comment]
An example is https://www.meteorgigs.io/jobs/new

Try adding "Test 1" and "Test 2" as responsibilities (click "Show extra details" first). You'll see only "Test 1" at the preview tab.

Maybe [my template helper](https://gist.github.com/msamoylov/858ccd681435850b7d6e#file-job_create-js-L39) is totally wrong? I guess so.

* forms.js: https://gist.github.com/msamoylov/6e9e69fa53afb0fffd50
* job_create.html: https://gist.github.com/msamoylov/670e7d405422510d5c61
* job_create.js: https://gist.github.com/msamoylov/858ccd681435850b7d6e
* _job_form.html: https://gist.github.com/msamoylov/5eea2be85d980e6f41f7
* _job_preview.html: https://gist.github.com/msamoylov/38f0957fff1553f063ce

**Comment by dukye** [comment]
Hello,

Found this issue when i was searching function tips for firstOption properties.

I have tried to apply those changes related to commit (9 days) following this comment : 
"**Compatibility break:** The function signature for `AutoForm.getFieldValue` is reversed from `(formId, fieldName)` to `(fieldName, [formId])` with `formId` optional. You should not pass the `formId` argument when using it in a helper that is run within the context of the form."

So i put in my own code : 
Case 1 : val = AutoForm.getFieldValue(fieldName, formId); // NOT WORKING reactivity problem
Case 2 : val = AutoForm.getFieldValue(fieldName); // WORKING :)

Is that normal ?

Thx Eric
duke
