### ISSUE TITLE
Updating only only some fields with a method

### ISSUE THREAD

**Issue by steph643** [aldeed/meteor-autoform#626]
I have the following schema:
```
Projects = new Meteor.Collection('projects');

Projects.schema = new SimpleSchema({
    title: { type: String },
    creationDate: { type: Date }
});

Projects.attachSchema(Projects.schema);
```
and the following form, to update only the title, not the creation date:
``
`
{{#autoForm id="updateProjectForm" collection="Projects" doc=project validation="keyup"  
                 type="method" meteormethod="Projects.mutate.update"}}
    {{> afQuickField name="title"}}
    <button type="submit" class="btn btn-primary">Submit</button>
{{/autoForm}}
```
This leads to the following error (`onError` hook):
```
pre-submit validation error: 
Error: Creation date is required 
{invalidKeys: Array[4], stack: (...), message: "Creation date is required"}
```
I guess it makes sense: the schema states that there should be a creationDate. But how could I tell autoform I just want to update the title?

**Comment by jgladch** [comment]
The way you've written your schema, creationDate is not optional. You have may options to resolve this:
- make that field optional
- write an autoValue function to insert or update the creationDate field. See: https://github.com/aldeed/meteor-simple-schema#autovalue
- add that field in your app code (probably in your Projects.mutate.update method)
- there are probably other ways as well. I suggest autoValue.
