### ISSUE TITLE
Disable the submit button when validation has failed (validation="keyup")

### ISSUE THREAD

**Issue by steph643** [aldeed/meteor-autoform#627]
I have an update form containing input fields with validation="keyup".
In this case, I think the user expects the submit button to remain disabled as long as an error message is displayed in the form.
Is there a simple way to achieve that?

**Comment by aldeed** [comment]
I think something like this would work:

```js
Template.myTemplateContainingMyAutoForm.rendered = function () {
  this.autorun(function () {
    if (AutoForm.getValidationContext(formId).isValid()) {
      // enable submit button
    } else {
      // disable submit button
    }
  });
};
```

This uses [isValid](https://github.com/aldeed/meteor-simple-schema#validating-an-object) from the simple-schema pkg, which is reactive.

**Comment by steph643** [comment]
Thanks!
