### ISSUE TITLE
disabled, required field with value stops the form from submitting

### ISSUE THREAD

**Issue by davidworkman9** [aldeed/meteor-autoform#628]
This, if a required field will prevent a form from being submitted, even though it has a value. Taking the disabled attribute off the element allows the form to be submitted.
```
{{> afQuickField name='widgetId' options=widgets disabled=true value=widgetId}}
```

**Comment by aldeed** [comment]
That's how form submission works. Disabled fields are not included. If you make it readonly=true instead, then it is included. Reference: http://www.w3.org/TR/html5/forms.html#constructing-the-form-data-set
