### ISSUE TITLE
Input type "tel" (telephone number)

### ISSUE THREAD

**Issue by Kestanous** [aldeed/meteor-autoform#629]
I am not seeing a phone number input option and I was wondering if anyone has done / is trying to build this? If not I can add a PR to my TODO ^_^

This is what my scheme has (using quickForm):
```js
phoneNumber: {
  type: Number,
  min: 9,
  max: 10,
  autoform: {
    afFieldInput: {
      type: "tel"
    }
  }
}
```

**Comment by Kestanous** [comment]
To clarify I am thinking something more like: http://www.bootply.com/wxb2AFyOnR

Also its worth noting that I am using the [semantic-ui](https://github.com/JamesLefrere/meteor-autoform-semantic-ui/) version but I am happy to handle that port.

**Comment by Kestanous** [comment]
Ach looks like I overlooked: ctjp:autoform-intl-tel-input. It is broken but thats what I was looking for.

**Comment by funkytaco** [comment]
@Kestanous  did you ever create an autoform template for semantic-ui?

**Comment by funkytaco** [comment]
Oh nevermind, I found https://atmospherejs.com/fabienb4/autoform-semantic-ui
