### ISSUE TITLE
Attribute "readonly" not working in afQuickField

### ISSUE THREAD

**Issue by steph643** [aldeed/meteor-autoform#630]
This does not work - input field is not readonly:
```
{{#autoForm ... type="method" meteormethod="Projects.mutate.update"}}
    {{> afQuickField name="title" readonly="readonly"}}
{{/autoForm}}
```
This does not work - input field is not readonly:
```
{{#autoForm ... type="readonly"}}
    {{> afQuickField name="title" readonly="readonly"}}
{{/autoForm}}
```

**Comment by aldeed** [comment]
Boolean props need to be set to boolean, unlike with normal HTML. `readonly=true`

**Comment by steph643** [comment]
Works like a charm, thanks!

I did not see this in the doc but maybe I missed it. If it is not there, I suggest replacing:

> Any additional attributes are passed along to the generated DOM element, meaning that you can add class, etc. You can also use this feature to set default values for inputs by supplying a value attribute.

by:

> Any additional attributes are passed along to the generated DOM element, meaning that you can add class, etc. You can also use this feature to set default values for inputs by supplying a value attribute. When using the readonly attribute, pass it as a boolean (readonly=true or readonly="true").
