### ISSUE TITLE
Autoform/Collection2/SimpleSchema security

### ISSUE THREAD

**Issue by aadamsx** [aldeed/meteor-autoform#631]
I use Autoform/Collection2/SimpleSchema in my project.  I have removed the insecure/autopublish packages and have allow/deny hooks in place.

I keep reading that allow/deny hooks are not secure enough, and that meteor methods should be used instead (specially for inserts).

As an example, this article point out that meteor methods are superior: 

``` https://www.discovermeteor.com/blog/meteor-methods-client-side-operations/ ```

In the conclusion section he states, "even when using something like the excellent ```Collection2``` package to help enforce a schema and reject invalid writes, there's just too much that can go wrong when trusting the client."

My questions are:

(1) What support does AF/C2/SS have for using meteor methods?

(2) What is your take on using meteor methods over allow/deny and vis-versa?

(3) If it's possible to use meteor methods with AF/C2/SS, are there examples you recommend following?

**Comment by aldeed** [comment]
One of my goals with collection2 pkg in particular was to make client side database operations perfectly safe. I'd say it's 98% there. There are still some loopholes and a bug or two for certain types of fields, but as long as any custom validation functions and autoValues are written well, it's pretty darn secure. If you combine it with allow/deny (actually I recommend ongoworks:security pkg instead) to prevent untrusted code changing anything that's mission critical, then it's 100% secure.

Keep in mind that a client side insert/update is simply calling a built-in server method behind the scenes.

Which is not to say that I never use server methods. If there's tricky, secure logic, it's often easier to lock down an entire collection from untrusted code, and then handle everything in a method. Also, methods are currently the best way to ensure that complex relationships between collections are properly linked (although collection-hooks pkg can help with that, too).

C2/SS work fine on both client and server. AutoForm can submit to methods. So I'd say your decision should not be affected by using any of those pkgs. [This recent DM post](https://www.discovermeteor.com/blog/meteor-pattern-two-tiered-methods/) shows how to use autoform with method submission.

**Comment by aadamsx** [comment]
Thank you for the feedback!

**Comment by Pushplaybang** [comment]
This was definitely a concern for me as well, I've been using methods up until now over allow / deny and validating everything on the server,  thanks for the great packages and the info.

**Comment by rustanacexd** [comment]
Thanks for this!
