### ISSUE TITLE
Using Meteor.users collection with Quickform

### ISSUE THREAD

**Issue by vertangelx** [aldeed/meteor-autoform#632]
I'm trying to use `quickForm` to edit a user's fields stored in the `users` collection created by `accounts-base`.

Why does the following give an error?

	{{> quickForm collection="Meteor.users" doc=profile id="profileUpdateForm" type="update" omitFields="createdAt" buttonContent="Save Changes"}}

with template helper
  
	Template.editProfile.helpers({
		profile: function () {
			if(Meteor.user())
				return Meteor.user()
		}
	});

The error is

     Uncaught Error: users is not in the window scope

**Comment by jgladch** [comment]
Have you attached a schema to your users collection?

See: https://github.com/aldeed/meteor-collection2#attach-a-schema-to-meteorusers

**Comment by vertangelx** [comment]
Works, thank you.

**Comment by vertangelx** [comment]
@jgladch I tried attaching the schema to `Meteor.users`, but now `accounts-base` packages are no longer working! Logging in from my iOS 8 app causes an `Internal server error`:

	=> App running at: http://localhost:3000/
	I20150116-18:36:48.921(8)? Exception while invoking method 'login' MongoError: '$addToSet' is empty. You must specify a field like so: {$mod: {<field>: ...}}
	I20150116-18:36:48.960(8)?     at Object.Future.wait (/Users/username/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:326:15)
	I20150116-18:36:48.960(8)?     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
	I20150116-18:36:48.961(8)?     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:634:1)
	I20150116-18:36:48.961(8)?     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:574:1)
	I20150116-18:36:48.961(8)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:159:1)
	I20150116-18:36:48.961(8)?     at Object.Accounts._insertHashedLoginToken (packages/accounts-base/accounts_server.js:622:1)
	I20150116-18:36:48.961(8)?     at Object.Accounts._insertLoginToken (packages/accounts-base/accounts_server.js:633:1)
	I20150116-18:36:48.961(8)?     at loginUser (packages/accounts-base/accounts_server.js:214:1)
	I20150116-18:36:48.962(8)?     at attemptLogin (packages/accounts-base/accounts_server.js:280:1)
	I20150116-18:36:48.962(8)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:436:1)
	I20150116-18:36:48.962(8)?     - - - - -
	I20150116-18:36:48.962(8)?     at Object.toError (/Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
	I20150116-18:36:48.963(8)?     at /Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:542:27
	I20150116-18:36:48.964(8)?     at /Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1129:7
	I20150116-18:36:48.964(8)?     at /Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1843:9
	I20150116-18:36:48.964(8)?     at Server.Base._callHandler (/Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
	I20150116-18:36:48.964(8)?     at /Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
	I20150116-18:36:48.964(8)?     at [object Object].MongoReply.parseBody (/Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
	I20150116-18:36:48.964(8)?     at [object Object].<anonymous> (/Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
	I20150116-18:36:48.965(8)?     at [object Object].emit (events.js:95:17)
	I20150116-18:36:48.965(8)?     at [object Object].<anonymous> (/Users/username/.meteor/packages/mongo/.1.0.11.7qrspe++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)

Any ideas?

**Comment by jgladch** [comment]
Please refer to: https://github.com/aldeed/meteor-collection2#attach-a-schema-to-meteorusers

Your schema needs to match the fields used by accounts-base. There is a rough outline in the link. If you are using other accounts packages, you may need to add additional fields.
