### ISSUE TITLE
custom field for array of object?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-autoform#635]
I would like custom field for array type like
```js
// Schema
    products: {
        type: [Object]
    },
    "products.$.name": {
        type: String
    },
    "products.$.qty": {
        type: Number
    },
    "products.$.price": {
        type: Number
    }

// Form
{{#each afArrayField="products"}}
   {{> afQuickField name=name}}
   {{> afQuickField name=qty}}
   {{> afQuickField name=price}}
{{/each}}
```

**Comment by aldeed** [comment]
There are ways to do it. You can use [afEachArrayItem](https://github.com/aldeed/meteor-autoform#afeacharrayitem) directly or use it within a custom template for `afArrayField`. See the built-in `afArrayField` template and copy that as your starting place.

**Comment by yuomtheara** [comment]
thanks, could you example? because i don't understand to putting (+) for add more / (-) for remove.

**Comment by vishim** [comment]
I dont understand how tp put + and -; Is there an example which I can follow?
Thanks
