### ISSUE TITLE
Update-form elements has rendered 5 times?

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#638]
```javascript
      if (this.name === 'testField') {
        console.log(this);
      }
```
I just has inserted this code here:
https://github.com/aldeed/meteor-autoform/blob/master/templates/bootstrap3/bootstrap3.js#L57

**Comment by aldeed** [comment]
It can rerender multiple times due to different things reactively updating. I'm always looking out for ways to reduce unnecessary reactions, but other than that, there's nothing to be done here.

**Comment by comerc** [comment]
Yes. It is big problem for reactive vars.

**Comment by lgandecki** [comment]
@aldeed 

Any ideas on how could someone try to help with this?
I'm digging into this currently. I update one field like this using mongodb:
``` db.rtiForms.update({_id: "N862YaXjeyknkne7c"}, {$set: {"scores.0.individualScore": "13"}}) ```

And the field reloads 11 (sic!) times and completes within 3 seconds (sic! again). this makes end-to-end tests super slow, and/or breaking. Also, this practically makes autosave on keyup non working - when you type, the field constantly gets reverted to one of the earlier updates. 

This gets worse and worse (meaning - more reloads) when adding more complexity/data to the collection /document (more fields, as long as they are not empty)

I've spent many hours on this already and will be putting some more - for our non-profit organization this is a matter of using this tool or writing a new one. We would prefer to use this one, and contribute.. but we need keyup saves. And tests. :)

I put a log inside:

``` Template.autoForm.helpers({
  atts: function autoFormTplAtts() {}) ```

So I know that the autoForm reloads just once.

Now, I hacked Template.afQuickField.helpers like so:

``` Template.afQuickField.helpers({
  isGroup: function afQuickFieldIsGroup() {
    if (this.name === "scores.1.targetScore") {
      var _date = new Date();
      console.log("reloading targetScore isGroup", _date.toISOString());
    }
    
    var _name = this.name.split(".");
    if (_name.length === 2) {
      return true;
    } else {
      return false;
    }
  },
  isFieldArray: function afQuickFieldIsFieldArray() {
    if (this.name === "scores.1.targetScore") {
      var _date = new Date();

      console.log("reloading targetScore isFieldArray", _date.toISOString());
    }
    var _name = this.name.split(".");
    if (_name.length === 1) {
      return true;
    } else {
      return false;
    }
  }, ```

to keep the form to display and update correctly, but to get rid of anything possibly reactive in those helpers. They still rerun multiple times. 
Something is making those helpers (or the whole afQuickField template) to reload. 
But I'm running out of ideas...
