### ISSUE TITLE
Default (date) values in form

### ISSUE THREAD

**Issue by mkarliner** [aldeed/meteor-autoform#64]
This may well be a case of my inability to read documentation, but I can't see an obvious way to have pre-set values show in an auto form. Obviously, the autoValue allows me to set a value before the actual insert, but I just want a default value to show in the form. Specically, I have a Date object in my schema which I would like to show up as a data selector, pre-set to today.

**Comment by aramk** [comment]
This is great for setting more obscure default values on the client instead of using `defaultValue`:
```
Template.projectForm.helpers
  startDate: -> @doc?.startDate ? getDefaultStartDate().toDate()
  endDate: -> @doc?.endDate ? getDefaultStartDate().add(1, 'week').toDate()
```
