### ISSUE TITLE
Boolean value returned as String

### ISSUE THREAD

**Issue by jarkelen** [aldeed/meteor-autoform#642]
I have a Boolean field defined:

    project_type: {
        type: Boolean,
        label: "Project type",
        autoform: {
           type: "boolean-radios",
           trueLabel: "Detailed",
           falseLabel: "Simple",
           value: false
        }
    }

And the form field is defined:

    {{> afQuickField name='project_type'}}

But when I look in the generated HTML, `true` and `false` are defined as strings:

    <input type="radio" value="false" name="project_type" required="">

And when submitting the form I receive an error:

    Match error: Expected boolean, got string in field project_type

**Comment by aldeed** [comment]
Please include a link to a [MeteorPad](http://meteorpad.com/) or an app in a public repo that reproduces this issue.
