### ISSUE TITLE
wrap over xautocomplete for AutoForm

### ISSUE THREAD

**Issue by miguelalarcos** [aldeed/meteor-autoform#643]
Hi, I just wanted you to know that I have released [miguelalarcos:afwrap-xautocomplete](https://github.com/miguelalarcos/afwrap-xautocomplete/).

You can use _ids to reference other collections. Example:
```html
{{> afFieldInput  type='xautocomplete' formid="1" name='authorsId' call='authors' xmultiple='true' reference='authors' valuefunction='valueAuthors' renderfunction='renderAuthors'}}
```

**Comment by miguelalarcos** [comment]
...and just released the package [afwrap-xdatetime](https://github.com/miguelalarcos/afwrap-xdatetime). This is a datetime widget picker for AutoForm. Both are intented to be used with semantic-ui.

Thanks for your attention.

**Comment by aldeed** [comment]
Thanks @miguelalarcos! I added them to the "Community Add-On Packages" section of the readme.
