### ISSUE TITLE
Autosave - it blocks the interface

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#645]
we need to perform it in the background

**Comment by aldeed** [comment]
It's a form submission so I don't think there's any way to do it differently. Please provide a reproduction of the issue if you still think something needs to be fixed.

**Comment by comerc** [comment]
Some tricks: https://github.com/oortcloud/unofficial-meteor-faq#how-do-i-animate-things-addingbeing-removed-from-collections

**Comment by devinmooers** [comment]
Is there any trick to get autosave working on a textarea? Currently, it submits the form and defocuses the textarea you're editing, breaking you off mid-typing. Super bad user experience for textareas. How does Gmail / Google Docs do it? They have really slick autosave that's totally transparent.

**Comment by devinmooers** [comment]
Or would contenteditable maybe work?

**Comment by devinmooers** [comment]
Oh! `resetOnSuccess=false` did the trick. Nice!
