### ISSUE TITLE
select with multiple option was not cleared when reset a form at autoform version 4.2.2

### ISSUE THREAD

**Issue by tkang007** [aldeed/meteor-autoform#648]
Hello friends,
I would like to report an issue about reset form function for select with multiple opiton.
It was happen at version 3.5.1, is there any workaround ? 
I appreciate your contribution for this nice packages.

**Comment by tkang007** [comment]
Updated this case version to 4.2.2

**Comment by aldeed** [comment]
Seems to be working in 5.0, which is not yet released.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
