### ISSUE TITLE
AutoValue example for userId

### ISSUE THREAD

**Issue by ccorcos** [aldeed/meteor-autoform#649]
It would be great if you gave an example of how to assign an owner to a document using autoValue and not displaying it in the quickForm:

```
  ownerId:
    type: String
    autoValue: -> @userId
```

How do I hide it from showing up in the form?

**Comment by aldeed** [comment]
To omit it from one quickForm, you can do `omitFields="ownerId"` on that quickForm. To omit from all, you can do this in the schema:

```js
{
  autoform: {
    omit: true
  }
}
```

Also, that `autoValue` is maybe a little too simplistic. It will add `userId: id` on insert, but it will also add `{$set: {userId: id}}` to every single update you do, and if you do an update from server code, `@userId` will be `null` so it will actually do `{$set: {userId: null}}` and clear out the ownerId (or make the update fail if ownerId is required).
