### ISSUE TITLE
User Profile Insert/Update Form

### ISSUE THREAD

**Issue by nicholasalanbrown** [aldeed/meteor-autoform#650]
Hello:

Really terrific package. I finally got it working as an update form for user profile fields as below:
```
{{#autoForm collection="Meteor.users" doc=current id="profileForm" type="insert"}}
      {{> afObjectField name='profile'}}
      <button type="submit" class="btn btn-primary">Update</button>
{{/autoForm}}
```
and my profile.js:
```
Template.usersProfile.helpers ({
  	current: function () {
    return Meteor.user();
  }
});
```

When I have profile fields that already have data in the user document, they populate the form fields and I can update them without trouble (though I still get 'Update Error' using the suggested before hooks in the console for some reason).

I have two questions:

1. I can't get it to insert profile fields if I change the type to "insert." Is that because it sees there's already a user object? This happens even if I clear the other data in the form that was prepoputed.

2. Can someone post a concrete example of creating a combo insert/update form? It's a pretty common use case I think - you show a user the profile fields they've set already and allow them to update them, or if they're blank, you allow them to fill them out. There's some mention of this is the FAQ, but it's far too vague for me as a noob to follow. Help?

**Comment by nicholasalanbrown** [comment]
I take it back - the form doesn't actually update anything. It prepopulates real data from the database, but I still get an "Update Error" in the console using the following code:
```
AutoForm.addHooks(['profileForm'], {
    before: {
      insert: function(error, result) {
        if (error) {
          console.log("Insert Error:", error);
          AutoForm.debug();
        } else {
          console.log("Insert Result:", result);
          AutoForm.debug();
        }
      },
      update: function(error) {
        if (error) {
          console.log("Update Error:", error);
          AutoForm.debug();
        } else {
          console.log("Updated!");
          console.log('AutoForm.debug()');
        }
      }
    }
  });
```

I'm still not sure where the ```AutoForm.debug();' method is supposed to go to get more detail in the console...

**Comment by aldeed** [comment]
"insert" and "update" refer to the document level, not the subdocument. You only need an update form because the user document already exists. It doesn't matter whether a `profile` object exists yet. Either way it's an `update` operation.

Call `AutoForm.debug();` just one time, anywhere in client code, or in your browser console before you submit the form. It just needs to be called once to activate debug mode.

Beyond that, you'll have to post the update error to get more help.

**Comment by jLouzado** [comment]
Oh so what I've been doing is:

    <template name="AboutMe">
      {{#if exists}}
        {{> updateProfileForm}}
      {{else}}
        {{> insertProfileForm}}
      {{/if}}
    </template>

are you saying that that's not necessary? because for an `update` operation you need to provide a document to the `doc` option and I'm not sure what that would be for the `insert` operation.

**Comment by rwcatalano** [comment]
Here is how I am doing it on http://dibbs.io.  Notice that both typeAction and docAction in the autoForm declaration are both helpers... that is important.

<pre>
<template name="edit_profile">
{{#autoForm collection="UserProfile" type=typeAction doc=docAction id="my_profile" }}
    {{clearErrors}}
    {{> afQuickField name="firstName"}}
    {{> afQuickField name="lastName"}}
    {{> afQuickField name="birthdate"}}
    {{> afQuickField name="postalCode"}}
    {{> afQuickField name="phoneNumber"}}
    &lt;button type="submit" class="btn btn-success"&gt;Submit&lt;/button&gt;
{{/autoForm}}
</template>
</pre>

Next in the .js wire the helpers in to return your action (insert or update) and the document:

<pre>
Template.edit_profile.helpers({
   'typeAction': function(){
       var a = "insert";

       if(Session.get("myCurrentUserProfile"))
            a = "update";

       return a;
   },

    'docAction': function(){
        //the result of a mongodb query that I saved to a session variable
        //this was the original query: UserProfile.findOne({ownerId: Meteor.userId()});
        var a = Session.get("myCurrentUserProfile");
        return a;
    }
});
</pre>
