### ISSUE TITLE
Crash on umlauts

### ISSUE THREAD

**Issue by obiwarn** [aldeed/meteor-autoform#651]
From my Schema (it is used for a Select):

           autoform:
                firstOption: TAPi18n.__('payChooseMethod')

When the payChooseMethod string translation contains German Umlauts (ä, ö, ü) it crashes.

**Comment by aldeed** [comment]
What crashes? Can you provide an error message and/or reproduction?

**Comment by aldeed** [comment]
I can't reproduce this. umlauts work fine for me.

**Comment by obiwarn** [comment]
The TAPi18n update seems to have removed the issue.
Thanks!
