### ISSUE TITLE
How to pass arguments to autoform?

### ISSUE THREAD

**Issue by czeslaaw** [aldeed/meteor-autoform#653]
Is there a some way to pass arbitrary arguments to autoform and then access them from hooks or meteor methods?

Something like this:

```
{{#autoForm collection="Comment" id="CommentForm" type="insert" params=myParams}}
 {{/autoForm}}
```
Then in hooks I could perhaps do something like this:
```
AutoForm.hooks({
  CommentForm:{
    formToDoc: function(doc, autoform){
      var params = AutoForm.instance().params;
      // or
      var params = autoform.params;
       // or something similar
    }
  }
})
```
The only way i manage to do this is to put hidden field in form but that is pretty ugly.

**Comment by aldeed** [comment]
In most hooks, `this.template` is available, so I think `this.template.data.params` would work. I don't remember if it's available in `formToDoc`, but it probably could be added.

The next release of AutoForm will have a function for getting the form's data context by formId, too.

**Comment by czeslaaw** [comment]
Thanks for fast answer.

Your solution works fine for strings and numbers but throws error when i pass object. Autoform component try to add this extra field as a html attribute but it can't parse object.

Having extra white list keyword like 'params' or 'arguments' here would be nice. I tried this on version 3.2.0 but it probably didn't change.

**Comment by aldeed** [comment]
Good point.

You could cache your own extra params in an object keyed by formId.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.

**Comment by derdaumen** [comment]
Do I understand correct that with version 5.0.0 it is now possible to pass an object as a parameter to afQuickField which is then available in my custom template? Something like this:
```HTML
{{> afQuickField name='someName' template='specialTemplate' object=someObject}}
```
and in my template
```HTML
<template name="afFormGroup_specialTemplate">
{{object.field}}
...
```
I'm getting this error when I do that:
```
Error: Unexpected object in htmljs in toText: [object Object]
 at HTML.ToTextVisitor.def.visitObject (visitors.js:240)
    at HTML.Visitor.def.visit (visitors.js:61)
    at Object.HTML.toText (html.js:259)
    at Object.Blaze._toText (view.js:720)
    at updateAttributes (materializer.js:129)
    at view.js:191
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at view.js:190
    at Object.Blaze._withCurrentView (view.js:523)
    at viewAutorun (view.js:189)
```
