### ISSUE TITLE
Populate Value Data & Autosave Using Type Meteor?

### ISSUE THREAD

**Issue by voidale** [aldeed/meteor-autoform#654]
I really need help with this one, I'm trying to do this for 2 days now and can't seem to find examples to help me.

I'm trying to create autoform using meteormethod (to skip the hassle of allow/deny) with the intent to update the database values. So I want to show the values inside inputs and autosave them so this form won't have any submit buttons.

How my collection looks:
````
{
 _id:  2,
 userId: 123,
 channels: [ 
  {name: "channel1", inventorySync: false, inventoryMaxqty: 0, inventoryMinQty: 0},
  {name: "channel2", inventorySync: false, inventoryMaxqty: 0, inventoryMinQty: 0}
 ]
}

````
Schema:
````
channels = new Meteor.Collection('channels');
channelsschema = new SimpleSchema({
  channels: {
    type: [Object],
    minCount: 1
  },
  "channels.$.name":{
      type: String,
      autoform: {
          omit: true
      }
  },
  "channels.$.inventorySync": {
    type: Boolean,
    label: "inventoryBoratSync"
  },
  "channels.$.inventoryMaxQty": {
    type: Number,
    label: "inventoryMaxQty",
    min: 0,
    max: 999
  },
  "channels.$.inventoryMinQty": {
    type: Number,
    label: "inventoryMinQty",
    min: 0,
    max: 999
  }
});
channelsschema.debug = true;
````
Autoform code:
````
  {{#autoForm collection="channels" id="insertBookForm" schema="channelsschema" doc=doc type="method" meteormethod="ChannelSettings"}}
    <fieldset>
        <h4><strong>Inventory Sync</strong></h4>
        <p>Automatically update your product listings quantities to match "Available" inventory</p>
      {{> afQuickField name='channels.$.inventorySync'}}
        <p>Set maximum quantity per item to </p>
      {{> afQuickField name='channels.$.inventoryMaxQty'}}
        <p>Set minimum quantity per item to</p>
      {{> afQuickField name='channels.$.inventoryMinQty'}}
    </fieldset>
  {{/autoForm}}
````
For doc data I tried:
````
Router.route('/channels/:_name', {
  name: 'channelPage',
  template: 'channelPage',
  waitOn: function() {
    return Meteor.subscribe('channelSettings', this.params._name);
  },
  data: function() {
      return channels.find({'channels.name':  this.params._name});
  }
});

or 

Template.channelPage.helpers({
    doc: function(){
        return channels.findOne();
    }
});

````

a) This won't populate the values what am I doing wrong? Should I manually set the value for each `afQuickField` 
b) about `autosave` I got no idea if this possible for meteor method or I must use `type update`? 

I also do not want the form to show the array inputs (+ -) as this settings per 1 channel only. In anyway it looks like my use case of autoform is not very popular or I'm doing it wrong? I will really appreicate some help with this one. Thank you!

**Comment by aldeed** [comment]
You can't use the "$" placeholder to generate a field. The names should be for example "channels.0.inventoryMaxQty" or whichever array index you are updating.

I think autosave is currently limited to update forms, but it should work with method forms when autoform 5.0 is released.
