### ISSUE TITLE
Invalid key passes submit

### ISSUE THREAD

**Issue by vladblindu** [aldeed/meteor-autoform#657]
I warned you I'm going to bother you again:)
I  have a field that confirms the password in an auto form that submits to a method that should insert a new user with Accounts password. (I am validating against a SimpleSchema, not the collection)
```
pass_again:{
		type: String,
		label:"Confirm Password",
		optional: false,
		custom: function(){
			if(this.value !== this.field("password").value){
			   UsersSimpleSchema.namedContext("adminContext").addInvalidKeys([{name: "pass_again", type: "noPassMatch", }]);
			}
		}
	},
```
I customised an error message :
```
UsersSimpleSchema.messages(
	{
		noPassMatch:"Passwords do not match"
	}
);
```
The problem is that the form gets submitted and doesn't behave as the other errors that prevent it and show up under the input field.
What am I missing?
Thank you for your time.

**Comment by aldeed** [comment]
Instead of the `addInvalidKeys` line, do `return "noPassMatch"`. The invalid key you're adding isn't part of the same validation run, so SS doesn't know about it.
