### ISSUE TITLE
Unable to submit update form

### ISSUE THREAD

**Issue by nicholasalanbrown** [aldeed/meteor-autoform#658]
Hello:

I'm reposting after following your advice about running ```AutoForm.debug();`. When doing so, it just says ```undefined```. I've attached a screenshot with the output after attempting to submit the form, which I changed to ``type:update```.

![screen shot 2015-01-22 at 8 20 47 pm](https://cloud.githubusercontent.com/assets/3259022/5868248/e38b1ab0-a274-11e4-83b7-16301bf2caaa.png)

**Comment by aldeed** [comment]
Not enough info here. Add an `onError` hook to your form and see what error is provided. Post a reproduction if possible.
