### ISSUE TITLE
AutoForm.getInputValue returns wrong value for Boolean inputs

### ISSUE THREAD

**Issue by dkoo761** [aldeed/meteor-autoform#659]
When using autoform to render a Boolean checkbox input (ie. via quickForm, afQuickField or afFieldInput), there is no problem.

However, we need to customize the label next to the checkbox, so instead of using afFieldInput to render the Boolean checkbox input, we are rendering it as follows directly in the form:

```html
<div class="checkbox">
    <label>
        <input type="checkbox" id="agreeToTerms" value="false" name="agreeToTerms" data-schema-key="agreeToTerms">
        Agree to the <a href="{{pathFor 'termsAndPolicy'}}">terms and policy</a>
    </label>
</div>
````

It turns out that AutoForm.getInputValue() returns the .val() of the HTML element as the value if no element template (such as afCheckbox) is used to render the element. However, in the case of a Boolean, I think it should return whether or not the element is checked, rather than returning .val() which only returns the value attribute. As a result, the HTML above leads to the wrong behaviour and the form will not validate correctly.

If this is not the right way to customize the label on a checkbox input, is there a better way?

**Comment by aldeed** [comment]
It would be best to create an override template for the "boolean-checkbox" input type.

```html
<template name="afCheckbox_termsLink">
  <div class="checkbox">
    <label>
        <input type="checkbox" value="true" {{atts}}>
        Agree to the <a href="{{pathFor 'termsAndPolicy'}}">terms and policy</a>
    </label>
  </div>
</template>
```

And then specify that template:

```js
{{> afQuickField name="agreeToTerms" template="termsLink"}}
```
