### ISSUE TITLE
Support request: NOW as default value for date field

### ISSUE THREAD

**Issue by theduke** [aldeed/meteor-autoform#660]
My schema has a simple date field which I render in a form with:

{{> afQuickField name='date' type="datetime-local" }}

I need to set the default value to the current date/time,
but I don't see a way right now.

Using defaultValue in the schema, the value would correspond to the time the Schema object is istantiated, right?

Thankful for pointer,
cheers

**Comment by tintoverano** [comment]
hi,

date & time is set when you instantiate the form

````
    createdAt: {
        type: Date,
        defaultValue: new Date(),
        autoform: {
            omit: true
        }
    }
````

cheers,

tinto

**Comment by theduke** [comment]
Thanks.
