### ISSUE TITLE
Non-collection form and method

### ISSUE THREAD

**Issue by n0ne** [aldeed/meteor-autoform#664]
Hi. 
I have strange problem: result in onSuccess or after "myMethodName" always undefined, although on  the server id exists, in the console is displayed, but return(id) from method in hooks always undefined...

**Comment by aldeed** [comment]
It should be whatever you return from your method. If not, you need to provide a reproduction repo or MeteorPad.

**Comment by n0ne** [comment]
Sorry, my mistake. you can close the issue
