### ISSUE TITLE
Validating a required hidden input type

### ISSUE THREAD

**Issue by ksmaingi** [aldeed/meteor-autoform#665]
Hi,

I have created 3 dropdown boxes (for day, month & year) instead of allowing a dateOfBirth field/date field. However, the field is still required, but the validation doesn't seem to fire, which is probably intentional., but I do get an "invalid keys" error. My code is as follows:

```
<div class="form-group">
  <label class="col-sm-3 control-label qformlabel">Date of Birth</label>
  <div class="col-sm-9"  style="height: 44px; margin-left: -15px;">
    <div class="col-xs-3">
      {{> daySelect inputClass="form-control" }}
    </div>
    <div class="col-xs-3">
      {{> monthSelect inputClass="form-control" }}
    </div>
    <div class="col-xs-3">
      {{> yearSelect inputClass="form-control" }}
    </div>
    <span class="help-block"></span>
  </div>
</div>
{{> afFieldInput name="dateOfBirth" type="hidden"}}
```
```
Template.yearSelect.events({
    'change #year': function(e) {
        var dobString = $('#year').val() + '-' + $('#month').val() + '-' + $('#day').val();
        if (moment(dobString).isValid()) {
            $("input[name=dateOfBirth]").val(moment(dobString).format('YYYY-MM-DD'));
        }
    }
});
```
Is there anything I should be doing to automatically display validation or should I roll my own?

**Comment by aldeed** [comment]
Try changing your help block to:

```html
<span class="help-block">{{{afFieldMessage name="dateOfBirth"}}}</span>
```

**Comment by ksmaingi** [comment]
That's great, thank you so much. Is there a simple way to add `has-error` to the div class with `form-group`?

**Comment by aldeed** [comment]
Yeah, you're basically duplicating some stuff that the bootstrap afFormGroup template does, so [take a look at that](https://github.com/aldeed/meteor-autoform/blob/master/templates/bootstrap3/bootstrap3.html#L18-L26).

**Comment by ksmaingi** [comment]
Thank you @aldeed that works very well!
