### ISSUE TITLE
Empty select options in afFieldInput

### ISSUE THREAD

**Issue by mathieutozer** [aldeed/meteor-autoform#667]
The option tags in the select form generated by afFieldInput are empty

` {{> afFieldInput name='majorMusclesWorked' label="Major Muscles Worked" options=muscleGroups}}`

produces

`<option></option>`
`<option></option>`
`<option></option>`
...

There is the correct number of options listed for what is being returned by the muscleGroups helper, which makes me think this is a bug. I reproduced the issue in a tiny app here

https://github.com/mathieutozer/autoformSelectFieldBug

**Comment by aldeed** [comment]
I don't think there's any support for passing in an array of strings as the options. You need to pass array of objects or dictionary object. See [here](https://github.com/aldeed/meteor-autoform#what-are-the-various-ways-i-can-specify-options-for-a-select-radio-group-or-checkbox-group).

**Comment by aldeed** [comment]
But in your case since they match the allowed options, you can also do `options="allowed"`.
