### ISSUE TITLE
Deleting [Object] subdocuments in form

### ISSUE THREAD

**Issue by theduke** [aldeed/meteor-autoform#671]
I have a form with a schema like this: 

```javascript
'images': {
  type: [Object]
},
'images.$.url': {
  type: String
}
```

I have implemented some custom javascript that deletes nested documents from the form, so for example, if there were 2 items in the form, it would initially render like this:

```html
<input type="text" name="images.0.url" data-schema-key="images.0.title" class="form-control" value="xxx">
<input type="text" name="images.1.url" data-schema-key="images.1.title" class="form-control" value="xxx">
```

I then delete the second input with javascript.
When submitting the form, a javascript error pops up: ```Uncaught TypeError: Cannot read property 'type' of undefined```.

Any ideas how to fix this?

**Comment by aldeed** [comment]
I'm not sure. You will have to post a repo or MeteorPad showing what you are doing.

**Comment by theduke** [comment]
Never mind, my fault.
