### ISSUE TITLE
using plain template for an afFieldInput

### ISSUE THREAD

**Issue by ChenRoth** [aldeed/meteor-autoform#672]
hey, 

using the template parameter seems to have no effect on afFieldInput:
```
{{> afFieldInput name="some_field" template="plain" }}
```
it still renders the ```<input>``` with form-control class (i.e. bootstrap)

how do i get a plain ```<input>```? (without customizing a new template!)

**Comment by aldeed** [comment]
What data type is the field?

I just tried this with the devel branch of autoform and it worked fine, so likely the issue is already fixed. You'd have to post the "some_field" schema for me to be able to say with certainty.

**Comment by aldeed** [comment]
OK, I just tested with all of those against the devel branch and there are no issues, so I'm going to assume this is already fixed.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
