### ISSUE TITLE
Update part of array (Do not overwrite whole array) using "update" or "meteor"

### ISSUE THREAD

**Issue by voidale** [aldeed/meteor-autoform#675]
So this kind of a huge limitation I got this collection:
````
{
 _id:  2,
 userId: 123,
 settings: [ 
  {name: "channel1", inventorySync: false, inventoryMaxqty: 1, inventoryMinQty: 0},
  {name: "channel2", inventorySync: false, inventoryMaxqty: 5, inventoryMinQty: 3}
 ]
}
````

I publish just 1 array so my form gets 1 settings array on each page 

` return channels.find({userId: this.userId, 'settings.name': channel}, {fields: {'settings.$': 1}} );`

so I can use this `{{> afQuickField name='settings.0.sync'}}` always index 0.

the problem with `type="update"` you cannot specify what index of array to update, But even if it was possible how the hell can I know the index if I got 20 settings? I didn't find any information on this. So I looked if it was possible to update it by finding the channel name like `settings.name = X` but it's not allowed from the client. So my next step was to try `type="method"` when I submit the form using meteor method I get the following error: `Uncaught TypeError: Cannot read property 'clean' of null autoform-validation.js:18` can't debug this one. Any help with this one? Maybe I should change collection schema?

**Comment by aldeed** [comment]
Usually, I would use a different `schema` and then do the update myself in `onSubmit` hook or method. But in your case, the index will be different on client versus server, so you don't want to do the update on the client anyway. So type="method" sounds right. I won't be able to debug that error without a reproduction of what you're doing. Sounds like maybe you're providing a schema that isn't actually a SimpleSchema instance.

**Comment by voidale** [comment]
@aldeed your clue was enough I had `collection="channels"` in my autoform removed it and it worked fine! Thanks going finally to solve this one I guess :)

**Comment by voidale** [comment]
@aldeed I got weird thing going on after using `type="method"`
How come meteor method `doc` object becomes undefined?

for example
````
  ChannelSettings: function(doc){
      // Important server-side check for security and data integrity
      check(doc, channelsschema);

      console.log(doc);
      console.log(doc.settings.name);
````
console.log(doc) works 
````
	  { settings:                                                                                                                                                                                                               
   [ { name: 'etsy',                                                                                                                                                                                                      
         sync: true,                                                                                                                                                                                                        
         max: true,                                                                                                                                                                                                         
        maxQty: 1,                                                                                                                                                                                                         
        min: false,                                                                                                                                                                                                        
        minQty: 1 } ] }  
````
but the other one not, you can switch the order same thing `doc` works just once sometimes more but I can't use it to change full `.update` call.

**Comment by aldeed** [comment]
Should be `console.log(doc.settings[0].name);`

**Comment by voidale** [comment]
omg. yes indeed! Thank you so much.
