### ISSUE TITLE
Example ContactForm returns: Did not check() all arguments during call to 'sendEmail'

### ISSUE THREAD

**Issue by engenheiro** [aldeed/meteor-autoform#678]
I'm having problems with the example of "ContactForm". After the user complete the form and submite it, the server returns the error: Did not check () all arguments During call to 'sendEmail'.

More details:

I20150208-00:53:48.239(-2)? Exception while invoking method 'sendEmail' Error: Did not check() all arguments during call to 'sendEmail'
I20150208-00:53:48.244(-2)?     at packages/ddp/livedata_server.js:648:1
I20150208-00:53:48.244(-2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150208-00:53:48.244(-2)?     at packages/ddp/livedata_server.js:647:1
I20150208-00:53:48.244(-2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150208-00:53:48.244(-2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150208-00:53:48.244(-2)?     at packages/ddp/livedata_server.js:546:1
I20150208-00:53:48.243(-2)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150208-00:53:48.243(-2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150208-00:53:48.243(-2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)

**Comment by aldeed** [comment]
You probably have the [audit-arguments-checks package](http://docs.meteor.com/#/full/auditargumentchecks) added. Remove it or check all arguments in your method.

**Comment by sunkay** [comment]
@engenheiro I faced the same problem. We have to check all arguments that are passed to the Meteor method call

check this out... http://sunkay.github.io/meteor/2015/02/24/autoform-audit/

see if this solves your problem. Let me know..

**Comment by aldeed** [comment]
Thanks, @sunkay. Note also that in upcoming 5.0, it's changed to pass only one arg to the method:

https://github.com/aldeed/meteor-autoform/blob/devel/CHANGELOG.md#change-log

**Comment by webyak** [comment]
Strange I'm still getting this error with 5.0. I'm using the `method` form type and there's only one argument in `arguments`, which I validate against a Simple Schema. Hmm do you have any idea?

**Comment by webyak** [comment]
Looks like it has to do something with matteodem:easy-security. When I add the method to ignoredMethods it works just fine.

**Comment by MrMegamind** [comment]
for me this worked when i placed the check codde above the insert statement

check([field1,field2], [Match.Any]);
