### ISSUE TITLE
Naïvely customizing form markup

### ISSUE THREAD

**Issue by dalgard** [aldeed/meteor-autoform#679]
It seems I'm running into some trouble with my forms when I try to do a couple of things.

1. If I take the exact markup otherwise output by `> afFieldInput` and insert it inside my `#autoForm` block helper, the form refuses to submit. `beginSubmit` and `endSubmit` are both called but `onError` gives an `expectedBoolean` (or similar) error – is this behavior correct? Is there anything I can do to not use `> afFieldInput`, such as registering my markup with the form somehow?

2. If I customize the output of `> afFieldInput` with jQuery in a `rendered` hook, the form also breaks. Specifically, I want to move some elements around a little and call `template.$(".my-input").dropdown()` or `.checkbox()` or other UI library code.

I'm currently reading up on creating custom inputs and other options, but I'd like to hear your opinion about what is happening in my case, as it may be the easiest way to go. Thanks.

**Comment by aldeed** [comment]
Registering a custom input type is best. It's easy to do.
