### ISSUE TITLE
Confusing validation error with type: [Number] field 

### ISSUE THREAD

**Issue by theduke** [aldeed/meteor-autoform#684]
I have a SimpleSchema which I am using to validate a {{>quickForm}}.

The schema looks like this:

```
...
numbers: {
    type: [Number],
    label: 'Numbers',
    min: 1
  } 
...
```

The form renders fine with the multi-value widget. 
If I input numbers, then validation works fine.
If I input regular strings, I would expect an error message like "needs to be a number" at the individual item.
What I actually get is a `numbers IS REQUIRED` error on the whole multi-value widget.

This is apparently quite confusing, since there is a value entered, just not a valid one.

**Comment by theduke** [comment]
Also, I just noticed, if option: true is set, it is not validated at all, even if not number string values are entered.

**Comment by aldeed** [comment]
Most likely some unwanted filtering going on. You could try `autoConvert=false` and/or `filter=false` attributes on the quickForm.

**Comment by oliversd** [comment]
Similar problem here, I have this in my Schema:

    goal: {
      type: Number,
      min: 1 
     },

When I put a String in the field I get Goal is required message, worst if I put optional: true in the schema and put a String I get no validation. 

I tried to put autoConvert=false and filter=false on the #autoForm with the same results.

Any ideas?

**Comment by aldeed** [comment]
OK, I see what the issue is here. By default `Number` types render with an `input[type=number]` field. But if you enter a string, the browser actually reports it as no value. So autoform has no idea what the user entered, but it appears to be nothing.

So it's a quirk of the HTML5 controls, not a fixable bug. If you don't like it, you can specify the "text" input type instead.

**Comment by AnthonyAstige** [comment]
A message like "[label] is a required number" in the case of undefined fields of type Number may be more clear.  That text somewhat works linguistically for both the case of nothing input, and the case of invalid text which doesn't get passed along.

However I don't see a simple way to achieve this.  I was thinking of a custom error message for just my Number fields, but looks like messages are only defined globally.
