### ISSUE TITLE
How to create labels for each embedded schema item in an array?

### ISSUE THREAD

**Issue by cpalanzo** [aldeed/meteor-autoform#686]
Love Simple Schema and Autoform - so useful - thanks!
I'm creating an operating hours record for customer.
For each of the days of the week I need to know if the store is open, when it opens and for how long.
I created a simple "day_schedule" schema  - then within a top level customer schema I created an array that requires 7 day_schedule schemas - one for each day of the week - fine!
I use a quickform - and all 7 days appear - but I have no way to label them "Sunday" "Monday" etc..
I can label the "day_schedule" object.. but I can't seem to provide a different label for every element in the array. Is there an easy way to do something like this? 
(I'm sure I can come up with some convoluted ugly way.. :)

![screen shot 2015-02-11 at 7 33 33 pm](https://cloud.githubusercontent.com/assets/9503630/6159538/ca0e93ea-b224-11e4-9a03-9be98cd716ad.png)
![screen shot 2015-02-11 at 7 33 50 pm](https://cloud.githubusercontent.com/assets/9503630/6159542/cfcd4114-b224-11e4-9c5f-47d42cfcf70b.png)

**Comment by aldeed** [comment]
I don't think it can be done with a quickForm. You can use a function for `label`, but I don't think the current array index is provided in that function.

The easiest might be to switch to an autoForm and do your own loop since you want exactly 7 anyway.

**Comment by cpalanzo** [comment]
Okay 
Can u point me to an example that would get me started?
C

Sent from my iPhone

On Feb 12, 2015, at 12:25 PM, Eric Dobbertin <notifications@github.com> wrote:

I don't think it can be done with a quickForm. You can use a function for label, but I don't think the current array index is provided in that function.

The easiest might be to switch to an autoForm and do your own loop since you want exactly 7 anyway.

**Comment by cpalanzo** [comment]
Okay... I found your online example with looping and I almost have it - but using autoform in a loop is giving me fits... I can see the three objects - but can't edit them. I'm sure it's something dumb on my part - but since I've returned only a piece of the doc - an internal array - and the schema is using and embedded schema I'm getting lost.

The three operating hours elements of each day as defined in the schema are shown - but I'm not setting up Autoform to edit them in place. ( I've tried a dozen different ways - not just what is here.)

I return the operating_hours array from the doc - for use in the loop and I return the whole doc for use by autoform itself.

![screen shot 2015-02-16 at 4 13 14 pm](https://cloud.githubusercontent.com/assets/9503630/6219444/7949e352-b5f7-11e4-835a-f5f15e66fbc6.png)

![screen shot 2015-02-16 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/9503630/6219443/717fe81a-b5f7-11e4-9467-026ba596119b.png)

I use a Table loop as shown in your online Demo example:

![screen shot 2015-02-16 at 4 13 00 pm](https://cloud.githubusercontent.com/assets/9503630/6219449/857b020a-b5f7-11e4-9693-7e888b38b954.png)

And the result is CLOSE... but no cigar! I see the objects - but am not rendering them as editable fields...

![screen shot 2015-02-16 at 4 12 41 pm](https://cloud.githubusercontent.com/assets/9503630/6219451/978d6578-b5f7-11e4-9da6-91d040337c2e.png)

**Comment by aldeed** [comment]
That's not quite what I meant. I think you can have a single `autoForm` with an `each` loop within that. In pseudo markup it would be something like:

```
#autoForm
  #each day
    <div class="day-label">{{name}}</div>
    {{> afQuickField name=fieldName label=false}}
  /each
/autoForm
```

Where your `day` helper returns

```js
return [
  {name: 'Sunday', fieldName: 'operating_hours.0'},
  {name: 'Monday', fieldName: 'operating_hours.1'},
  // etc...
];
```
