### ISSUE TITLE
More flags that reflect form state, such as dirty, pristine, etc.

### ISSUE THREAD

**Issue by jcheroske** [aldeed/meteor-autoform#689]
I find myself wanting the same level of information from AutoForm that I had available in Angular. It has dirty, pristine, valid, invalid, touched, and untouched flags at the field level. At the form level it has dirty, pristine, valid, invalid, and submitted. Check out their form docs for more info: https://docs.angularjs.org/guide/forms. The AutoForm + SimpleSchema architecture is superior, imho, to Angular for two reasons: 1) SimpleSchema captures the validation rules in one place, and 2) Since the code runs on the client and server there's no need to write validation code twice. But, as it currently stands, there is less information available about form state available to the AutoForm developer.

**Comment by aldeed** [comment]
Seems to duplicate your comment in #548. We can track and discuss there.
