### ISSUE TITLE
Changing input error validation style

### ISSUE THREAD

**Issue by ErmosK** [aldeed/meteor-autoform#694]
I noticed that the error message appears on the bottom of the input box (for bootstrap) but I was wondering if there is a way that I can use bootstrap popover to show the error message in a popover instead of under the input box.

**Comment by aldeed** [comment]
You can make a custom afFormGroup theme template

https://github.com/aldeed/meteor-autoform#theme-templates

**Comment by aldeed** [comment]
You can put `{{afFieldMessage name='foo'}}` anywhere within an `autoForm` block, but currently you cannot put it outside of the `autoForm` block. If you need the message outside of the form, you could use simple schema directly by making a helper that displays `MyFormSchema.namedContext('formId').keyErrorMessage(fieldName)`
