### ISSUE TITLE
CheckBoxes

### ISSUE THREAD

**Issue by engenheiro** [aldeed/meteor-autoform#695]
Hello, I having problems to setup a field checkbox based on your demo: http://autoform.meteor.com/types

Also unable to set the fields to "checked" for default and give a css class for them.

Missing tips in the documentation on this issue, including on radio buttons.

**Comment by aldeed** [comment]
`value=true` attribute will set them checked. `class="class"` will add classes.

**Comment by engenheiro** [comment]
Thanks!
