### ISSUE TITLE
Placeholders instead of labels

### ISSUE THREAD

**Issue by VladShcherbin** [aldeed/meteor-autoform#699]
Currently, we have to create our own templates or specify the placeholder in html to get rid of labels and use placeholders. It would be awesome to specify this in schema - to use labels or placeholders.

As 5.0 is coming, maybe it can be added in release version.

**Comment by aldeed** [comment]
It's already possible to put any component attribute in the `autoform` object of the schema:

```js
{
   name: {
      type: String,
      autoform: {
         label: false,
         placeholder: "schemaLabel"
      }
   }
}
```

**Comment by VladShcherbin** [comment]
@aldeed thank you a lot! didn't find it in the docs..

**Comment by aldeed** [comment]
For posterity: https://github.com/aldeed/meteor-autoform#putting-field-attribute-defaults-in-the-schema

Will create a better docs site someday.

**Comment by VladShcherbin** [comment]
@aldeed huge thank you! I tried to read the docs for your 3 awesome packages (simple form, collection 2, autoform) from top to bottom. They are really big and impressive. Didn't pay big attention to that small section.

Maybe you can add this example with placeholders in the demo page - it is a great place to find the correct usage and possibilities for newcomers like me. Thank you!
