### ISSUE TITLE
Add form legend with quickForm

### ISSUE THREAD

**Issue by sturoid** [aldeed/meteor-autoform#701]
Hi is it possible to add a form legend when using a quickForm? I can only see how to do it when using the autoForm method. Thank you in advance for your time.

**Comment by aldeed** [comment]
It would be part of the quickForm template. You can do `template="plain"` on the quickForm or make your own custom template and set it to that.

**Comment by sturoid** [comment]
Thanks a ton @aldeed, and thanks for all the work you've done on this package. It is life altering.
