### ISSUE TITLE
reset behavior with update

### ISSUE THREAD

**Issue by stocksp** [aldeed/meteor-autoform#704]
I was expecting (and need) 'reset form' to clear the form and deselect the item.
In the demo:

http://autoform.meteor.com/updateaf

After selecting a person from the People List:
Reset Form doesn't do anything.
Calling this.resetForm() in the onSuccess handler also does nothing...

**Comment by aldeed** [comment]
You can get that behavior by setting the `doc` attribute to `null` before resetting. AutoForm replicates normal browser form resetting, which resets everything to initial values rather than clearing.

**Comment by stocksp** [comment]
excellent!
thank you!
