### ISSUE TITLE
Question about field syntax within the afEachArrayItem loop

### ISSUE THREAD

**Issue by jcheroske** [aldeed/meteor-autoform#708]
Schema:

```javascript
new SimpleSchema({
   name: {
      type: String,
      label: 'Name',
      max: 40
   },
   methods: {
      type: [Object],
      minCount: 1
   },
   'methods.$.type': {
      type: String,
      allowedValues: ['email','phone'],
      autoform: {
         options: [
            { label: 'Email', value: 'email' },
            { label: 'Phone', value: 'phone' }
         ]
      }
   },
   'methods.$.email': {
      type: String,
      regEx: SimpleSchema.RegEx.Email,
      max: 50
   },
   'methods.$.phone': {
      type: String,
      min: 7,
      max: 25
   },
   }
});
```

Template:

```html
           {{# autoForm collection="Contacts" id="insertContactForm" type="insert" template="bviw" validation="keyup"}}
              {{> afFormGroup name="name" template="bviw"}}

              {{# afEachArrayItem name="methods" template="bviw"}}
                    {{> afFieldInput name="methods.$.type" template="bviw"}}
                    {{#if afFieldValueIs name="methods.$.type" value="email"}}
                       {{> afFieldInput name="methods.$.email" template="bviw"}}
                    {{/if}}

                    {{#if afFieldValueIs name="methods.$.type" value="phone"}}
                       {{> afFieldInput name="methods.$.phone" template="bviw"}}
                    {{/if}}
              {{/afEachArrayItem}}
           {{/autoForm}}
```
My question is, given what I'm trying to do, a) can it currently be done, and b) what is the correct syntax? It kind of half works. Here's what works:

* The 'methods.$.type' field populates with its option list read from the schema.
* The afFieldValueIs helper reads the value of the select list and allows the email and phone fields to be switched on and off.

Here's what doesn't work:

* No validators run
* Looking at the generated HTML, the names of all the array fields are of the format 'methods.$.type' and not 'methods.0.type' as i think they should be.

**Comment by jgladch** [comment]
Can you try something like this and let me know how it works for you:

```js
{{# autoForm collection="Contacts" id="insertContactForm" type="insert" template="bviw" validation="keyup"}}
  {{> afFormGroup name="name" template="bviw"}}

  {{# afEachArrayItem name="methods" template="bviw"}}
        {{> afFieldInput name="type" template="bviw"}}
        {{#if afFieldValueIs name="type" value="email"}}
           {{> afFieldInput name="email" template="bviw"}}
        {{/if}}

        {{#if afFieldValueIs name="type" value="phone"}}
           {{> afFieldInput name="phone" template="bviw"}}
        {{/if}}
  {{/afEachArrayItem}}
{{/autoForm}}
```

If not, I will investigate further.

**Comment by jcheroske** [comment]
It blows up on the three calls that look for a 'type' field: the
afFieldInput call, and the two afFieldValueIs calls. All three throw the
same exception:

Exception in template helper: Error: Invalid field name: type
    at Object.getDefs (
http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:221:13
)
    at Object.autoFormNormalizeContext [as normalizeContext] (
http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:525:20
)
    at Object.afFormGroupContext (
http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:6110:30
)
    at bindDataContext (
http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16
)

Jay

**Comment by jcheroske** [comment]
Ok, I just created a [pad here](http://meteorpad.com/pad/jXT8ZmMR78kbvr3iM/afEachArrayItem%20test). I'm new to all this, so let me know if I made a mistake or you can't see it.

**Comment by aldeed** [comment]
Hey guys, within the the `afEachArrayItem`, `this.name` will contain the name with proper index for the object field. You are technically trying to do an object field within an array field, so that's the confusion. To make it work the way you currently have it written, you'll need a helper that combines `this.name` with the subproperty. For example

```html
{{> afFieldInput name=typeName template="bviw"}}
```

```js
Template.myTemplate.helpers({
  typeName: function () {
    return this.name + '.type';
  }
});
```

**Comment by jcheroske** [comment]
I just put some logging in so I could inspect the `this` object. Like you said, there's a `name` field (in this case, set to `"methods.0"`), but I also noticed there's a `current` field that has an object with all the fields in my form mapped to their full names (`this.current.type -> "methods.0.type"`). Is there a reason to not use that field?

I just updated the pad using `this.current` and more things are working.

* The loop is running fine. I changed the `minCount` to 2 just to see if that would cause it to run twice and it did.
* The various helpers and templates are being passed the contents of `this.current.type`, `this.current.email`, etc.
* `afFieldValueIs` is correctly toggling between the two fields.

What's not working:

* There is no validation running on the fields inside the loop.
* Inspecting the phone and email fields, there is no `name` property set on them.

**Comment by aldeed** [comment]
Yeah, I forgot about `this.current`.

Inputs should always be generated using `afFieldInput`. So rather than `afInputEmail`, it should be `{{> afFieldInput type="email" name=this.current.email}}`. The input templates aren't meant to be called directly. They're selected based on the `type` and `template` attributes that you provide to `afFieldInput`.

**Comment by jcheroske** [comment]
That's funny. I probably figured out not to call the input templates directly a few minutes before you wrote that. Things are going well right now. I do have a suggestion or two, but I'm gonna wrench on things a bit more to make sure I really understand how things are working. But I'm a happy customer! Your libraries really fill some missing pieces of meteor. That you wrote them says a lot about your sense of smell.

**Comment by Aparus** [comment]
@aldeed this.current.type doesn't work for me. there is an error: 
Exception in template helper: TypeError: Cannot read property 'singleType'
but methods.$.type works. what should I do ?

**Comment by allenfuller** [comment]
I'm getting the same error as @Aparus. This seems to be happening since 6.2, but I'll have to dig further to confirm. Might be better to file as a separate issue?

**Comment by alexpyslar** [comment]
Have the same issue with this.current. @aldeed can you please confirm is this a bug?
How can it be resolved?
I'm using 6.3 autoform version.

**Comment by maplefu0601** [comment]
The afEachArrayItem cannot connect to the schema
<div class="row">
              {{#afEachArrayItem name="accounts"}}

              <div class="col-md-4">{{> afFieldInput name=this.current.accountNumber}}</div>
              <div class="col-md-4">{{> afFieldInput name=this.current.holdingShares type="number"}}</div>
              <div class="col-md-2">{{> afQuickField name=this.current.notEligible type="boolean-checkbox"}}</div>
              <div class="col-md-2">
                <button type="button" class="btn btn-primary autoform-remove-item">
                  <span class="glyphicon glyphicon-minus"></span>
                </button>
              </div>

              {{/afEachArrayItem}}
            </div>

I've declared a schema already, but theafFieldInput doesn't connect to that schema. Also, this.current doesn't connect to the schema field. After clicking submit, the value of accounts doesn't save.
