### ISSUE TITLE
QuickForm method type with fields not working 

### ISSUE THREAD

**Issue by aminjam** [aldeed/meteor-autoform#712]
`quickForm` with `type="method"` and selecting the `fields` property is not triggering the Meteor.Method. Steps to reproduce:

```
{{> quickForm collection="Collection" id="myForm" type="method" meteormethod="addMe" fields="items.0"}}
```

Anyone knows a solution to this?

**Comment by jgladch** [comment]
Does this issue persist when using an #autoForm?

You could try something like:
```js
{{#autoForm collection="Collection" id="myForm" type="method" meteormethod="addMe"}}
  {{> afQuickField name="items.0"}}
{{/autoForm}}
```

or something very similar

**Comment by aminjam** [comment]
That throws the same error. I was able to track down the error further. The problem is that SimpleSchema has other properties that are required (e.g. name). When the autoform type is `method`, it's not indicating whether it's an `update` or `insert`, so you can see the [problem here](https://github.com/aldeed/meteor-autoform/blob/master/autoform-validation.js#L56). The code is checking for `formDetails.submitType === "update"` and otherwise the entire form validation, even though it's a partial update. I was able to fix my problem with adding `validation="none"` to the `quickFrom`, but I can send in a pull request that will skip validation for `type="method"` as well. Let me know.

**Comment by aldeed** [comment]
In the `devel` branch, upcoming AutoForm 5.0, there is a `method-update` form type, which I think probably solves your issue.

https://github.com/aldeed/meteor-autoform/blob/devel/CHANGELOG.md

**Comment by aminjam** [comment]
That's great! Yes, that will resolve this issue as well. Looking forward to it.

**Comment by aldeed** [comment]
AutoForm 5.0 released.
