### ISSUE TITLE
AutoForm.resetForm(formId) silently failing

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-autoform#716]
On a form where

````javascript
$('#formId')[0].reset()
````

works, 

````javascript
AutoForm.resetForm(formId)
````

does not and does not produce any errors either.

**Comment by aldeed** [comment]
Please retest against autoform 5.0 and if it's still an issue, post a reproduction app or MeteorPad and I can reopen.

**Comment by serkandurusoy** [comment]
I cannot upgrade to 5.0 at this time, perhaps due to bs datepicker, but I'll try as soon as possible
