### ISSUE TITLE
Render only part of a form?

### ISSUE THREAD

**Issue by Jorenm** [aldeed/meteor-autoform#720]
I have a large array of objects, and I would like to render a form only for one of the objects at a time.

I wrapped the object form in an if statement, and got it only rendering one at a time, but the form doesn't seem to manipulate the source document when form elements change, so any data entry done in a form not currently rendered gets lost.

**Comment by aldeed** [comment]
Kind of difficult to picture this. Can you provide a code example?

**Comment by Jorenm** [comment]
Locations has 50+ objects in it, which really slow everything down if they're all rendered, so I'm trying to just render the one the user clicks on (editLocation).

Schemas = {}
Schemas.CampaignSchema = new SimpleSchema
	name: {
		type: String
		label: "Campaign Name"
	},
	store: {
		type: String
		label: "Game Store"
	},
	password: {
		type: String
		label: "Password"
		optional: true
	}
	locations: {
		type: [Object]
		label: "Locations"
		optional: true
	}
	'locations.$.name': {
		type: String
		label: 'Name'
		optional: true
	}
	'locations.$.owner': {
		type: String
		label: 'Owner'
		allowedValues: General.factions
		optional: true
	}
	'locations.$.resources': {
		type: [String]
		label: ''
		allowedValues: General.resources
		optional: true
	}

		+autoForm(schema=schema doc=campaign id="EditCampaignForm")
			+afQuickField name="name"
			+afQuickField name="store"
			+afQuickField name="password"
			ul.locations
				+afEachArrayItem name="locations"
					li
						+afQuickField name=this.current.name readonly=true
						button.edit Edit
						if isEqual a=this.index b=editLocation
							div.location
								+afQuickField name=this.current.name readonly=true
								+afQuickField name=this.current.owner options="allowed"
								label Resources
								+afEachArrayItem name=this.current.resources
									+afQuickField name=this.name options="allowed"

**Comment by aldeed** [comment]
I think the logic is pretty dependent on everything being in the dom, but you could possibly render them all, but render the others hidden (e.g., add "hidden" class unless this.index equals editLocation).

Or you can separate into two forms, which is likely the easier solution. Have the location form render the div.location without using `afEachArrayItem`. Build the field names yourself with `"locations." + editLocation + ".name"` etc.

**Comment by Jorenm** [comment]
Condtionally showing them works fine from a UX perspective, but whatever digest stuff is going on is choking on 94 objects with multiple fields each. The browser hangs for a second or two on submit.

Maybe I should render it on edit, then hide it? That way the altered form elements still exist in the dom, while the ones that weren't altered never get rendered.

**Comment by Jorenm** [comment]
+afEachArrayItem name="locations"
	li
		h2 {{getLocationName this.index}}
		button.edit Edit
		if inArray thing=this.index array=editedLocations
			div.location(class="{{classIfEqual a=this.index b=editLocation cssClass='visible'}}")
				+afQuickField name=this.current.name readonly=true
				+afQuickField name=this.current.owner options="allowed"
				+afQuickField name=this.current.type readonly=true
				+afQuickField name=this.current.terrain readonly=true
				label Resources
				+afEachArrayItem name=this.current.resources
					+afQuickField name=this.name options="allowed"
				+afFieldInput name=this.current.x type="hidden"
				+afFieldInput name=this.current.y type="hidden"

Template.edit_campaign.events =
	'click #EditCampaignForm button.edit': (e) ->
		e.preventDefault()
		editedLocations = Session.get('editedLocations')
		if !editedLocations
			editedLocations = []

		if this.index not in editedLocations
			editedLocations.push(this.index)

		Session.set('editedLocations', editedLocations)
		Session.set('editLocation', this.index)

AutoForm.addHooks 'EditCampaignForm', {
		onSubmit: (insertDoc, updateDoc, currentDoc) ->
			editedLocations = Session.get('editedLocations')
			
			# Map the updated location data onto the full location list.
			if editedLocations?
				for i in editedLocations
					campaign.locations[i] = updateDoc.$set.locations.shift()
				updateDoc.$set.locations = campaign.locations

			Campaigns.update campaign._id, updateDoc
			Session.set('modal', null)
			Session.keys = {}
			this.done()
			return false
		onError: (operation, error, template) ->
			console.log error
	}, true
