### ISSUE TITLE
Modify the document of a autoform using javascript function

### ISSUE THREAD

**Issue by umbra268** [aldeed/meteor-autoform#721]
I am wondering if there is a better way for a javascript function on the same page as the form to modify the document or data of an autoform.

My collection/schema has an item that is an array of strings. People can manually enter them one by one if they choose. Otherwise they can click on a button which opens a popup dialog where they enter a url, this url is then read and line by line populates the form.

Currently I am doing this by using a for loop to create an jquery event (waitUntilExists) which I found online which populates the textbox with it's line of data and pragmatically clicks the create next element buttons, until all lines have been entered into the form.

I was wondering if there was a simple way of doing this task without adding the overhead of waiting for dom to update between each and every element.

Cheers

UPDATE: can close this. Just realised I can use a textarea and use docToForm & formToDoc to do this.

**Comment by aldeed** [comment]
To answer the question, no I don't think there's any great way to do it. You could call the array tracker function directly, but that's not really any different from simulating the button click. I suppose we could eventually have ability to programmatically add or set the array tracker array, but I'll wait until there are more requests for that.
