### ISSUE TITLE
onSuccess firing multiple times

### ISSUE THREAD

**Issue by Maxhodges** [aldeed/meteor-autoform#722]
if I update one item, autoform will fire OnSuccess once. If I then edit a second item, after I submit the OnSuccess will fire twice. Edit a third item and when I click to submit, I will fire OnSuccess three times. etc.

Seen this before by chance? Any idea what's going on?

Cheers!

**Comment by aldeed** [comment]
Will need a link to a simple reproduction repo.

**Comment by Maxhodges** [comment]
ok will work on it

**Comment by Maxhodges** [comment]
hi @aldeed, OK so I solved the multiple events issue. We had the autoform hook in the templates rendered event, and it seems each time the template was loaded it was add the hook again, so that they were being added multiple times.

I tried to move it to the templates created event instead, but that didn't solve it either. Finally used this alternative method you mentioned in the readme

     AutoForm.addHooks('form1', {
    onSubmit: function () {
      console.log("Only this onSubmit");
    }
    }, true);   

That worked!

But I want to ask: where is this (below) syntax suppose to go if not in the template created or rendered events?

`AutoForm.hooks({
  myFormId: {...`

**Comment by aldeed** [comment]
I usually just put it in the client code file, not within any other callbacks.

**Comment by Maxhodges** [comment]
ah interesting. so instead of this

    Template.adminReceiveItem.rendered = function() {
    AutoForm.hooks({
      receiveItemForm: {
        onSuccess: _.once(function(operation, result, t){

it should just go outside the template logic

line1
    AutoForm.hooks({
      receiveItemForm: {
        onSuccess: _.once(function(operation, result, t){...

    Template.adminReceiveItem.rendered = function() {

**Comment by aldeed** [comment]
Yes, but you wouldn't want to use `_.once` in that case.

**Comment by Maxhodges** [comment]
yeah, that was our workaround regarding the multi-firing issue ;)

*Max Hodges* | Partner at White Rabbit Japan <http://whiterabbitjapan.com> |
t 03.6303.1840 | m 090.1795.4446
