### ISSUE TITLE
No keyup validation of array schema field

### ISSUE THREAD

**Issue by chickenwing** [aldeed/meteor-autoform#725]
First off, thanks for this great meteor package :)

Now, my issue:
Go to http://autoform.meteor.com/quickform
Choose "Optional array of strings"
Set "minCount" to 2 and update
Enter a tag in the first field and submit
You get the error "You must specify at least 2 values"
Enter a tag in the second input.
The error does not go away while typing. Shouldn't submitThenKeyup be the default and working?

Also:
Only enter a tag in the second field. Leave the first one empty and submit. Shouldn't that raise an error, because the first input is empty? Is this a bug or by design? How could I fix it?

thx alot.

**Comment by aldeed** [comment]
Thanks, this is fixed in the devel branch now.

**Comment by jcheroske** [comment]
This may be related to #707.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.
