### ISSUE TITLE
Start of Week Change

### ISSUE THREAD

**Issue by romant** [aldeed/meteor-autoform#726]
Please add the ability to change the Week Start value; at the moment all dialogs; despite regional browser settings - start on the Sunday.

**Comment by aldeed** [comment]
What is this referring to? There are no calendars in autoform core package.

**Comment by romant** [comment]
@aldeed the date picker

**Comment by aldeed** [comment]
The add on package? If you're just doing `type="date"`, then that's showing the date picker generated by the browser. Nothing coming from autoform there.

**Comment by romant** [comment]
weird then. As all other date pickers within the browser, abide by the regional settings of the OS; and display accordingly. For some reason the meteor-autoform doesn't.

Is there a way to explicitly specify the region then?

**Comment by aldeed** [comment]
AutoForm isn't doing anything other than generating the input[type=date]. It should not have any differences in UI. If it does, you'll need to provide a reproduction repo so we can see what's going on.

**Comment by aldeed** [comment]
Closing pending reproduction
