### ISSUE TITLE
Adding custom styles to elements showed by afQuickField

### ISSUE THREAD

**Issue by nadimdiaz** [aldeed/meteor-autoform#727]
Hey! ... this is more a question than a issue, can I apply custom styles to my afQuickField... my afQuickField have an array of strings that actually is displayed as option list.

E.g.

{{> afQuickField name='problems' options=problemList noselect=true}}

I want to apply some style to every entry of the list (e.g. borders things like that)... but I am not sure if is possible and can't find the documentation related. BTW this library is cool, thanks!!

**Comment by chickenwing** [comment]
According to the doc "any additional attributes are passed along to the generated DOM element".

So you could try:
```
{{> afQuickField name='problems' options=problemList noselect=true class="myClass"}}
```
and in your css file:
```
.myClass {
 background: red;
}
```

**Comment by nadimdiaz** [comment]
Thanks for your answer, looks like "myClass" is just applied to the checkboxes, BTW I guess I can use the default styles applied to every div, I mean something like:

.af-checkbox-group .checkbox {
  border: 2px solid;
}

The af-checkbox-group is applied to each div that contains the checkbox and label. 

Thanks!
