### ISSUE TITLE
Type Update switch to Insert if no doc found?

### ISSUE THREAD

**Issue by voidale** [aldeed/meteor-autoform#728]
I'm trying to show `type update` form. But when there is no doc (findOne) I expect it to be an insert form. Is it possible?

**Comment by aldeed** [comment]
It's only an insert form if you switch the type to "insert". Some people use `doc` with an insert form to provide default values.

**Comment by voidale** [comment]
so this means, If I want to have type="update" I must have at least 1 document. What If I don't have it yet.  Is there a way to check if no document make it type="insert" so after first time it will always be update

**Comment by aldeed** [comment]
Yes, you can do that. The `type` attribute can be set to a helper that returns "insert" or "update" as appropriate. Or you can just wrap two different forms

```html
{{#if doc}}
  {{> quickForm id="updateForm" type="update" doc=doc}}
{{else}}
  {{> quickForm id="insertForm" type="insert"}}
{{/if}}
```

**Comment by voidale** [comment]
This way, After you submit the form. You get an error `Exception in delivering result of invoking '/settings/insert': Error: Can't select in removed DomRange` and you have to refresh the page for auto values to appear to the form.

**Comment by aldeed** [comment]
Hi @voidale, please test using autoform 5.0. If you still get the error, post a simple reproduction app that produces that error.

**Comment by voidale** [comment]
@aldeed Hi, I think we can close this one, It's not an issue anymore as far I can tell.
