### ISSUE TITLE
Complex Schema how to define subfields

### ISSUE THREAD

**Issue by kamil7732** [aldeed/meteor-autoform#729]
Hi,
I'm trying to define subfields in autoform.
I tried to follow this guidence https://github.com/aldeed/meteor-autoform/blob/master/README.md#complex-schemas
But this example doesn't follow some showed previously schema. 
I tried to access field emails.$.address with {{> afQuickField name='emails.address '}} but I get "Error: Invalid field name".
In my situation I need to attach data to a select that is inside complex schema.

**Comment by aldeed** [comment]
You need to use the real index in autoform, i.e., `emails.0.address`. If you're trying to provide a way to add/remove from the array, edit multiple indexes at once, etc., then you can let `afArrayField` component do it for you, or you can use `afEachArrayItem` to help with the process.
