### ISSUE TITLE
QuickFields inside a <table> leading to "Aw Snap" crash in Chrome.

### ISSUE THREAD

**Issue by mgruen** [aldeed/meteor-autoform#730]
First of all thanks for the awesome package.

Whenever I put two afQuickFields inside a table I quickly get a "Aw Snap" blue screen in Chrome 40.  Meteor 1.0.3.2, Autoform 4.2.2.  Glad to show the rest of the code, but the problem happens if I simply do this (inside a bootstrap "panel"), and ceases to happen if I remove the table and leave the fields alone.

{{#autoForm id=this._id collection="Services" type="update" doc=this template="bootstrap3-horizontal" autosave=true }}

table width="100%"
      tr
        td  {{> afQuickField name='x1' }}  /td
        td  {{> afQuickField name='x2' }}  /td
      /tr
/table

**Comment by aldeed** [comment]
@mgruen, I can't reproduce against `devel` brach of autoform, so it is either fixed or you'll need to provide a full reproduction. Goal is to have the next autoform release out shortly.

**Comment by aldeed** [comment]
AutoForm 5.0 is released. If you still have this issue after updating, post a simple reproduction app and I will reopen.
