### ISSUE TITLE
How to do complex global validation over the whole document

### ISSUE THREAD

**Issue by skeetmtp** [aldeed/meteor-autoform#731]
Let take a simplified case where I have a schema with 3 booleans values.
To be valid, a document need that at least one of thoses booleans is set to true.
How can I do this kind of validation over the whole document. So I can display a *'has-error'* class in a *'form-group'* and/or a explicit message at the bottom of the form ?

This is a simplified case to point my needs, my real case is more complex, as I need to compare severale fields between each others.

**Comment by aldeed** [comment]
You can probably do it with [this method](https://github.com/aldeed/meteor-simple-schema#validate-one-key-against-another), checking whether the current field is `false` and the other two also are. That would work for inserts, but for updates, this would require querying the database, so it's probably best to use a server method and do your checking there before updating.

**Comment by skeetmtp** [comment]
Thanks for the super quick reponse. 
That's the solution I use, but I found it a bit cucumbersome when there is more than a couple of fields to check, and I was wondering if there was a hook somewhere to do this kind more smoothly.
Something like : 
```javascript
validateDocument : function(doc) {
 ... check fields consistency...
  return true; //if ok
}
```

**Comment by aldeed** [comment]
In a form situation, you can do it pretty easily in a "before" hook, but it wouldn't be a bad idea to add something like that to the simple-schema package for a more general solution. Can you post an issue over on the simple-schema repo with that suggestion? There is `mySimpleSchema.addValidator()` but that's still per-key validation. So we could add a similar `mySimpleSchema.addDocValidator()`.

**Comment by skeetmtp** [comment]
Sure. I'll open an issue on simple-schema.

**Comment by skeetmtp** [comment]
I close the issue, since there is this new one in simple schema : aldeed/meteor-simple-schema#281
