### ISSUE TITLE
how to custom "_id" like "001" when insert?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-autoform#734]
how to custom "_id" like "001" when insert?

**Comment by aldeed** [comment]
Set `doc._id = "001"` in a "before insert" hook.

**Comment by yuomtheara** [comment]
very thanks, but i want to increase id by `the last record +1`:
- I used `subscribe` and then get the `last id + 1`
- but can not get any thing maybe problem with `subscribe`
- how to wait the `subscribe` is ready and pass the value of the last id to `doc._id`?

**Comment by aldeed** [comment]
Don't show the form template until the subscription is ready.

**Comment by yuomtheara** [comment]
don't understand.
