### ISSUE TITLE
A way to disable submit on enter temporarily

### ISSUE THREAD

**Issue by abtx** [aldeed/meteor-autoform#736]
Hi, I have the form broken down into few cards that animate in and out, I want to change the card on enter until reaching the last one, which will submit the form. I'm using jQuery to hide parts of the form. Is there a way to accomplish this? Thanks

**Comment by aldeed** [comment]
It should work to capture the key press and don't let it propagate up. Like a `keyup` listener attached to `form *` and call `event.stopPropagation()` if it's the enter key.

**Comment by abtx** [comment]
Grand, thanks a bunch Aldeed!

**Comment by OminStyle** [comment]
Can you share your solution @abtx ? ```event.stopPropagation();``` isn't working for me. 
```
  document.getElementById("form").addEventListener('keydown', function(event) {
    var keycode = (event.keyCode ? event.keyCode : event.which);
    if(keycode == '13'){
      event.stopPropagation();
      console.log("Pressed Enter");
    }
  });
```

**Comment by OminStyle** [comment]
nvm [this](http://webcheatsheet.com/javascript/disable_enter_key.php) worked for me.

**Comment by abtx** [comment]
Hi, I think I just dropped the listener to addEventListener. Cheers
