### ISSUE TITLE
Omitting 'for' attribute on labels breaks accessibility

### ISSUE THREAD

**Issue by ndarilek** [aldeed/meteor-autoform#739]
If you're using a screen reader, it is essential to set the _for_ attribute on labels to the _id_ of their inputs so the user knows what they've landed on. Otherwise, the field's input type is spoken without the useful label context. (I.e. you hear "Edit text" when you land on a text box, instead of "Display name: Edit text" which is vastly more helpful.)

This doesn't appear to happen by default. I wonder if the default input fields might generate a random UUID ID if one isn't set, then set that as the value of the _for_ attribute?

A quick grep through the sources suggests that there is some support for setting this attribute, but I can't seem to get it working. I tried (Jade code):

`+afQuickField(id = "displayName" name = "profile.displayName")`

but this doesn't appear to set the id attribute on my field. Is there some way to set the _for_ attribute on the label as a temporary workaround? Then hopefully this can be implemented directly into autoform, since lots of folks just use it without too much customization and setting up labels would be a huge accessibility win.

Thanks.

**Comment by aldeed** [comment]
Pretty sure we're already doing this, but I'm not sure if it's released yet or just in devel branch. Next release should be out within a few days, so I can investigate more if this is an issue after that. It's related to what theme template is being used, too.

**Comment by aldeed** [comment]
In general, I don't recommend ever setting `id` attribute in Meteor. Due to reusability of templates, you can end up with two of the same `id` and strange things happen. But setting to UUID to make `for` work is fine, and afaik it's what the package is doing.

**Comment by ndarilek** [comment]
Definitely doesn't appear to be happening now. Cool, I can hold off for
the next release in a few days. My app is specifically targeted at blind
users so this is a must-have feature.

Thanks for the quick response!

**Comment by aldeed** [comment]
I did a quick check before releasing 5.0 and for/id seemed to be getting set. If you're still seeing this after updating to autoform 5.0, post a reproduction repo or MeteorPad, and I'll reopen to investigate.
