### ISSUE TITLE
Global form validation flag

### ISSUE THREAD

**Issue by vladblindu** [aldeed/meteor-autoform#740]
It might a duplicate, but I couldn't find a specific answer myself.
Is there any global form validity flag and is there any way to clear the "invalid error" (like afFieldIsInvalid for the whole form). I would like to clear the error messages once the user starts typing again, but AutoForm.resetForm clears the input also.
Thank you.

**Comment by aldeed** [comment]
There is an existing issue and a PR regarding form valid/invalid/dirty/pristine.

For clearing errors, try `AutoForm.getValidationContext(formId).resetValidation()`
