### ISSUE TITLE
{{submitButtonAtts}} not working in custom form template?

### ISSUE THREAD

**Issue by Jehu** [aldeed/meteor-autoform#741]
i use quickForm with a template attribute, my own form template has just a template for the main form, not for any afForm types.

it seems {{submitButtonAtts}} is ignored. The defined buttonClasses attribute from quickForm is not added.

Here is my jade-template:
```jade
  +quickForm collection="Events" id="insertEventForm" type="insert" class="event_add pure-form" buttonContent="Speichern" buttonClasses="pure-button pure-button-primary" template="pureCSS"
```
and this is the template file
```html
<template name="quickForm_pureCSS">
  {{#autoForm this.qfAutoFormContext}}
  <fieldset>
    {{> afQuickFields id-prefix=idPrefix}}
    {{#if qfShouldRenderButton}}
    <div class="pure-control-group">
      <button type="submit" {{submitButtonAtts}}>
        {{#with ../atts.buttonContent}}
        {{this}}
        {{else}}
        Submit
        {{/with}}
      </button>
    </div>
    {{/if}}
  </fieldset>
  {{/autoForm}}
</template>
```

Any hints?

**Comment by aldeed** [comment]
If you copy from a built in template, you have to copy any template helpers, too. For example, https://github.com/aldeed/meteor-autoform/blob/master/templates/plain-fieldset/plain-fieldset.js

Or you can inherit them if using `aldeed:template-extension` package.

**Comment by Jehu** [comment]
many thanks @aldeed
