### ISSUE TITLE
Override regex error message?

### ISSUE THREAD

**Issue by dkoo761** [aldeed/meteor-autoform#742]
Hi there,

I'm current getting a regex error message of "XXXXX failed regular expression validation". I'd like to change this error message to something friendlier, but can't seem to see where that's done? I'm using an afQuickField to render the element. I don't want to hardcore the error message since it the error should be different if the user leaves the field blank.

Thanks,
Dave

**Comment by aldeed** [comment]
That is handled in [simple schema](https://github.com/aldeed/meteor-simple-schema#customizing-validation-messages)

**Comment by dkoo761** [comment]
OK great, thanks.
