### ISSUE TITLE
multiple autoform with one submit button

### ISSUE THREAD

**Issue by YouSour** [aldeed/meteor-autoform#744]
hi, i'm using autoform with one project . i want multiple autoform with one submit button , have any good option ?

**Comment by aldeed** [comment]
You can make the button `type="button"`, handle the button click yourself, and call `$('form1').submit()`, etc. for all forms in the click handler.

**Comment by YouSour** [comment]
thank you for reply , but what should i do if  form1 validation  error and form2 should be not work too ?

**Comment by aldeed** [comment]
There may not be a perfect way, but you can validate each field manually using [AutoForm.validateForm](https://github.com/aldeed/meteor-autoform/blob/master/api.md#autoformvalidateformformidclient) before you call submit for any of them, and submit them all only if all are valid.

**Comment by YouSour** [comment]
thank you every much for info :) !
