### ISSUE TITLE
Server method not called when modifying doc in 'before' hook

### ISSUE THREAD

**Issue by Framnk** [aldeed/meteor-autoform#747]
I have a working form submission that I want to add a custom field to in the 'before' hook before the doc is sent to the server side method.  However if I modify the doc in any way in the 'before' hook, the server method never seems to get called.  I have verified this with console.log both in the before hook and in the server method.  If I left the hook in place and comment out all code that modifies the doc, the server method is called.  However if I add a single additional property to the doc before returning it from the 'before' hook, the server method never gets called (I have dumped the doc object after modifying it in the 'before' hook and can verify the property was added).

**Comment by Framnk** [comment]
Apparently this is happening because the doc I am returning is being validated *after* the 'before' hook is run for 'method' type forms.  This seems to go contrary to intention if I read this right:

"The before hooks are called after the form is deemed valid but before the submission operation happens. (The submission operation depends on the form type. For example, the insert, update, method call, etc.) These hooks are passed the document or modifier as gathered from the form fields. If necessary they can modify the document or modifier. "

This seems to indicate the form should be validated before the 'before' hook is called not after.  Anyway, I was able to get around it by adding the additional field as an optional field to my schema and omitting it from my form.

**Comment by williamkhshea** [comment]
@Framnk I am having similar issue. I am trying to add fields in the before hooks and the validation runs before the fields are added and throwing "fields are required" error.

See #766 .

**Comment by aldeed** [comment]
@Framnk that description of before hooks is maybe not quite accurate. See [here](https://github.com/aldeed/meteor-autoform/issues/766#issuecomment-84171424) for expected behavior on method forms. Seems like it's not behaving that way, though, so this is a bug. We'll track in #766.
