### ISSUE TITLE
Form that saves to multiple collections

### ISSUE THREAD

**Issue by ShavonnahTiera** [aldeed/meteor-autoform#749]
How can I create a form that updates more than one collection on submit?

I've created a new Meteor.user schema that I'm using for login and I'd like to collect one more piece of information that would either save to a Teacher or Student collection.

Here's a quick example:

```
<template name="insertUser">
  {{#autoForm collection="User" id="insertUserForm" type="insert"}}
  <fieldset>
    <legend>Signup</legend>
    {{> afQuickField name='firstName'}}
    {{> afQuickField name='lastName'}}
    {{> afQuickField name='email'}}
    {{> afQuickField name='pword'}}
    {{> afQuickField name='pwordCheck'}}

    <--! if session is student, enter project name and submit to Student collection -->
   {{#if student}} 
    <div class="form-group">
              {{> afFieldInput name='projectName'}}
      </div>
    {{/if}}
    <div>

     <--! else session is teacher, enter class name and submit to Teacher collection -->
      {{> afFieldInput name='className'}}
    </div>
  </fieldset>
  <button type="submit" class="btn btn-primary">Signup</button>
  {{/autoForm}}
</template>
```

I'm still pretty new to programming and meteor. Let me know if there's a better way

**Comment by SachaG** [comment]
I don't think this will work with the `insert` form type. On the other hand, if you use the `method` form type, you can just pass data to a method that will do whatever you want it to, including inserting documents in two different collections.

**Comment by aldeed** [comment]
You can also omit the `type` attribute and put your inserting logic in an `onSubmit` hook for the form, if you want to do the inserts on the client.

Either way you may also have to pass a custom form schema with the `schema` attribute, if the fields are from different collections or not in a collection schema at all.

**Comment by ShavonnahTiera** [comment]
Thanks for the tips @SachaG and @aldeed! I'll give them a try.
