### ISSUE TITLE
getFieldValue with form Id option?

### ISSUE THREAD

**Issue by BradRyan** [aldeed/meteor-autoform#750]
I have a use case where I am using a schema to create a number of input fields from the same schema key (but with unique id's) and would like to use the reactivity of the getFieldValue function.  It's not tied to a collection so I was just using autoform and simple schema as an easy way to generate input fields and reactiviely grab values.  I didn't see the option to pass in the field Id (only form Id), but I thought I'd ask anyways.

Perhaps there's a work around for my use case?  I'm going to go back and add schema keys for the specific field names for the demo version of a project, but it will eventually need to have potentially many instances of the same field type on the same form.  It would be nice to not have to create a bunch of unique schema keys.

It's quite possible that there's an obviously better way to do what I'm doing...

**Comment by aldeed** [comment]
Logic is predicated on there being only one input per schema key in each form, so you would have to duplicate the key definition however many times you need fields, with a different key name for each. You could build the schema object in a loop to avoid typing them all out.
