### ISSUE TITLE
Optional nested schemas being required on update

### ISSUE THREAD

**Issue by freer4** [aldeed/meteor-autoform#754]
I have schemas set up so that I can have an array of complex input sets nested on main schema. Something like:

    address = {
      street:{
        type: String
      },
      city: {
        type: String
      },
      ...
    }
    
    people = {
      name:{
        type: String
      },
      address:{
        type: [address],
        optional: true
      }
    }

This way adding an address is optional, but if you add an address all of the address fields are required.

This worked in (I believe it was) version 4.2.2. This still works on insert type autoforms, but not on update type autoforms. Doing an update, none of the fields in the form will submit unless all required fields, including those in the optional nested schemas,  are also valid.

For reference, I'm creating the form as such:

    {{#autoForm collection="people" id=formId type="update" doc=getDocument autosave=true template="autoupdate"}}    
      {{> afQuickField name='name' template="autoupdate" placeholder="schemaLabel"}}
      {{> afQuickField name='address' template="autoupdate"}}
    {{/autoForm}} 

I just tried recreating all of my form templates (originally modified boostrap3 templates) using the bootstrap3 templates from 5.0.2. 

Is no one else seeing this behavior?

**Comment by freer4** [comment]
Updated for clarity and better examples after testing.

**Comment by freer4** [comment]
Set the default value to an empty array. 

      address:{
        type: [address],
        optional: true,
        defaultValue: []
      }

But!!! Boolean type inputs in the nested template cause there to be validation errors on input. Meteor sees this as "false" and attempts to force the other associated inputs to be required. I've fixed this temporarily by running a `formToDoc` hook changing false to null for Boolean inputs on insert only. Should probably be addressed as a bug though.

**Comment by aldeed** [comment]
boolean checkboxes have only false and true states, but you can use `type="boolean-select"` to provide an unselected/undefined state.

**Comment by workflow** [comment]
@aldeed I'm experiencing the exact same issue as @freer4, except that there are no booleans involved,
and setting
`defaultValue: {}`
doesn't help.

( I have an embedded sub-document, not an array of documents)

Should we re-open or should I create a new issue?

**Comment by aldeed** [comment]
@workflow new issue please, post full schema and update call that's producing the error.

**Comment by workflow** [comment]
@aldeed In creating a minimalistic working example, I noticed that the culprit was actually using `defaultValue` somewhere inside the complex sub-schema.

So happy to say that the mistake was on my side and everything works as it should here! :)

Thank you for your amazing work.

**Comment by luixal** [comment]
Just hit this. I can confirm that removing `defaultValue` from fields in inner schema solves this but... doesn't provide the expected functionality.

This is, I just want to use an optional nested schema which would have some default values in its fields. Seems like a common situation in some forms.

It's been a year of this issue... should I open a new one with an example?
