### ISSUE TITLE
Select options keep growing due to multiple ccalls to autoform:{options: function}

### ISSUE THREAD

**Issue by ssteinerx** [aldeed/meteor-autoform#757]
The list just keeps growing and growing...and the console shows that the function is called multiple times.
UPDATE: I just noticed that, after I put records in Clients manually with the `meteor mongo` console, they were being given ObjectID default Mongo keys and my getClientSelectOptions was returning that object as 'value.'  

This was causing an exception:
  Exception from Tracker recompute function: Error: Unexpected object in htmljs in toText: 

It seems that Meteor gets grumpy unless its string type keys are used.

Regardless, should autoform be handling this exception somehow, or is this an upstream issue with an unfortunate side effect for autoform?

Given this in the schema:
 ```javascript
clientId: {
    type: String,
    optional: false,
    autoform: {
      options: getClientSelectOptions
    }
  }
```
And this as the options function:
```javascript
function getClientSelectOptions() {
  // body...
  return Clients.find().map(
    function (client) {
      console.log("getClientSelectOptions-detached map clients");
      console.log(client);
      return ({
        label: client.companyName,
        value: client._id
      });
    }
  )
}
```

**Comment by aldeed** [comment]
Probably an upstream issue. I don't see any problem with your code. Options and any other attribute functions are reactive so they often will be called many times as different things happen in your form. (For example, as more `Clients` are created or published to the client in your example, the options list will be automatically updated by rerunning your function.)

**Comment by ssteinerx** [comment]
I think this threw me off: "autoform.options can be a function, but it is not recalculated reactively."

If I'm reading what you said above correctly, that's not entirely true...maybe the doc should be clarified a bit around this issue?

**Comment by aldeed** [comment]
Used to be true, but not anymore. I'll fix.
