### ISSUE TITLE
quickForm: way to disable some fields?

### ISSUE THREAD

**Issue by testbird** [aldeed/meteor-autoform#76]
I think the quickForm feature may be much more usefull if there were a way to not have inputs for some fields. (For example autoValue fields.)

Ideas to disable inputs for quickForms may be, to skip all `autoValude` fields, to add some `afQuickField input=false` statements to the quickForm, or to add `quickForm: false` to the schema.

**Comment by dr-dimitru** [comment]
@driesvancraen +1 
this is highly required feature

**Comment by typ90** [comment]
+1
