### ISSUE TITLE
Dynamic arrays: Freeze when changing main option

### ISSUE THREAD

**Issue by nQk2** [aldeed/meteor-autoform#762]
In this ( https://github.com/aldeed/meteor-autoform/issues/585 ) scenario, my browser window freezes, when

1. Selecting a main option (this generates sub options)
2. Changing that main option.

collections.js:
```
Products = new Mongo.Collection('products');
Categories = new Mongo.Collection('categories');

Products.attachSchema(new SimpleSchema({
  name: {
    type: String,
    label: "Name",
    max: 100,
  },
  categories: {
    type: [Object],
    minCount: 1
  },
  "categories.$.mainCategory": {
    type: String,
    autoform: {
      options: function() {
        return Categories.find().map(function(obj) {
          return { label: obj.name, value: obj.name };
        });
      }
    }
  },
  "categories.$.subCategory": {
    type: String,
    autoform: {
      options: function() {
        var mainCat = AutoForm.getFieldValue(this.name.replace('.subCategory', '.mainCategory'));
        return Categories.findOne({ name: mainCat }).subCategories.map(function(obj) {
          return { label: obj.name, value: obj.name };
        });
      }
    }
  }
}));

Categories.attachSchema(new SimpleSchema({
  name: {
    type: String,
    unique: true
  },
  subCategories: {
    type: [Object],
    minCount: 1
  },
  "subCategories.$.name": {
    type: String
  }
}));
```

server.js:
```
if (Meteor.isServer) {
  Meteor.startup(function () {
    Categories.remove({});
    Categories.insert( 
      {
        name: "MainCategory1",
        subCategories: [
          {name: "SubCategory1.1"},   
          {name: "SubCategory1.2"}
        ]
      }
    );
    Categories.insert( 
      {
        name: "MainCategory2",
        subCategories: [
          {name: "SubCategory2.1"},   
          {name: "SubCategory2.2"}
        ]
      }
    );
  });
}
```

template.html:
```
{{> quickForm collection="Products" id="insertProductForm" type="insert"}}
```

Also I get millions of the same warning:

    TypeError: Cannot read property 'subCategories' of undefined
    at Object.Products.attachSchema.SimpleSchema.categories.$.subCategory.autoform.options

**Comment by nQk2** [comment]
Browser also freezes when selecting a main option and then clicking the plus-button.

Would be really great if you could have a look at this. I'm not able to find a workaround.

**Comment by aldeed** [comment]
I'm guessing it's the same cause as #785. I will try to get a fix in place.

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by nQk2** [comment]
Thank you, working now.

However, there are still 2 issues when adding update/insert functionality:

- Setting doc to null doesn't reset the form (https://github.com/aldeed/meteor-autoform/issues/751).
- In update mode, clicking the plus button sets doc to null (thus turning it into insert mode).
