### ISSUE TITLE
Issue with 1.0.4-rc3 and AutoForm.getFormSchema()

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#763]
By chance I was running the 1.0.4-rc3 version of Meteor and I noticed that `AutoForm.getFormSchema()` wasn't working properly anymore for some reason.

Not a big deal since I was just doing that to test out something, but I thought I'd make a note of it.

**Comment by aldeed** [comment]
Thanks. Haven't tested against 1.0.4 yet, but I guess I better do that.

**Comment by aldeed** [comment]
Fixed
