### ISSUE TITLE
Validation happens before the "before hook" runs

### ISSUE THREAD

**Issue by williamkhshea** [aldeed/meteor-autoform#766]
I have logged a similar issue in #395.

It seems there is a behavior change in v5.0. The validation now happens BEFORE the "before hook" runs, while in previous version validation happends AFTER the "before hook" runs.

I am adding a field in the before hooks but it is not fired. I have run AutoForm.debug() and the error says:
```
Error in sendRequestForm pre-submit validation Error: Menu is required {invalidKeys: Array[2], stack: (...), message: "Menu is required"}
```
which seems to suggest the validation happens before the before hook runs.

My code as below:

client.html
```
    {{#autoForm schema=sendReqModalSchema id="sendRequestForm" type="method" meteormethod="sendRequest" class="ui form"}}
    <div class="two fields">
      {{> afQuickField name='req.guest' icon='users icon' min=../minOrder max=../maxOrder value=../minOrder}}
      {{> afQuickField name='req.date' icon='calendar icon' type='datetime-local'}}
    </div>
    <div class="field">
      {{> afQuickField name='req.loc' icon='marker icon'}}
    </div>

    <div class="field">
      {{> afFieldInput name='msgs.0.content' rows=2 placeholder='Send a message'}}
    </div>
    <button type="submit" class="ui positive button">{{i18n "send"}}</button>
    {{/autoForm}}
```

client.js
```
AutoForm.hooks({
  sendRequestForm: {
    before: {
      method: function (doc) {
        doc.req.menu = {
          menuId: Template.parentData(1)._id
        };
        return doc;
      },
    }
});
```

Is the behavior change intentional?

**Comment by williamkhshea** [comment]
The code below is saying the form data is validated before the "before hook" is run.

Just wonder is there any way that I can turn the preValidate off?

autoform-event.js: line 261
```
    // Get the form type definition
    var ftd = AutoForm._formTypeDefinitions[formType];
    if (!ftd) {
      throw new Error('AutoForm: Form type "' + formType + '" has not been defined');
    }

    // Ask form type definition whether we should prevalidate. By default we do.
    var shouldPrevalidate = ftd.shouldPrevalidate ? ftd.shouldPrevalidate.call(hookContext) : true;
```

**Comment by aldeed** [comment]
I think the correct behavior is that it should prevalidate only if there is both a `schema` attribute and a `collection` attribute on the autoForm. In such cases, the order should be:

1. Validate against form schema (prevalidate)
2. Run before hooks if valid
3. Validate against collection schema
4. Call method if valid

If there is only `schema` or only `collection`, order should be:

1. Run before hooks
2. Validate against form or collection schema
3. Call method if valid

So it sounds like a bug. Will need to verify and adjust logic.
