### ISSUE TITLE
Autoform.getFieldValue not reactive?

### ISSUE THREAD

**Issue by BradRyan** [aldeed/meteor-autoform#767]
So I just went through the fun drill of switching all of my getFieldValues from (formId, fieldName) to 
(fieldName, [formId]).  Now it seems I've lost reactivity of all of these functions.

I can insert AutoForm.getFieldValue("returnTripType", "tripType"); in the developer console and get the expected result, but it is not reactively grabbing the field value as it changes.  I have a console.log in my template helper returning the result "undefined" so it seems like it is only running once before the form has even rendered.  Here's an example of the code:

quote.html
```
<template name="QuoteTool">
	{{#autoForm schema="DepartRouteQuote" id="tripType"}}
		{{> afQuickField name='returnTripType' id="selectlegoption" label=false value="Round Trip"}}
	{{/autoForm}}

	{{> Route1}}

	{{#if roundTrip}}
		{{> Route2}}
	{{/if}}
</template>
```

quote.js
```javascript
Template.QuoteTool.helpers({
	roundTrip: function() {
		var returnType = AutoForm.getFieldValue("returnTripType", "tripType");
		console.log("returnTripType: "+returnType);
		if (returnType == 'Round Trip') {
			return true;
		} else {
			return false;
		}
	}
});
```

schema.js
```javascript
DepartRouteQuote = new SimpleSchema({
	returnTripType: {
  		type: String,
  		allowedValues: ["Round Trip","One Way", "Multi-Leg"],
  		defaultValue: "Round Trip",
		autoform: {
			type: "select-radio-inline",
			options: 'allowed'
		}
  	}
});
```

As I mentioned before, the console.log only runs once, returning undefined.  I can select the various returnTripTypes options and the getFieldValue function never fires.  Since getFieldValue only returns undefined, template "Route2" does not display when the page loads even though the returnTripType is set to the default value of "Round Trip".

**Comment by williamkhshea** [comment]
@BradRyan Try using getFieldValue without the formId in quote.js:

```
var returnType = AutoForm.getFieldValue("returnTripType");
```

From the changelog:
```
Compatibility break: The function signature for AutoForm.getFieldValue is reversed from (formId, fieldName) to (fieldName, [formId]) with formId optional. You should not pass the formId argument when using it in a helper that is run within the context of the form.
```

**Comment by j3omal** [comment]
I am seeing the same the same issue as @BradRyan.  When I remove the formId from getFieldValue call, I see this error in the console:

```
Exception in template helper: TypeError: Cannot read property 'clean' of undefined
    at Object.autoFormGetFormValues [as getFormValues] (http://localhost:3000/packages/aldeed_autoform.js?95e4d3c1e4a248502de2befc9436a32b15999fa3:2188:5)
    at Object.autoFormGetFieldValue [as getFieldValue] (http://localhost:3000/packages/aldeed_autoform.js?95e4d3c1e4a248502de2befc9436a32b15999fa3:2250:22)
    at Object.Template.scoresPage.helpers.totalScore (http://localhost:3000/client/templates/seasons/scores_page.js?4fa83b81b6270e5226ac78347e2c608a7d0a6f67:33:21)
    at http://localhost:3000/packages/blaze.js?b0fa84e3d7a352d325a81441bf2b6dd19cb7e554:2787:16
    at http://localhost:3000/packages/blaze.js?b0fa84e3d7a352d325a81441bf2b6dd19cb7e554:1607:16
    at http://localhost:3000/packages/blaze.js?b0fa84e3d7a352d325a81441bf2b6dd19cb7e554:2835:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?b0fa84e3d7a352d325a81441bf2b6dd19cb7e554:3383:12)
    at http://localhost:3000/packages/blaze.js?b0fa84e3d7a352d325a81441bf2b6dd19cb7e554:2834:21
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
```

HTML:
```
<template name="scoresPage">

	Enter Scores for Week:
	<select class="form-control" id="selectWeek">
	  <option value="0">1</option>
	  <option value="1">2</option>
	  <option value="2">3</option>
	</select>

	{{#autoForm id="updateScores" type="update" collection="Seasons" doc=selected}}

	  {{#afEachArrayItem name=selectedWeek }}
		{{> afQuickField name=this.name label=holeLabels}}
		Total Score: {{totalScore this.name}}
	  {{/afEachArrayItem}}

          <button type="submit" >Submit</button>
        {{/autoForm}}

</template>
```

JS:
```
Template.scoresPage.helpers({
  holeLabels: function() {
    var holeLabel = 'Hole ' + String(this.index + 1);
    return holeLabel;
  },
  selectedWeek: function() {
    return Session.get("selectedWeek");
  },
  totalScore: function(fieldName) {
    return AutoForm.getFieldValue(fieldName);
  }
});

Template.scoresPage.events({
    "change #selectWeek": function (event, template) {
        var week = $(event.currentTarget).val();
        Session.set("selectedWeek", "schedule." + week + ".scores");
    }
});
```

Schema:
```
Schemas = {};

Schemas.Season = new SimpleSchema({
    userId: {
        type: String,
        optional: true
    },
    userName: {
        type: String,
        optional: true
    },
    tenantId: {
        type: String,
        optional: true
    },
    year: {
        type: String,
        optional: true
    },
    teamName: {
        type: String,
        optional: true,
        label: "Team Name"
    },
    schedule: {
        type: [Object],
        optional: true
    },
    "schedule.$.week": {
        type: Number,
        optional: true,
        defaultValue: 1
    },
    "schedule.$.totalScore": {
        type: Number,
        optional: true,
        defaultValue: 1
    },
    "schedule.$.scores": {
        type: [Number],
        optional: true
    }
});

Collections = {};

Seasons = Collections.Seasons = new Mongo.Collection("seasons");

Seasons.attachSchema(Schemas.Season);
```

**Comment by arvi** [comment]
Hi all. I had this problem too that took me hours to fix haaaa!
What I did was try to open Chrome's console tool while still in my meteor project and try the ff:

```javascript
AutoForm.getFieldValue('helloField'); //undefined
AutoForm.getFieldValue('helloField', 'helloForm'); //undefined
AutoForm.getFieldValue('helloForm', 'helloField'); //yey! it works
```

I tried to do 

```
meteor update aldeed:autoform
```
but it won't update (_Your packages are at their latest compatible versions._)

After that, I followed meteor's suggestion which is to

```shell
meteor add aldeed:autoform@5.0.2
 => Errors while adding packages:

While selecting package versions:
error: conflict: constraint aldeed:autoform@4.2.2 is not satisfied by 5.0.2.
Constraints on aldeed:autoform come from:
<top level>
robertlowe:autoform-pickadate@0.1.1
```

even the 5.0.0 is not satisfied. Now I'm currently stuck with 4.2.2 and current solution is 

```javascript
AutoForm.getFieldValue('helloForm', 'helloField'); //yey! it works
```

Hope this helps!

**Comment by miri-am** [comment]
Having exact the same issue. Calling AutoForm.getFieldValue from console delivers the current field value, however nothing changes reactively from the Template.helper function. Using version  5.0.2 and trying to get the value of a select2 box.

**Comment by aldeed** [comment]
@j3omal, there could be some issue with using it on array fields. Not sure.

@BradRyan, I'm assuming yours works when you remove formId arg.

@miri-am, it may not work reactively with select2, but if you use the latest version of my autoform-select2 pkg with select2 4.0, I think it probably will.

**Comment by miri-am** [comment]
@aldeed thanks. After trying it without the formId arg, it also work with select2. Why is it not working "reactively" as documented: ``` AutoForm.getFieldValue(fieldName, [formId]) ```?

**Comment by aldeed** [comment]
@miri-am, you'll need to post a link to a reproduction repo if it's not working reactively. We can only cause reactive update if we know the value changed, and with third party libraries, sometimes the events we're using don't fire so we don't know the value changed.

**Comment by miri-am** [comment]
sorry, I was not clear enough. It DOES work reactively with select2. I was just wondering why the formId as a parameter to getFieldValue breaks functionality - it only works without it. Anyways, for me it is working now. Thanks

**Comment by aldeed** [comment]
oh, ok. I'm not exactly sure why it breaks with formId. It's possible it could be fixed, but for now it's best to omit if executing within the reactive context of a form.

**Comment by BradRyan** [comment]
@aldeed @williamkhshea  Hmmm well my inclusion of the form Id is very like the issue then.  Thanks for the input.

My concern is that I have a part of my app where I am using multiple forms with the same schema in the same template.  Will having multiple instances of the same form within a single template cause issues?  I reverted back to an older version, so I'll have to test to see. 

Here is the scenario... I'm trying to create a multi-leg route, each route with an origin, 2 potential waypoints, a destination, and a departTime (all part of the same schema).  The user can create multiple routes, so rather than having a unique template for each route, I was generating a new form with a unique route Id.  I put a simplified example below.

html
```
<template name="QuoteTool">
{{#each RouteLeg}}
   {{> RouteTemplate}}
{{/each}}
</template>

<template name="RouteTemplate">
{{#autoForm schema="DepartRouteQuote" id=routeNumber}}
{{> afQuickField name='pickup' placeholder="Pickup Location"}}
{{> afQuickField name='departTime' placeholder="Pickup Time" value=getDepartTime}}
{{> afQuickField name='address' id="waypt1" class="waypoint" placeholder="Location #2"}}	
{{> afQuickField name='address' id="waypt2" class="waypoint" placeholder="Location #3"}}
{{> afQuickField name='dropoff' placeholder="Dropoff"}}
{{/autoForm}}
</template>
```
js
```
Template.RouteTemplate.helpers({
  var routeNo = this.routeNumber;
  var departTime = AutoForm.getFieldValue(routeNo, "departTime");  // This is the I have it set up in version aldeed:autoform@4.2.2
  var departTimeNew = AutoForm.getFieldValue("departTime"); // This is how I should set it up in version 5.0 +

  // do something with depart time
});

```

So my QuoteTool template potentially has up to 5 forms with the same Schema.  If I understand correct, var departTimeNew that I wrote out in my helper should be reactive and grab from the correct form.  Right?  And if I have a helper outside of the form, I can call var departTimeNew = AutoForm.getFieldValue("departTime", formId); and it will still work reactively?

Sorry for my confusion.  I missed the bit about excluding formId for reactivity.  I won't be able to test my case until later this week or the weekend.  Thanks!

**Comment by aldeed** [comment]
@BradRyan I think multiple forms with same schema should be fine. The helpers look up the tree to the closest containing autoform. My goal is eventually to not require an `id` on the form but allow passing a selector when not within the form. But for now many things rely on a required `id` still.

**Comment by kingkevin** [comment]
Spent some time debugging this today. 

Theres an expectation that changes in an afFormGroup template must be triggered by the actual HTML input DOMNode. Wherever the data-schema-key is defined within your template.

It would be nice if reactivity was tracked through the `AutoForm.addInputType` `valueOut` method. 

But if you're running into this problem, be sure that changes to your input element are propagating up.

**Comment by ChJJin** [comment]
It does not rerun while calling ```AutoForm.getFieldVale``` inside an autorun callback. 
The code looks like:
```javascript
Template.myTemplate.onCreated(function(){ // There is an autoform in this template
  this.autorun(function(){
    console.log(AutoForm.getFieldValue('title'));
  });
});
```
It does not rerun after the first run even when I add the ```formId``` (But it works if I put the code in a helper).

**Comment by alexandrzavalii** [comment]
@ChJJin I have the same problem. I can not run it onCreated or onRendered.
Did you find a workaround?

**Comment by rafinskipg** [comment]
@aldeed  Yes there are issues with array fields, (When removing items in the middle of the array) There are several bugs opened with this issue. I have spent a couple of days looking at the issues XD
