### ISSUE TITLE
Displaying error messages from server method

### ISSUE THREAD

**Issue by stizzlestizzle** [aldeed/meteor-autoform#769]
Thanks for this great package. Everything works well, but my attempts to display usable validation errors fail for server side validation.

I am using autoForm like so:

```
{{#autoForm
    schema="MySchema"
    id="myForm"
    type="method"
    meteormethod="myMethod"
    }}

    (...)

    {{> afQuickField name="profile.inviteCode"}}
    {{> afQuickField name="profile.name"}}

    (...)

{{/autoForm}}
```

Frontend validation works fine. I need to validate certain fields on the server and this is where problems start. I experience similar issues in displaying those errors as mentioned in #668 and #755 but none of the workarounds or solutions work properly. I tried:

**Preferred method: addInvalidKeys()**
```
AutoForm.hooks({
  myForm: {
    onError: function(formType, error) {
      var validationContext = AutoForm.getValidationContext(this.formId);

      if (typeof error.reason === 'string') {
        if (error.reason.indexOf('invalidCode') !== -1) {
          validationContext.addInvalidKeys([{name: 'profile.inviteCode', type: 'invalidCode'}]);
        }
      }
    }
  }
});
```
* After submitting the form which will fail server side validation, the error is returned correctly and flashes for a fraction of a second on the respective field.
* After submitting a second time, the error is displayed correctly.
* I can re-submit the form as often as I want and the server method gets called every time - this is good! Read on to find out why I mention this ;-)

**Alternative 1 using only addStickyValidationError()**
```
AutoForm.hooks({
  myForm: {
    onError: function(formType, error) {
      if (typeof error.reason === 'string') {
        if (error.reason.indexOf('invalidCode') !== -1) {
          this.addStickyValidationError('profile.inviteCode', 'invalidCode');
        }
      }
    }
  }
});
```
* If I submit the form, server method is called but no errors shown on the field.
* If I submit for a second time, server method is NOT called but the error is displayed correctly.
* Unfortunately, on key up the message does not disappear (after all, it is a stickyValidationError - I get that, but it might confuse users). However, I could live with that, if there wasn't...
* ... submitting the form again does not work. The user has now probably entered a correct value, but the server method is never called again.

**Alternative 2 using addStickyValidationError() + validateField()**
```
AutoForm.hooks({
  myForm: {
    onError: function(formType, error) {
      if (typeof error.reason === 'string') {
        if (error.reason.indexOf('invalidCode') !== -1) {
          this.addStickyValidationError('profile.inviteCode', 'invalidCode');
          AutoForm.validateField(this.formId, 'profile.inviteCode');
        }
      }
    }
  }
});
```
* The error message is displayed immediately. But...
* ... the server method is never called again after re-submitting the form.
* (so this is pretty much the same as alternative 1 with the only difference that the error is actually shown immediately)

I hope to find some help here. Are there any other workarounds I might try to use? It must be possible to correctly display an error message and being able to submit the form again somehow.

Thanks in advance

**Comment by aldeed** [comment]
Your last method (sticky + workaround for sticky bug) should work fine. You just have to add a hook (most likely a "before.method" hook in your case) where you remove the sticky validation error upon the next submit. You might also want to remove it on keyup for whatever field it applies to. This logic is specific to each situation so autoform can't do it for you.

**Comment by MichaelJCole** [comment]
Hey, sorry to be dense.  How do I convert 'invalidCode' into an human readable error?

I'm using AutoForm with type="method"
```
Meteor.methods({
  'insertOther': function(obj) {
    if (! SimpleSchema.RegEx.Email.test(obj.email) ) {
      throw new Meteor.Error('This email doesn\'t look valid');
    }
});
```
And in the AutoForm.hooks:
```
  onError: function(formType, error) {
    if (error.errorType && error.errorType === 'Meteor.Error') {
      this.addStickyValidationError('email', error.error);
      AutoForm.validateField(this.formId, 'email');
    }
  },
```
I see the error come back, but the form shows `Unknown validation error` instead of the message

Thanks!

**Comment by afriC84** [comment]
When implementing it like the "Preferred method" (above), I also have the problem, that the validation-message next to the field only flashes for a split-second, when I submit for the first time. After that it seems to work as expected.

**Comment by pdiniz13** [comment]
This was marked as closed but the bug is still there.
