### ISSUE TITLE
A way to disable fields in afQuickForm

### ISSUE THREAD

**Issue by abtx** [aldeed/meteor-autoform#772]
Hi, is there a way to use only specific fields using afQuickForm for a complex object, as in QuickForm (fields="name,hours")? I've got an object in my schema with few different fields, but want to display only specified ones. I call entire object with {{> afQuickField name='milestones'  fields="name,hours"}}, so I cannot use hidden anywhere. How can I deal with that? Thanks!

**Comment by aldeed** [comment]
Yes, dot notation will work. There is a similar example on [this page](http://autoform.meteor.com/qfdetails).
