### ISSUE TITLE
AutoForm.Utility.dateToDateStringUTC doesn't handle years < 1000

### ISSUE THREAD

**Issue by jfly** [aldeed/meteor-autoform#774]
See the following behavior of [AutoForm.Utility.dateToDateStringUTC](https://github.com/aldeed/meteor-autoform/blob/master/utility.js#L356):

```javascript
var d = new Date();
d.setFullYear(1);
AutoForm.Utility.dateToDateStringUTC(d)
"1-03-15"
```

When using `input type="date"` combined with `autosave=true`, this can cause a `The specified value '2-03-14' does not conform to the required format, 'yyyy-MM-dd'` message when typing in today's date (3/14/2015), because the first valid date chrome sees is 3/14/2, which causes autoForm to do its thing and break.

Am happy to submit a PR to fix this if interested. The correct thing to do here would be to return "0001-03-15" in the example, which will make chrome happy.

**Comment by aldeed** [comment]
If you do a PR, please fix dateToDateString function, too, and add tests for this. Otherwise I will fix as soon as I have some time.
