### ISSUE TITLE
AutoForm.getCurrentDataForForm gets null value for removed array items

### ISSUE THREAD

**Issue by williamkhshea** [aldeed/meteor-autoform#775]
I am removing some items of an array fields from an existing document and the resulting document fills those removed array items with null after submit.

The root cause is AutoForm.getCurrentDataForForm gets null values for the removed array items when the form is submitted and those array items are then $unset to null.

![image](https://cloud.githubusercontent.com/assets/4775489/6654974/61e5cc36-cb22-11e4-8459-dba8a87b166a.png)

**Comment by aldeed** [comment]
Probably related to #765

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by williamkhshea** [comment]
Works now. Thanks.

**Comment by hockeyj85** [comment]
I think that this bug still exists in AutoForm 5.1.2.

It only occurs if you remove elements other than the final element in the array.

I've put together a minimal example at: https://github.com/hockeyj85/autoforms-5-array-bug

**Comment by jankapunkt** [comment]
I have the same issue on a multi upload when no "plus" has been clicked. After adding a second entry it works @autoform 6.2.0
