### ISSUE TITLE
problem with update on array field?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-autoform#777]
I have problem in array field like this:
```
// Schema
roles: {
        type: [String],
        autoform: {
            type: "select-multiple"
        }
    }

// Form udpate
{> afQuickField name='roles' options=roleList size=5}}
```
I want to update by replacing the new array in old array of all (not push).
please help me.

**Comment by yuomtheara** [comment]
After i test, i think that auto form update array field with index of array.

**Comment by aldeed** [comment]
Might be related to #765

**Comment by yuomtheara** [comment]
I seem don't understand.
Ex: in my multiple select = [A, B, C, D]
- the time I insert by selected [C, D] (in my db = [C, D])
- after that I update by selected [A, B] don't selected [C, D], but in db = [A, B, C, D]
I think that in my db = [A, B]

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by nicolaslopezj** [comment]
It works using keep array, without its not working

```js
localization: {
    type: [String],
    autoform: {
        keepArrays: true,
        noselect: true,
        options: {
            'a': 'a',
            'b': 'b',
            'c': 'c'
        }
    }
},
```

**Comment by yuomtheara** [comment]
Now work fine.
Very thanks...
