### ISSUE TITLE
Excluding fields on nested schema

### ISSUE THREAD

**Issue by rustanacexd** [aldeed/meteor-autoform#778]
I have a nested schema and I want to exclude the field of the nested schema. how?

**Comment by elGusto** [comment]
You can use the omitFields or the fields attributes of the quickform.
i.e: {{>quickForm type="insert" ... omitFields="nestedObject.nestedProp"}}

Or if you want it to be omitted for every form for the schema you can specify in the schema the autoform object like so:
```javascript
autoform: {
      omit: true
}
```

**Comment by rustanacexd** [comment]
@elGusto thank you very much got it now!
