### ISSUE TITLE
Uncaught TypeError: Cannot read property 'formValues' of undefined.

### ISSUE THREAD

**Issue by aclever** [aldeed/meteor-autoform#781]
Hello. Have issue.
"Uncaught TypeError: Cannot read property 'formValues' of undefined" in browser console. All seems like works but I think it's not well.

Please tell me, if anybody got the same issue and how can I fix it.
Thanks.

**Comment by aldeed** [comment]
It is not an error to worry about for now, but it should go away in next autoform release.

**Comment by pociej** [comment]
+1
