### ISSUE TITLE
Array of objects question

### ISSUE THREAD

**Issue by dkmooers** [aldeed/meteor-autoform#783]
So I'm tracking recurring item "last done dates" for clients, and trying to create an edit form for "clients" that will eventually have the following object format - this is an example client (person):

    {
    	name: 'Jingo Starr',
    	notes: 'Some notes here',
    	recurringItems: [
    		{
    			_id: 'xyz',
    			name: 'OKA',
    			lastDoneDate: '2014-09-15'
    		},
    		{
    			_id: 'abc',
    			name: 'LPO',
    			lastDoneDate: '2015-03-12'
    		},
    		{
    			_id: 'qrx',
    			name: 'FNP',
    			lastDoneDate: '2014-07-12'
    		}
    	]
    }

I'm trying to build the autoform using these schemas:

    ClientRecurringItemSchema = new SimpleSchema ({
    	name: {
    		type: String,
    		label: 'Name',
    		autoform: {
    			type: "hidden"
    		}
    	},
    	_id: {
    		type: String,
    		label: "id",
    		autoform: {
    			type: "hidden"
    		}
    	},
    	lastDoneDate: {
    		type: Date
    	}
    });
    
    ClientSchema = new SimpleSchema ({
    	name: {
    		type: String,
    		label: 'Name',
    		trim: false
    	},
    	notes: {
    		type: String,
    		autoform: {
    			rows: 5
    		},
    		optional: true
    	},
    	recurringItems: {
    		type: [ClientRecurringItemSchema]
    	}
    });

And here's my autoform code:

    +autoForm collection="Clients" type="method-update" meteormethod="editClient" id="edit-client-form" doc=this buttonContent="Save" buttonClasses="btn btn-success"
    	+afQuickField name="name"
    	+afQuickField name="notes"
    	//- +afQuickField name="recurringItems"
    	each visibleRecurringItems
    		h4= name
    		+afQuickField name="recurringItems"
    	+saveButton

But that's rendering an "afArrayFieldInput" for each recurring item. What I'm trying to get is this:

Name: ______ (string)

Notes: ______ (textarea)

OKA
Last Done Date: _____ (date input)
[_id - this is a hidden value that should grab the _id associated with this OKA recurring item]

LPO
Last Done Date: _____ (date input)
[_id - this is a hidden value that should grab the _id associated with this LPO recurring item]

FNP
Last Done Date: _____ (date input)
[_id - this is a hidden value that should grab the _id associated with this FNP recurring item]

I think what I want is an array field, since recurringItems should conceptually be of the type [ClientRecurringItemSchema], but I don't need +/- buttons, since I should only have exactly three recurring item last-done-date inputs in this instance, because it's dependent on how many recurringItems there are associated with this user's account. Any help on how to accomplish this? Do I need to just do something like this and skip validation?

    +autoForm collection="Clients" type="method-update" meteormethod="editClient" id="edit-client-form" doc=this buttonContent="Save" buttonClasses="btn btn-success"
    	+afQuickField name="name"
    	+afQuickField name="notes"
    	each visibleRecurringItems
    		h4= name
    		| Last completed:
    		input(type="date" data-id="{{this._id}}")
    	+saveButton

**Comment by dkmooers** [comment]
Or maybe I need to use a custom template?

**Comment by aldeed** [comment]
The main point of afArrayField is to add/remove a variable number of array fields. If you have an exact number, you can simply create the fields for them. So yes, your code at the end is pretty close, but you should use autoform to create the input. I think it would be something like this within the each, in place of the `input` you have:

```html
+afQuickField name=dateFieldName type="date"
+afQuickField name=idFieldName type="hidden" value=_id
```

Where you'll have to set `dateFieldName` and `idFieldName` in the object returned by visibleRecurringItems. These should be, for example, `recurringItems.0.lastDoneDate` and `recurringItems.0._id`, where the number is 0, 1, 2 based on the array index. You can probably use `_.map` for that.

A custom afArrayField template may also work. You'd have to copy the built in one and then remove the +/- buttons, etc.
