### ISSUE TITLE
Problem with afArrayField custom template when migrating to autoform 5

### ISSUE THREAD

**Issue by nate331** [aldeed/meteor-autoform#784]
In Autoform 4 I was able to do the following: I built my custom afArrayField template to which I could pass a "subtemplate". 
```
{{> afArrayField name="myEmployers" id="employers" template="customArray" subtemplate="company"}}
```
The subtemplate specified the layout of each array item. 
```
<template name="company">
    {{> afQuickField name=current.name}}
    {{> afQuickField name=current.position}}
    <div class="row">
        <div class="col-md-6">
            {{> afQuickField name=current.startDate}}
        </div>
        <div class="col-md-6">
            {{> afQuickField name=current.endDate}}
        </div>
    </div>
</template>
```
I used
```
{{> UI.dynamic template=../atts.subtemplate}} 
```
in my custom template to do this (that's the only thing I changed from the default bootstrap template):
```
<template name="afArrayField_customArray">
    <div class="panel panel-default">
        <div class="panel-heading">{{afFieldLabelText name=this.atts.name}}</div>
        {{#if afFieldIsInvalid name=this.atts.name}}
        <div class="panel-body has-error">
            <span class="help-block">{{{afFieldMessage name=this.atts.name}}}</span>
        </div>
        {{/if}}
        <ul class="list-group">
            {{#afEachArrayItem name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
            <li class="list-group-item autoform-array-item">
                <div>
                    <div class="autoform-remove-item-wrap">
                        {{#if afArrayFieldHasMoreThanMinimum name=../atts.name minCount=../atts.minCount maxCount=../atts.maxCount}}
                        <button type="button" class="btn btn-primary autoform-remove-item"><span class="glyphicon glyphicon-minus"></span></button>
                        {{/if}}
                    </div>
                    <div class="autoform-array-item-body">
                        <!--{{> afQuickField name=this.name label=false options=afOptionsFromSchema}}-->
                        {{> UI.dynamic template=../atts.subtemplate}} 
                    </div>
                </div>
            </li>
            {{/afEachArrayItem}}
            {{#if afArrayFieldHasLessThanMaximum name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
            <li class="list-group-item">
                <button type="button" class="btn btn-primary autoform-add-item" data-autoform-field="{{this.atts.name}}" data-autoform-minCount="{{this.atts.minCount}}" data-autoform-maxCount="{{this.atts.maxCount}}"><span class="glyphicon glyphicon-plus"></span></button>
            </li>
            {{/if}}
        </ul>
    </div>
</template>
```

Now in Autoform 5 it is not working properly anymore. The subtemplate is used, but the afQuickFields in the subtemplate do not render correctly anymore: on the inputs the form-control class is missing). That's what the resulting html of one of the fields looks like:
```
<div class="form-group" data-required="true">
    <label for="wGQXRPML9hS9wTPue" class="control-label">Company Name</label>
    <input type="text" name="myEmployers.0.name" id="wGQXRPML9hS9wTPue" required="" data-schema-key="myEmployers.0.name">    
    <span class="help-block"></span>
</div>
```

How can I get this working again? Did I miss something on the migration?

**Comment by aldeed** [comment]
A lot of the internal handling as far as how it looks up the tree for templates and such has changed. Can you just add `template="bootstrap3"` to all of your `afQuickField`s in the "company" template?

**Comment by nate331** [comment]
That worked. Thanks. 
However, quite a few of my custom autoform templates have some problems with autoform 5. I will have to investigate in detail what's going on.

**Comment by lucatros** [comment]
You might want to check the change log. There you'll find the info on what changes were introduced to templates.

**Comment by nate331** [comment]
I already did all the migration changes proposed in the change log. I guess regarding custom templates there are more changes not documented in the change log.

**Comment by aldeed** [comment]
It's certainly possible I missed some. Lots of internal changes, and it's not always obvious what they affect. I can add to the change log if you figure out what's missing.

**Comment by nate331** [comment]
I found the following changes which should go into the changelog:
- AutoForm.find() does not exist anymore
- AutoForm.getFieldValue(fieldName, [formId]): if formId is in the context you are not allowed to pass formId as second parameter otherwise it did not work properly. I thought I could still pass it if I want to.
- noselect="1" not working anymore; you have to use noselect=true (this was the reason why most of my custom templates did not work anymore)

Another thing I noticed: When saving a form, it seems to disappers for a few milliseconds. This is a bit annoying if you stay on the same route when submitting. The form seems to flicker then when submitting.

**Comment by aldeed** [comment]
Thanks @nate331. The `getFieldValue` stuff was already mentioned in changelog, but I updated it to include the other changes you mention.

I'm not sure about the flickering. You should submit that as a separate issue with a reproduction.

**Comment by thearabbit** [comment]
I need the example to custom array field to.
Could you like show link of your source or `meteor pad`?
Thanks...
