### ISSUE TITLE
AutoForm.getFieldValue causes infinite rerun of Template helper

### ISSUE THREAD

**Issue by gandev** [aldeed/meteor-autoform#785]
If i try to access the value of a form field (AutoForm.getFieldValue()) inside a helper, which returns the possible options for a inputField, the helper reruns indefinitely...

For a quick reproduction:

Template:

```handlebars
{{#autoForm schema="Schema" doc=doc id="form" validation="submit"}}
    {{> afFieldInput name="refId"}}
    {{> afFieldInput name="description" options=optionsByRefId}}
{{/autoForm}}
```

Schema and helpers:

```javascript
Schema = new SimpleSchema({
  refId: {
    type: String,
    optional: true
  },
  description: {
    type: String,
    optional: true
  }
});

Template.body.helpers({
  doc: function () {
    return {
      refId: '001',
      description: 'test'
    };
  },
  optionsByRefId: function () {
    var refId = AutoForm.getFieldValue('refId'); // <-- CAUSES INFINITE LOOP
    
    console.log('DO SOMETHING WITH REFID', refId);
    
    return [];
  }
});
```

A quick fix, was to change the following code (located in the AutoForm.getFieldValue() function), but i'm not sure what side effects this will cause...

```javascript
var doc = AutoForm.getFormValues(formId, template);

// --> TO

var doc;
Tracker.nonreactive(function() {
  doc = AutoForm.getFormValues(formId, template);
});
```

**Comment by ssteinerx** [comment]
I'm not sure if it's the same issue, but I've noticed that the helper runs waaaaaaaay more times than is necessary.  Like 10 times for each page reload/reactive event even if the event has nothing to do with the form/fields's data.

S

**Comment by aldeed** [comment]
I can take another look at minimizing the reruns. It's a fine line because we're trying to be sure to rerun whenever the "value changed" but that's not always a clearcut thing for some input types. So we err on the side of overreacting right now, but maybe caching the previous value and comparing is what's needed. Maybe set up ReactiveVars to take care of that.

**Comment by gandev** [comment]
I also noticed some unnecessary reruns. But the problem i have described is that the helper never stops rerunning... i have to kill my browser tab because of that!

**Comment by aldeed** [comment]
@gandev, I'm assuming that my proposed fix will fix both issues. Infinite rerunning is likely the result of rerunning when the value hasn't actually changed.

**Comment by gandev** [comment]
@aldeed It's a weird reactivity problem in my eyes. I briefly looked/debugged over the code that triggers the Tracker.Dependencies established by getFieldValue and noticed that these are not rerunning the helper. I'm not saying that there isn't potential for checking if something actually changed but i think the real problem is with the getFormValues() function in this case.

**Comment by tijs1993** [comment]
I think I have the same problem.
I have a selectbox (quickform) that only appears when a radiobutton is selected. In another textfield, the value of the chosen option must be displayed. 
I've tried out with a console.log of AutoForm.getFieldValue(select), because nothing happened, and i couldn't do anything anymore.
Result (see picture, token 5-10 seconds after the log appears): an infinite loop, the moment that I click on the radiobutton. ('undefined', because the automatic (select one)-option has no value.) 
I can't do anything on the page anymore, and the only way to stop the loop is by killing my browser.

This is started when I update autoform to 5.0.2. Any ideas for the solution?
![autoformproblem](https://cloud.githubusercontent.com/assets/6057822/6708669/b9c00154-cd72-11e4-95ef-30e437fae07c.png)

**Comment by dbernhard** [comment]
+1. I tried looking into the internals for a fix but it has eluded me so far. Fixed the problem for now with a rollback to -v 4. Either way, thanks for a great package.

**Comment by arvi** [comment]
Hi @aldeed, I'm getting infinite reload after updating to 5.0... hmmm maybe it's also related?

```javascript
    region: {
        type: String,
        autoform: {
            type: "select",
            options: function () {
                if (Meteor.isClient) {
                    var docId = '';

                    docId = AutoForm.getFieldValue('center'); 
                        //replaced 4.2.2 AutoForm.getFieldValue('regionForm', 'center');
                        //trying out AutoForm.getFieldValue('center', 'regionForm'); results to no form id error

                    return Regions.find({center: docId}).map(function (c) {
                            return {label: c.name + ' (' + c.code + ')', value: c._id};
                   });
                }
            }
        }
    },

```

Maybe I 'll rollback to 4.2.2 just like @dbernhard for the meantime.

**Comment by miri-am** [comment]
I updated to the latest version with the patch from @gandev, but I still get infinite loops.
The following simplified code creates a "product" with a number of "communication" elements that can be of type "photoAction" or "textAction". I created an own template "afArrayField_communication" for that, which adds based on the selection of "type" dynamic templates of "photoAction" or "textAction". The "currentActionType" helper gets called multiple times whenever an element is added to afArrayField_communication and eventually creates an infinite loop (sometimes after the second element is added. Would be really thankful if somebody has a hint how to debug this or how to design this differently.

The schema is the following:

```javascript
Schemas.Products = new SimpleSchema({
    communication: {
        type: [Schemas.Communication],
        optional: true
    }
});

Schemas.Communication = new SimpleSchema({
    type: { 
        type: String,
        optional: true,
        autoform: {
           firstOption: "Choose Action",  
           options: function() {
                return [{
                    label: "Text",
                    value: "text"
                }, {
                    label: "Photo",
                    value: "photo"
                }];
            }
        }
    }
});
```
The templates are the following:

```html
<template name="addProduct">
            {{#autoForm id="addProductForm" type="insert" collection="Products"}} 
                {{> afArrayField name='communication' id="nothingForm" template="communication"}}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create Product</button>
            </div>
            {{/autoForm}}
</template>

<!--copied and adjusted from https://github.com/aldeed/meteor-autoform/tree/master/templates/bootstrap3/components/afArrayField-->
<template name="afArrayField_communication"> 
    <div class="panel panel-default">
        <div class="panel-heading">{{afFieldLabelText name=this.atts.name}}</div>
        {{#if afFieldIsInvalid name=this.atts.name}}
        <div class="panel-body has-error">
            <span class="help-block">{{{afFieldMessage name=this.atts.name}}}</span>
        </div>
        {{/if}}
        <ul class="list-group">
            {{#afEachArrayItem name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
            <li class="list-group-item autoform-array-item">
                        {{#if afArrayFieldHasMoreThanMinimum name=../atts.name minCount=../atts.minCount maxCount=../atts.maxCount}}
                        <button type="button" class="btn btn-block btn-danger autoform-remove-item">
                        Remove communication element
                        </button>
                        {{/if}}
                    <div class="autoform-array-item-body">
                        {{> afQuickField name=this.current.type class="form-control"}}
                        {{> UI.dynamic template=currentActionType}}
                </div>
            </li>
            {{/afEachArrayItem}} 

            {{#if afArrayFieldHasLessThanMaximum name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
            <li class="list-group-item">
                <button type="button" class="btn btn-success autoform-add-item" data-autoform-field="{{this.atts.name}}" data-autoform-minCount="{{this.atts.minCount}}" data-autoform-maxCount="{{this.atts.maxCount}}">
                 Add communication element
                </button>
            </li>
            {{/if}}
        </ul>
    </div>
</template>

<template name="textAction">
</template>

<template name="photoAction">
</template>
```

This is the helper that returns the current selected type:
```javascript
Template.afArrayField_communication.helpers({
    currentActionType: function(){
        console.log("currentActionType called"); //this gets called increasingly whenever an element is added/removed to/from the afArrayField_communication template and eventually creates an infinite loop that freezes the browser
        return AutoForm.getFieldValue(this.current.type)+"Action" || "nothing selected";
    }
})
```

**Comment by miri-am** [comment]
@gandev What about the approach you suggested above. Did you encounter any side-effects- because when I remember correctly this seemed to be working for me!?

```javascript
var doc = AutoForm.getFormValues(formId, template);

// --> TO

var doc;
Tracker.nonreactive(function() {
  doc = AutoForm.getFormValues(formId, template);
});
```

**Comment by gandev** [comment]
@miri-am no, not that i know of
but i wanted to be sure and investigated why my problem occurred. maybe there are other calls to Blaze.getData() who cause your/other problems, e.g. AutoForm.getCurrentDataForForm() which is called quite a lot, even in Autoform.getValues()

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by miri-am** [comment]
Thanks @aldeed. That has resolved the infinite loops behavior for the situation that I decribed.

**Comment by samdieck** [comment]
I had this infinite loop problem as well in 5.3.2 with the following line inside a helper:
    
    var p_id = AutoForm.getFieldValue(this.name.replace('.task_id', '.project_id')).project_id;

However, if I change the above line to the following, it works just fine.
    
    var p_id = AutoForm.getFieldValue(this.current.project_id);

Hope it helps others.

**Comment by brendonlamb** [comment]
Just to get some clarification- I'm having this rerun problem, maybe there's a better way but basically I need the "max" value in a field to include what it is in that field... I was trying to define this in the schema... is that no going to work?

**Comment by jpmelnik** [comment]
I'm having reruns into:

```
autoform : {
      type: "select",
      options: function () {
       console.log('múltiple reruns here');
      }
}
```
