### ISSUE TITLE
Not working: {{#autoform ..  template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"

### ISSUE THREAD

**Issue by silentwarrior** [aldeed/meteor-autoform#787]
In one of the examples you have this, but this doesnt actually work :
{{> quickForm id="demo" schema=schemaFromJSON type="method" meteormethod="demoSubmission" template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}

I am using, and it does not work, it will show the labels above the textfields, and ignore the extra rulls after the type="update" : 
{{#autoform collection="Keys" doc=this type="update" template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}

**Comment by aldeed** [comment]
It works for quickform, but you're using an autoform. They don't have theme templates so the `template="bootstrap3-horizontal"` doesn't mean anything in your case. Instead you should put the `template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"` on each `afFormGroup` within your autoform.

**Comment by silentwarrior** [comment]
I am a little confused as to why there is 2 versions, a {{#autoform}} and a {{#quickform}}

**Comment by aldeed** [comment]
The autoForm is the basic form wrapper in which you can design your own form. The quickForm renders the form for you based on the fields in the schema, using a theme template.
