### ISSUE TITLE
update-pushArray does not update Collection

### ISSUE THREAD

**Issue by sjt-mbed** [aldeed/meteor-autoform#788]
I spent 2 frustrating days trying to make quickForm\autoform update-puashArray work and finally decided to check out with http://autoform.meteor.com/updatepush source code running locally on my dev box. 
I was disappointed to see that with the latest versions of Meteor+autoform, this example also exhibits the same problem. Can you take a look pls?

**Comment by aldeed** [comment]
By latest, do you mean Meteor 1.0.4? I haven't done any testing against that release yet.

**Comment by sjt-mbed** [comment]
I initially saw the problem with Meteor 1.0.3.2 and then upgraded to 1.0.4 and still see the same issue.

**Comment by lucatros** [comment]
I think that by latest he refers to Autoform 5.x. ````udpate-pushArray```` not working here either.

**Comment by sjt-mbed** [comment]
Does this work for you in a previous Autoform version Lucatros?
If so, which one?

**Comment by lucatros** [comment]
I just tested it on version 5 and it's not working. I'm now testing it on Autoform 4.2.2 and it's not working either. I cloned the autoform demo repository and on my end the update-pushArray is not showing the selected scope. Instead it's showing the entire schema.

**Comment by lucatros** [comment]
@aldeed Any idea why ````update-pushArray```` is working on the live Demo but not on the repository?

**Comment by lucatros** [comment]
@sjt-mbed What about you? Did you managed to make it work in any version?

**Comment by sjt-mbed** [comment]
Not yet.

**Comment by aldeed** [comment]
It is new in AF 5.0, so it would not work prior to that. I'll try running the demo locally to see what's up.

**Comment by aldeed** [comment]
Running the demo code that I just pushed to master, pushArray seems to work fine. Can someone create an example repo that is not working? There's currently a bug with autoform on Meteor 1.0.4 so don't use autoform with that release yet.

**Comment by lucatros** [comment]
I see... Then the problem is that the repo is still using 4.2.2. I updated the repo to use 5.0.2 (after removing some packages that are not compatible) and ````update-pusharray```` is working as it should.  I'll give it another try on my project and let you know.

**Comment by lucatros** [comment]
Ok. I confirm it's working with ````AutoForm 5.0.2```` and ````Meteor 1.0.3.1````. 
@sjt-mbed: as @aldeed mentioned, source code for the demo is working now. If your Collection is not updating make sure you are returning a valid object for the ````doc```` attribute.

**Comment by sjt-mbed** [comment]
Works for me too. Let me know when this gets fixed with Meteor 1.0.4. Closing

**Comment by lucatros** [comment]
Hi @aldeed. Do you mind adding a sample of ````update-pusharray```` if we want to update an array? I can't figure it out. Thanks!

**Comment by aldeed** [comment]
@lucatros did you look at these?

http://autoform.meteor.com/updatepush
http://autoform.meteor.com/update-array-item

**Comment by lucatros** [comment]
Yeap, but I had the impression that ````update-pushArray```` could be use to "push" and Array or to "update" and Array passing the index of the array or something like that. Do you mean that for updating an array we should just use a normal ````update```` form as in the demo?

**Comment by aldeed** [comment]
Yes, if an array item already exists in the array, you should just update it by putting the correct index in the key name (e.g., `foo.2.bar`) and using a type="update" form. `update-pushArray` is sort of like an "insert" into an existing (or not yet existing) array.

**Comment by lucatros** [comment]
Great. That's what I'm doing right now but because of the name of the form type I thought it could be used for both ````update```` & ````insert```` an array. 
Thanks for the clarification :+1:

**Comment by rollymaduk** [comment]
@aldeed I am having an issue with inserting new item in an array document in my collection using update-pushArray.I followed the examples [here](http://autoform.meteor.com/updatepush)  but I get my parent document schema displayed instead of the child array schema. please help

**Comment by femiveys** [comment]
@rollymaduk I have the same problem. Did you find a solution yet?

**Comment by rollymaduk** [comment]
@femiveys  I did not, just reverted to managing the array items through custom code... was on a project and pressed for time.
