### ISSUE TITLE
How can I get the custom input type AutoForm.getFieldValue

### ISSUE THREAD

**Issue by arvi** [aldeed/meteor-autoform#791]
Hi @aldeed @comerc. I've been trying for hours to figure out how to get the type: "typeahead" AutoForm.getFieldValue in schema. It always return an empty string. For normal inputs, AutoForm.getFieldValue is working as expected. I just need the value on my typeahead field for use on my other field.

P.S I'm still using AutoForm@4.2.2 since some of its dependants _(e.g robertlowe/autoform-pickadate)_ I use are not yet satisfied by 5.0.2 which prevents me from updating for the meantime.

I've tried this
_sample.js_
```javascript
Template.sample.rendered = function () {
    $('input[name=account_name]').on('typeahead:selected', function (event, data) {
        $(this).attr('value', $(this).val());
    });

    $('input[name=account_name]').on('change', function (event, data) {
        $(this).attr('value', $(this).val());
    });
}
```

_schema-sample.js_
```javascript
Schemas.Acc = new SimpleSchema({
    account_name: {
        type: String,
        autoform: {
            type: 'typeahead',
            options: function () {
                return Accs.find().map(function (c) {
                    return {label: c.account_name, value: c.account_name};
                });
            },
            typeaheadOptions: {
                minLength: 3
            }
        }
    },
    account_segment: {
        type: String,
        autoform: {
            type: 'select',
            options: function () {
                if (Meteor.isClient) {
                    var docText = AutoForm.getFieldValue('insertForm', 'account_name');
                    console.log(docText); //returns empty string :(
                }
            }
        }
   }
});
```

Do you have any suggestions for this scenario? Thanks a lot! :)

**Comment by aldeed** [comment]
Try 

```js
$('input[name=account_name]').on('typeahead:selected', function (event, data) {
    $(this).attr('value', $(this).typeahead('val')).trigger('change');
});
```

And remove the change listener.

If you are using the input type from `comerc:autoform-typeahead` and it still doesn't work, you should submit an issue to that repo. I'm not familiar with that package.
