### ISSUE TITLE
Prevent/override autosave on field

### ISSUE THREAD

**Issue by freer4** [aldeed/meteor-autoform#793]
I have a custom-built typeahead-like input. I want to be able to autosave this form which contains several fields, however the loss of focus on the field happens before the click event for the options, so autosave submits before a proper value is selected. 

I couldn't find anything in the docs or code that looked like a way to prevent this on one field, or a way to call it manually from my own event handlers if I could stop it. Correct me if I'm wrong, or perhaps this could be a future feature?

**Comment by freer4** [comment]
I'm a moron. Using 'mousedown' instead of 'click' fixes this issue. Sleep deprivation yay! 

It may still be useful to be able to disable/enable autosave for specific elements.

**Comment by aldeed** [comment]
At the moment, an "autosave" is just a form submit, so calling $('#myFormId').submit() is all you need to do to manually autosave. I hope to make a more advanced autosave eventually.

**Comment by aldeed** [comment]
Tracking autosave enhancements in #799
