### ISSUE TITLE
Autoform and Meteor release 1.0.4

### ISSUE THREAD

**Issue by aadamsx** [aldeed/meteor-autoform#794]
Will Autoform and all related packages (SC, C2) work with the latest release of Meteor: 1.0.4?

**Comment by tudobala** [comment]
If anyone needs to revert back to 1.0.3.2 while 1.0.4.x support is being done, the following command worked for me:

````
meteor update --release 1.0.3.2
````

**Comment by aldeed** [comment]
Planning to work on it tomorrow. There are two issues that I know of so far.

**Comment by aldeed** [comment]
Currently waiting on [this Meteor issue](https://github.com/meteor/meteor/issues/3973). Need to figure out how to make it work.
