### ISSUE TITLE
Do I still need to declare the variable for the document?

### ISSUE THREAD

**Issue by BrooklynC** [aldeed/meteor-autoform#796]
I'm trying to reconcile what I learned in Discover Meteor with what autoform and simple-schema take care of for me. Specifically, the following code from the Microscope example:

    Template.postSubmit.events({
      'submit form': function(e) {
        e.preventDefault();
    
    var post = {
      url: $(e.target).find('[name=url]').val(),
      title: $(e.target).find('[name=title]').val()
    };

I'm assuming autoform handles the first block of code here. However, how do I declare the variable ?  In my app, it would be "company" and I have about 30 attributes, some required, most not.  Can I somehow replace the last two lines above with a collective reference to the schema?  Or do I need to write out every key?

My reason for the question is to replicate this:

    var user = Meteor.user();
    var post = _.extend(postAttributes, {
      userId: user._id, 
      author: user.username, 
      submitted: new Date(),
      commentsCount: 0,
      upvoters: [], 
      votes: 0

I added similar code but it's pretty clear I haven't defined "company". Just not sure how to do that in relation to the extensive schema. Thanks in advance for any guidance.

**Comment by aldeed** [comment]
Yes, autoform gathers all values into an object for you. So if your form is `type="insert"`, you might put the `_.extend` stuff in a "before insert" hook, and then return `post` from that hook. If your form is `type="method"`, you'd probably extend the post in your server method before you insert it, or potentially do some of it in the "before method" hook on the client. Either way, it will all be validated before insertion as long as you attached the schema to the collection.

@SachaG maybe a good blog post someday?

**Comment by BrooklynC** [comment]
Thanks man, always very helpful.  I'll work on that.  To confirm re: the document, does the following code, defining the schema, automatically name the document "company"?  Just as "var post" works above?  Or is a separate declaration still required?

    CompanySchema = new SimpleSchema({
        name: {
            type: String,
            label: "Company Name"
        },
        sector: {
            type: String,
            label: "Sector",
            optional: true
        },
        capTable: {
            type: CapTableSchema,
            optional: true
        },
        financials: {
            type: FinancialsSchema,
            optional: true
        },
        multiples: {
            type: MultiplesSchema,
            optional: true
        }
    });
    Companies.attachSchema(CompanySchema);

**Comment by aldeed** [comment]
The variable name is irrelevant. You would name it "post" or "company" only to improve the readability of the code. It's passed as the first argument to the server method for a `type="method"` form, so if you name that argument `company`, then it will be named company. For example:

```js
Meteor.methods({
  myCompanyFormSubmitMethod: function (company) {
    company.userId = this.userId;
    return Companies.insert(company);
  }
});
```

**Comment by SachaG** [comment]
Yeah, I should write about AutoForm, just haven't had much time to blog lately (what with Telescope). We're happy to accept guest posts too by the way ;)

**Comment by aldeed** [comment]
I'll be working on improved AF docs soon, so that might lead to some ideas for posts.

**Comment by BrooklynC** [comment]
Eric, I can now insert using the form, but the method is not adding the userId to extend the document as it should.  I used your code but I also added the extend code from the Microscope example - I have a feeling that is where I'm screwing it up, as it seems to conflict with what you explained - without it, it doesn't seem like the method has any purpose.  I've included the autoform below as well:

    Meteor.methods({
        insertCompanyFormMethod: function(company) {
            var user = Meteor.user();
            var company = _.extend(company, {
                userId: this.userId
        });
             return Companies.insert(company);
        }
    });

    <template name="CompanyCreate">
        {{#autoForm collection="Companies" id="insertCompanyForm" template="form-horizontal" type="method" meteormethod="insertCompanyFormMethod" resetOnSuccess=false}}
            <fieldset>
                <div class="form-group frame" id="company-general">
                    <div class="container">
                        <div class="frame-header">
                            <h3>Company Profile</h3>
                        </div>
                        <div class="frame-header">
                            <button type="submit" class="btn btn-primary">Insert</button>
                        </div>
                    </div>
                    <table class="table input-group">
                        <thead>
                        <tr>
                            <td>Company</td>
                            <td >{{> afFieldInput name='name' type="text" class="form-control"}}</td>
                        </tr>
                        <tr>
                            <td>Sector</td>
                            <td>{{> afFieldInput name='sector' type="text" class="form-control"}}</td>
                        </tr>
                        </thead>
                    </table>
                </div>
            </fieldset>
        {{/autoForm}}
    </template>

**Comment by aldeed** [comment]
Since `company` is already a variable being passed in, `var company =` should be `company =`. Technically you don't even need `company =` because `_.extend` will add the prop to `company` just by calling it.

Also make sure your schema has `userId` property defined or it will be stripped out.

**Comment by BrooklynC** [comment]
There it is!  I was under the impression that the extend call added the property, without it needing to be defined ahead of time in the schema.  Working great now.  Your patience is much appreciated.
