### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by ciwolsey** [aldeed/meteor-autoform#803]
Would it be possible to add a section to the Autoform or SImple Schema docs which has an example of using a server method as part of a custom validation? I haven't yet been able to find a way to do a check server side which a custom validation can use. It seems like such a common thing to do it would be nice to have an official example.

**Comment by aldeed** [comment]
There isn't any great way since custom validation runs synchronously. Generally you can just put your logic in the custom function, but do something like `if (Meteor.isClient) { return; }` at the top. That way the custom validation will run only on the server where Meteor code is synchronous.

**Comment by ciwolsey** [comment]
Well my validation method is only defined on the server side but I can't get a return since the custom validation function ends before the Meteor.call callback returns. It's a shame there's no way to reactively supply validation data. Thanks for confirming I'm not just missing something.

**Comment by aldeed** [comment]
You should use `Meteor.call` without a callback since you're on the server. Then it will be synchronous.

**Comment by ciwolsey** [comment]
The validation is for a form (client side) but the method is purely server side.

**Comment by aldeed** [comment]
But validation still runs on the server even if you call insert/update on the client.

**Comment by interfaith** [comment]
what is the simplest example that works ?
<template name="insertBookForm">
  {{> quickForm collection="Books" id="insertBookForm" type="insert"}}
</template>
--> error no such template quickForm ??
