### ISSUE TITLE
`Error: Invalid field name: (not a string)` when subobjects meet {{#each afFieldNames}}

### ISSUE THREAD

**Issue by guidouil** [aldeed/meteor-autoform#804]
Hi Aldeed,
here is the repo with my quick reproduction of this strange bug. https://github.com/guidouil/autoform_error

The setup to reproduce is a schema with subobjects and using the `autoForm -> each afFieldNames -> afQuickField` way
I know it doesn't make much sense in this setup but I need it so I can customise some other fields in my form.
Thank you for your time and hard work
cheers

**Comment by aldeed** [comment]
There were changes to this in 5.0. See the [readme](https://github.com/aldeed/meteor-autoform#affieldnames) and the [changelog](https://github.com/aldeed/meteor-autoform/blob/master/CHANGELOG.md#500)
