### ISSUE TITLE
Compatibility - lastIndexOf undefined Error

### ISSUE THREAD

**Issue by vladblindu** [aldeed/meteor-autoform#808]
This is not an issue, because the **change-log.md** points out that option="auto" is no longer supported,
but others might run into the same error I did when upgrading from **4.2.2**  to **5.0.0~**  and before reading the change-log, waste two hours to debug this error.
So, when you provide an name attribute to QuickForm like: 

` {{> afQuickField name="password"}} `

don't supply a *options=afOptionsFromSchema* or you'll get the *TypeError: Cannot read property 'lastIndexOf' of undefined* - error.

The change-log points out that:  "*The afOptionsFromSchema helper requires that you have a property named name in the current context, which is set to the field name.*". I'm quite a new in the area and maybe that's why I didn't get it in the first place.

I hope this saves somebody else's time.

**Comment by aldeed** [comment]
Yeah, that is a bit confusing but "current context" is set by the parent template or block, so it would probably work with:

```html
{{#with name="password"}}
  {{> afQuickField name="password" options=afOptionsFromSchema}}
{{/with}}
```

Though I am not recommending actually doing that.
