### ISSUE TITLE
setting options in schema doc clarification

### ISSUE THREAD

**Issue by limabeans** [aldeed/meteor-autoform#811]
In the section of the README where you use a helper to "calculate" the options in the schema, and then use map, I found it more helpful to use `[collection_name].find().fetch()` instead of just `[collection_name].find()`. This is because fetch() returns an array of Objects, which then can easily be mapped to an object with a label and name. Here is an example of me doing so in my own code:

```javascript
  workshops: {
    type: [String],
    label: 'workshops',
    autoform: {
      options: function() {
        return _.map(Workshops.find().fetch(), function(c) {
          return {label: c.name, value: c.name};
        });
      }
    }
  }
```
Consider slightly modifying README to include this example?

**Comment by aldeed** [comment]
I usually use `cursor.map`, like [here](https://github.com/aldeed/meteor-autoform#use-a-helper). I assume it's faster than converting to an array and using `_.map`, though I have no numbers to back that up.

**Comment by limabeans** [comment]
Ahhh I see, got it, thanks. My bad, didn't realize that cursors have a built-in map method.
