### ISSUE TITLE
updating [string] field

### ISSUE THREAD

**Issue by MurWade** [aldeed/meteor-autoform#813]
[Repo](https://github.com/MurWade/afbug)

Autoform has a bug when updating a field that has a type of `[String]`. Instead of array it appends the string as objects which  misses things up.

**Comment by SenerDemiral** [comment]
#777

**Comment by aldeed** [comment]
It's actually a mongo bug, but it's now visible in AF 5.0. Still figuring out the best way to address it, but in the meantime, you just need to ensure that the field in the database is set to an array before submitting an update form.

**Comment by SenerDemiral** [comment]
Workaorund
// tags: [String]

AutoForm.hooks({
  autoFormId: {
    before: {
      update: function(doc) {
        // delete tags.0, tags.1, ... from $set 
        var ta = [];  // tempTagArray
        var ts = {};  // temp$set
        ts = this.updateDoc.$set;  // do not modify enumerator directly
        for(var key in this.updateDoc.$set) {
          if (key.indexOf('tags.', 0) === 0) {
            ta.push(this.updateDoc.$set[key]);
            delete ts[key];
          }
        }
        // if there are tags
        if (Object.keys(ta).length != 0) {
          ts = _.extend(ts, { tags: ta });  // new $set
        }
        this.updateDoc.$set = ts;

        return doc;
      }
    }
});

**Comment by mologie** [comment]
May be worth noting: This bug affects me too, but only happens when updating existing documents which do not yet have the to-be-modified array field. This happens a lot when the field is optional. Creating a new document with a populated array field uses the correct field type in the database.

**Comment by mologie** [comment]
A very clean workaround is to simply add `defaultValue: []` to the schema for all optional array fields. Collection2 will then replace all unset array fields by empty arrays on the server. This cannot be bypassed on the client and can therefore not be broken by a malicious user.

AutoForm's $set and $unset queries behave correctly afterwards. The empty array causes Mongo to use array operations instead of building an object in the document.

**Comment by SenerDemiral** [comment]
Yes, there is already defaultValue: [] in the schema.
But if you delete some of array item, problem starts!
Yes, It should be done in Server with Collection hooks not Client AutoForm hooks.

**Comment by MurWade** [comment]
@SenerDemiral yes that's right when you remove everything from the array field, problem starts!. problem is also there when you create a document with empty array and try updating it after.

**Comment by MurWade** [comment]
@mologie adding `defaultValue: []` to the field actually helps. when you first create the document using auto forms, you can update it after fine which you couldn't before without the `defaultValue: []`. but after removing all the items from that field as @SenerDemiral  mentioned, the bug is back.

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by MurWade** [comment]
This is fixed!. Thanks @aldeed  and @SenerDemiral  for your workaround.
