### ISSUE TITLE
Links in documentation do not work

### ISSUE THREAD

**Issue by mwarren2** [aldeed/meteor-autoform#818]
Please note that NONE of the links in the documentation in atmospherejs.com work: not one!
Please fix !

**Comment by aldeed** [comment]
They work on GitHub. If they don't work on atmosphere, that's an atmosphere issue.

**Comment by mwarren2** [comment]
Ok, thanks, I'll use the documentation on Github


Il 24/03/15 22:19, Eric Dobbertin ha scritto:
