### ISSUE TITLE
AutoForm.hooks and Iron:Router conflicts

### ISSUE THREAD

**Issue by limabeans** [aldeed/meteor-autoform#820]
I've written this code 

 ` AutoForm.hooks({
    signupKidForm: signupHooksObject
  });
`
within a` if(Meteor.isClient)`.

Inside of my template: `{{#autoForm collection="Kids" id="signupKidForm" type="insert" validation="keyup"}}`

From within `signupHooksObject`, in onSuccess function, I'm calling Router.go, which is causes this Uncaught Error message.

I'm getting this error in my console: Uncaught Error: No form with ID signupKidForm is currently rendered. If this call originated from within a template event or helper, you should call without passing a formId to avoid seeing this error

..Upon submitting my form. I've tried to debug this error message for some time now to little success. And the `onSuccess` function in `signupHooksObject` seems to run fine, but I still get that message. Any suggestions as to why that comes up still?

**Comment by vladblindu** [comment]
Same here. 

Somwhere here is the conflict (maybe with iron-router). Somehow autoform checks too soon if the template has been destroyed.

```
function _validateField(key, formId, skipEmpty, onlyIfAlreadyInvalid) {  
  var docToValidate, isModifier;  
                                                                                                       
  // Due to throttling, this can be called after the autoForm template is destroyed. 
  // If that happens, we exit without error.                                                             
  var template = AutoForm.templateInstanceForForm(formId);                         
  if (!template || !template.view._domrange || template.view.isDestroyed) {       
    return;                                                                    
  }     
```
So this "exit without error" doesn't happen.
I also use iron-router and I noticed this error when filling  a afQuickField and leaving the page with a 
```
<a href={{pathFor "whatever"}}>Link</a>
```
link. Before filling in the form, if I leave the route, there's no error.  The autoform is set to validate to:
submitThenKeyup.

I hope this helps.

**Comment by limabeans** [comment]
Yeah, even after I put the call to Router.go in the 'after' field of the hookObject, I still get the Uncaught error message. 

Based on what I read in the readme, everything in the after field should be called after the form is done and submitted, performed in the same manner as the async callback that can be optionally provided to Meteor.call. 

But based on the Uncaught console error that I'm getting, this isn't the case. 

I think a temporary hacky fix to this would be to listen for the 'submit' event and do calls to Router.go there?

**Comment by vladblindu** [comment]
I didn't try it yet, but it sounds ok.
In fact except from "seeing red", there's no damage done to the flow of the code
but like everybody else that is not into TDD, I get annoyed when I see red :)

I hope this will get fixed because I love Iron's {{linkTo}} and {{pathFor}} easy routing.

**Comment by aldeed** [comment]
This should be fixed in next release.
