### ISSUE TITLE
Error when using schemaless form on meteor windows 1.1-rc.0

### ISSUE THREAD

**Issue by Yian** [aldeed/meteor-autoform#825]
I'm using a schemaless autoform (autoform 5.0.2) on the windows 1.1-rc.0 version of Meteor and I'm getting an error. It's pretty much the same as per your example, setting a custom schema in a helper and using {{#autoForm id="demo" schema=getSchema id="insertQuestionsForm" doc=getDoc}}. Works on Linux version of Meteor.

The error is below:
Exception in template helper: TypeError: Cannot read property 'objectKeys' of undefined 
at Object.autoFormFieldNames (http://localhost:3000/packages/aldeed_autoform.js?95e4d3c1e4a248502de2befc9436a32b15999fa3:1446:19)

Do you know any work around or quick fix to this problem or should I not be using the windows version of Meteor just yet? Thanks.

**Comment by aldeed** [comment]
If you update to autoform `5.0.3`, I think it will probably be fixed.

**Comment by Yian** [comment]
Yep latest release worked, thanks!
