### ISSUE TITLE
redirect when form is submitted

### ISSUE THREAD

**Issue by MurWade** [aldeed/meteor-autoform#826]
I have a separate route for my insert form.

After the form is submitted and inserted, i want to redirect to another route. So i added hook like this

    after: {
           insert: function(){
                   Router.go('home')
           }
      }

but i get this error

` Uncaught Error: No form with ID insertPostForm is currently rendered. If this call originated from within a template event or helper, you should call without passing a formId to avoid seeing this error`

 I tried adding my hook to `endSubmit` but no luck.. and this error doesn't get thrown some times. so its abit weird. most of the times it does.

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by MurWade** [comment]
No more getting errors. Thanks!
