### ISSUE TITLE
Error with nested schema and update-pushArray

### ISSUE THREAD

**Issue by ColadaFF** [aldeed/meteor-autoform#827]
Hi!
I've been working with the last update of autoForm and and I have the following on my schema: 
```javascript
   "example.$.subdoc": {
        type: Array,
        optional: true
    },
    "example.$.subdoc.$": {
        type: Object,
        optional: true
    },
    "example.$.subdoc.$.SuName": {
        type: String,
    },
```
When I try to create the form with autoform, only show the form if in the scope option I set: ```scope="example.$.subdoc"```, but when I try to update, meteor throws the following exception: ```error: 409, reason: "MinimongoError: The positional operator did not find the match needed from the query", details: undefined```
I also tried with index scope options, like: ```scope="example.0.subdoc```, but in this case the autoForm thows: ```Exception in template helper: Error: Invalid field name: SuName```

Using ```aldeed:autoform@5.1.0```

**Comment by aldeed** [comment]
`scope="example.0.subdoc"` should be correct. It would not work with a `$`. Meteor doesn't support that on the client.

Are you using a `quickForm` or `autoForm`? Can you post the form? I'm not sure why it says "invalid field name".

**Comment by SenerDemiral** [comment]
```
Schemas = {};

Schemas.SS = new SimpleSchema({
  ad: {
    type: String
  },
  aaa: {
    type: [Object],
    optional: true,
    blackbox: true
  },
  "aaa.$.hTakimId": {
    type: String,
    optional: true,
  },
  "aaa.$.vTakimId": {
    type: String,
    optional: true,
  },
  "aaa.$.maclar": {
    type: [Object],
    optional: true,
    blackbox: true
  },
  "aaa.$.maclar.$.hOyuncu": {
    type: String,
    optional: true,
  },
  "aaa.$.maclar.$.vOyuncu": {
    type: String,
    optional: true,
  }
});

SS = new Mongo.Collection('ss');
SS.attachSchema(Schemas.SS);
--------------------------------------
<template name="insSS">
  {{#autoForm collection="SS" id="insSS" type="insert"}}
    <fieldset>
      <legend>SS</legend>
      {{> afQuickField name='ad'}}
    </fieldset>
    <button type="submit" id="btnInsSS" class="btn btn-primary">Insert</button>
  {{/autoForm}}
</template>

<template name="insSS2">
  {{#autoForm collection="SS" id="insSS2" type="insert"}}
    <fieldset>
      <legend>SS2</legend>
      {{> afQuickField name='ad'}}
      {{> afQuickField name='aaa'}}
    </fieldset>
    <button type="submit" id="btnInsSS2" class="btn btn-primary">Insert</button>
  {{/autoForm}}
</template>

<template name="insSS3">
  {{#autoForm id="insSS3" collection="SS" type="update-pushArray" doc=docSS scope="aaa"}}
    <fieldset>
      <legend>SS3</legend>
      {{> afQuickField name='hTakimId'}}
      {{> afQuickField name='vTakimId'}}
    </fieldset>
    <button type="submit" id="btnInsSS3" class="btn btn-primary">Insert</button>
  {{/autoForm}}
</template>

<template name="insSS4">
  {{#autoForm id="insSS4" collection="SS" type="update-pushArray" doc=docSS scope="aaa.0.maclar"}}
    <fieldset>
      <legend>SS4</legend>
      {{> afQuickField name='hOyuncu'}}
      {{> afQuickField name='vOyuncu'}}
    </fieldset>
    <button type="submit" id="btnInsSS4" class="btn btn-primary">Insert</button>
  {{/autoForm}}
</template>
```

insSS:   OK
insSS2: OK
insSS3: OK
insSS4: !!
Exception in template helper: Error: Invalid field name: hOyuncu
Exception in template helper: Error: Invalid field name: vOyuncu

**Comment by amllano** [comment]
Hi, any update on this? or any suggested workaround? I'm still experiencing a similar issue with autoform@5.3.0.

Thanks,

**Comment by amllano** [comment]
An update on the issue. Seems that is fixed replacing on the line: 
`var searchString = scope+'.$.';`

by     

`var searchString = scope.replace(/[0-9]/g, "$") +'.$.';`

on the line adjustSchema method of 'update-pushArray' definition (https://github.com/aldeed/meteor-autoform/blob/master/formTypes/update-pushArray.js#L43).
