### ISSUE TITLE
Problem with type="normal", quickForm and omitFields

### ISSUE THREAD

**Issue by krizka** [aldeed/meteor-autoform#834]
Imagine you have a schema:
```
DocSchema = new SimpleSchema({
    someId: { type: String },
    name: { type: String }
});
```
and a quick form:
```
quickForm(id='formId' schema='DocSchema' type='normal' omitFields='someId')
```
onSubmit will newer be called because of validation error on required field.

**Comment by aldeed** [comment]
Correct. You cannot omit fields that are required unless you have a `formToDoc` hook that sets the property prior to validation. Instead your form schema can simply not include that field.
