### ISSUE TITLE
Quickform Update with meteor methods.

### ISSUE THREAD

**Issue by trinric** [aldeed/meteor-autoform#835]
I am using Meteor methods to submit the form I am using initially and check for proper authentication but there doesn't seem to be a way to do this with `type="update"`. Is there a way to still use a meteor method in this situation? Like this? 
`{{> quickForm schema=BuildSchema collection="Builds" id="updateBuildForm" type="update" doc=this meteormethod="updateBuild"}}`

It gives me an error like this : `Exception in delivering result of invoking '/builds/update': Error: Access denied. No allow validators set on restricted collection for method 'update'` which probably is referring to Allow & Deny rules?

**Comment by garenor** [comment]
You can use a method for this. You must use a `type="method' or `type="method-update` for this (see docs). I personally use an onSubmit hook with a Meteor.call().

Your errors are indeed from the allow/deny rules (or lack of them). You are now trying to do a client side insert, witch need the allow/deny rules set.

**Comment by trinric** [comment]
Oh perfect I didn't see this form type. Thanks!
