### ISSUE TITLE
simplest example

### ISSUE THREAD

**Issue by interfaith** [aldeed/meteor-autoform#839]
searching for a working hook
simply adding the userId

**Comment by interfaith** [comment]
no examples show a hook to add the user id
this fails on client side
AutoForm.hooks({
  insertBookForm2: hooksObject
});




var hooksObject = {
  before: {
    // Replace `formType` with the form `type` attribute to which this hook applies
    insert: function(doc) {
      // Potentially alter the doc
      doc.userId = Meteor.userId();
      console.log("got user doc" + Meteor.userId());
      // Then return it or pass it to this.result()
      //return doc; (synchronous)
      //return false; (synchronous, cancel)
      //this.result(doc); (asynchronous)
      //this.result(false); (asynchronous, cancel)
    }
  }
}

**Comment by aldeed** [comment]
Is that the same order as in your code? `hooksObject` needs to be defined before calling `AutoForm.hooks` with it.

**Comment by interfaith** [comment]
lucky me changing insertaf.js works

var hooksObject = {

 before: {
    // Replace `formType` with the form `type` attribute to which this hook applies
    insert: function(doc) {
      // Potentially alter the doc
      doc.userid = 'bar';
      doc.age = 0;
      console.log("hellojoe2 " + doc);
      // Then return it or pass it to this.result()
      return doc;// (synchronous)
      //return false; (synchronous, cancel)
      //this.result(doc); (asynchronous)
      //this.result(false); (asynchronous, cancel)
    }
  }
}

AutoForm.hooks({
  afInsertDemo: hooksObject
});

**Comment by interfaith** [comment]
working as advertised, thx !

On Mon, Mar 30, 2015 at 1:33 PM, Eric Dobbertin <notifications@github.com>
wrote:

> Is that the same order as in your code? hooksObject needs to be defined
> before calling AutoForm.hooks with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aldeed/meteor-autoform/issues/839#issuecomment-87824065>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
