### ISSUE TITLE
contenteditable has no value

### ISSUE THREAD

**Issue by chrisbutler** [aldeed/meteor-autoform#844]
i have a form with an `afFIeldInput` using `type='contenteditable'` and the input shows no value when the form is in update mode... but if i remove the `type='contenteditable'` it works as expected. is there an issue with that particular input code, or am I missing something?

**Comment by chrisbutler** [comment]
@aldeed in my case, this line is false when the helper is run: https://github.com/aldeed/meteor-autoform/blob/master/inputTypes/contenteditable/contenteditable.js#L22

and it doesn't seem to run again

**Comment by retani** [comment]
+1

**Comment by akiarostami** [comment]
I have this problem too
