### ISSUE TITLE
before hook not working properly with method type

### ISSUE THREAD

**Issue by yanndebelgique** [aldeed/meteor-autoform#845]
Hi,
this code worked before but don't know if it is us that changed the code or if autoform is doing it differently now (read the docs but couldn't find anything). So I want to add something to the document before submitting to the 'questions/answer' method but the hooks dont run. 

```
AutoForm.addHooks(null,{
    before: {
      "questions/answer": function(doc, template) {
        doc.question = _.omit(template.data,"schema");
        return doc;
      }
    }
});
```

```
{{> quickForm schema=this.schema id=this.name type="method" omitFields="question" meteormethod="questions/answer"}}
```

**Comment by aldeed** [comment]
Change `"questions/answer": function` to `method: function`. It's just the form type now. This is mentioned in the [changelog](https://github.com/aldeed/meteor-autoform/blob/master/CHANGELOG.md#500) and updated in the docs, but I know there are a lot of changes there so easy to miss.

**Comment by yanndebelgique** [comment]
ok thanks! :+1:
