### ISSUE TITLE
Range Type: Show the selected value

### ISSUE THREAD

**Issue by jimmiebtlr** [aldeed/meteor-autoform#847]
Any easy way to show the selected value as well as minimum and maximum for this type?

**Comment by aldeed** [comment]
Show it where?

**Comment by jimmiebtlr** [comment]
Sorry, didn't give a very good description.  Currently when you use the type "range" and use afQuickField, it doesn't seem to show any value for the slider or it's minimum and maximum.  

Is the recommended action is to use afInputField?

**Comment by jimmiebtlr** [comment]
I've created slider autoform plugin located at 

https://github.com/ElevateDevelopmentAndDesign/meteor-autoform-nouislider

It can be configured to have marks indicating values on the slider, though it doesn't show the currently selected values yet.

**Comment by aldeed** [comment]
@jimmiebtlr, I don't have time to dig into your code and do a PR right now, but if it helps, I have a nouislider custom input I've been using in an app for single values. Feel free to put it in your package. If it's not straightforward to handle the logic for both types in a single input type, you could probably copy-paste my stuff and just have it be a separate registered type.

Template:

```html
<template name="noUISliderInput">
  <div class="autoform-no-ui-slider-input"></div>
</template>
```

JS:

```js
AutoForm.addInputType('noUiSlider', {
  template: 'noUISliderInput'
});

Template.noUISliderInput.rendered = function () {
  var template = this;

  template.autorun(function () {
    var data = Template.currentData();

    var min = (data.atts.min === +data.atts.min) ? data.atts.min : 0;
    var max = (data.atts.max === +data.atts.max) ? data.atts.max : 100;
    var step = (data.atts.step === +data.atts.step) ? data.atts.step : 1;
    var value = data.value || 0;

    template.$('.autoform-no-ui-slider-input').noUiSlider({
      start: value,
      step: step,
      range: {
        'min': min,
        'max': max
      }
    }, true);

  });
};
```

**Comment by jimmiebtlr** [comment]
The pull request was just a documentation update, to point people to a nouislider input type I put on atmosphere.

**Comment by aldeed** [comment]
I merged your PR. I meant that I don't have time to do a PR for merging my code into your package. Your docs say it doesn't currently support single values.

**Comment by jimmiebtlr** [comment]
I've added support for single values, but am currently having trouble with getFieldValue not returning a value for the field.  Should the example code you attached work correctly with getFieldValue?

**Comment by aldeed** [comment]
@jimmiebtlr, not necessarily. I'm planning a rewrite of field value tracking to make it possible for custom input types to indicate when they changed.
