### ISSUE TITLE
Custom template based on default bootstrap3 template doesn't insert "form-control" class

### ISSUE THREAD

**Issue by derdaumen** [aldeed/meteor-autoform#850]
Heya,

I've created my custom template based on a duplicate of the default bootstrap3 template. I wanted to ad an info-icon to the label. I've achieved that with the template shown below, with one line added above `<label>`.
The problem is that the inputs are now missing the class "form-control" and the layout is different from using the default bootstrap3 template.

What do I need to do so that the layout/styles is the same as if I would use the default template?
What do I not understand?

```html
<template name="afFormGroup_infoButton">
  <div class="form-group {{#if afFieldIsInvalid name=this.name}}has-error{{/if}}" data-required={{required}}>
    {{#unless skipLabel}}
    <i class="fa fa-info-circle" data-toggle="modal" data-target="#{{this.afFieldInputAtts.modal}}"></i>
    <label {{bsFieldLabelAtts}}>{{#if this.labelText}}{{this.labelText}}{{else}}{{afFieldLabelText name=this.name}}{{/if}}</label>
    {{/unless}}
    {{> afFieldInput this.afFieldInputAtts}}
    <span class="help-block">{{{afFieldMessage name=this.name}}}</span>
  </div>
</template>
```

Here is how I use the template:

```html
{{> afQuickField name='question' template='infoButton' modal='modal-question' class=" text-center"}}
```

Thank you for this great package!
Stephan

**Comment by aldeed** [comment]
Copy the original template's helpers, too.

**Comment by derdaumen** [comment]
I duplicated
meteor-autoform/templates/bootstrap3/components/afFormGroup/afFormGroup.html
and 
meteor-autoform/templates/bootstrap3/components/afFormGroup/afFormGroup.js

I renamed the template name in both files.
Still "form-control" is missing

**Comment by aldeed** [comment]
OK, I see. Actually the input template adds the class, so you need to specify the bootstrap template for the input in your formGroup template:

```html
{{> afFieldInput afFieldInputAtts}}
```

```js
Template.afFormGroup_infoButton.helpers({
  afFieldInputAtts: function () {
    return _.extend({template: 'bootstrap3'}, this.afFieldInputAtts);
  }
});
```

**Comment by derdaumen** [comment]
I understand. The afFieldInput gets my custom infoButton template passed down as its template. 
```javascript
afFieldInputAtts {
...
template: "infoButton",
...
}
```
So a helper is needed to change it to bootstrap3. So far so good.

The helper function you posted doesn't do the job though.
I implemented it, the helper gets called, but the template remains 'infoButton'.

Because I don't fully understand the _.extend function I changed it to this:
```JavaScript
afFieldInputAtts: function () {
    this.afFieldInputAtts.template = 'bootstrap3';
    return this.afFieldInputAtts;
  }
```
which does the job, but I assume (anticipate) this is a solution with some flaws?

Thanks a lot.

**Comment by aldeed** [comment]
Your solution is fine. The advantage of `_.extend` is that if `template="foo"` were added on the `afFormGroup` when you use it, that would not get overridden. But I'm guessing you're unlikely to do that in your situation. Not sure why it didn't work. Maybe autoform adds a `template` attribute to `this.afFieldInputAtts`; I can't remember.

**Comment by derdaumen** [comment]
Sweet. I greatly appreciate your willingness to make life more beautiful. You did so for me and I'm trying to do the same with what I'm coding for others. Seems we're employed by the same company, and the company is growing. I like it.

**Comment by todda00** [comment]
@derdaumen @aldeed  this information was helpful and needed when I was creating a custom afFormGroup template, FYI the _extend was not working for me as well.
