### ISSUE TITLE
Cannot use before action on meteor method?

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-autoform#853]
I was trying to do the following:

```
AutoForm.hooks({
  'createPlanFromTemplatesForm': {
    before: {
      method: function(doc) {
        console.log(doc);
        doc.studentId = Router.current().params._id;
        return doc;
      }
    },
    onSuccess: function(formType, doc) {
      Router.go('home');
    },
    onError: function(err) {
      console.log(err);
    }
  }
});
```
where my html tag is basically as follows:

```
{{>quickForm schema="PlanFromTemplatesForm" id="createPlanFromTemplatesForm" type="method" meteormethod="createPlanFromTemplates"}}
```
The idea was to grab the doc and add the route's `studentId` to it before it went to the meteor method

```
Meteor.methods({
  'createPlanFromTemplates': function(doc) {
    var studentId = doc.studentId;
    var templates = doc.templates;
    // ...
    var id = Plans.insert(mydata, function(err, result) {
      Students.update(result, {
         $addToSet: { planIds: myIds }
      })
    }); 
    return id;
  }
});
```

However, it seems as though the before action is never firing. It never logs anything and never alters the doc.

**Comment by guilhermedecampo** [comment]
Could you find a way @AlexFrazer ?

**Comment by guilhermedecampo** [comment]
I'm trying to do the exactly same thing! And also would like to add a confirmation box before call the method.

**Comment by AlexFrazer** [comment]
I did find a way, that might be a bit sleight of hand, but hopefully it can help you out. It involves adding a `formToDoc` such that, when they submit it, it will contain the correct value.

Here is my `client/templates/students/createFromTemplates.js` file that handles it.

```
AutoForm.hooks({
  // no need to include
  formToDoc: function (doc) {
    doc.studentId = Router.current().params._id;
    return doc;
  }
});
```

**Comment by guilhermedecampo** [comment]
Interesting solution. I did this:

template.html
```
{{> afFieldInput type="hidden" name='itemId' value=itemId}}
```
helper:
```
itemId: function() {
    return Router.current().params.itemId;
  }
```

But also I need to popup a confirmation modal.
So I managed with a horrible workaround using `.click()`  :disappointed:

**Comment by aldeed** [comment]
Pretty sure this has since been fixed

**Comment by guilhermedecampo** [comment]
Thanks @aldeed  will check it out.
