### ISSUE TITLE
allowedValues could be shorten just "allow"?

### ISSUE THREAD

**Issue by alitavector** [aldeed/meteor-autoform#856]
Just thought writing less without the need for camel case is still clear to me.

One of the tutorial (http://www.webtempest.com/meteor-js-autoform-tutorial) explain and found it needlessly to write camel case:
```
category: {
    type: String,
    label: "Category",
    allowedValues: ['business', 'health', 'finance'],
    autoform: {
      options: [
        {label: "Business", value: "business"},
        {label: "Health", value: "health"},
        {label: "Finance", value: "finance"}
      ]
    }
```

**Comment by zimme** [comment]
I think it's better to have it as it is. There's no room to confuse it with meteors concept of allow/deny rules.
