### ISSUE TITLE
Customizing afObjectField from schema parameters

### ISSUE THREAD

**Issue by yourcelf** [aldeed/meteor-autoform#862]
Looking through the documentation, I can't find much on the use of the ``autoform`` parameter in a simple schema definition to customize the behavior of ``afObjectField`` and ``afArrayField`` types.  If my schema is this:

    var schema = new SimpleSchema({
        "name": {type: String}
        "interests.archery": {type: Boolean},
        "interests.fire": {type: Boolean},
        "interests.pottery": {type: Boolean}
    });

and I render with

    {{> quickForm schema=schema }}

I get a panel named "Interests" with the subfields for the object below.  How can I change the "Interests" panel title? I could override the template or type by adding e.g. ``autoform: {template: "custom"}``, but then I have to duplicate templates just to change the title of the panel.  If I wanted to override the label next to the input, I could just add e.g. ``label: "Pottery is Awesome"``to the field def.  But is there something I can add to the ``autoform`` property which will override the panel title for the ``afObjectField``?

**Comment by aldeed** [comment]
I think it uses the object field label so although it may not be semantically the best solution, it should work to add this to your schema:

```js
interests: { type: Object, label: "Panel Title" }
```

The default templates could perhaps be updated to check for an override label.

**Comment by yourcelf** [comment]
Thanks, that works.
