### ISSUE TITLE
When type=number and optional=true, no validation possible

### ISSUE THREAD

**Issue by yourcelf** [aldeed/meteor-autoform#863]
This is not so much a bug in autoform as it is a consequence of browser implementations of ``type=number``; and I'm raising this issue mostly to document for others that might search for it.

In both Chrome 41 and Firefox 37, a non-numeric value can be typed into a field with ``type=number``; however attempting to retrieve the value of the field through the DOM or jquery yields empty-string.  As a result, AutoForm can't distinguish a ``type=number`` field with a non-number typed into it, and a field with nothing typed into it.  This means that you'll never see a ``<field> must be a number`` error if you use ``type=number``, and if the field is optional, it will be silently unset.  If the field is non-optional, you'll only see a ``<field> is required`` error, even if the field has something typed into it.

A workaround is to use ``type=text`` even for numeric fields.  The downside is you don't get the native number widget.

**Comment by aldeed** [comment]
Yep, same for date type. See https://github.com/aldeed/meteor-autoform/issues/610
