### ISSUE TITLE
How to pass class and data attribute to afFieldInput

### ISSUE THREAD

**Issue by rwatts3** [aldeed/meteor-autoform#870]
I am working on a tooltip implementation for autoform. I am not sure how to pass or assign a data attribute to afFieldInput.

**Comment by aldeed** [comment]
All the attributes you add to the spacebars inclusion tag get added to the element.

```
{{> afFieldInput name="foo" class="bar" data-extra="baz"}}
```

**Comment by rwatts3** [comment]
I was successfully able to get the tooltip working without having to create an extension package.  I'd be happy to provide an example of how I did it , and maybe this can close the tooltip feature request.

**Comment by aldeed** [comment]
Can you submit a PR to add an example to "common questions" section of the readme?

**Comment by U54** [comment]
> rwatts3 commented on Apr 8, 2015 
I was successfully able to get the tooltip working without having to create an extension package. I'd be happy to provide an example of how I did it , and maybe this can close the tooltip feature request.

@rwatts3 It would be very helpful and appreciated if you could share how you did this?

**Comment by U54** [comment]
Of course I figure it out right after posting that... Anyways, here's how I achieved it:


```
<div class="form-group">
    <label class="control-label" data-toggle="tooltip" data-placement="right" data-original-title="This is some example text for the tooltip!">Referral URL <i class="glyphicon glyphicon-info-sign"></i></label>
    <div class="input-group">
        {{> afFieldInput name='code' value=referrerURL }}
    </div>
</div>
```

Then I added this .onRendered to my .js file for the tooltip:

```
Template.ExampleTemplateName.onRendered(function() {
    // Tooltip
    $("[data-toggle=tooltip]").tooltip();
});
```

Result:

<img width="535" alt="screen shot 2016-05-06 at 10 48 06 pm" src="https://cloud.githubusercontent.com/assets/16723563/15090440/b6e0db8c-13dc-11e6-8d42-f94605098513.png">
