### ISSUE TITLE
[5.1.2] AutoForm.getValidationContext().isValid() not reactive.

### ISSUE THREAD

**Issue by Pagebakers** [aldeed/meteor-autoform#875]
After upgrading to AutoForm 5.1.2, the isValid() method of a form's validation context doesn't seem to be reactive anymore. If I use simple schema to get the context however, it works as expected.

``` javascript
Template.myTemplate.helpers({
  isValid: function() {
    // var context = AutoForm.getValidationContext().isValid(); // only returns on render, isn't re-run reactively.
    return Collection.simpleSchema().namedContext('form-id').isValid(); // works as expected.
  }
});
```
Note that `AutoForm.getValidationContext()` does return the correct validation context.

Also, this throws an error AutoForm.getValidationContext('form-id'); if run from a template helper. The documentation still states the form id parameter is mandatory.

```
Exception in template helper: Error: No form with ID form-id is currently rendered. If this call originated from within a template event or helper, you should call without passing a formId to avoid seeing this error
```

**Comment by aadamsx** [comment]
This is basically the same as the issue I just opened: #877

**Comment by thebarty** [comment]
Just stumbled upon the same issue. +1 to get it solved.

**Comment by aldeed** [comment]
It should work as long as you do `AutoForm.getValidationContext('form-id').isValid()`

**Comment by aldeed** [comment]
Fixed to work without passing the formId argument in 5.8.1
