### ISSUE TITLE
Conditionally diaplaying afFormGroup, using template helper, causes form not to submit

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-autoform#878]
When I add a conditional {{#if}} block around an afFormGroup within autoForm, the form does not submit. The block helper checks the truthyness of a template helper, which gets its value reactively from another af field, via ReactiveVar.

**Comment by aldeed** [comment]
Did you call `AutoForm.debug()` in your client code or add an error hook to see what form errors there are?

**Comment by brylie** [comment]
Thanks @aldeed. That pointed me to an unknown bug. Is AutoForm.debug() documented somewhere?

**Comment by brylie** [comment]
Ah, I did find a mention in the [API docs](https://github.com/aldeed/meteor-autoform/blob/master/api.md#autoformdebugclient).
