### ISSUE TITLE
Feature Request: X-Editable Template

### ISSUE THREAD

**Issue by testbird** [aldeed/meteor-autoform#88]
Maybe it is possible to avoid requiring to maintain separate templates to render a read-only view of a document and editable auto-form templates. And to get x-editable like features at the same time:

Just defining an autoform template with desired layout classes may be enough in many cases, if autoform could toggle between rendering the fields as input elements, as click-to-edit-links (e.g. dotted underline), or plain text (making the read-only template unnecessary).

Toggling could be controlled by an option or the user clicking on the link or buttons if this is allowed.

(Additional hidden fields may still be rendered for the click-to-edit links or plain text representations, if some other field is editable and the form is submittable.)

**Comment by KrishnaPG** [comment]
Wondering if x-editable integration took place. In-place editing would be invaluable for screen-space optimization, especially in tables + mobile combination scenarios

**Comment by KrishnaPG** [comment]
Ok - I took a stab at it and was able to make simpleschema work with **xeditable** upto the point of being **able to display the editor and update the value in UI fine** - but updating the value back to the collection is leading to error `Error("When the modifier option is true, validation object must have at least one operator");` Once it is fixed, this `xeSelectField` can be used similar to select quickfield  and other equivalents can be easily created simiarily.
````
Template["xeSelectField"].rendered = function () {
    var self = this;
    var collection = (self.data.collection == null ? ((self.data.doc != null && self.data.doc._af!=null)? self.data.doc._af.collection : null ): self.data.collection);
    if (!collection) {
        throw new Error("xeSelectField: You must specify a collection.");
    }
    var ss = collection.simpleSchema();
    var fieldName = self.data.name;
    self.$('a.xEditable').editable({
            pk: self.data.doc.id,
            type: 'select',
            value: self.data.doc[fieldName],
            source: _.map(self.data.options, function (x) { return { text: x.label, value: x.value }; }),
            mode: "inline",
            onblur: "ignore", 
            success: function (response, newValue) { collection.update({ _id: self.data.doc.id }, { fieldName: newValue }); } //TODO: if using backend server, may want to check server response
    });
}

// HTML
<template name="container">
  {{#each esMappings}}
	{{> xeSelectField collection=esMappingsColl doc=this name="measureFn" options=measureOptions }}
  {{/each}}
</template>
<template name="xeSelectField">
	<a class="xEditable" href="#" data-placeholder="Select Value" data-emptytext="Click to Edit"></a>
</template>
````
Helpers
````
Template['container'].created = function () {
    this.esMappings = new Mongo.Collection(null);
    this.esmAFSchema = new SimpleSchema({
        label: { type: String, index: 1, unique: true },
        tgm: { type: String, optional: true }, 
        measureFn: { type: String },
        displayTitle: { type:String, optional: true}
    });
    this.esMappings.attachSchema(this.esmAFSchema);
}

Template['container'].helpers({
    esMappings: function () {
        return Template.instance().esMappings.find(); // a reactive cursor is returned
    },
    esMappingsColl: function () {
        return Template.instance().esMappings; // the whole collection is returned (and may not be reactive ?)
    },
    measureOptions: function() {
        return [
                { label: "Average", value: "Average" },
                { label: "Count", value: "Count" },
                { label: "Max", value: "Max" },
                { label: "Min", value: "Min" },
                { label: "Sum", value: "Sum" },
                { label:"UniqueCount", value:"UniqueCount"}
        ];
    },
});

````
Note that I tried both using the `xeSelectField` directly and also inside an `autoform` directive - did not help, still gets that error.
````
	{{#autoForm id=makeUniqueID_gb type="update" collection=esMappingsColl doc=this autosave=true  template="bootstrap3-inline"}}
	    {{> xeSelectField  doc=this name="measureFn" options=measureOptions }}
	{{/autoForm}}
````

**Comment by dandv** [comment]
:+1: for x-editable integration. The project itself is frozen, but there's a [semi-promising fork](https://github.com/vitalets/x-editable/issues/610#issuecomment-68804699).

**Comment by vieko** [comment]
+1
