### ISSUE TITLE
Placeholder not working for [String] type

### ISSUE THREAD

**Issue by Pierre-Ferreira** [aldeed/meteor-autoform#880]
tags:
		type: [String]
		label: 'Schlagwörter'
		optional: true
		autoform:
			type: 'tags'
			afFieldInput:
				placeholder: 'Use comma to end tag'
				tagClass: 'label label-default'

The placeholder value for type: [String] is not showing in the autoform field. Works on my String and Date types. Please advise.

**Comment by aldeed** [comment]
It would be up to the package that is providing the "tags" custom input type to support placeholders.
