### ISSUE TITLE
 Autoform unique ID error when having more then one form.

### ISSUE THREAD

**Issue by Difusio** [aldeed/meteor-autoform#886]
Using Jade templating to write my pages I run into a weird problem. Below is the template with modals I'm trying to render (truncated)

````
template(name="modals")
    #createModal.modal.fade
        .modal-dialog
            .modal-content
                +autoForm collection="Shifts" id="insertShiftForm" type="insert"
                      (TRUNC)

    #ownShiftModal.modal.fade
        .modal-dialog
            .modal-content
                +autoForm collection="Shifts" doc=thisShift id=updateShiftForm type="update"
                      (TRUNC)

    #availableShiftModal.modal.fade
        .modal-dialog
            .modal-content
                +autoForm collection="Shifts" doc=thisShift id=takeShiftForm type="update"
                       (TRUNC)
````

If I comment out updateShiftForm and takeShiftForm then insertShiftForm will render. Any other form gives:

*Uncaught Error: Every autoForm and quickForm must have an "id" attribute set to a unique string.*

If I render insertShiftForm then I can see that the ID attribute is being set correctly on the form that is being rendered.

thisShift happens here:

````
Template.modals.helpers({
    shifts: function () {
        return Shifts.find();
    },
    thisShift: function () {
        return Session.get('shift');
(TRUNC)
````

`shift` isn't set until a button is clicked so I suppose that might be the problem. However if I return a hardcoded random string then it still won't work.

This problem exists since v5.

**Comment by GQAdonis** [comment]
Did anyone ever look at this?  I have the same problem.

**Comment by aldeed** [comment]
I think it's just because you don't have quotation marks around `updateShiftForm` and `takeShiftForm` for those `id` attributes.
