### ISSUE TITLE
datetime stamp on insert and update

### ISSUE THREAD

**Issue by amazingBastard** [aldeed/meteor-autoform#887]
Hey, not sure if this was explained in the docs somewhere but I couldn't find anything on this issue.

Is there a way to add a datetime stamp into the db when a form gets inserted or updated? I'm trying to add a created and updated variable with the Date.now() object in it but have no idea how to accomplish this with autoform since the submit sort of happens magically. 

Thanks for the help!

**Comment by ildarsamit** [comment]
See https://github.com/aldeed/meteor-autoform#callbackshooks

For example:

```javascript
AutoForm.hooks({
  myForm: {
    before: {
      insert: function(doc) {
        doc.dateCreated = new Date;
        this.result(doc);
      }
    }
  }
});
```

**Comment by amazingBastard** [comment]
Nice, thanks a lot!
