### ISSUE TITLE
Manually calling submit on a form?

### ISSUE THREAD

**Issue by MurWade** [aldeed/meteor-autoform#899]
I have a quickForm for my collection posts

`    {{> quickForm collection="Posts" id="postForm" type="insert" buttonContent=false}}
`

with no insert button.

I want to add my insert button somewhere else and when that is clicked, i want to manually call the submit on that form. how can i do this?

**Comment by i-Hun** [comment]
+1

**Comment by elGusto** [comment]
how about getting the form object and calling submit() ?

http://api.jquery.com/submit/

This question is not really autoform related you should close this issue.

**Comment by aldeed** [comment]
Yes, `$('form#myFormId').submit()` is the correct way to do it.

**Comment by sweetticket** [comment]
This isn't working for me. I've tried $('form#myformid').submit() and document.forms['myformid'].submit(), but neither of them behave the same way as click the submit button. Any work arounds for this?

**Comment by tomyo** [comment]
I just tried aldeed suggestion and it worked fine for 'insert' type forms.

**Comment by diuzzoli** [comment]
For my code works the follow script:

`AutoForm.hooks({
    YourFormName: {
        before: {
            update: function(doc) {
                 //here your code just after the submit action
            }
        }
    }
});`

**Comment by fortunes-technology** [comment]
This seems late, but try to add submit button and have it hidden. and try to call submit again.
