### ISSUE TITLE
Use same form for "insert" and "update", but "insert" form use the data of "update" form.

### ISSUE THREAD

**Issue by zgjie** [aldeed/meteor-autoform#904]
>Can I reuse the same quickForm or autoForm for both inserts and updates?

>Yes. Your code that flips between states should do the following in this order:

>Change the type attribute's value to "insert" or "update" as appropriate, probably by updating a reactive variable.
Change the doc attribute's value to the correct document for an update or to null (or a document containing default values) for an insert, probably by updating a reactive variable.
Call AutoForm.resetForm(formId). This will clear any existing validation errors for the form.

Open an "update" form, then back to open an "insert" form, the "insert" form filled with data of just opened "update" from.

I think this is a bug. 

I have a workaround now: don't pass "null" to "doc" of "insert" form, instead pass `{key: ""}` to doc. If you have "default value" in the scheme of the form, you should pass those default values to the "doc" variable too.

**Comment by elGusto** [comment]
https://github.com/aldeed/meteor-autoform/issues/751

**Comment by aldeed** [comment]
See linked issue. Should be fixed.
