### ISSUE TITLE
Dynamically setting checkbox input to checked

### ISSUE THREAD

**Issue by abhirakshit** [aldeed/meteor-autoform#909]
I am trying to set some of the values of select-checkbox to checked.
```javascript
{{> afFormGroup name="products" type="select-checkbox" options=prodOptions}}
```
The prodOptions return an array like this:
```javascript
[ {label: "2013", value: 2013},
  {label: "2014", value: 2014},
  {label: "2015", value: 2015}];
```

Using the defaultValue will not work for me as the options data is received from the DB and this is an update operation. Is there a way I can set some of these to checked by doing something like below
```javascript
[ {label: "2013", value: 2013, checked: true},
  {label: "2014", value: 2014},
  {label: "2015", value: 2015}];
```

If not is there another way to do this? I looked at the documentation and the demo but could not find a way to do this. 

Thanks

**Comment by abhirakshit** [comment]
I found the solution. Setting the value attribute for the afFormGroup with the values to be checked does the trick.

```javascript
{{> afFormGroup name="products" type="select-checkbox" options=prodOptions value=checkedValues}}

checkedVal = [2013]
```

Guess I posted too early.

**Comment by Mzwamandla** [comment]
hey just pumped in this issue, been looking for something like this but i cant get it work as am reading the checkbox values from a collection like this. 
`oStatutoryCost: {
  type: [String],
  label: "Statutory Cost",
  defaultValue:true,
  autoform:{
    type: 'select-checkbox-inline',
    options: function () {
      var oBenefitCategory = colBenefitCategory.findOne({
        iRanking : 2,
        bIsActive : true
      });
      return colBenefitType.find({
        cBenefitCategoryId : oBenefitCategory._id,
        //                              _id : {$in : oCouncil.oBenefitTypes },
        bIsActive : true
      },
      {sort:
        {
          cBenefitTypeName: 1
        }
      }
    ).map( function ( doc) {
      return {
        label: doc.cBenefitTypeName,
        value: doc._id
      };
    } );
  },
},
}`
