### ISSUE TITLE
Autoform Autovalue doesnt allow to update collection

### ISSUE THREAD

**Issue by evilhei** [aldeed/meteor-autoform#918]
Hi,

Im using autoform and autovalue, defined like this:

Products = new Mongo.Collection("products");

Products.attachSchema(new SimpleSchema({
isItReady: {
    type: Boolean,
    autoValue: function() {
      isItReady = false;
      return isItReady
    }
  }
}));

this works ok.

But then im running a function:

Meteor.setInterval( function () {
  productDate = Products.findOne({isItReady: false});
    var timeNow = Date();
    var timeCreated = productDate.createdAt 
    var productId = productDate._id;
    console.log(timeNow + " time now")
    console.log(timeCreated + " time when created")
        if (2 >= 1) {
          console.log("kapsas");
          console.log(productId, + " 2");
          console.log(productId);
        Products.update({_id: productId}, {$set: {isItReady: true}})
    }
  }, 5000);

And the function works create, I get all the console logs but the collection value is not set to true.

It only works when I remove return from the autovalue, then it updates the collection after meteor has built the application again.

Could you please check and suggest a fix/workaround?

I need to use the autoform to enter this value and then some logic to set it true afterwards.

**Comment by fpaboim** [comment]
If you only want autovalue on insert use:

```
autoValue: function() {
  if (this.isInsert)
    return false
}
```

**Comment by aldeed** [comment]
autoValue is part of the SimpleSchema package. If this is still an issue, please submit there.
