### ISSUE TITLE
Problems with custom async validation

### ISSUE THREAD

**Issue by nQk2** [aldeed/meteor-autoform#919]
I'm using a custom async validation similar to the example
````
username: {
  type: String,
  regEx: /^[a-z0-9A-Z_]{3,15}$/,
  unique: true,
  custom: function () {
    if (Meteor.isClient && this.isSet) {
      Meteor.call("accountsIsUsernameAvailable", this.value, function (error, result) {
        if (!result) {
          Meteor.users.simpleSchema().namedContext("createUserForm").addInvalidKeys([{name: "username", type: "notUnique"}]);
        }
      });
    }
  }
}
````
No validation errors appear, even though `result` is false. The item is added to the collection without any errors.

**Comment by nQk2** [comment]
Do I maybe have to add some kind of hook?

**Comment by aramk** [comment]
I get the same issue. I can actually see an error appear near the validated field but the form closes immediately afterwards without any errors.

**Comment by Adiel-Sharabi** [comment]
You should make validation on the server too, the form is "valid" so the submitting can occur.

**Comment by aramk** [comment]
Ah ok, presumably it will wait on a response from any Meteor.call() invocations before allow the submission to succeed?

**Comment by Adiel-Sharabi** [comment]
No, but it will be very fast... :)
