### ISSUE TITLE
Feature Request: Conditionally Hiding Fields from Schema Setup

### ISSUE THREAD

**Issue by etyp** [aldeed/meteor-autoform#924]
I know there are ways to hide/show fields within custom templates using the `afFieldValueIs` helper, but this limits the conditional to just template logic.

Ideally it would be nice to be able to define dependent hide/show options in the Schema. This would allow for conditionally hiding/showing fields when using `quickForm`.

Maybe it could be defined like:

```
 myField: {
    label: 'My Field',
    autoform: {
        visible: function() {
            // Grab value of another field to determine whether to show this field
            // In this case, we return true if the 'otherField' value is also true
            // (e.g. if 'otherField' is a checkbox and is checked, show 'myField')
            var otherField = this.field("otherField");
            return otherField.value;
        }
    }
  }),
```

Where `this.field(...)` works in the same type of context that `autoValue` does.

**Comment by timfam** [comment]
+1

**Comment by kepler** [comment]
+1

**Comment by alexcorre** [comment]
+1

**Comment by JuusoV** [comment]
+1!

**Comment by 57even** [comment]
+1

**Comment by jrothman** [comment]
+1

**Comment by TomFreudenberg** [comment]
+1

**Comment by RobertLowe** [comment]
+1

**Comment by Maado** [comment]
+1

**Comment by 57even** [comment]
+1

**Comment by ChrisCinelli** [comment]
:+1:

**Comment by ChrisCinelli** [comment]
I think hiding a field is pretty easy. 
The problem may be the conditional logic associate with being invisible. 
For example: does being invisible imply that we should not validate this field? That is never set in the object? What about default values?

**Comment by joaobarcia** [comment]
+1

**Comment by aheissenberger** [comment]
:+1:

**Comment by aheissenberger** [comment]
it would help if autoform could be a function - but this code **fails** with:
`Error: Invalid definition for layout.size field.`
```javascript
    autoform: function() {
      if (this.field('type').content !=='headline') {
        return {omit: true,}
      } else {
        return {
          options: [
            {label: "Groß", value: "big"},
            {label: "Mittel", value: "medium"},
            {label: "Klein", value: "small"},
          ]
        }
      }
    },
```

**Comment by oliroy** [comment]
+1

**Comment by weeger** [comment]
+1

**Comment by macrozone** [comment]
I created a PR https://github.com/aldeed/meteor-autoform/pull/1296 that allows omit to be a function.

`````
 myField: {
    label: 'My Field',
    autoform: {
        omit: function(fieldName) {
            var otherField = AutoForm.getFieldValue("otherField");
            return otherField === "someValue";
        }
    }
  }),
``````

**Comment by sgelbart** [comment]
+1

**Comment by jjman505** [comment]
+1

**Comment by Simomultimedia** [comment]
+1

**Comment by Simomultimedia** [comment]
+1

**Comment by alexoldenburg** [comment]
This looks very promising! +1!

@aldeed where do you see this going?
Will it be in your next version? Do you guys need more testing? 

How can we help?

I know for a fact that all these ppl that +1 this thread, are willing to lend a hand!

**Comment by devarashetty** [comment]
+1

**Comment by 7immy** [comment]
+1

**Comment by smilansky** [comment]
+1 - im using jquery toggle right now with template events and its not really working properly.

**Comment by tomtom87** [comment]
+1

**Comment by edwardsf** [comment]
+1

**Comment by aessig** [comment]
+1

**Comment by kaiyes** [comment]
1+

**Comment by dooch** [comment]
1+

**Comment by cdolek** [comment]
+1

**Comment by richardgsands** [comment]
+1000000000000000....!!!

**Comment by andretessmann** [comment]
+1

**Comment by KevinMarzec** [comment]
+1

**Comment by aliyekurumlu** [comment]
+1

**Comment by devinwagman** [comment]
+1

**Comment by b1gbrother** [comment]
+1

**Comment by Xplic1T** [comment]
+10000

**Comment by juliomac** [comment]
+1, This could work in conjunction with optional. Instead of ``optional: true|false`` we could have ``optional: true|hide|false`` and use very same custom function. That would eliminate the risks @ChrisCinelli mentions.

**Comment by tdotholla** [comment]
+100

**Comment by Siim** [comment]
+1

**Comment by BeanMc** [comment]
test: {
        type: Boolean,
        label: "test",
        autoform: {
            id:"test",
            afFieldInput: {
                type: "boolean-checkbox"
            },
        },
    },
    test2: {
        type: Boolean,
        label: "dsad",
        autoform: {
            afFieldInput: {
                type:function () {
                    console.log(AutoForm.getFieldValue("test"));
                    if(AutoForm.getFieldValue("test")){
                        return ""
                    }
                    return "hidden"
                },
                options: [
                    {label: "Groß", value: "big"},
                    {label: "Mittel", value: "medium"},
                    {label: "Klein", value: "small"},
                ]
            },
        },
    },

**Comment by AlmogRnD** [comment]
Was this every done?

**Comment by aldeed** [comment]
There are a few ways to do this. You can use a `quickForm` with `fields` or `omitFields`, but you might get into trouble if you omit fields that are required, unless you are adding values for those in some other way, like in a hook. But my preferred way is to set the form's `schema` to the schema returned by `schema.pick` or `schema.omit`

**Comment by AlmogRnD** [comment]
Well that be reactive ? I thought omit fields only works when the schema loads. 

I would like to have a dropdown in the form and when a user selects X show Y fields. What would be the best approach for this?

**Comment by aldeed** [comment]
@AlmogRnD For `schema.pick` in a helper, you would use a reactive variable for the selection and based on that it would return a new schema each time. The one downside would be that you'd lose all of the validation errors every time it reruns, so you might need to limit the reactivity after the form is invalid. Or if there are a finite number of X options, you could precreate a schema for each and swap in the correct one as the return value from the helper.

The `fields` or `omitFields` options on `quickForm` should be reactive, though.
