### ISSUE TITLE
Custom form group templates

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#928]
I know it's possible to provide custom input types templates. But is there a way to do the same for form groups? i.e. replace the whole label+input field block with a custom element?

My use case is getting rid of the label for a specific field, by the way.

**Comment by elGusto** [comment]
Hi @SachaG 

you can specify options for the afFormGroup template as explained here (I think your use case is covered):

afFormGroup
------------------

Just as quickForm renders a form in one line, afFormGroup renders a form group, that is, everything related to a single field -- the label, the input, and the error message -- in one line.

This component accepts the same attributes as afFieldInput. Attributes that are prefixed with label- become attributes on the rendered label element while any remaining attributes are forwarded to the afFieldInput component. You can also set label=false to omit the label element or set label to a string to use that text as the label text.


Overwise, you can create your own custom template like: <template name="afFormGroup_bootstrap3_custom">

And then in your schema or form template you can pass the afFormGroup object with a template attribute:
```
myField: {
    type: String,
    autoform: {
      afFieldInput: {
        disabled: true
      },
      afFormGroup: {
        template: 'bootstrap3_custom',
      }
    }
  };
```

**Comment by SachaG** [comment]
Maybe I'm doing something wrong, but I don't think that works:

```js
myField: {
    type: String,
    autoform: {
      afFormGroup: {
        template: 'bootstrap3_custom',
      }
    }
  };
```

I should mention that I'm talking specifically about using a custom form group template when using `quickform`, not `afFormGroup`.

**Comment by elGusto** [comment]
Odd…

I think the template name has to be prepended by ‘afFormGroup_' or it will not work.

The other thing you could do in your use case is :

```
myField: {
    type: String,
    autoform: {
      afFormGroup: {
	label: false
    }
  };
}

```

**Comment by aldeed** [comment]
https://github.com/aldeed/meteor-autoform#creating-a-custom-template

**Comment by lonniev** [comment]
Say @aldeed, can you alter that documentation advice to (also) describe how one implements a custom template for just one of the form elements of an {{> autoForm}}? What does the syntax look like if one wants to, say, alter only one of the line items so that it shares its row with some other non-form horizontal elements?

I'm sure some trial and error work with the templating will eventually lead me to the working answer - but since you went to the trouble to document this a little, can you spell it out a bit more?
