### ISSUE TITLE
Using enumerations to set dropdown? (e.g. lookup in MongoDB array or another collection)

### ISSUE THREAD

**Issue by victorhooi** [aldeed/meteor-autoform#931]
What is the best way to use an use enumerations to set a dropdown field in meteor-autoform?

(Enumeration could be an array of values, or ideally another collection).

For example, say you had a field called `occupation` - you want to pick from `(fireman,policeman,scientist,teacher)`.

What are the "best practices" for doing this with meteor-autoform?

**Comment by victorhooi** [comment]
Sorry, to clarify, if you use `allowedValues`, what is the recommended way of populating this, outside of just hardcoding it in the variable itself? Could you look it up in a MongoDB array, or in a specific field in documents in another collection?

Curious how people are doing this.

**Comment by aldeed** [comment]
https://github.com/aldeed/meteor-autoform#what-are-the-various-ways-i-can-specify-options-for-a-select-radio-group-or-checkbox-group

See "Use a helper" subsection for example for DB lookup
