### ISSUE TITLE
How to properly  get  allowedValues from a cursor?

### ISSUE THREAD

**Issue by michelkeyaerts** [aldeed/meteor-autoform#940]
I have a roadMapComment collection and a roadMapTags collection
I want  a select form where allowedValues match to roadMapTags

roadMapComment allowedValues- I tried:
```

   roadMapTags: {
    type: String,
    max: 100,
    allowedValues: function(){
      var result = [];
      roadMapTags.find().map( function(tag) { 
        result.push(tag.name);        
        
        } )
    
       console.log(result);
       return result;
    }
  }
  
}));

```

```   console.log(result);``` return at first an empty array and after the correct value: ```Array [ "design", "édition", "recherche" ]```

It doesn't work. My template doesn't return any value:
```
 {{> afQuickField name='roadMapComment'  options='allowed'}}
```

What can I do?

**Comment by myknbani** [comment]
any solution to this?

**Comment by victorhooi** [comment]
Hmm, I seem to have been able to get this working - I didn't use an anonymous function, not sure if that actually makes a difference though:
```
list_of_sports = function() {
    var results = [];
    Sports.find().map( function(sport) {
        results.push(sport.name);
    })
    return results
}
```

Then, in my schema:
```
Ratings.attachSchema(new SimpleSchema({
    name: {
        type: String,
        label: "Name of Sport",
        allowedValues:list_of_sports(),
        max: 200,
        //autoform: {
        //    type: "select2"
        //}
    },
    etc.
```

**Comment by victorhooi** [comment]
Actually, I spoke too soon - sometimes it seems to return an empty array - I suspect this is to do with the data not being loaded yet.

Maybe there's something that can be done with waitOn, to wait for the subscription to be ready.

@aldeed Is there perhaps a better way of doing this?

**Comment by aldeed** [comment]
If your allowed values are dynamic, you probably shouldn't use them to generate the field options. Better to use a helper for the `options` attribute value, subscribe to the data when the containing template is created, and then the `options` function will rerun as data is loaded.

For validation, you can then use a `custom` function that checks the value to see if it's allowed on the server only.
