### ISSUE TITLE
Show / hide sub-form depending on an Autoform checkbox field

### ISSUE THREAD

**Issue by mchan75** [aldeed/meteor-autoform#948]
I am trying to show a sub-form (dependent on a sub-schema) when the user clicks YES in the 'credit' field, and show another sub-form (dependent on another sub-schema)  if the user checked the 'require shipping' checkbox. 

Yet I am not sure how I can trigger the onClick event for the checkbox and radio button in autoform so that I can show / hide sub-forms depending on the user selection? Also how I can instruct autoform to save the two sub-schemas when the require shipping checkbox or credit radio button is checked? Thanks

      schemas.Invoice = new SimpleSchema({
        customer: {
          type: String,
          label: "Customer Name"
        },
       credit: {
            type: Boolean,
            label: "To be paid later?",
            autoform: {
               type: "boolean-radios",
               trueLabel: "Yes",
               falseLabel: "No",
               value: false
            }
        },
        requireshipping: {
            type: Boolean,
            defaultValue: false,
            label: "Ship products to me"
        }
      });

**Comment by st3phan** [comment]
Have a look at this example: http://autoform.meteor.com/fieldvalues

**Comment by mchan75** [comment]
@st3phan  thanks a lot, that did it :)
