### ISSUE TITLE
how to get or use this.doc on "after, onSuccess" hook?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-autoform#951]
I want to record events (audit trail), when user insert doc.
how to get or use this.doc on "after, onSuccess" hook?
```js
onSuccess: function (formType, result) {
            Events.trackInsert({
                description: this.doc
            });
            alertify.success('Success');
        },
```

**Comment by st3phan** [comment]
From the docs:

> The following properties and functions are available in all submission hooks when they are called. This does not include formToDoc, formToModifier, or docToForm.

> `this.currentDoc`: The current document attached to the form (from doc attribute)
> `this.insertDoc`: The gathered current form values, as a normal object

````javascript
onSuccess: function (formType, result) {
    var self = this;
    Events.trackInsert({
        description: self.insertDoc
    });
    alertify.success('Success');
}
````

**Comment by yuomtheara** [comment]
Now work fine.
Thanks.
