### ISSUE TITLE
addInputType valueOut() isn't firing

### ISSUE THREAD

**Issue by ciwolsey** [aldeed/meteor-autoform#954]
I'm trying to use addInputType for a jQuery plugin. But the function for valueOut is never firing. The template displays fine. I'm simply returning a string to make it as simple as possible.
 
https://gist.github.com/ciwolsey/e7d2b27ab0603ee3ff83

**Comment by ciwolsey** [comment]
Was my own error

**Comment by delgermurun** [comment]
@ciwolsey I am facing same problem, what's your error?

**Comment by st3phan** [comment]
Same problem here too, how did you fix it?

**Comment by ciwolsey** [comment]
It was 4 months ago I'm not sure but I wouldn't have closed this stating it was my own error if that wasn't the case.

**Comment by jeff-hsu** [comment]
@delgermurun @st3phan  Has anyone figured out the cause of your errors?
