### ISSUE TITLE
Autoform: issue with defaultValue: new Date() is returning the meteor launch time ?!

### ISSUE THREAD

**Issue by JVercout** [aldeed/meteor-autoform#955]
Hi, 
I'm having trouble dealing with a type: Date into SimpleSchema having a defaultValue. I'm using mongodb (3.0.1).

The date entry have the time the meteor thread have been launch isntead of having the expected behaviour: have the insertion date of the object on the server.

```
Schema.DateCol = new SimpleSchema({
  date: {
    type: Date,
    defaultValue: new Date()
  },
  dateModified: {
    type: Date,
    autoValue: function () { return new Date(); }
  }
});
```

Into the mongo, after inserting two objects:

* meteor thread launch at "Wed May 20 2015 12:28:42 GMT+0200 (CEST)"
* both objects have been inserted at one minute of interval: the first at "Wed May 20 2015 12:30:50 GMT+0200 (CEST)" and the second at "Wed May 20 2015 12:31:30 GMT+0200 (CEST)"
* the date field (defaultValue) for both object is: "Wed May 20 2015 12:28:42 GMT+0200 (CEST)"
Object 1
```
{
  "_id": "PuME9jWwJJiw9diSC",
  "date": new Date(1432117722634),
  "dateModified": new Date(1432117850366)
}
```
Object 2:
```
{
  "_id": "qqHqkN4YapWDsFhxx",
  "date": new Date(1432117722634),
  "dateModified": new Date(1432117890380)
}
```

You'll find reproduction into this enclose repository:  https://github.com/JVercout/meteor-defaultValue-date-errored

Any ideas? 

Cheers,
Jérôme

**Comment by JVercout** [comment]
[Answered on StackOverflow: http://stackoverflow.com/questions/30349517/meteor-new-date-invalid-with-mongodb-3-0-1-and-autoform-simple-schema]

The problem is that the `new Date()` expression is evaluated once when the code creating the schema is run. That value is then used as the defaultValue. There is no difference between:

```
var x = new SimpleSchema({
  date: {defaultValue: new Date(), ...}
});
```

and

```
var defaultDate = new Date();
var x = new SimpleSchema({
  date: {defaultValue: defaultDate, ...}
});
```
It looks like you'll need an autoValue, since it doesn't look like you can use a function for defaultValue. The Collection2 documentation actually has an example of using autoValue for a "created at" field. It depends on fields added by Collection2 but I saw in your git repo that you're using that.
```
// Force value to be current date (on server) upon insert
// and prevent updates thereafter.
createdAt: {
  type: Date,
  autoValue: function() {
    if (this.isInsert) {
      return new Date;
    } else if (this.isUpsert) {
      return {$setOnInsert: new Date};
    } else {
      this.unset();
    }
  }
}
```

**Comment by ironmanromeo** [comment]
I need a dateStart field that customer need to modify. DateStart is a date field in array of objects. I want dateStart to be always updated to Date.now() value. It's easy in flattened fields, not inside an array. I want buttons, headers, labels to be unchanged.
