### ISSUE TITLE
Exception in template helper: Error: Invalid field name

### ISSUE THREAD

**Issue by mchan75** [aldeed/meteor-autoform#969]
In reference to issue #802 I've followed the workaround provided by @abecks for Schema reactivity as I have almost the same use case in my Meteor project, where I need to dynamically change the schema in autoform as the schema to be loaded is dependent on the selection in a select box . Below the code I am using in my application. 

Even though when I try to switch schema it changes smoothly without any problem, and a new form is displayed but in the browser console when switching I get tons of errors as that shown below. Can you please tell me what I might be missing / doing wrong here? Thanks

//Error

    Exception in template helper: Error: Invalid field name: DateOfPurchase
    at Object.getDefs (http://localhost:3000/packages/aldeed_autoform.js?2ffcea3a8ad7973ac5bdee51c024bdbbd450ae19:257:13)
    at Object.autoFormGetComponentContext [as getComponentContext] (http://localhost:3000/packages/aldeed_autoform.js?2ffcea3a8ad7973ac5bdee51c024bdbbd450ae19:516:20)
    at Object.afFormGroupContext (http://localhost:3000/packages/aldeed_autoform.js?2ffcea3a8ad7973ac5bdee51c024bdbbd450ae19:7130:30)
    at bindDataContext (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at wrapHelper (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27)
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at http://localhost:3000/packages/aldeed_autoform.js?2ffcea3a8ad7973ac5bdee51c024bdbbd450ae19:7097:23

//JS

    var destroyForm = new ReactiveVar(false);
    var invoiceSchema = new ReactiveVar(null);

      this.classTempArrayToJSON = function(classTempArray) {
          var tempSchemaObj = {};
          for(var i=0; i<classTempArray.length; i++){
              if(classTempArray[i].fieldtype=='String'){
                  tempSchemaObj[classTempArray[i].fieldname] = {  type: String,
                                                                 label: classTempArray[i].fieldlbl,
                                                                 min: Number(classTempArray[i].minval),
                                                                 max: Number(classTempArray[i].maxval),
                                                                 optional: !classTempArray[i].required };
              }
          }
          return tempSchemaObj;
      };

     function getInvoiceSchema(selectedSchema){
        var x = InvoiceTempCol.find().fetch();
        if(x.length > 0){
          var schema = classTempArrayToJSON(x[selectedSchema].fieldsList);
          destroyForm.set(false);
          return new SimpleSchema(schema);      
        }else{
          destroyForm.set(true);
          return {};
        }
    }
    Template.invoiceTemplate.created = function(){
      invoiceSchema.set(getInvoiceSchema(9)); //Loading any invoice template on startup
    };

    Template.invoiceTemplate.helpers({
      destroyForm: function(){
        return destroyForm.get();
      },
      schema: function(){
        return invoiceSchema.get();
      }  
    });

//HTML

        {{#if destroyForm}}
            <h3>Invoice not loaded yet!</h3>
        {{else}}
            {{> quickForm id="invoiceForm" buttonContent="Insert" buttonClasses="btn btn-primary btn-sm" schema=schema type="method" meteormethod="saveInvoice"}}
        {{/if}}

**Comment by abecks** [comment]
I am working on a reactive-schema-safe branch of AutoForm, please see: https://github.com/aldeed/meteor-autoform/issues/802#issuecomment-105348416

**Comment by abecks** [comment]
For the record, I have never been able to get rid of those errors with the workaround. I have situations where they only appear *sometimes*. I believe there are cases where delayed validation throws errors too.

**Comment by mchan75** [comment]
Thanks @abecks for your help, based on your second comment here, does this mean that if I just ignored those console errors, everything will remain working smoothly without any problem (assuming of course there are no other problems beside the console errors)?

**Comment by abecks** [comment]
Yes, that has been my experience. I am currently using the workaround in a production app, and while it fires errors, the only real problem it is causing is filling my Kadira error logs up.

**Comment by mchan75** [comment]
@abecks  Thanks a lot, appreciate it

**Comment by abecks** [comment]
I should also note that I am now using my reactive-schema branch in production with no errors. But I don't cover every use case, so be sure to test it for yourself if you want to go that route.
