### ISSUE TITLE
Console displays error when validating

### ISSUE THREAD

**Issue by jaypanares** [aldeed/meteor-autoform#972]
Hi,

My form is validating quite fine, but I noticed that errors keep popping up in the console and terminal whenever a field is invalid.  Error below:

```
update failed: Error: [field_name] is required
    at getErrorObject...
```

The form is working perfectly fine by showing the appropriate messages, but I also get these errors printed out in the console and terminal.  Is this normal or does this mean there is something wrong with my implementation?

Thanks!

**Comment by aldeed** [comment]
Those are errors coming from the `update` call that AutoForm does for you for a `type="update"` form. So that's normal.
