### ISSUE TITLE
Set Form Values 

### ISSUE THREAD

**Issue by niklasp** [aldeed/meteor-autoform#973]
I want to save default form values for a huge form. I managed to extract them, via
`AutoForm.getFormValues(formId).insertDoc`
But how can I use this doc to populate the form again in javascript. I can only find the Blaze method with `doc=reactiveFunction` which seems like a dirty workaround, because I want the form to be populated when the user clicks a button. Are there best practices or functions I am missing?

**Comment by aldeed** [comment]
Set the form's `doc` attribute to the document you extracted.
