### ISSUE TITLE
problem with "formToModifier" in update type?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform#979]
I try
```js
// Hook
depositUpdate: {
        .....................
        formToModifier: function (modifier) {
            console.log(modifier);
            return modifier;
        }
```
When I click submit on update form, don' show console.
Please help me.

**Comment by zimme** [comment]
#859

**Comment by cskaandorp** [comment]
Hi Eric,

Please address https://github.com/aldeed/meteor-autoform/issues/983 as well. afFieldValueIs is not reactive and afFieldValuesContains needs some encouraging by multiple clicks to be reactive. Attached is a test app if you might need one.

thanks

Casper

**Comment by aldeed** [comment]
@cskaandorp yep, working on it.

**Comment by cskaandorp** [comment]
Thanks man! That is a big relieve.

C




On 22 Jun 2015, at 15:11, Eric Dobbertin <notifications@github.com<mailto:notifications@github.com>> wrote:


@cskaandorp<https://github.com/cskaandorp> yep, working on it.
