### ISSUE TITLE
How test autoform git branch package?

### ISSUE THREAD

**Issue by bySabi** [aldeed/meteor-autoform#982]
When clone autoform repo on test App local "package" folder always got error:

 ```
(STDERR) ReferenceError: Template is not defined
W20150528-23:41:37.665(2)? (STDERR)     at app/package/meteor-autoform/templates/bootstrap3-horizontal/components/afArrayField/afArrayField.js:1:36
```

How test autoform git branch??

**Comment by aldeed** [comment]
Weird, is that in the server console? AutoForm is a client package and it should not be attempting to run that file on the server. I can't help much more unless you can provide specific reproduction steps starting from a new blank app.

**Comment by bySabi** [comment]
Hello Eric.
Here we go, a test repo: https://github.com/bySabi/autoform-test

**Comment by bySabi** [comment]
Is a bug!!!
In my eyes. I clone autoform on `package` than `packages`.
Work fine.
sorry for that :-(
