### ISSUE TITLE
afFieldInput with optional:true not rendered if in collection with optional:false

### ISSUE THREAD

**Issue by andmitsch** [aldeed/meteor-autoform#990]
Somehow it seems like using `afFieldInput` does not render forms that have a `optional:true` flag, if there is one that is `optional:false` in the same collection.

The code fragments are from telescope https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-posts/lib/posts.js

```javascript
url: {
    type: String,
    optional: true,
    editableBy: ["member", "admin"],
    autoform: {
      type: "bootstrap-url"
    }
  },
  title: {
    type: String,
    optional: false,
    editableBy: ["member", "admin"]
  },
  body: {
    type: String,
    optional: true,
    editableBy: ["member", "admin"],
    autoform: {
      rows: 5
    }
  },
```

```html
{{#autoForm id="submitPostForm" type="method" collection="Posts" meteormethod="submitPost" template="bootstrap3-horizontal"}}

  <div class="form-group {{#if afFieldIsInvalid name='url'}}has-error{{/if}}">
    {{> afFieldInput name='url'}}

    <label class="control-label input-label" for="url">{{afFieldLabelText name='url'}}</label>

    {{#if afFieldIsInvalid name='url'}}
      <span class="help-block">{{{afFieldMessage name='url'}}}</span>
    {{/if}}
  </div>

  <div class="form-group {{#if afFieldIsInvalid name='title'}}has-error{{/if}}">
    {{> afFieldInput name='title'}}

    <label class="control-label input-label" for="title">{{afFieldLabelText name='title'}}</label>

    {{#if afFieldIsInvalid name='title'}}
      <span class="help-block">{{{afFieldMessage name='title'}}}</span>
    {{/if}}
  </div>

  <div class="form-group {{#if afFieldIsInvalid name='body'}}has-error{{/if}}">
    {{> afFieldInput name='body' type="string" rows="6"}}

    <label class="control-label text-label" for="body">{{afFieldLabelText name='body'}}</label>

    {{#if afFieldIsInvalid name='body'}}
      <span class="help-block">{{{afFieldMessage name='body'}}}</span>
    {{/if}}
  </div>

  {{> afQuickField name='categories' template="bootstrap3"}}

  {{> afQuickField name='status' template="bootstrap3"}}

  <div class="form-group">
    <button type="submit" class="btn btn-submit">{{_ "submit"}}</button>
    {{#if userIsAdmin}}
    <a class="delete-link" href="/">{{_ "delete_post"}}</a>
    {{/if}}
  </div>

{{/autoForm}}
```

For some reason, the title gets rendered but the url does not get injected at all. There's just a div with the label.

**Comment by SachaG** [comment]
Could you post the entirety of your form markup? Maybe link it in a gist if it's too long?

**Comment by andmitsch** [comment]
@SachaG done edit

**Comment by SachaG** [comment]
So for example the `body` field does not get rendered if you set `optional` to `false`, but does if you change it to `true`?

**Comment by andmitsch** [comment]
Body is on true and does not get rendered. The only thing rendered is the required field, that is title in this case.

**Comment by SachaG** [comment]
And you've checked that it gets rendered if you change it to `false`?

**Comment by andmitsch** [comment]
Okay, took another look into it.

Seems like the auto type selection does not work in this scenario (cause of the custom type `type='bootstrap-url'`), which is why I have to force a type for the URL form.

Solution is simply to force type in the fieldinputs like:
`{{> afFieldInput name='url' type='url'}}`

Title does work, because it's the default type, which is text. Hence `{{> afFieldInput name='title' }}` works. 

Though textarea does work as well without type declaration, because in telescope it has a autoform setting for the rows, which automatically identifies this field as a textarea by autoform.

```javascript
  body: {
    type: String,
    optional: true,
    editableBy: ["member", "admin"],
    **autoform: {
      rows: 5
    }**
  },
```

**But**, for URL the telescope collection does not have a type declaration that autoform recognizes, which is why simply using afFieldInput without type declaration will simply render nothing.

Unfortunately, using the custom type does not work in afFieldInput like `{{> afFieldInput name='title' type='bootstrap-url'}}`

Or at least, I do not know how to make it work, yet!
