### ISSUE TITLE
mrt:moment-timezone dependency involves mrt:moment

### ISSUE THREAD

**Issue by tcastelli** [aldeed/meteor-autoform#991]
Since autoform package moved away from mrt:moment to official momentjs:moment, I would suggest switching from mrt:moment-timezone package to one that doesn't use mrt:moment, otherwise both (mrt:moment and momentjs:moment are sent to the client which turns out in some nasty extra KBs).

Instead of using mrt:moment-timezone, what about risul:moment-timezone? (I have nothing to do with that package but it uses momentjs and seems to be updated)

**Comment by aldeed** [comment]
You can use `aldeed:moment-timezone` instead now. Either way, it's a weak dependency so the package is not automatically added to your project.
