### ISSUE TITLE
Saving Object data to autoform from page

### ISSUE THREAD

**Issue by latitudehopper** [aldeed/meteor-autoform#996]
I have leaflet-draw generating a geoJson object. How do I attach this to the autoform field so that it saves with the rest of the form?

**Comment by latitudehopper** [comment]
OK I have managed to do this but I am struggling with updates.

I have checked the docs but I cannot get my head around this. I have an object that I want to update using Auto-Form and Collections2 with meteor.

//Schema
```
Records = new Mongo.Collection('records');

var Schemas = {};


Schemas.Record = new SimpleSchema({
title: {
    type: String,
    label: "Title",
    max: 200
},
caption: {
    type: String,
    label: "Caption",
    max: 200
},
text: {
    type: String,
    label: "Detailed text",
    optional: true,
    max: 1000
},
loc: {
    type: Object,
    optional: true,
    blackbox: true
},
createdAt: {
    type: Date,
    autoform: {
        type: "hidden"
    },
    autoValue: function() {
        if (this.isInsert) {
            return new Date;
        }
        else if (this.isUpsert) {
            return {
                $setOnInsert: new Date
            };
        }
        else {
            this.unset();
        }
    }
},
updatedBy: {
    type: String,
    autoValue: function() {
        return Meteor.userId();
    }
}
});

Records.attachSchema(Schemas.Record);
```
I have a hook so that I assign the object before update
```
AutoForm.hooks({
    insertCommentForm: {
        before: {
            insert: function(doc) {
                doc.commentOn = Template.parentData()._id;
                return doc;
            }
        } 
    },


    updateRecordForm: {
        before: {
            update: function(doc) {
                console.log("storing location data");
                doc.loc = Session.get('geoData');
                console.log(doc.loc);
                return doc;
            }
        } 
    }
});
```
I get this error.

Uncaught Error: When the modifier option is true, all validation object keys must be operators. Did you forget $set?
I don't know how to "$set" with autoform.

**Comment by micahalcorn** [comment]
I ran into this and noticed that the doc contains the modifier. So in your case the solution would be to...

```JavaScript
updateRecordForm: {
  before: {
    update: function (doc) {
      doc.$set.loc = Session.get('geoData');

      return doc;
    }
  } 
}
```

The readme suggests adding the property directly to doc as you attempted, so I'm not sure why this is happening. Perhaps I am misunderstanding or the readme has not yet been updated?

**Comment by latitudehopper** [comment]
Yes, that is how I resolved this. Thank you.

**Comment by micahalcorn** [comment]
@latitudehopper: for the record, my issue was that I was using version 4.x and the README is currently applicable to version 5.x. If that was the case for you, then you might consider closing the issue.
