### ISSUE TITLE
Exception in template helper: Error: Invalid field name: (not a string)

### ISSUE THREAD

**Issue by YouSour** [aldeed/meteor-autoform#998]
hi , i have some problem , i notice that this code work on autoform v.4.2.1 but when i update to v 5.3.0    not work , any idea ? thank advance .
 
code: HTML
-------------------------------------------------------------------------------------
<body>
<div class="row">
    {{> addNewClientBody}}
</div>
</body>

<template name="addNewClientBody">
    {{#autoForm id="addClientForm" type="insert" buttonContent=false collection="Clients" validation="keyup" afFieldInput-placeholder="schemaLabel"}}
        {{> afArrayField name="phoneNumber" template="phoneNumbers" label-class="col-sm-3 qformlabel" input-col-class="col-sm-9" }}

        <div>
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-blue cancel reactive-modal-btn" data-dismiss="modal">Cancel</button>
        </div>
    {{/autoForm}}
</template>

<template name="afArrayField_phoneNumbers">

    <div class="form-group{{#if afFieldIsInvalid name=this.atts.name}} has-error{{/if}}">
        <div class="col-sm-9">
            {{#if afFieldIsInvalid name=this.atts.name}}
                <div class="panel-body has-error">
                    <span class="help-block">{{{afFieldMessage name=this.atts.name}}}</span>
                </div>
            {{/if}}
            <ul class="list-group">
                {{#afEachArrayItem name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
                    <li class="list-group-item autoform-array-item">
                        <div class="row">
                            <div class="col-xs-12">

                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Diagnosis</th>
                                        <th>Qty</th>
                                        <th>Price</th>
                                        <th>Discount</th>
                                        <th>Amount</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {{> afObjectField name=this.name template="customObjectField"}}
                                    <div class="col-xs-2">
                                        <div class="form-group">
                                            <td>
                                                {{#if afArrayFieldHasMoreThanMinimum name=../atts.name minCount=../atts.minCount maxCount=../atts.maxCount}}
                                                    <label class="col-xs-3 control-label">&nbsp;</label>
                                                    <button type="button" class="btn btn-primary autoform-remove-item">
                                                        Delete
                                                    </button>
                                                {{/if}}
                                            </td>
                                        </div>
                                    </div>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </li>
                {{/afEachArrayItem}}

                {{#if afArrayFieldHasLessThanMaximum name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
                    <li class="list-group-item">
                        <button type="button" class="btn btn-primary autoform-add-item"
                                data-autoform-field="{{this.atts.name}}" data-autoform-minCount="{{this.atts.minCount}}"
                                data-autoform-maxCount="{{this.atts.maxCount}}">Add New
                        </button>
                    </li>
                {{/if}}
            </ul>
        </div>
    </div>
</template>

<template name="afObjectField_customObjectField">

    {{#if afFieldIsInvalid name=this.atts.name}}
        <span class="help-block">{{{afFieldMessage name=this.atts.name}}}</span>
    {{/if}}
    {{#each afFieldNames name=this.atts.name}}
        <td>
                <div class="col-xs-12">
                    {{> afFieldInput name=this options="auto" label-class="col-sm-3 qformlabel" class="phoneNumber" }}
                </div>
        </td>
    {{/each}}

</template>

Code : js
collection & schema
------------------------------------------------------------
Clients = new Mongo.Collection("clients");

var Schemas = {};

Schemas.Client = new SimpleSchema({

    phoneNumber: {
        type: Array,
        minCount: 1
    },
    'phoneNumber.$': {
        type: Object
    },
    'phoneNumber.$.Diagnosis': {
        type: String,
        allowedValues: ['Mobile', 'Home', 'Work', 'Other']
    },
    'phoneNumber.$.qty': {
        type: Number
    },
    'phoneNumber.$.price': {
        type: Number,
        decimal:true
    },
    'phoneNumber.$.discount': {
        type: Number
    },
    'phoneNumber.$.amount': {
        type: Number,
        decimal:true
    }
});

Clients.attachSchema(Schemas.Client);

**Comment by YouSour** [comment]
problem fixed !

**Comment by OptimisticLock** [comment]
> problem fixed !
How?

**Comment by YouSour** [comment]
check here Compatibility break !
https://github.com/aldeed/meteor-autoform/blob/master/CHANGELOG.md

**Comment by OptimisticLock** [comment]
Thank you!

Personally, I think Autoform should do its own validation. I switched to it for simplicity and spent the last few hours debugging stack traces that have no code of mine included and no indication of the offending line. Fantastic product, but needs to be more robust.
